### PR TITLE
data:add profile kundangupta1993

### PR DESCRIPTION
**Pull request by kundangupta1993**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4836"></a>

### CODE REVIEW

**Review by swagataroy30 — COMMENTED** [review]
You need to change this icon name to `FaLinkedin`. For further icon reference you can check this out https://linkfree.eddiehub.io/icons. Thank You!

**Review by Sindhuinti — CHANGES_REQUESTED** [review]
please change the icon name for linkedin to `FaLinkedin`
Follow the link to know more about the icons https://linkfree.eddiehub.io/icons.

**Comment by SaraJaoude** [comment]
> please change the icon name for linkedin to `FaLinkedin`
> Follow the link to know more about the icons https://linkfree.eddiehub.io/icons.

@Sindhuinti this suggestion is a duplicate of another contributor's suggestion above.  In future it is best to check the conversation as duplicates can create confusion for the author of the Pull Request.

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
