### PR TITLE
data: Miraz

### PR DESCRIPTION
**Pull request by mirazxmondal**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5132"></a>

### CODE REVIEW

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Review by GauravKanwat — APPROVED** [review]
Looks Good :tada:

**Comment by mirazxmondal** [comment]
@SurajPratap10 @GauravKanwat Thanks! 😄

**Comment by SurajPratap10** [comment]
> @SurajPratap10 @GauravKanwat Thanks! 😄

No worries

**Review by mahfuztbt — APPROVED** [review]

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
