### PR TITLE
fix: add Lokesh Digari

### PR DESCRIPTION
**Pull request by lokicodedaily**
my first contribution by adding a file LokeshDigari.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/887"></a>

### CODE REVIEW

**Review by syedsohan — CHANGES_REQUESTED** [review]
Change the PR title to - `fix: add Lokesh Digari`

**Comment by lokicodedaily** [comment]
> Change the PR title to - `fix: add Lokesh Digari`

done

**Review by syedsohan — APPROVED** [review]

**Review by krishguptadev — APPROVED** [review]

**Review by Pradumnasaraf — APPROVED** [review]
LGTM 🚀

**Review by nathgoutam93 — APPROVED** [review]

**Review by Cahllagerfeld — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
