### PR TITLE
Create SurajKumar.json

### PR DESCRIPTION
**Pull request by Suraj-kumar00**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

I tried first to contribute in open-source just because of you , you all are doing amazing work in community. thanks for providing this beginner level open-source contribution. And I would like to update my Linkfree Profile

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8530"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Congrats on the first contribution, Suraj! We appreciate your kind words! 🤗

--
Your filename should be exactly same as your GitHub username, Please [rename your file here](https://github.com/Suraj-kumar00/LinkFree/edit/Suraj-kumar00-Linkfree-Profile/data/SurajKumar.json) to `Suraj-kumar00.json`

Change `SurajKumar.json`  -->  `Suraj-kumar00.json`.

Let us know if you need any help with this! 🛠

**Comment by Suraj-kumar00** [comment]
Hello Priyanshu, thanks for reply , now as you said i change the name and now can you tell me what i do?

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! 🎉

**Comment by Suraj-kumar00** [comment]
Thanks a lot for merging me PR, can i ask where i find me linkfree profile link?

**Comment by kumarsonsoff3** [comment]
It's `https://linkfree.io/YOUR_USERNAME` should be at https://linkfree.io/Suraj-kumar00

**Pull request merged**
