### PR TITLE
Add my data to the public/data

### PR DESCRIPTION
**Pull request by Pulkit007**

### CODE REVIEW

**Review by vikasganiga05 — CHANGES_REQUESTED** [review]
Change the avatar URL to this
```diff
- https://avatars.githubusercontent.com/u/77740386?v=4
+ https://github.com/Pulkit007.png
```

**Review by nhcarrigan — CHANGES_REQUESTED** [review]
Please revert your changes to the package.json and package-lock.json files to avoid conflicts. Let us know if you have any questions.

**Comment by Pulkit007** [comment]
> Please revert your changes to the package.json and package-lock.json files to avoid conflicts. Let us know if you have any questions.

How to revert changes can you please tell me?

**Comment by nhcarrigan** [comment]
https://www.nhcarrigan.com/notes/#/git-commands/rebase-branch

You can perform a rebase 🙂

**Pull request closed without merging**
