### PR TITLE
data:mohit-marathe

### PR DESCRIPTION
**Pull request by mohit-marathe**

### CODE REVIEW

**Review by sidharthviz — CHANGES_REQUESTED** [review]
Hi @mohit-marathe Please remove the comma in line no. 12 after javascript.

**Review by sidharthviz — APPROVED** [review]
Great 👍🏼

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"></p>

**Pull request merged**
