### PR TITLE
check node version before build

### PR DESCRIPTION
**Pull request by shivam-sharma7**
fixes: #7667

 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7655"></a>

### CODE REVIEW

**Comment by SaraJaoude** [comment]
What issue does this relate to?

**Comment by shivam-sharma7** [comment]
> What issue does this relate to?

his is particularly important if your project relies on certain language features or APIs that are only available in specific Node.js versions.

**Comment by SaraJaoude** [comment]
> > What issue does this relate to?
> 
> his is particularly important if your project relies on certain language features or APIs that are only available in specific Node.js versions.

@shivam-sharma7 this was not my question.  You did not link the issue that this PR relates to. Has an issue been raised and assigned to you on this subject?

**Comment by SaraJaoude** [comment]
@shivam-sharma7 I see that you have created an Issue (https://github.com/EddieHubCommunity/LinkFree/issues/7667) after raising this Pull Request. In future please follow this project's [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md).

1. First raise an issue (and mention if you want this to be assigned to you);
2. If this is given the label `status: ready for dev` by the maintainers, and has been assigned to you 0  then raise the Pull Request. 

Not doing so may lead to your Pull Request being closed.

As to your changes, I do not see these changes having benefit to the project. The node version you are trying to output is already specified 2 lines above your changes here https://github.com/EddieHubCommunity/LinkFree/pull/7655/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R29 but also the specific version is already output in the GitHub Action logs (please see the screenshot) 

Screenshot 2023-06-18 at 15 46 10

I am therefore closing this Pull Request.

**Pull request closed without merging**
