### PR TITLE
Update [username].js

### PR DESCRIPTION
**Pull request by ursmahi**
flex-wrap for profile tags for responsive design

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Before adding flex-wrap
before-flex-wrap

After adding Flex-wrap
after-flex-wrap

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2212"></a>

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Hi @ursmahi! :) Great decision on adding `flex-wrap`. It made Eddie's profile more organized.

**Comment by ursmahi** [comment]
> Hi @ursmahi! :) Great decision on adding `flex-wrap`. It made Eddie's profile more organized.

Thanks, @CBID2, can you merge this issue.

**Comment by CBID2** [comment]
> > Hi @ursmahi! :) Great decision on adding `flex-wrap`. It made Eddie's profile more organized.
> 
> Thanks, @CBID2, can you merge this issue.

Sadly, I can’t @ursmahi :(

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
