### PR TITLE
Created liza-bhutani.json

### PR DESCRIPTION
**Pull request by liza-bhutani**
## Changes proposed
I have added Liza-Bhutani.json file 
## Check List (Check all the applicable boxes)

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6522"></a>

### CODE REVIEW

**Review by SaraJaoude — CHANGES_REQUESTED** [review]
Please make sure your file name matches your GitHub username exactly (it is case sensitive). Instead of `data/Liza-Bhutani.json` it should be `data/liza-bhutani.json`

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

**Comment by liza-bhutani** [comment]
> Please make sure your file name matches your GitHub username exactly (it is case sensitive). Instead of `data/Liza-Bhutani.json` it should be `data/liza-bhutani.json`
> 
> I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

Okay thanks 👍

**Review by SaraJaoude — APPROVED** [review]
looks good

**Comment by liza-bhutani** [comment]
Thanks for merging my PR😄

**Pull request merged**
