### PR TITLE
data: khushalarora

### PR DESCRIPTION
**Pull request by khushalarora**
## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers
Awesome and easy to understand documentation. Thanks for encourging me for my first PR :)

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5327"></a>

### CODE REVIEW

**Review by SurajPratap10 — APPROVED** [review]

**Review by yrncollo — APPROVED** [review]
Looks fine

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by SaraJaoude — APPROVED** [review]
looks good

**Comment by khushalarora** [comment]
Thank You :smiley:

**Pull request merged**
