### PR TITLE
Create moonLight-7k

### PR DESCRIPTION
**Pull request by moonLight-7k**

### CODE REVIEW

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Please rename your file and add `.json` in the end as file extension. 

Change `data/moonLight-7k`  ->  `data/moonLight-7k.json` [here](https://github.com/moonLight-7k/LinkFree/edit/patch-2/data/moonLight-7k).

**Comment by moonLight-7k** [comment]
I was unable to find the file I created previously, so I created this one  I'll delete the previous one soon.

**Comment by moonLight-7k** [comment]
Changed file name to moonLight-7k.json

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! 🎉

**Pull request merged**
