### PR TITLE
Update links.js for hiding reorder button when there are no links.

### LINKED ISSUE #8282: Hide Reorder button when there is no link added
### Description

We can hide the reorder button when there is no link added.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sanyamx**
## Fixes Issue #8282 

Edit by Eddie: to help maintainers close the issue when merged
fixes #8282 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8505"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Looks ok, but a `0` appears in it's place?

Screenshot 2023-08-05 at 08 53 38

**Comment by sanyamx** [comment]
> Looks ok, but a `0` appears in it's place?
> 
> Screenshot 2023-08-05 at 08 53 38

made the requested changes in the commit.

**Comment by sanyamx** [comment]
@eddiejaoude any updates?

**Comment by eddiejaoude** [comment]
Please only update your PR when it makes sense to, otherwise you are spamming the maintainers every time - we are working through notifications but all these extra notifications makes us go slower

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
