### PR TITLE
fix(animation): fade out on hover

### LINKED ISSUE #110: Change the profile photo opacity on hover
We can add a `:hover` CSS selector to fade the avatar in/out on hover.

### PR DESCRIPTION
**Pull request by krishguptadev**
fixes #110

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/611"></a>

### CODE REVIEW

**Comment by Vyvy-vi** [comment]
Hey there @krishguptadev, the profile picture bug has been fixed!
We could test this now, after you merge the `main` branch into this PR's branch!

**Review by Panquesito7 — APPROVED** [review]

**Review by ssensalo — APPROVED** [review]

**Review by Vyvy-vi — CHANGES_REQUESTED** [review]
Hey, um can you rebase your PR so that we can see how it looks?
Or, have you tested how it looks and can share that?

**Comment by Panquesito7** [comment]
> Hey, um can you rebase your PR so that we can see how it looks? Or, have you tested how it looks and can share that?

You can test it yourself by opening Gitpod for this PR. 🙂
https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/611

**Comment by krishguptadev** [comment]
> > Hey, um can you rebase your PR so that we can see how it looks? Or, have you tested how it looks and can share that?
> 
> You can test it yourself by opening Gitpod for this PR. 🙂 https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/611

I am confused, why to rebase when the branch is up-to-date?

**Comment by krishguptadev** [comment]
While hover:

image

Not on hover:

image

**Comment by Vyvy-vi** [comment]
Alright 🤔 
I don't know what the hover's purpose is for, but probably some design aesthetic...

**Review by Vyvy-vi — APPROVED** [review]
Thanks for contributing to LinkFree!

**Pull request merged**
