### PR TITLE
Dhruvverma28000 patch 1

### PR DESCRIPTION
**Pull request by dhruvverma28000**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3790"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
The other file from the `root directory` should be removed. Let us know if you need any help with this!

**Comment by dhruvverma28000** [comment]
Iam new to github please tell me steps on how to delete it
I just follwed steps for getting that link by eddie joude there was some
error in file name due to which i did it again. And 2 files went for pull
request.

**Comment by dhruvverma28000** [comment]
I have deleted the file named dhruvverma28000@json.

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Unfortunately you've removed both the files from your branch. You were only mean to delete the one in base folder.

Now it's like fresh start. So, you can now follow the steps in [docs](https://linkfree.eddiehub.io/docs/quickstart), add your file in `data/dhruvverma28000.json`. Let us know if you need any help with this. 🙂

**Comment by dhruvverma28000** [comment]
oops, I'll do it again 
thank you

**Pull request closed without merging**
