### PR TITLE
data:BaileyLuu

### PR DESCRIPTION
**Pull request by BaileyLuu**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2747"></a>

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by BaileyLuu** [comment]
Thank you so much! It feels great to make the first contribution to EddieHubCommunity! 😄

**Comment by Pradumnasaraf** [comment]
> Thank you so much! It feels great to make the first contribution to EddieHubCommunity! 😄

Awesome. Thank you

I just realized. You are  Bailey from the MLH community. Hey hey :)

**Comment by eddiejaoude** [comment]
Welcome @BaileyLuu 🎉 We look forward to more geeking out in EddieHub 💯

**Pull request merged**
