### PR TITLE
Update devsachinsharma.json

### PR DESCRIPTION
**Pull request by devsachinsharma**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5184"></a>

### CODE REVIEW

**Review by TRohit20 — COMMENTED** [review]
Looks like just a minor edit. If that's all. LGTM!

**Review by Krishnapro — COMMENTED** [review]
I think some changes will be please check.

**Comment by SurajPratap10** [comment]
Check for the conflict first

**Review by kumarsonsoff3 — APPROVED** [review]

**Review by kumarsonsoff3 — APPROVED** [review]
Hey @devsachinsharma, you had merge conflicts with your file as your fork seems to be outdated. 

Try updating your fork branch using the `Sync` button [here](https://github.com/devsachinsharma/LinkFree).

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Please check the inline comment above.

**Review by devvsakib — CHANGES_REQUESTED** [review]
Your PR has conflict

**Review by TRohit20 — APPROVED** [review]

**Comment by eddiejaoude** [comment]
@devvsakib please do not duplicate the comments, it does not help and creates noise - pleas read the existing timeline first

**Comment by SaraJaoude** [comment]
Given the length of time this Pull Request has been open and the conflicts have not been resolved, I will be closing it. 

If you wish to make changes to your Profile I suggest you look at our Editing Guide in Docs which also contains a video as to how to avoid conflicts: https://linkfree.eddiehub.io/docs/how-to-guides/editing

**Pull request closed without merging**
