### PR TITLE
Update vishrut19.json

### PR DESCRIPTION
**Pull request by Vishrut19**

### CODE REVIEW

**Review by ChinmayMhatre — APPROVED** [review]

**Review by AbbeyIT — APPROVED** [review]
LGTM!

**Comment by Vishrut19** [comment]
> LGTM!

Thanks a lot @AbbeyIT !

**Review by kumarsonsoff3 — DISMISSED** [review]
Looks Good this time. 👍

**Comment by Vishrut19** [comment]
How to do it in this PR only ??

**Comment by Vishrut19** [comment]
@kumarsonsoff3 this is the original file that I already had in my linkfree codebase. You can check it too.

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by SaraJaoude — APPROVED** [review]
> this is the original file that I already had in my linkfree codebase. You can check it too.

Please update the filename to be the exact match (including case sensitive) as your GitHub username. 

Yes this is how you had it before, but future features are unlikely to work so we would recommend that this is updated. I will merge and update this for you. Your LinkFree Profile URL will be the same.

**Comment by Vishrut19** [comment]
Thanks a lot, @SaraJaoude! for merging my PR

**Pull request merged**
