### PR TITLE
Add: profile.json

### PR DESCRIPTION
**Pull request by Pajimo**
Profile addition to LinkFree

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1381"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
Your profile looks good. However, please revert the changes to the package lock file and the links file.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by kumarsonsoff3 — APPROVED** [review]
Code looks good to me. 🚀 

But could you please rename the file with `yourUsername.json`.
<hr/>

**Comment by Pajimo** [comment]
> Code looks good to me. 🚀
> 
> But could you please rename the file with `yourUsername.json`.

Thank you @kumarsonsoff3 , i just fixed it.

**Review by kumarsonsoff3 — APPROVED** [review]
Great! Good to goo! 🚀 🚀

**Review by Panquesito7 — APPROVED** [review]
Awesome, thanks! 🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient, Elegant

**Review by schmelto — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by emmalearnscode — APPROVED** [review]

**Pull request merged**
