### PR TITLE
data: Anmol-Baranwal

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

- `All new and existing tests passed` : I don't really know how this can be done since it is my first PR to this repo

- I have validated the JSON using the tool mentioned in the docs.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4470"></a>

### CODE REVIEW

**Review by iamthecloverly — APPROVED** [review]

**Review by priyankarpal — APPROVED** [review]
Awesome looks good.  LGTM 👍🏻

**Review by himanshu1221 — APPROVED** [review]
LGTM :+1:

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
