### PR TITLE
Abhi03 tech patch 1

### PR DESCRIPTION
**Pull request by Abhi03-tech**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3355"></a>

### CODE REVIEW

**Comment by Abhi03-tech** [comment]
Please go with last commit i.e. single commit for file Abhi03-tech

**Review by dan-mba — CHANGES_REQUESTED** [review]
Please move your profile to the data directory

**Comment by Abhi03-tech** [comment]
> Please move your profile to the data directory

I am unable to move my profile to directory. I am not getting the point.

**Comment by Abhi03-tech** [comment]
> Please move your profile to the data directory

I am unable to move my profile to data directory. don't know what is the issue.

**Comment by dan-mba** [comment]
> I am unable to move my profile to data directory. don't know what is the issue.

How are you editing the file?
If you are doing it on GitHub, there is a box with the name in it at the top.
Put `data/` in front of the filename in the box and it should be moved.

**Pull request closed without merging**
