### PR TITLE
data: darvesh29

### PR DESCRIPTION
**Pull request by darvesh29**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3916"></a>

### CODE REVIEW

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Your profile looks good. However, please move it into the data folder.

**Comment by darvesh29** [comment]
> Your profile looks good. However, please move it into the data folder.

how can i move it into data folder

**Comment by EmmaDawsonDev** [comment]
Did you create it locally or on GitHub? 

If you did it locally you can move the file and then commit the changes. If you did it on GitHub you might need to copy everything and redo the PR

**Comment by darvesh29** [comment]
> If you did it on GitHub you might need to copy everything and redo the PR

i did it on github , when i trying to rename darvesh.json to data/darvesh.json it says darvesh.json file already exists , try with another name

**Comment by Pradumnasaraf** [comment]
> > If you did it on GitHub you might need to copy everything and redo the PR
> 
> i did it on github , when i trying to rename darvesh.json to data/darvesh.json it says darvesh.json file already exists , try with another name

Because you already have added the profile in https://github.com/EddieHubCommunity/LinkFree/pull/3806 PR

**Comment by darvesh29** [comment]
> > > If you did it on GitHub you might need to copy everything and redo the PR
> > 
> > 
> > i did it on github , when i trying to rename darvesh.json to data/darvesh.json it says darvesh.json file already exists , try with another name
> 
> Because you already have added the profile in #3806 PR

so now?what should i do?
why is this always be commited in root folder not on data folder , last time also this happened ,

**Comment by darvesh29** [comment]
> > > If you did it on GitHub you might need to copy everything and redo the PR
> > 
> > 
> > i did it on github , when i trying to rename darvesh.json to data/darvesh.json it says darvesh.json file already exists , try with another name
> 
> Because you already have added the profile in #3806 PR
> 
> And it's live here - https://linkfree.eddiehub.io/darvesh29

okk got it 
thanks
didnt know that it gets merged 2 days ago

**Comment by EmmaDawsonDev** [comment]
So this can be closed?

**Comment by darvesh29** [comment]
> So this can be closed?

**Pull request closed without merging**
