### PR TITLE
Abhi jain patch 1

### PR DESCRIPTION
**Pull request by abhijain2003**

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
There is a conflict please resolve it.

**Comment by abhijain2003** [comment]
please check it now

**Review by priyankarpal — CHANGES_REQUESTED** [review]
Now also have
Screenshot from 2023-02-04 18-04-43

**Comment by abhijain2003** [comment]
how should I do, basically by mistaken I removed the package-lock.json file and later I added it as well, and that is conflicting error

can you help me

**Comment by priyankarpal** [comment]
hey  @abhijain2003  check this doc
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by priyankarpal** [comment]
@abhijain2003 I think you deleted a file.

**Comment by abhijain2003** [comment]
i think I messedup thinks

**Comment by priyankarpal** [comment]
You can close it. Create another fresh PR. don't forget to check the official doc https://linkfree.eddiehub.io/docs/quickstart

**Pull request closed without merging**
