### PR TITLE
Krishnapro  profile links added and update

### PR DESCRIPTION
**Pull request by Krishnapro**
## Changes proposed
- Add socials and links in my profile section please merge it 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2397"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
I think you need to update your branch

**Review by Krishnapro — COMMENTED** [review]
I think the conflict is resolved. please let me know.

**Comment by eddiejaoude** [comment]
It looks like your branch is out of date

**Comment by Krishnapro** [comment]
Hey @eddiejaoude , please help me 
I resolved the conflict and then push it but after some time conflict is there

**Comment by eddiejaoude** [comment]
I don't think you need to resolve the conflicts, I think it is because your branch is out of date.

It might be easier for you to create a new Pull Request with your profile json file?

**Pull request closed without merging**
