### PR TITLE
fix: data not to have stats property

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4652"></a>

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Hey, Eddie, a question.

If we remove that property, then how will people set if they want to have stats public or not?

**Comment by eddiejaoude** [comment]
Public stats has now been removed https://github.com/EddieHubCommunity/LinkFree/pull/4642

**Review by Pradumnasaraf — DISMISSED** [review]
Looks good. Removed the failing check (Profile name check Action)

**Review by Pradumnasaraf — APPROVED** [review]
Looks good!

**Comment by jayk-gupta** [comment]
What do I need to do to fix this, I can't get it?
I have this file and I can't see any stats property.
```
{
  "name": "Jay kumar Gupta",
  "type": "personal",
  "bio": "CSE Undergraduate,passionate about frontend developement",

  "links": [
    {
      "name": "Follow me on Twitter",
      "url": "https://twitter.com/jayk_gupta",
      "icon": "FaTwitter"
    },
    {
      "name": "Follow me on LinkedIn",
      "url": "https://www.linkedin.com/in/jay-kumar-gupta-ba0434201/",
      "icon": "FaLinkedIn"
    },
    {
      "name": "Follow me on Github",
      "url": " https://github.com/jayk-gupta",
      "icon": "FaGithub"
    }
  ]
}
```

**Comment by eddiejaoude** [comment]
I have removed it from all profiles @jayk-gupta , you do not need to do anything https://github.com/EddieHubCommunity/LinkFree/blob/main/data/jayk-gupta.json

**Comment by jayk-gupta** [comment]
okay, thanks!

 Now I have this link for my profile  : https://linkfree.eddiehub.io/jayk-gupta
I just wanted to ask that can I edit the UI of my profile and how do I add more content to my profile?

**Comment by eddiejaoude** [comment]
@jayk-gupta yes you can edit your profile, here are the official documentation https://linkfree.eddiehub.io/docs/how-to-guides/editing

Also in the documentation are more sections to add more information, events, testimonials, grouping links, tags and more

Any questions please ask in EddieHub Discord, not here as here it is notifying many people

**Comment by jayk-gupta** [comment]
> @jayk-gupta yes you can edit your profile, here are the official documentation https://linkfree.eddiehub.io/docs/how-to-guides/editing
> 
> Also in the documentation are more sections to add more information, events, testimonials, grouping links, tags and more
> 
> Any questions please ask in EddieHub Discord, not here as here it is notifying many people

Okay, thanks for the reply @eddiejaoude.
I would join the discord and sorry for asking here

**Pull request merged**
