### PR TITLE
fix : updating links

### PR DESCRIPTION
**Pull request by kartikgajjar7**

### CODE REVIEW

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Your suggested changes looks good to me, @kartikgajjar7 ! ✔️ 
But we need some more changes too, not sure if we should change someone else's profile! 

Required changes - 
- Line no. `9`, remove `.png`. (That should be link to profile)
-  Twitter account doesn't exist! (Link should be updated with the correct one! )

@abhaytaras7, if you'd like to make those changes!

**Comment by kartikgajjar7** [comment]
> Your suggested changes looks good to me, @kartikgajjar7 ! ✔️ But we need some more changes too, not sure if we should change someone else's profile!
> 
> Required changes -
> 
> * Line no. `9`, remove `.png`. (That should be link to profile)
> * Twitter account doesn't exist! (Link should be updated with the correct one! )
> 
> @abhaytaras7, if you'd like to make those changes!

yes right for twitter link we should ask him

**Review by abhaytaras7 — CHANGES_REQUESTED** [review]
twitter && github handles awaiting changes !!!!!!!

**Comment by kartikgajjar7** [comment]
> twitter && github handles awaiting changes !!!!!!!
you want to update or not ?

**Comment by kartikgajjar7** [comment]
> Your suggested changes looks good to me, @kartikgajjar7 ! ✔️ But we need some more changes too, not sure if we should change someone else's profile!
> 
> Required changes -
> 
> * Line no. `9`, remove `.png`. (That should be link to profile)
> * Twitter account doesn't exist! (Link should be updated with the correct one! )
> 
> @abhaytaras7, if you'd like to make those changes!

hey priyanshu i think we should only consider about GitHub link coz it s causing this issue
image

about social media links he/she will raise pr by self if they want to update .

**Comment by eddiejaoude** [comment]
Thank you for the improvements but I will close this PR because profile changes should only be raised by the profile owner

**Pull request closed without merging**
