### PR TITLE
Fix: Cannot de-select tag/skill in search page when coming from profile.

### LINKED ISSUE #7340: [BUG] Cannot de-select skill in search when coming from Profile
### Description

Clicking on a particular skill from a profile takes us to the search menu with that skill selected. That skill can not be unselected unless manually removed from the search bar.

Steps to reproduce: 

1. Go to the profile - https://linkfree.io/eddiejaoude
2. Select Javascript.
3. We are taken to the search menu with Javascript pre-selected.
4. When trying to un-select Javascript, it does not happen and one more tag of `javascript` appears.

### Screenshots

Steps to reproduce:
1.
Screenshot 2023-06-03 at 2 06 10 AM

2. 
Screenshot 2023-06-03 at 2 06 29 AM

3. 
Screenshot 2023-06-03 at 2 06 42 AM

### Additional information

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by ribhav-pahuja**
## Fixes Issue
Closes #7340 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

1. Go to a profile
Screenshot 2023-06-04 at 11 41 52 PM

2. Select any tag.
Screenshot 2023-06-04 at 11 41 59 PM

3. Try de-selecting it and it should work.
Screenshot 2023-06-04 at 11 42 05 PM

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7384"></a>

### CODE REVIEW

**Review by krishstwt — COMMENTED** [review]
It only improves consistency between the urls, how does it fix th deselect issue?

**Comment by ribhav-pahuja** [comment]
> It only improves consistency between the urls, how does it fix th deselect issue?

@krishstwt have you gone through the source code?

**Comment by krishstwt** [comment]
Yes I had a brief look, it is just a question I am curious about

**Comment by eddiejaoude** [comment]
> > It only improves consistency between the urls, how does it fix th deselect issue?
> 
> @krishstwt have you gone through the source code?

I think the inconsistency was the problem, when going to the search page it did not match the case, so could not be unselected

Thank you for your contribution @ribhav-pahuja and fixing the bug 👍 

Btw just a small recommendation, it is better to write a helpful reply to questions on your PR, after all, open source and pull requests are about collaboration over the code. Plus, a future employer might see this sort of reply and make a negative decision based on it.

**Review by eddiejaoude — APPROVED** [review]
It works great, thank you 👍

**Comment by ribhav-pahuja** [comment]
@eddiejaoude gotcha! I will keep this in mind.
Also, thanks for merging the PR!

**Pull request merged**
