### PR TITLE
Testimonial button added to profile page

### LINKED ISSUE #2443: [FEATURE] Submit a testimonial from UI
### Description

Idea

From a linkfree profile testimonials tab, there should be a way for a profile visitor to click to add a testimonial.  This could simply open a new testimonial issue template for now

Future....
In the future, it could allow for submission of non-Github user testimonials

Concerns to consider (if we pursue a non GH version):
Approval flow for a testimonial
Authentication of a person providing the testimonial - for example, if they are not a GH user could they authenticate via linkedIn or twitter?

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

fixes #2443 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot 2023-01-03 at 18 24 51

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2627"></a>

### CODE REVIEW

**Review by amandamartin-dev — COMMENTED** [review]
LGTM but i saw you have one test failing. I'm not sure what is wrong from looking though.  Also just a reminder to check mobile view if you have not to make sure the length of the submit button is not blocking anything important in the UI

**Comment by eddiejaoude** [comment]
> LGTM 

Thank you 👍 

> i saw you have one test failing. I'm not sure what is wrong from looking though

oops, I will take a look

> just a reminder to check mobile view if you have not to make sure the length of the submit button is not blocking anything important in the UI

Oh yes let me double check

**Comment by eddiejaoude** [comment]
I think for mobile, it will be over some items but not blocking them completely

Screenshot 2023-01-03 at 19 24 50

**Review by amandamartin-dev — APPROVED** [review]
Agree! It's not blocking anything and can be improved in the future as needed/folks come up with ideas

**Comment by schmelto** [comment]
Is this something that should be only displayed in the testimonials tab in the profile?

**Comment by eddiejaoude** [comment]
I thought of this idea also, but then realised if the person has no testimonials the tab is not displayed and then the button would not be reachable - I think there are definitely improvements we can make to this button though 👍

**Pull request merged**
