### PR TITLE
fix: prevent eventcard overflow on hover

### PR DESCRIPTION
**Pull request by GauravBurande**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
https://user-images.githubusercontent.com/100035026/220453793-aaf8dae2-38de-4b58-b2c7-54f1b6a56000.webm

## Note to reviewers: I've changed the hover effects, you can see it in the above video, let me know if it's fine or if I should change the hover effects, which solves the problem of overflowing of eventcards on devices in between of desktop and smartphones.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5143"></a>

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
Looks good 🎉

**Review by SurajPratap10 — APPROVED** [review]
looks good

**Review by amandamartin-dev — APPROVED** [review]
lgtm!

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! :tada:

**Pull request merged**
