### PR TITLE
Updated Search page UI

### LINKED ISSUE #3849: [FEATURE] Add filter tags on Search page as well
### Description

Right now we are allowing users to click on tags in the discover page and then it redirects them to the search page with the found results but this introduces a bit of time lag which is kind of annoying. Why not add these tags on the search page as well so that it's convenient for users to search profiles with the help of it rather than just making them type it out in the search bar?

### Screenshots

image

### Additional information

I would like to get assigned for this issue.

### PR DESCRIPTION
**Pull request by Ananya2001-an**
## Fixes Issue

closes #3849 

## Changes proposed

Added filtering option with tags on Search page as well. Users can select and deselect tags to get the desired results based on the combination chosen. For example: if I select tags open source and DevOps then only those users that have both of these tags will be shown. You can click on the tag again to remove the selection. You can also manually type out in the search bar to get the results otherwise use tags directly. When the user selects a tag from the discover page or their LinkFree profile, it will redirect them to the search page showing the results along with the highlighted tag.    

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

LinkFree-Search-Users

LinkFree-Search-Users1

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4000"></a>

### CODE REVIEW

**Comment by Ananya2001-an** [comment]
Working on the build fail

**Comment by eddiejaoude** [comment]
@Ananya2001-an did you mean to close the pull request?

**Comment by Ananya2001-an** [comment]
@eddiejaoude I didn't mean to close it. But since I clicked on update main branch accidentally it discarded those changes. But I have the new PR open at #4030. And I am making all my commits to it right now.

**Comment by eddiejaoude** [comment]
Ok thank you 👍

**Pull request closed without merging**
