### PR TITLE
data:Dheerajjha451

### PR DESCRIPTION
**Pull request by Dheerajjha451**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7050"></a>

### CODE REVIEW

**Review by Krishnapro — APPROVED** [review]
Looks good to me 🚀 Thanks for contributing

**Review by Vishrut19 — APPROVED** [review]
Looks Good!

**Review by SaraJaoude — APPROVED** [review]
looks good

**Comment by Dheerajjha451** [comment]
Thank You!!!

**Pull request merged**
