### PR TITLE
removed extra main tag

### LINKED ISSUE #4224: Nested main tags
### Description

On the landing page there are two main tags one nested inside the other when there should only be one.

### Screenshots

Screenshot_20230129_164626

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alokVerma749**
## Fixes Issue

Closes #4224 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [  ] My change requires changes to the documentation.
- [  ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

Extra main tag is removed

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4243"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you for the contribution.

It looks like you have used `npm install` instead of `npm ci` from the docs, this causes the generated file `package-lock.json` to be updated, this is not a problem but these should not be committed without specific changes to `package.json`.
https://linkfree.eddiehub.io/docs/environments/local-development

Please remove the unrequired changes with:

- `git checkout main -- package-lock.json`

It is always best to check file changed with `git status -s` before doing a commit and never use `.` in your git commands as this will include files you may not want.

Any questions come and ask in the EddieHub Discord http://discord.eddiehub.org

**Comment by alokVerma749** [comment]
ok i will take care of all this from now

**Comment by alokVerma749** [comment]
Here i made a new fresh PR: #4317

**Comment by eddiejaoude** [comment]
Please close this PR if it is no longer needed

**Comment by eddiejaoude** [comment]
I

**Pull request closed without merging**
