### PR TITLE
adding my profile to the project

### PR DESCRIPTION
**Pull request by neutr0n420**
## Fixes Issue
I am trying to add my profile's JSON file to the webpage

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1797"></a>

### CODE REVIEW

**Review by imlakshay08 — APPROVED** [review]
Congratulations on your first PR! Keep up the good work mate.

**Review by EmmaDawsonDev — APPROVED** [review]

**Comment by neutr0n420** [comment]
Thank you @imlakshay08 for approving these changes!!! when will my pr is going to merge?

**Comment by EmmaDawsonDev** [comment]
> Thank you @imlakshay08 for approving these changes!!! when will my pr is going to merge?

Once there are 2 maintainer approvals it will be merged

**Comment by neutr0n420** [comment]
> > Thank you @imlakshay08 for approving these changes!!! when will my pr is going to merge?
> 
> Once there are 2 maintainer approvals it will be merged

Thanks for the help @EmmaDawsonDev

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thanks! 🎉

**Pull request merged**
