### PR TITLE
Navigation bar animation

### LINKED ISSUE #4320: [FEATURE]  Add animation
### Description

It could be a good addition, if we add animation when clicking on hamburger menu (Dropdown menu).

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SyedImam1998**
## Fixes Issue

fixes #4320 

## Changes proposed

1. I have made the nav tag and its first child as a relative position with the z-index of 30.
2. I have made the nav tag's  2nd  child as absolute position and with z-index of 20 so that it slides under the nav tag.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### Before:
linkfree nn1

### After:
linkfree nn

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4382"></a>

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
LGTM 👍🏻

**Comment by SyedImam1998** [comment]
> LGTM 👍🏻

Thanks for the Feedback Mate !!!

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Looks good 👍 

Please could you update your fork/branch with the latest changes, then we should be able to merge

**Comment by SyedImam1998** [comment]
> Looks good 👍
> 
> Please could you update your fork/branch with the latest changes, then we should be able to merge

Done @eddiejaoude  🐱‍🏍

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
