### PR TITLE
data:tobySolutions

### PR DESCRIPTION
**Pull request by tobySolutions**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

This PR is to add a testimonial to my profile by @krshkun.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3818"></a>

### CODE REVIEW

**Comment by tobySolutions** [comment]
Please review @Pradumnasaraf, @eddiejaoude, @EmmaDawsonDev!!

**Comment by eddiejaoude** [comment]
@tobySolutions please give the maintainers some time, we get the notification that the pull request was created. Please do not create extra notifications for the maintainers by tagging them also

If a few days have gone by then you might want to nudge us but not after a few minutes please

**Comment by tobySolutions** [comment]
Thank you so much @eddiejaoude for pointing that out, I'm very sorry for the irritable behaviour. Do forgive me, this won't happen again. 

Once again, I'm very sorry.

**Comment by eddiejaoude** [comment]
No problem, just making you aware 👍

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by tobySolutions** [comment]
> Looks good 👍 

Thank Eddie!!

**Pull request merged**
