### PR TITLE
data:MAYANKpandey14

### PR DESCRIPTION
**Pull request by MAYANKpandey14**
Creating my LinkFree profile

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5369"></a>

### CODE REVIEW

**Review by SurajPratap10 — APPROVED** [review]

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks for your Contribution! 🎉

**Review by mahfuztbt — APPROVED** [review]

**Review by vedprakashnautiyal — APPROVED** [review]

**Comment by MAYANKpandey14** [comment]
Hey, quick question I have a PR pending for a issue to submit . Earlier what happened was when i was making any PR all the changes for the issue and my profile were being pushed together . 
Should i wait for this pr to be merge and then open a new pull request for the issue, I am not sure what to do .

**Review by amandamartin-dev — APPROVED** [review]
lgtm!

**Comment by amandamartin-dev** [comment]
> Hey, quick question I have a PR pending for a issue to submit . Earlier what happened was when i was making any PR all the changes for the issue and my profile were being pushed together . Should i wait for this pr to be merge and then open a new pull request for the issue, I am not sure what to do .

Your new PR should only contain the changes relevant to the issue.  I have just merged this profile in so you should be able to update your branch by pulling in main.

In the future to prevent this type of issue, make sure to make a new branch off of main so that you don't have multiple unrelated changes in the same branch.  

If you have some trouble, you can ask in discord or comment on your other PR for some assistance from the community

Thank you for your contributions!

**Comment by MAYANKpandey14** [comment]
> > Hey, quick question I have a PR pending for a issue to submit . Earlier what happened was when i was making any PR all the changes for the issue and my profile were being pushed together . Should i wait for this pr to be merge and then open a new pull request for the issue, I am not sure what to do .
> 
> Your new PR should only contain the changes relevant to the issue. I have just merged this profile in so you should be able to update your branch by pulling in main.
> 
> In the future to prevent this type of issue, make sure to make a new branch off of main so that you don't have multiple unrelated changes in the same branch.
> 
> If you have some trouble, you can ask in discord or comment on your other PR for some assistance from the community
> 
> Thank you for your contributions!

Thank you Amanda , I was thinking of making a new branch but got confused .

**Pull request merged**
