### PR TITLE
data: Sahilll15

### PR DESCRIPTION
**Pull request by Sahilll15**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8538"></a>

### CODE REVIEW

**Review by accodes21 — COMMENTED** [review]
Looks good but can you move the ```tags``` to below ```bio```

**Comment by Sahilll15** [comment]
@accodes21 done!!!

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks for Contributing! 🎉 

<p align="center"><a href="https://linkfree.io/docs/how-to-guides/editing"></a></p>

**Comment by Sahilll15** [comment]
what does it take to join the organisation???

**Comment by kumarsonsoff3** [comment]
> what does it take to join the organisation???

To join the GitHub org, [create an issue in the support repo](https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization), and you'll receive an invite!

**Pull request merged**
