### PR TITLE
A pull request for my linkfree contribution

### PR DESCRIPTION
**Pull request by Ewaaugustine**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4472"></a>

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
LGTM 👍🏻

**Comment by Ewaaugustine** [comment]
Thanks for the approval and the support.

Please which others contributions can i make?
 i'm still trying to understand a large codebase, how to understand an
issues that needs to be fixed etc

**Comment by priyankarpal** [comment]
@Ewaaugustine you can check issues or you can join the discord.

**Comment by kumarsonsoff3** [comment]
Hey Augustine, you can check out the other issues on LinkFree you can contribute to. 

Here is a great article by Pradumna explaining other 5 ways you can find open-source projects you can contribute to: https://blog.pradumnasaraf.dev/5-ways-to-find-projects-in-open-source

>i'm still trying to understand a large codebase, how to understand an issues that needs to be fixed etc

- You can be good at these by practicing, but one thing I wanted to add is that you can look at the past closed and merged PRs. It really helps you to understand the codebase of a project easily when you took reference to an issue. 
- For any issue you feel like you can fix, you can always ask the maintainers if you have any confusion about what changes needed to be made and where, or if you need more info about that. 🤝 

Hope this helps! 
Happy Open-Sourcing! 🚀

**Review by kumarsonsoff3 — APPROVED** [review]

**Pull request merged**
