### PR TITLE
Updated more social links and added an avatar

### PR DESCRIPTION
**Pull request by Its-Aman-Yadav**
Closes #4133

## Changes proposed
I have added more Social links and an avatar to my profile

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4237"></a>

### CODE REVIEW

**Review by Ananya2001-an — COMMENTED** [review]
Avatar field is no longer needed because of a recent update, please remove it.

**Comment by Its-Aman-Yadav** [comment]
@Ananya2001-an done di 👍

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks for your contribution! 🎉 

<p align="center"></p>

**Pull request merged**
