### PR TITLE
add test for popular profile search

### LINKED ISSUE #2084: [OTHER] Test for popular profile.
### What would you like to share?

Test for the most popular profile  to appear at the top of the list when opening the popular page.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jaynarayan-vaishnav**
## Fixes Issue
Closes #2084 

## Changes proposed
- skeleton for testing wheather the popular profile is displayed at the top in the popular page.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
 
##Screenshot:

popuular

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2088"></a>

### CODE REVIEW

**Comment by jaynarayan-vaishnav** [comment]
Ready for review Thanks for letting me contribute to this repo 😌

**Review by eddiejaoude — APPROVED** [review]
LGTM 👍

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
This test needs to go into the relevant file

**Comment by jaynarayan-vaishnav** [comment]
@eddiejaoude I made the required changes can you please check whether they are relevant on not.

**Review by eddiejaoude — APPROVED** [review]
LGTM 👍

**Pull request merged**
