### PR TITLE
data:abhiraj-ku

### PR DESCRIPTION
**Pull request by abhiraj-ku**
## Changes proposed
Created LinkFree profile

## Check List (Check all the applicable boxes) 

- [X ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ X] This PR does not contain plagiarized content.
- [ X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4511"></a>

### CODE REVIEW

**Review by Sindhuinti — APPROVED** [review]
LGTM 👍🏻

**Review by priyankarpal — APPROVED** [review]
Looks Great

**Review by Hrishi5111998 — APPROVED** [review]
LGTM

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
