### PR TITLE
Update juliafmorgado.json

### PR DESCRIPTION
**Pull request by juliafmorgado**
Update my LinkFree page

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2436"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
@juliafmorgado I think you have the GitHub Actions running in your fork which is adding changes

**Comment by juliafmorgado** [comment]
> @juliafmorgado I think you have the GitHub Actions running in your fork which is adding changes

How do I stop it?

**Comment by Panquesito7** [comment]
> How do I stop it?

I believe you can disable Actions in the repository settings. https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository

**Review by Pradumnasaraf — APPROVED** [review]
It was kind of hard to revert those. I have done it for you so that you get your updated profile ASAP :)

Looks good to merge. Thank you for your contribution! :tada:

**Comment by juliafmorgado** [comment]
Thank you!!

**Pull request merged**
