### PR TITLE
RahulkumarRV profile added

### PR DESCRIPTION
**Pull request by RahulkumarRV**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1603"></a>

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Please revert `package-lock.json` file. If you need any help feel free to reach out.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Profile looks good but please revert the changes to the package-lock file.

**Comment by RahulkumarRV** [comment]
how to revert package-lock.json?
please can you explain to me why I need to revert?

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Since you run `npm`, it automatically updates the package version to the latest! Changes in dependencies file may leads to further conflicts, so you need to revert these! 

Simply just make these 2 changes to revert those: 
- line no `9`, change the package version back to initial as suggested below! 
- Remove the `empty endline` from `package-lock.json` file!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

**Comment by EmmaDawsonDev** [comment]
How’s this going for you @RahulkumarRV ?

**Comment by EmmaDawsonDev** [comment]
Since this has not been updated for a while I will close it for now. Feel free to open a new PR with your profile but without committing the package lock file.

**Pull request closed without merging**
