### PR TITLE
data: Bharath292003

### PR DESCRIPTION
**Pull request by Bharath292003**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8058"></a>

### CODE REVIEW

**Comment by sandramsc** [comment]
Update your file so it ends with .json 
scre

**Comment by Bharath292003** [comment]
> Update your file so it ends with .json scre

yeah i updated ,thank you :)

**Review by sandramsc — APPROVED** [review]
File looks good.
welcome_to_linkfree

**Comment by Bharath292003** [comment]
> File looks good. welcome_to_linkfree

where can i find my link after it is merged?

**Review by kumarsonsoff3 — APPROVED** [review]

**Comment by kumarsonsoff3** [comment]
Looks good, Thanks! 🎉 

> where can i find my link after it is merged?
At `https://linkfree.io/Your_Username`, which should be https://linkfree.io/Bharath292003

**Pull request merged**
