### PR TITLE
Create myrausman.json

### PR DESCRIPTION
**Pull request by Myrausman**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8753"></a>

### CODE REVIEW

**Review by sital002 — CHANGES_REQUESTED** [review]
Your filename must match your github username. Please move the file from data/Myrausman/myrausman.json to data/Myrausman.json.

**Comment by Myrausman** [comment]
@sital002  done

**Comment by sital002** [comment]
> @sital002 done

Your filename isnot matching your github username, it's case sensitive so please change your filename to data/Myrausman.json

**Comment by Myrausman** [comment]
@sital002 done

**Pull request merged**
