### PR TITLE
ci: exclude from hacktoberfest

### LINKED ISSUE #1811: Add hacktoberfest topic + automate exclude label for profiles
### What would you like to share?

- add hacktoberfest label to repo 
- automate with Reviewpad adding label `hacktoberfest-invalid` if there is a profile change

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

fixes #1811 

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1812"></a>

### CODE REVIEW

**Review by schmelto — APPROVED** [review]
## Looking good to me

Your suggested changes looking good to me.

---
**Summary:** :ok_hand: This code looks good

**Comment by eddiejaoude** [comment]
ok I will merge and we can test it 👍

**Comment by schmelto** [comment]
image

@eddiejaoude

**Comment by eddiejaoude** [comment]
oh 😱

**Comment by schmelto** [comment]
Not sure if this is also a general issue cause I saw similar behavior of reviewpad in our actions before that change ig.

**Comment by eddiejaoude** [comment]
I think they had a bug, but it was suppose to be fixed recently. I have a temporary solution if we need to, but maybe let's see if it was a glitch in the matrix. If it happens again please let me know

**Pull request merged**
