### PR TITLE
Add my profile

### PR DESCRIPTION
**Pull request by ezinneanne**
## Changes proposed
**I added my profile details**

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers
**I added my details for my profile**

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1243"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please revert the changes in the `package-lock.json` file. Let us know if you need any help. :)

**Comment by ezinneanne** [comment]
**I have corrected the error. Please could you review it one more time**

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍

**Review by vikasganiga05 — APPROVED** [review]
Looks good to me :+1: Thanks for adding your profile :pray:

**Review by kumarsonsoff3 — APPROVED** [review]
LGTM 👍

**Review by Pradumnasaraf — APPROVED** [review]
Looks great to me! 👍 Thank you for the contribution!

📄 [EddieHubCommunity/Hacktoberfest/1005](https://github.com/EddieHubCommunity/hacktoberfest-practice/pull/1005#pullrequestreview-927142939)

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by schmelto — APPROVED** [review]
## Looking good to me

Your suggested changes looking good to me.
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Pull request merged**
