### PR TITLE
Adding my profile

### PR DESCRIPTION
**Pull request by youhavechad**
Adding my profile and links. I'm pretty new to open source. Let me know if I made a mistake. Thanks.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/643"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please revert the changes in the `package-lock.json` file.

**Review by Panquesito7 — APPROVED** [review]

**Comment by eddiejaoude** [comment]
Great collaboration 👍

**Comment by eddiejaoude** [comment]
oops sorry meant to hit `comment` not `close` 🤦‍♂️

**Comment by eddiejaoude** [comment]
I think it is time for my bed 😂 - but I will merge first

**Comment by youhavechad** [comment]
Thanks and great GitHub profile course!

**Pull request merged**
