### PR TITLE
improve appearance of GitHub accelerator section

### LINKED ISSUE #6658: Footer GitHub accelerator image pixelates on larger screens
### Description

A higher quality image can be added and a `bg-contain` classname for smaller devices?

image

image

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by plbstl**
## Fixes Issue

Fixes #6658 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

**Before:**

<details>
<summary>Larger Screen</summary>
<br/>

Appearance on larger screens before changes
</details>

<details>
<summary>Smaller Screen</summary>
<br/>

Appearance on smaller screens before changes
</details>

**After:**

<details>
<summary>Larger Screen</summary>
<br/>

Appearance on larger screens after changes
</details>

<details>
<summary>Smaller Screen</summary>
<br/>

Appearance on smaller screens after changes
</details>

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8159"></a>

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
@plbstl can you can screenshots of the changes please.

**Comment by plbstl** [comment]
They're in the pull request description

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
This looks really good and I learnt a lot from it, but the SVG is almost 200kb

I don't think it needs to be so perfect, but we should try to keep the page lighter weight as the homepage should be as fast as possible

**Comment by SaraJaoude** [comment]
Thank you for your contribution but, due to lack of activity I am going to close this Pull Request.

**Pull request closed without merging**
