### PR TITLE
data: Parsifal-M

### PR DESCRIPTION
**Pull request by Parsifal-M**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Hey :wave: I hope this is okay? Please let me know if otherwise.

Thanks!

Signed-off-by: Peter Macdonald <macdonald.peter90@gmail.com>

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2925"></a>

### CODE REVIEW

**Review by yashdev9274 — APPROVED** [review]
This profile is set to build.
No error so far, all links are working properly, format is also perfect.

**Review by dan-mba — APPROVED** [review]
Looks good to me

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍 

Great collaboration 💪 

You can also join us in the EddieHub Discord http://discord.eddiehub.org

**Pull request merged**
