### PR TITLE
BUG Fix: Events are now sorted in date ascending order

### PR DESCRIPTION
**Pull request by tanbirali**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots
Screenshot (135)

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8158"></a>

### CODE REVIEW

**Review by amandamartin-dev — COMMENTED** [review]
The sorting looks good, but there is something going on between. your branch and what is on the live site.  When I loaded your branch into Gitpod to test, the border CSS color is missing on all the cards.  Can you take a look and see if you can tell what's up?

**Comment by tanbirali** [comment]
Okay let me take a look and see

**Comment by tanbirali** [comment]
Please check the PR now, I assume it was because my branch was not updated with the repository, I have updated it and now it should work fine.

**Comment by eddiejaoude** [comment]
Great collab 💪  thank you both!

**Pull request merged**
