### PR TITLE
data: Abid-dev

### PR DESCRIPTION
**Pull request by Abid-dev**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

To add myself to linkfree

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5506"></a>

### CODE REVIEW

**Review by khushalarora — APPROVED** [review]
Looks good :tada:

**Review by bkpecho — APPROVED** [review]
Thanks for your contribution! @Abid-dev 🎉

Good luck on your open-source journey! I hope you have a great day ahead.

**Review by amandamartin-dev — APPROVED** [review]

**Review by schmelto — APPROVED** [review]

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
