### PR TITLE
data: dmprieto

### PR DESCRIPTION
**Pull request by dmprieto**
## Note to reviewers
Added my bio info after following https://linkfree.eddiehub.io/docs/quickstart docs

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4326"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Your filename must match your GitHub username. In this case, it should be `dmprieto`.
Please update accordingly. Do let us know if you need any help with this. 🙂

**Review by dmprieto — COMMENTED** [review]
I renamed the file to my github handle as requested

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
