### PR TITLE
Additional step for the users who have got the error: npm: command no…

### PR DESCRIPTION
**Pull request by Recognizeyourself**
…t found

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/47"></a>

### CODE REVIEW

**Comment by stemount** [comment]
There's so many ways to suggest someone installs Node.js, and unfortunately putting any information about how to get Node.js will end up becoming stale just in case in the future for example Windows Terminal magically installs things like `npm` or `node` if you don't have it.

**Comment by Recognizeyourself** [comment]
> There are so many ways to suggest someone installs Node.js, and unfortunately putting any information about how to get Node.js will end up becoming stale just in case in the future for example Windows Terminal magically installs things like `npm` or `node` if you don't have it.

Thanks for notifying this Was not aware of it. This was my first ever pull request by the way. Learned a lot. 
I was hoping to get at least one green squares. 😅

**Comment by eddiejaoude** [comment]
@Recognizeyourself well done on your 1st pull request 🔥 . Keep going 💪  You got the green square and you will get many more 💥

**Comment by Recognizeyourself** [comment]
> @Recognizeyourself well done on your 1st pull request 🔥 . Keep going 💪 You got the green square and you will get many more 💥

Thanks to you !! Already a fan of Eddie community, More power to you sir 😁

**Pull request closed without merging**
