### PR TITLE
Responsive Profile Page

### LINKED ISSUE #2465: Responsiveness - Profile page
### Description

I am checking the responsive in 320px width

The profile image on the profile page looks odd in the mobile view
image

we can change the layout to this to prevent the name of wrapping and also saving to image from being distorted
image

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by stephenokyere233**
## Fixes #2465

 Closes #2465 

## Changes proposed

- Made profile page mobile responsive (especially 320px screens)

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

WhatsApp Image 2022-12-28 at 5 45 11 PM (1)

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2526"></a>

### CODE REVIEW

**Review by Aadarsh805 — CHANGES_REQUESTED** [review]
it's causing the profile icons to be centered on a desktop screen too

how it's supposed to be:
image

after this change:
image

**Comment by stephenokyere233** [comment]
> it's causing the profile icons to be centered on a desktop screen too
> 
> how it's supposed to be: image
> 
> after this change: image

I'll check that now @Aadarsh805

**Review by stephenokyere233 — COMMENTED** [review]
Okay I fixed that now @Aadarsh805

**Review by Aadarsh805 — APPROVED** [review]
Yep it's all good now, good work  👍

**Comment by stephenokyere233** [comment]
> Yep it's all good now, good work  👍

Thanks man!

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you 👍 

I don't think `package-lock.json` are needed. Could you also make other changes for example to `Event.js` in another PR, this PR should focus on the profile

**Comment by stephenokyere233** [comment]
> Thank you +1
> 
> I don't think `package-lock.json` are needed. Could you also make other changes for example to `Event.js` in another PR, this PR should focus on the profile

Actually after npm install `package-lock.json` was modified didn't wanna edit `.gitignore` so i rather left it. Anyways what updates would you like to see in the `Event.js` .

**Comment by eddiejaoude** [comment]
> Actually after npm install package-lock.json was modified didn't wanna edit .gitignore so i rather left it

It is better to use `npm ci` so the lock file is not modified without changes to `package.json` file. It correct that we should  not ignore this file - maybe we need to improve the docs?

> what updates would you like to see in the Event.js 
I was suggesting the changes you made to the events file should be in another PR as I don't think they are related to the issue this PR is solving?

**Comment by stephenokyere233** [comment]
> > Actually after npm install package-lock.json was modified didn't wanna edit .gitignore so i rather left it
> 
> It is better to use `npm ci` so the lock file is not modified without changes to `package.json` file. It correct that we should not ignore this file - maybe we need to improve the docs?
> 
> > what updates would you like to see in the Event.js
> 
> I was suggesting the changes you made to the events file should be in another PR as I don't think they are related to the issue this PR is solving?

Okay the `Event.js` was pull was merged already so i think i'll have to make a new pull use `npm ci` like you said then add these changes again , I guess that will do

**Comment by eddiejaoude** [comment]
Oh if the `events.js` was already merged, then you can update your current PR and these will disappear - it means this PR includes the other changes probably because you branched from a previous PR and not the `main` branch

You can revert your changes to the lock file, but also if easier you can create a new PR but the discussion/collaboration will be lost

**Comment by stephenokyere233** [comment]
> Oh if the `events.js` was already merged, then you can update your current PR and these will disappear - it means this PR includes the other changes probably because you branched from a previous PR and not the `main` branch
> 
> You can revert your changes to the lock file, but also if easier you can create a new PR but the discussion/collaboration will be lost

I'm make a new PR and do it all over again , don't worry.

**Comment by eddiejaoude** [comment]
Ok, please reference this PR in the new PR, so it is all traceable

**Pull request closed without merging**
