### PR TITLE
Added my name in the list

### PR DESCRIPTION
**Pull request by umaresso**
removed package-lock file 
and Capitalized my bio

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1098"></a>

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@umaresso Again theres package.json. Please make a subbranch and do this there.

@Panquesito7 @emmalearnscode @umaresso Please close this.

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
Deleting the package-lock file removes it from the project for everyone. Please restore the file by copying the package-lock from the main repo.

**Comment by emmalearnscode** [comment]
> @umaresso Again theres package.json. Please make a subbranch and do this there.
> 
> @Panquesito7 @emmalearnscode @umaresso Please close this.

It doesn't need closing, the package-lock just needs restoring

**Comment by umaresso** [comment]
i'm really sorry , i don't know about reverting

**Comment by umaresso** [comment]
i will make a new issue then :(

**Comment by KendallDoesCoding** [comment]
> i'm really sorry , i don't know about reverting

You can use github desktop

**Comment by KendallDoesCoding** [comment]
> i will make a new issue then :(

pull request*

**Pull request closed without merging**
