### PR TITLE
data: PritamSaha7.json

### PR DESCRIPTION
**Pull request by Saha-7**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7651"></a>

### CODE REVIEW

**Review by RohanSasne — CHANGES_REQUESTED** [review]
Can you please change your filename to your GitHub username, i.e. `Saha-7`

**Comment by Saha-7** [comment]
Screenshot 2023-06-17 212901
It's Showing this.

**Review by SaraJaoude — CHANGES_REQUESTED** [review]
@Saha-7 it looks like you already have a profile with your new GitHub username: https://github.com/EddieHubCommunity/LinkFree/blob/main/data/Saha-7.json - Please update that file with your latest changes and remove https://github.com/EddieHubCommunity/LinkFree/blob/main/data/PritamSaha7.json as this appears to be your old username.

**Comment by Saha-7** [comment]
Okay got it I am closing this PR.

**Pull request closed without merging**
