### PR TITLE
Create uvacoder.json

### PR DESCRIPTION
**Pull request by Uvacoder**
`<!--` If your PR fixes an open issue, use `Closes #999` to link your PR with the issue. #999 stands for the issue number you are fixing -->

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3928"></a>

### CODE REVIEW

**Comment by Uvacoder** [comment]
data: uvacoder

**Review by Tejender1521 — APPROVED** [review]
Everything looks good

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Filename case is not same as username. Please rename your file to `Uvacoder.json` 🛠

**Review by devvsakib — APPROVED** [review]
LGTM, but you can add tags to your profile
"tags": ["example", "example1"]

**Comment by ilhammeidi** [comment]
@Uvacoder please check this https://github.com/Uvacoder/starter-nextra-nextjs-docs/issues/1 and please respond asap.

Thanks

**Pull request merged**
