### PR TITLE
data: modirocks

### PR DESCRIPTION
**Pull request by modirocks**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4447"></a>

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
You might want to add some links, socials, and milestones to your profile. Check the LinkFree docs to get started with it: https://linkfree.eddiehub.io/docs/quickstart

**Review by priyankarpal — CHANGES_REQUESTED** [review]
I wanna say that please add at least one social link.

**Comment by modirocks** [comment]
> I wanna say that please add at least one social link.

yeah, sure

**Comment by SaraJaoude** [comment]
Hi @modirocks as @Panquesito7 mentioned, it is a good idea to add links to your socials to your Profile, so that people can look at your content and follow you/subscribe to you on those platforms. 

In addition to the Editing guide, you might also want to look at the Social shortcuts guide: https://linkfree.eddiehub.io/docs/how-to-guides/socials-shortcuts

But, not having links does not mean you cannot have your Pull Request merged - I will do this now and I would suggest you raise a new PR when you are ready to add links, testimonials etc.

**Pull request merged**
