### PR TITLE
feat: add graduation Hat

### LINKED ISSUE #757: [FEATURE] Add Icon for University or School to use in Milestone Section
### Description

When adding graduation details in the milestones section of the profile, there is no school or university icon.

An Icon such as YouTube, Github in Milestone list if made available, those who want to add their graduation can make use of it.

- [ ] Added Icon for Uni/School

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by RagibAjmal**
## Fixes Issue

Closes #757 
## Changes proposed

Created a new file to add SVG of Graduation Hat , Added the SVG Component to the milestone.js

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/808"></a>

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
I'm not sure if we should add this 😅 I think we should only use from the official icon list. Let's see what other people think. Thank you. 😃

**Comment by Panquesito7** [comment]
Actually, never mind, just read the issue properly. 😅

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍

**Review by ssensalo — APPROVED** [review]

**Review by CodingSpecies — APPROVED** [review]

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
I’m not sure that creating a whole component for an icon is necessary, or the direction this project should take. There is already a discussion about icon packages and I think we should wait for that to be resolved or find something suitable from the current prime icons package. It is possible to request new icons by raising an issue on their repo here: https://github.com/primefaces/primeicons/issues

**Comment by eddiejaoude** [comment]
Thanks all 👍 

We should not add images to the project.

We will move to using another Icon library that will have more icons available

**Comment by Vyvy-vi** [comment]
Considering the recent developments and because this was added in the PR which integrated react-icons, we would have to close this PR. Thanks for opening the PR and contributing to LinkFree!

**Pull request closed without merging**
