### PR TITLE
data: kirtankp

### PR DESCRIPTION
**Pull request by kirtankp**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8394"></a>

### CODE REVIEW

**Comment by SaraJaoude** [comment]
@kirtankp can you please change the description to include the issue number this PR fixes?

**Comment by eddiejaoude** [comment]
I have updated the PR to `data: ...` to show it is a profile change

**Review by Sindhuinti — APPROVED** [review]

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! 🎉

**Comment by kirtankp** [comment]
> Looks good, Thanks! 🎉

Thanks

**Pull request merged**
