### PR TITLE
add: chandraprakash

### PR DESCRIPTION
**Pull request by Chandraprakash-Darji**

### CODE REVIEW

**Review by Njong392 — CHANGES_REQUESTED** [review]
You have your LinkedIn link twice. I'd advise that you remove one :)

**Review by Njong392 — APPROVED** [review]
Will just go ahead and approve this :) Even though there isn't a 'proper' way of writing the word "LinkedIn" per se, you could change the one you have, which is "LinkedIN", to one that is common (Linkedin or LinkedIn). This is totally optional btw.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Chandraprakash-Darji** [comment]
Fixed All ✅

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🎉


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Please update your filename to your `username.json` which should be `Chandraprakash-Darji.json`

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inelegant

**Comment by Chandraprakash-Darji** [comment]
`Merge branch 'EddieHubCommunity:main' into main` i done by the github online editor

**Review by kumarsonsoff3 — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant, Maintainable

**Pull request merged**
