### PR TITLE
Nikhilfy linkfree profile 

### PR DESCRIPTION
**Pull request by Nikhilfy**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5717"></a>

### CODE REVIEW

**Comment by Nikhilfy** [comment]
me making my linkfree
this community is awesome

**Review by khushalarora — CHANGES_REQUESTED** [review]
Hi @Nikhilfy, thank you for contributing :tada:

**Review by Nikhilfy — COMMENTED** [review]
Thanks for the Corrections

**Review by amandamartin-dev — APPROVED** [review]

**Comment by Nikhilfy** [comment]
thanks for the approval

**Pull request merged**
