### PR TITLE
feat: Add another layout

### PR DESCRIPTION
**Pull request by niranjank2022**
## Changes proposed
* Two columns (order: My Links & Milestones, Testimonials & Events) in Desktop version and Single column(order: My Links, Milestones, Testimonials, Events) in Mobile version
* Use of UserTab.js is avoided as it is unnecessary for this layout

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots
Screenshot (22)
Screenshot (23)
Screenshot (24)
Screenshot (25)
Screenshot (26)
Screenshot (27)
Screenshot (28)
Screenshot (29)
Screenshot (30)
Screenshot (31)
Screenshot (32)

## Note to reviewers

As this layout doesn't require UserTab.js, some lists and functions in UserPage.js can be modified or removed. I need the permission from reviewers to do that. Thank you!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7564"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for the contribution 👍 

- there are failing automated tests, please check the failing GitHub Action
- please add a screenshot to the PR description 
- as this is an additional layout, please add the new layout to new files as not to effect the current layout

**Comment by niranjank2022** [comment]
> Thank you for the contribution 👍
> 
> * there are failing automated tests, please check the failing GitHub Action
> * please add a screenshot to the PR description
> * as this is an additional layout, please add the new layout to new files as not to effect the current layout

Regarding new files,
Where to save them, inside the Components folder or someother folder? And also, how to name them?

**Comment by eddiejaoude** [comment]
> Regarding new files, Where to save them, inside the Components folder or someother folder? And also, how to name them?

Maybe `components/user/themes/grid/`

**Comment by niranjank2022** [comment]
> Thank you for the contribution 👍
> 
> * there are failing automated tests, please check the failing GitHub Action
> * please add a screenshot to the PR description
> * as this is an additional layout, please add the new layout to new files as not to effect the current layout

I think I have done all these. What else I have to do?

**Comment by eddiejaoude** [comment]
> > Thank you for the contribution 👍
> > 
> > * there are failing automated tests, please check the failing GitHub Action
> > * please add a screenshot to the PR description
> > * as this is an additional layout, please add the new layout to new files as not to effect the current layout
> 
> I think I have done all these. What else I have to do?

Thank you for making the changes 👍 I think there are large parts of the code that is duplicated, it would be better to move this to reusable components

**Comment by niranjank2022** [comment]
> > > Thank you for the contribution 👍
> > > 
> > > * there are failing automated tests, please check the failing GitHub Action
> > > * please add a screenshot to the PR description
> > > * as this is an additional layout, please add the new layout to new files as not to effect the current layout
> > 
> > 
> > I think I have done all these. What else I have to do?
> 
> Thank you for making the changes 👍 I think there are large parts of the code that is duplicated, it would be better to move this to reusable components

I'm not getting it. Can you please explain it elaborately?

**Comment by eddiejaoude** [comment]
> > Thank you for making the changes 👍 I think there are large parts of the code that is duplicated, it would be better to move this to reusable components
> 
> I'm not getting it. Can you please explain it elaborately?

I am suggesting to reduce the code duplication. I think there are a lot that is repeated from the original style, making these reusable component would be best

**Comment by Dev-Arhaan** [comment]
@niranjank2022 please point me towards your codebase, let me see if I can help with maintaining the reduundancy in the codebase by making reusable components

**Comment by niranjank2022** [comment]
> > > Thank you for making the changes 👍 I think there are large parts of the code that is duplicated, it would be better to move this to reusable components
> > 
> > 
> > I'm not getting it. Can you please explain it elaborately?
> 
> I am suggesting to reduce the code duplication. I think there are a lot that is repeated from the original style, making these reusable component would be best

Please apologize me for not being active in the last couple of days as I was caught up with College exams.

**Comment by niranjank2022** [comment]
> @niranjank2022 please point me towards your codebase, let me see if I can help with maintaining the reduundancy in the codebase by making reusable components

Yeah, sure. This [Link](https://github.com/niranjank2022/LinkFree/tree/change-layout/components/user/themes/grid) is for the folder that holds my changes in my fork

**Comment by niranjank2022** [comment]
> > > Thank you for making the changes 👍 I think there are large parts of the code that is duplicated, it would be better to move this to reusable components
> > 
> > 
> > I'm not getting it. Can you please explain it elaborately?
> 
> I am suggesting to reduce the code duplication. I think there are a lot that is repeated from the original style, making these reusable component would be best

You saying, that I have to create a component similar to UserTab.js, i.e. UserGrid.js, right?

**Comment by eddiejaoude** [comment]
Have a look how we have done different profile layouts already. You can add 1 more layout https://github.com/EddieHubCommunity/LinkFree/tree/main/components/user/themes

**Comment by eddiejaoude** [comment]
I will merge to a temporary branch and refactor the duplicate code to use the existing components

**Pull request merged**
