### PR TITLE
Add dark mode accessibility tests

### LINKED ISSUE #5975: [OTHER] - A couple of a11y issues in dark mode
### What would you like to share?

Looks like there are a couple of a11y issues on the homepage after a Lighthouse audit.

1. Buttons do not have an accessible name

Screenshot 2023-04-10 at 11 51 24 PM

2. Background and foreground colors do not have a sufficient contrast ratio.

Screenshot 2023-04-10 at 11 51 36 PM

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dan-mba**
## Changes proposed
Setup accessibility tests to specifically check light & dark mode
Closes #5975 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5992"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Oh wow awesome Dan ❤️

**Comment by dan-mba** [comment]
> Oh wow awesome Dan ❤️

Now we just need to fix the the failing tests 😒

**Comment by ChinmayMhatre** [comment]
The aria label issue is being addressed in #5975

**Review by eddiejaoude — APPROVED** [review]
Amazing work 🚀

**Pull request merged**
