### PR TITLE
data: Trikcode

### PR DESCRIPTION
**Pull request by Trikcode**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2820"></a>

### CODE REVIEW

**Comment by nanthakumaran-s** [comment]
@Trikcode The filename should match the GitHub username case... Please change `trikcode.json` to `Trikcode.json`

> NOTE: GitHub doesn't know filename case changes. The way is to delete the existing file, commit and then add your data with the filename as your GitHub username.

**Comment by nanthakumaran-s** [comment]
Also, I think there is no provision for Cloudinary in the `next.config.mjs`

```diff
+ "avatar": "https://res.cloudinary.com/trikerl/image/upload/v1673061467/computer/img-2_ehxqwk.png",
```
Does it works on your local machine ???

@eddiejaoude can we add this to the config file?

**Comment by eddiejaoude** [comment]
Good spot @nanthakumaran-s yep we can add `cloudinary` the config if required 👍 

@Trikcode did you mean to close this pull request? If you need any help let us know

**Comment by eddiejaoude** [comment]
Ah I see there is a new pull request https://github.com/EddieHubCommunity/LinkFree/pull/2826

**Comment by Trikcode** [comment]
Yes! I did another one @eddiejaoude

**Pull request closed without merging**
