### PR TITLE
Updated milestone section

### PR DESCRIPTION
**Pull request by CBID2**
## Changes proposed

I updated my Milestones section 

## Check List (Check all the applicable boxes) 

- [X ] My code follows the code style of this project.
- [ X] My change requires changes to the documentation.
- [X ] I have updated the documentation accordingly.
- [X ] All new and existing tests passed.
- [ X] This PR does not contain plagiarized content.
- [ X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2114"></a>

### CODE REVIEW

**Comment by CBID2** [comment]
I also deleted the word public data

**Comment by CBID2** [comment]
I changed it to word data.

**Comment by eddiejaoude** [comment]
thank you, some feedback

- these changes should be in the `nextjs` branch
- all changes should be in their own branch, otherwise it will contain other changes

I will close the pull request, please can you create a new one

**Comment by CBID2** [comment]
Ok

**Pull request closed without merging**
