### PR TITLE
data: SwapnilPatle01

### PR DESCRIPTION
**Pull request by SwapnilPatle01**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4233"></a>

### CODE REVIEW

**Review by AgniveshChaubey — COMMENTED** [review]
Please write more about the additions/changes you made!

**Comment by SwapnilPatle01** [comment]
> Please write more about the additions/changes you made!

I can't understand what you are saying...

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by Ananya2001-an — APPROVED** [review]

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good to merge. Thanks for your contribution! 🎉 

<p align="center"></p>

**Pull request merged**
