### PR TITLE
data: AxelGarciaK

### PR DESCRIPTION
**Pull request by AxelGarciaK**
## Changes proposed

I have added my profile in LinkFree. 🎉 

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8426"></a>

### CODE REVIEW

**Review by Krishnapro — APPROVED** [review]
Looks good to me

**Comment by AxelGarciaK** [comment]
@Krishnapro Thanks mate! 😁

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Your file is in wrong directory! Please move your file into the `data` directory! 🛠

Change `LinkFree/data/AxelGarciaK.json`   --->   `data/AxelGarciaK.json` [here](https://github.com/AxelGarciaK/LinkFree/edit/AxelGarciaK-patch-1/LinkFree/data/AxelGarciaK.json)! 

Let us know if you need any help with this! :)
image

**Comment by AxelGarciaK** [comment]
Good catch @kumarsonsoff3, fixed!

**Review by SaraJaoude — APPROVED** [review]
Thanks for making the changes - looks good!

**Pull request merged**
