### PR TITLE
Add tailwind variables to styles in repos, admin page

### LINKED ISSUE #8441: [BUG] Light/Dark mode for new pages
### Description

Light/Dark mode has not been added to new pages

- manage repos `pages/manage/repos.js`
- admin section `pages/admin/*`
- profile repo list `components/user/UserRepos.js`

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ChinmayMhatre**
## Fixes Issue
fixes #8441 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8492"></a>

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
we do not have tailwind variables for these green,yellow,blue color. should they be created?
image

@eddiejaoude

**Comment by eddiejaoude** [comment]
> we do not have tailwind variables for these green,yellow,blue color. should they be created? image
> 
> @eddiejaoude

I would not worry about those for now, thank you for asking 👍

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by eddiejaoude** [comment]
Sorry you have a conflict, can you resolve? Any questions let me know

**Comment by ChinmayMhatre** [comment]
> Sorry you have a conflict, can you resolve? Any questions let me know

Fixed. Let me know if I missed anything👍🏻

**Review by eddiejaoude — APPROVED** [review]
Great, thank you 👍

**Pull request merged**
