### PR TITLE
Update README.md

### LINKED ISSUE #996: Arranging the icons of readme in order
### Description

The ICONS are not in order 

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Ash-KODES**
## Fixes Issue
Fixes #996 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1183"></a>

### CODE REVIEW

**Comment by Ash-KODES** [comment]
@vikasganiga05 please review

**Review by CodingSpecies — COMMENTED** [review]
@Ash-KODES I'm not sure, but I think this pr already covers the issue.

**Comment by Ash-KODES** [comment]
> @Ash-KODES I'm not sure, but I think this pr already covers the issue.

Ya but,there were few corrections in the previous PR so I mde a new one.

**Comment by CodingSpecies** [comment]
> > @Ash-KODES I'm not sure, but I think this pr already covers the issue.
> 
> Ya but,there were few corrections in the previous PR so I mde a new one.

Yes, sorry for the error I made. Thank you.

**Comment by Ash-KODES** [comment]
> > > @Ash-KODES I'm not sure, but I think this pr already covers the issue.
> > 
> > 
> > Ya but,there were few corrections in the previous PR so I mde a new one.
> 
> Yes, sorry for the error I made. Thank you.

:)

**Review by emmalearnscode — APPROVED** [review]
It looks good to me, thanks for your help 👍

**Review by vikasganiga05 — APPROVED** [review]
LGTM :+1: Well done 
:pray: Thanks for your contribution :tada:

**Review by ssensalo — APPROVED** [review]

**Review by krshdev — APPROVED** [review]
Looks good, Thanks 👍

**Review by schmelto — APPROVED** [review]

**Review by kumarsonsoff3 — APPROVED** [review]
LGTM 👍  Thanks for your contribution! 🚀🚀

**Comment by schmelto** [comment]
One tip for the future a pr that references and closes a issue should be linked with `fixes #issuenumber` so that the issue will automatically gets closed on pr merge. I've updated the pr description :)

**Pull request merged**
