### PR TITLE
New link(Updated With Milestones)

### PR DESCRIPTION
**Pull request by AliJafriETH**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2705"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
You have merge conflicts on your json file. Make sure you update your Fork before making changes!

Please resolve the merge conflicts on <kbd>data/AliJafriETH.json</kbd>. 
Let us know if you need any help with this! 🛠

**Comment by AliJafriETH** [comment]
Hey @kumarsonsoff3, thanks so much for the update :))
Could you please help me with the conflicts?

**Comment by AliJafriETH** [comment]
Hey @kumarsonsoff3, thank you so much for the update :))
Fixed it 👍

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Review by Panquesito7 — APPROVED** [review]
Amazing. Thanks! 🎉

**Comment by I-MirzaBaig** [comment]
MirzaBaig.json
Please review mine pull request

**Pull request merged**
