### PR TITLE
fix: Skip-Empty-Releases (#7496)

### PR DESCRIPTION
**Pull request by nitheesh-daram**
## Fixes Issue

#7496 

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7747"></a>

### CODE REVIEW

**Comment by nitheesh-daram** [comment]
https://github.com/EddieHubCommunity/LinkFree/issues/7496#issuecomment-1593344256

As mentioned here, I don't know how we can deploy only docs changes if there are any resources please share them here, I'll work on that also

**Comment by dan-mba** [comment]
> As mentioned here, I don't know how we can deploy only docs changes if there are any resources please share them here, I'll work on that also

Sorry for the delayed response.

In the [vercel workflow](https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/workflows/vercel.yml#L9-L14) you need to add a path for docs similar to the one for data.
```
- "pages/docs/**"
```

**Comment by nitheesh-daram** [comment]
> > As mentioned here, I don't know how we can deploy only docs changes if there are any resources please share them here, I'll work on that also
> 
> Sorry for the delayed response.
> 
> In the [vercel workflow](https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/workflows/vercel.yml#L9-L14) you need to add a path for docs similar to the one for data.
> 
> ```
> - "pages/docs/**"
> ```

No issues Dan! Thanks for the info , made the changes as required please review

**Review by dan-mba — APPROVED** [review]
Looks good to me

**Pull request merged**
