### PR TITLE
added my profile susheel.json

### PR DESCRIPTION
**Pull request by susheelpal**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1627"></a>

### CODE REVIEW

**Review by CodingSpecies — CHANGES_REQUESTED** [review]
@susheelpal I think the package-lock.json changes need to be reverted. Thank you.

**Review by Njong392 — CHANGES_REQUESTED** [review]
The addition of your profile looks great, but I don't think you're allowed to make changes to the `package-lock.json`. Would you mind reverting these changes?

**Comment by susheelpal** [comment]
yeah sure will do it. but I don't know how to revert the changes. could you please tell me? thank you

**Comment by Njong392** [comment]
> yeah sure will do it. but I don't know how to revert the changes. could you please tell me? thank you

Shows that you changed version from "version":"0.70.1" to "version":"0.70.17" Must've been a small typo on your part. Remove the extra 7, commit your changes and push again.

**Comment by susheelpal** [comment]
> > yeah sure will do it. but I don't know how to revert the changes. could you please tell me? thank you
> 
> Shows that you changed version from `"version":"0.70.1"` to `"version":"0.70.17"` Must've been a small typo on your part. Remove the extra 7, commit your changes and push again.

I have not changed the version. this version has released 11 days ago. so I have updated it to the current version.

**Comment by Njong392** [comment]
> 
> I have not changed the version. this version has released 11 days ago. so I have updated it to the current version.

I understand. If you typed it in yourself, then you'll need to revert. If the version was updated after you installed dependencies, then I think it's fine.

**Review by Njong392 — APPROVED** [review]
I understand. If you inputted this by hand, you'll have to revert, I think. If the changes came along when you downloaded dependencies then it's fine. Normally, there should be changes only to one file

**Review by Njong392 — CHANGES_REQUESTED** [review]
I understand. If you inputted this by hand, you'll have to revert, I think. If the changes came along when you downloaded dependencies then it's fine. Normally, there should be changes only to one file

**Comment by Njong392** [comment]
> I understand. If you inputted this by hand, you'll have to revert, I think. If the changes came along when you downloaded dependencies then it's fine. Normally, there should be changes only to one file

Ignore this approval please.

**Comment by susheelpal** [comment]
> I understand. If you inputted this by hand, you'll have to revert, I think. If the changes came along when you downloaded dependencies then it's fine. Normally, there should be changes only to one file

I have not inputted the version by myself. I have cloned it today and requested PR.

**Comment by Njong392** [comment]
> I have not inputted the version by myself. I have cloned it today and requested PR.

Then awesome! So sorry for overhauling the issue :)

**Comment by susheelpal** [comment]
> > I have not inputted the version by myself. I have cloned it today and requested PR.
> 
> Then awesome! So sorry for overhauling the issue :)

It's okay. don't feel sorry. we are in a learning phase.

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Hey @susheelpal, you're required to make these changes to be good to goo! 

- Update your filename to your `username.json`, which should be `susheelpal.json`
- Revert the changes from the `package-lock.json` file! 

**[Click here](https://gist.github.com/kumarsonsoff3/fbc6ecde519250a9f0a4d7ccc9993a1a)** to know how and why to revert the changes from dependency file!

**Comment by susheelpal** [comment]
> @susheelpal I think the package-lock.json changes need to be reverted. Thank you.

could you please assure me? if yes, then please tell me how to revert the changes. Because I'm not sure about package-lock.json.will have to revert or not.

**Comment by susheelpal** [comment]
> Hey @susheelpal, you're required to make these changes to be good to goo!
> 
> * Update your filename to your `username.json`, which should be `susheelpal.json`
> * Revert the changes from the `package-lock.json` file!
> 
> **[Click here](https://gist.github.com/kumarsonsoff3/fbc6ecde519250a9f0a4d7ccc9993a1a)** to know how and why to revert the changes from dependency file!
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** hammer_and_wrench This code needs a fix  |  **Tags:** Inefficient, Inelegant

ok, thanks for the clarification.

**Comment by Njong392** [comment]
Thank you @kumarsonsoff3 for the clarifications :)

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🎉


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Review by kumarsonsoff3 — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant, Maintainable

**Pull request merged**
