### PR TITLE
Ayush sarode patch 1 1

### PR DESCRIPTION
**Pull request by AyushSarode**
Created json file

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2729"></a>

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

Sorry, my bad your previous file naming was okay, I got confused due to the Twitter handle. I have fixed it by myself

**Comment by AyushSarode** [comment]
> Looks good to merge. Thank you for your contribution! 🎉
> 
> Sorry, my bad your previous file naming was okay, I got confused due to the Twitter handle. I have fixed it by myself
All good!!! Thought I forgot my own username  🤣

**Comment by AyushSarode** [comment]
I want to edit my file, There is one mistake!!!

**Comment by eddiejaoude** [comment]
Sure you can edit your file, here are the documentation https://linkfree.eddiehub.io/docs/how-to-guides/editing

Any questions you can come and ask in the EddieHub Discord http://discord.eddiehub.org

**Pull request merged**
