### PR TITLE
Add Sudhansu's data

### PR DESCRIPTION
**Pull request by the-lazy-learner**
## Changes proposed

Add Sudhansu's user data

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers
Please review and suggest changes. Thank you!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1574"></a>

### CODE REVIEW

**Review by EmmaDawsonDev — APPROVED** [review]

**Review by kumarsonsoff3 — APPROVED** [review]
Looks go to me! 🚀

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Review by Njong392 — APPROVED** [review]
Went over it, and it looks good :+1:

**Review by jaynarayan-vaishnav — APPROVED** [review]
LGTM 🙌🏼
Awesome work Sudhansu

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Elegant

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

**Pull request merged**
