### PR TITLE
fix: ux improvement on docs page

### LINKED ISSUE #6096: UX improvement on docs page
### Description

When we vist the docs page: https://linkfree.io/docs

- There are cards on the page to navigate between docs:
Screenshot 2023-04-15 at 2 59 33 PM

- When we hover the card it show the border:
Screenshot 2023-04-15 at 3 00 20 PM

But is clickable only on in the red border: (I have added the border to explain)
Screenshot 2023-04-15 at 3 00 55 PM
It would be good that when we click in the green border also. 

It show border all over that it should be clikable

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by thehashmap**
## Fixes Issue

Closes #6096

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6126"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for your contribution 

Please remove generated files, this might be because you have enabled GitHub actions on your fork

**Comment by thehashmap** [comment]
> Thank you for your contribution
> 
> Please remove generated files, this might be because you have enabled GitHub actions on your fork

I have removed the generated files now

**Review by harshsingh32 — COMMENTED** [review]
LGTM

**Review by amandamartin-dev — APPROVED** [review]
LGTM -  checked on desktop and mobile via browser in gitpod

**Pull request merged**
