### PR TITLE
Added default icon for links

### LINKED ISSUE #549: [FEATURE] Add default icon
### Description

Add a default icon if icon doesnt exist

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Kunal0007**
Closes #549

Added default icon if the icon not found in PrimeReact

Before:
image

After:
image

If any suggestions for the default icon plz comment down

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/579"></a>

### CODE REVIEW

**Comment by krishguptadev** [comment]
Hey there @Kunal0007 👋 Just checking in, do you need any help?

**Comment by Kunal0007** [comment]
> Hey there @Kunal0007 👋 Just checking in, do you need any help?

Hello 👋, As I told in the above comments this issue can't be solved https://github.com/EddieHubCommunity/LinkFree/pull/579#issuecomment-951792586. 
We have to change the icon library. So, I think I should close this PR. Should I close it?

**Comment by krishguptadev** [comment]
Yeah sure :D

**Comment by Vyvy-vi** [comment]
Yes, i think we should close the PR and make changes in a newer PR, with an icon library/set of our choice.
Thanks for contributing to LInkFree!

**Pull request closed without merging**
