### PR TITLE
fix: mobile menu open and close functionality

### LINKED ISSUE #1980: Menu on Mobile Devices
### Description

The navigation menu is permanently open on mobile devices. The hamburger menu seems to be broken as well, as clicking on it gives no observable response.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by k99sharma**
## Fixes Issue
Closes #1980 

## Changes proposed
Added react state to open and close mobile menu on click

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

ezgif com-gif-maker

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2001"></a>

### CODE REVIEW

**Comment by LinuxGamer** [comment]
Hmm, Build/tests has failed, I can't spot the issue, but idk if others can.

**Comment by k99sharma** [comment]
Build/tests are failing because of some storybook code. It's happening since I fetched other commits.

**Comment by k99sharma** [comment]
@eddiejaoude Can you take a look if any more changes are necessary.

**Review by mkubdev — APPROVED** [review]
Hello ⚡ The changes look good to me.

**Comment by k99sharma** [comment]
Cool 👍

**Comment by E-fais** [comment]
Mobile view is not so good.
Your suggestion looks good 👍

**Pull request merged**
