### PR TITLE
Adds Highlight on Focus in Copy Button

### PR DESCRIPTION
**Pull request by Deveesh-Shetty**
## Changes proposed

The `Copy` button was a div element so there was no focus state on it by default
- This PR changes it to a button so it is easily accessible by keyboard navigation

The Video shows the difference before the fix (original website) and after (development server)
[linkfree-8457.webm](https://github.com/EddieHubCommunity/LinkFree/assets/89470104/5a9bfb4e-ca20-48fb-9d1b-499ef422ff22)

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Focus State on the button
Screenshot_743

## Note to reviewers
I am new to open source contributions... so if i missed anything, I am more than ready to fix it.

Also thanks to Eddie for helping with my errors and questions in Discord!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8509"></a>

### CODE REVIEW

**Review by accodes21 — COMMENTED** [review]
Looks good, Thanks for contributing.

**Review by adityaraute — COMMENTED** [review]
It was mentioned on the issue #8457 that the repo has a button component.

I wonder if you should be using that one instead of writing a button html. But I'm not entirely sure, hence only a comment.

**Comment by Deveesh-Shetty** [comment]
> It was mentioned on the issue #8457 that the repo has a button component.
> 
> I wonder if you should be using that one instead of writing a button html. But I'm not entirely sure, hence only a comment.

The CopyToClipboard button is a button component by itself and all the stylings were done beforehand, I just shifted the elements, so `button` is the parent.

**Review by eddiejaoude — DISMISSED** [review]
Looks good 👍

**Comment by eddiejaoude** [comment]
> It was mentioned on the issue #8457 that the repo has a button component.
> 
> I wonder if you should be using that one instead of writing a button html. But I'm not entirely sure, hence only a comment.

Good spot @adityaraute 👍 I think we can refactor the button component in another PR to be more flexible, then this can also be updated afterwards

**Pull request merged**
