### PR TITLE
data:ShubhamSinghgit

### PR DESCRIPTION
**Pull request by ShubhamSinghgit**
## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ x] My change requires changes to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3680"></a>

### CODE REVIEW

**Review by dan-mba — CHANGES_REQUESTED** [review]
To fix the JSON issues, please remove the commas on lines 11,16, & 22

**Comment by ShubhamSinghgit** [comment]
> To fix the JSON issues, please remove the commas on lines 11,16, & 22

Can you check it now?

**Review by dan-mba — APPROVED** [review]
Looks good to me

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"></p>

**Pull request merged**
