### PR TITLE
docs: renaming doc to make more sense

### LINKED ISSUE #3044: [DOCS] Rename `Single User Mode` to `Self-host`
### Description

I think it is not a good idea to name it Single User Mode, because that does not make as much sense as "Self Host"

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by krshkun**
Renames "Single User Mode" to "Self-Host"

## Fixes Issue

closes #3044

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3054"></a>

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
Great point, Krish. Looks good

**Review by schmelto — DISMISSED** [review]

**Review by Panquesito7 — APPROVED** [review]
Awesome. Thanks! 🚀

**Comment by Panquesito7** [comment]
You might want to update this in other docs as well, such as the FAQ https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/docs/faqs.mdx

**Review by Panquesito7 — APPROVED** [review]

**Review by lewisushindi — APPROVED** [review]

**Review by eddiejaoude — APPROVED** [review]
Great collab everyone 💪

**Pull request merged**
