### PR TITLE
Fix/keydown event

### LINKED ISSUE #8661: [BUG] Preventing keydown event capture when input is focused
## Expected Behavior:
When `search` input element is focused on the search page, keydown events should not be captured, allowing users to interact with the input without unintended side effects.

## Actual Behavior:
Currently, when the `search` input is focused on the search page, keydown events are still being captured, which can lead to unexpected behavior and conflicts with user input.

## Steps to Reproduce:

* Open the [linkfree.io](linkfree.io)
* Navigate to the search page
* Select any tags. (f.e. - `javascript`)
* Focus on `search` input element.
* Attempt to type right arrow(&rarr;) into the input and pagination will go next page

### Screenshots

_No response_

### Additional information

Would love to fix this

### PR DESCRIPTION
**Pull request by KSSaiTeja**
## Fixes Issue

Fixes #8661 

Closes #8661 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

please consider my PR

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8691"></a>

### CODE REVIEW

**Comment by badrivlog** [comment]
@KSSaiTeja  You aren't allowed to raise PR without getting the issue assigned to you. I would highly recommend you to please read the contributing guildelines carefully https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by SaraJaoude** [comment]
This PR is being closed for the reasons mentioned here: https://github.com/EddieHubCommunity/LinkFree/issues/8661#issuecomment-1683671163

- this issue is not assigned to you
- you are causing confusion for the issue assignee and maintainers 
- as mentioned previously please read the [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) before continuing

**Comment by KSSaiTeja** [comment]
please assign me. this

**Comment by KSSaiTeja** [comment]
i will work on this mam, please assign me this

**Pull request closed without merging**
