### PR TITLE
Adding profile detail on LinkFree shubhamsigdar1.json

### PR DESCRIPTION
**Pull request by shubhamsigdar1**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1483"></a>

### CODE REVIEW

**Comment by shubhamsigdar1** [comment]
After this what i have to do???

**Review by kumarsonsoff3 — APPROVED** [review]
LGMT 👍  Thanks for contributing! 🚀

**Comment by kumarsonsoff3** [comment]
> After this what i have to do???

Just wait for another approval, then we'll let your PR merge!

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
