### PR TITLE
Add My Profile : kiritocode1.json

### PR DESCRIPTION
**Pull request by kiritocode1**
This PR Proposes Changes to ```/public/data``` 
 ## Changes Proposed to 
---
Added kiritocode1.json to the directory ```/public/data``` .
## Check List 
- [x] Compiles to the Code Style of the project ✍️
- [x] New and Existing test passed 
- [x] Does Not Contain Copyright Exclusive Content of any type . 
- [x] Describes what  changes i made .
## Screenshots 
image
#Note : 
please review and merge this PR  , Love you 😄 
    

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1897"></a>

### CODE REVIEW

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Your profile looks good but you accidentally committed the package lock file. Please use git revert to remove it from your commit.

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
No changes are required in `package-lock.json` for adding your profile! You can follow [this step by step guide](https://gist.github.com/kumarsonsoff3/fbc6ecde519250a9f0a4d7ccc9993a1a) to revert the changes from `lock file.` 
Let us know if you need any help with this! :)

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Unfortunately, you've deleted the `lock` file! You're only required to revert the changes from `package-lock` file. 

Just do one thing, copy the whole content from [main](https://raw.githubusercontent.com/EddieHubCommunity/LinkFree/main/package-lock.json) `package-lock` file, and paste it in that of your fork! 

If you run with any issues, feel free to reach us out!

**Comment by EmmaDawsonDev** [comment]
How are you getting on with this @kiritocode1 ?

**Comment by kiritocode1** [comment]
Sorry @EmmaDawsonDev  , i went on a break, ill get back to it monday,

**Comment by EmmaDawsonDev** [comment]
No problem at all, just wanted to check in 😊

**Pull request closed without merging**
