### PR TITLE
Mylink

### PR DESCRIPTION
**Pull request by RoushanakRahmat**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2519"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by eddiejaoude — DISMISSED** [review]
Looks great 👍  but please rename the file so the case matches your GitHub username `RoushanakRahmat`

**Review by accodes21 — COMMENTED** [review]
Looks great, just as Eddie suggested use your GitHub username as filename

**Review by yashdev9274 — COMMENTED** [review]
Update the file by adding "displayStatsPublic" to make visit-counter visible on your profile.

**Comment by EmmaDawsonDev** [comment]
How are you doing with the requested changes @RoushanakRahmat ? Let us know if you need any help.

**Pull request merged**
