### PR TITLE
fixed need some margin on profile section #8210

### LINKED ISSUE #8210: [BUG] Milestone, Events and Links section needs some margin top
### Description

Steps to reproduce : 
In Dark Mode Go to account section and click on events and milestone section on mobile view 
The No Event found message is missing some margin. I will attach some of the images below.
I would like to work on this issue this is a simple fix. Can you assign rhis to me.

- milestone
- events
- links

### Screenshots

Screenshot_20230715-211223_Chrome
Screenshot_20230715-211229_Chrome

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sital002**
## Fixes Issue 
Need some magin on profile section

 Closes #8210 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Before : 
previos

After :
milestone
Screenshot 2023-07-21 113817
Screenshot 2023-07-21 113850

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8286"></a>

### CODE REVIEW

**Comment by sital002** [comment]
can someone review my pr

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
`my-2` will be partially overwritten by `mb-3`

**Comment by sital002** [comment]
I have changed my-2 to mt-3 can you review the changes.

**Review by sital002 — COMMENTED** [review]
I have changed my-2 to mt-3

**Review by eddiejaoude — APPROVED** [review]
Thank you for your contribution 👍 

I think this adds too much margin on other pages the alert component is used, like search or manage profile - but this is not a blocker

**Pull request merged**
