### PR TITLE
data: Manishku0722

### PR DESCRIPTION
**Pull request by Manishku0722**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5065"></a>

### CODE REVIEW

**Review by mahfuztbt — APPROVED** [review]
LGTM, ready to merge

**Review by shubhsharma19 — APPROVED** [review]
LGTM, Thankyou for your contribution 🎉

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Review by sansarmaske — APPROVED** [review]
LGTM 👍

**Review by iamthecloverly — APPROVED** [review]

**Review by stevenovak123 — APPROVED** [review]

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
