### PR TITLE
data:nowayski

### PR DESCRIPTION
**Pull request by nowayski**
## Changes proposed

Add my personal json file to the linkfree project.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2810"></a>

### CODE REVIEW

**Comment by nanthakumaran-s** [comment]
Hello, @nowayski your file name should match your GitHub username.... make sure you have your file name as `nowayski.json`

**Comment by nowayski** [comment]
> Hello, @nowayski your file name should match your GitHub username.... make sure you have your file name as `nowayski.json`

Thanks i've made the change

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

Add your profile to the `data` directory. It will be `data/nowayski.json`

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by nowayski** [comment]
@Pradumnasaraf I had to make one more change because of a JSON syntax error

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf I had to make one more change because of a JSON syntax error

No worries we have JSON formatted Action set after it gets merged. This is why I approved that :)

**Pull request merged**
