### PR TITLE
perf: compress site

### PR DESCRIPTION
**Pull request by krshkun**
I think it will be a good idea to compress the site and also serve images in webp format, as per my understanding if nextjs converts them to webp, we won't face the api errors

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1845"></a>

### CODE REVIEW

**Comment by krshkodes** [comment]
Also unsure why tests ran before build...

**Comment by eddiejaoude** [comment]
Thanks Krish! But not sure if `webp` is supported on Mac yet though

**Comment by krshkun** [comment]
You would be surprised to know, yes, they decided to support webp but not svg: https://caniuse.com/webp

**Comment by eddiejaoude** [comment]
Thanks Krish 👍 It would be great to know the size comparison before and after?

Btw I am curious why these are not on by default? There must be a reason?

**Comment by krshkun** [comment]
NextJS wouldn't fiddle with the quality of the images - but because the avatars/images we don't use aren't so detailed already - we don't need that...

Plus, most websites use it including Discord as well :D 

I am not sure about comparison - I'll have to install a bunch more code so that it checks the bundle size each time - but that sounds like not having a place in this PR,

but:

> WebP lossless images are 26% smaller in size compared to PNGs.
-- developers.google.com

**Review by eddiejaoude — APPROVED** [review]
Thanks Krish 👍

**Pull request merged**
