### PR TITLE
Add RotrixLOL

### PR DESCRIPTION
**Pull request by RotrixLOL**
Added my profile!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2313"></a>

### CODE REVIEW

**Comment by RotrixLOL** [comment]
What happened?

**Review by kumarsonsoff3 — APPROVED** [review]
Well not sure why the format check is failing. But, Your changes looks good to me! 👍

**Comment by RotrixLOL** [comment]
Ok, could you merge my PR?

**Comment by Pradumnasaraf** [comment]
> Ok, could you merge my PR?

Hey, thanks for your patience. Not sure why the action is failing, We are merging it on a temp branch and then merging it internally.

**Pull request merged**
