### PR TITLE
feat: increase `scale` on hovering the links

### LINKED ISSUE #135: Increase `scale` of buttons on hover
When hovered, the links will get a little bigger which looks cool and interactive as well! 💥 
If you like the idea, can you please assign me this issue, I'd love to work on this 🥳 

Check out this GIF: 
linkfree-hover

### PR DESCRIPTION
**Pull request by guptasajal411**
closes #135 

Thanks for giving us chance to work on LinkFree! Check out the output of changes here:
 
linkfree-hover

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/140"></a>

### CODE REVIEW

**Comment by guptasajal411** [comment]
Issue for this feature: https://github.com/EddieHubCommunity/LinkFree/issues/135

**Comment by eddiejaoude** [comment]
Please remove the changes to the `package*` files these are not required

**Review by nhcarrigan — CHANGES_REQUESTED** [review]
Please refer to Eddie's changes

**Comment by guptasajal411** [comment]
I reverted the changes to `package-lock.json`, but I can't get to remove the newline char at the end of `package.json` file. Can you have a look at that please

**Comment by nhcarrigan** [comment]
You can perform a rebase:

https://www.nhcarrigan.com/notes/#/git-commands/rebase-branch

**Comment by guptasajal411** [comment]
New pull request: https://github.com/EddieHubCommunity/LinkFree/pull/160
Merged 🎉

**Pull request closed without merging**
