### PR TITLE
modified LABEL as Docker official documentation

### PR DESCRIPTION
**Pull request by susheelpal**
## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1657"></a>

### CODE REVIEW

**Review by imlakshay08 — APPROVED** [review]
This PR looks great. Keep it up

**Review by vedanshi555 — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by eddiejaoude** [comment]
Thank you for improving 👍  here are the official docs for reference https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package#connecting-a-repository-to-a-container-image-using-the-command-line

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge!

**Review by maharshi-sinha — APPROVED** [review]
Looks good to merge! Keep contributing :)

**Review by Vyvy-vi — APPROVED** [review]
looks good to me!

**Pull request merged**
