### PR TITLE
data:CoffeeGeek101

### PR DESCRIPTION
**Pull request by CoffeeGeek101**
## Changes proposed

- Adding Profile to LinkFree

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot 2023-02-13 at 8 28 45 PM
## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4796"></a>

### CODE REVIEW

**Review by Ananya2001-an — COMMENTED** [review]
You have to add this file into the data folder.

**Review by priyankarpal — CHANGES_REQUESTED** [review]
Hey @CoffeeGeek101, you mistakenly created your file in the main folder, you need to create it in the `data` folder. 
### from `CoffeeGeek101.json` to `data/CoffeeGeek101.json`

**Review by priyankarpal — APPROVED** [review]
LGTM 🎉

**Review by Hrishi5111998 — APPROVED** [review]

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"></p>

**Pull request merged**
