### PR TITLE
fix: show just single tooltip

### LINKED ISSUE #96: Tooltip for Homepage-Avatars
When hovering a Avatar, the username of the hubber could be displayed with a tooltip

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #96 

There was an issue, that the Tooltip got rendered in the `map`-Loop which resulted in quite many tooltips that got generated.

@eddiejaoude I saw you removed this feature from version 27.
I cherry-picked the commit from @Sejal-16 and fixed this issue.
In case it was because it looked a bit strange, I think you can review this with gitpod.
If it was another reason feel free to reach out to me or close the issue 😄 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/423"></a>

### CODE REVIEW

**Comment by rtynski** [comment]
image

Keep convection.
Sort import component.

**Comment by eddiejaoude** [comment]
Thanks @Cahllagerfeld 👍 yeah it was a bit strange and I had a quick look at it, but then decide to remove it because there is another PR coming soon that I think might replace it https://github.com/EddieHubCommunity/LinkFree/pull/406

Let me know what you think?

**Comment by eddiejaoude** [comment]
I was thinking, now we have the chips on the homepage, could the `bio` info be added to the generated list json file and have that as a tool tip - but the text could be quite long

**Comment by Cahllagerfeld** [comment]
I'm not sure if a tooltip is the right component for that 😅

**Comment by Cahllagerfeld** [comment]
I think this PR is even closable, as we are having chips now.

**Comment by eddiejaoude** [comment]
> I'm not sure if a tooltip is the right component for that 😅
> I think this PR is even closable, as we are having chips now.

ok 👍

**Pull request closed without merging**
