### PR TITLE
data:VaibhavSingh

### PR DESCRIPTION
**Pull request by VaibhavSinghDev**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2783"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

Please fix your JSON profile naming. It should be `{your GitHub username}.json` -> `VaibhavSinghDev.json`.

If you need any help feel free to ask.

**Comment by VaibhavSinghDev** [comment]
> Hey,
> 
> Please fix your JSON profile naming. It should be `{your GitHub username}.json` -> `VaibhavSinghDev.json`.
> 
> If you need any help feel free to ask.

Done! Thanks Pradumna.

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍  Great collaboration everyone 🎉

**Pull request merged**
