### PR TITLE
Dark Theme

### LINKED ISSUE #123: Add a dark theme for night
We should add a toggle for users to switch between dark and light mode.

### PR DESCRIPTION
**Pull request by Shivansh-yadav13**
- This pull request is for #123 
- Continuation of #303 
- This time not using reload to change the style

# Changes
- added Header.js
- modified App.js
- modified Links.js

# Screenshots
LF-1

LF-2
LF-3

LF-4

- I would also like to change style of Chips and Milestones, can someone help me with that?

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/512"></a>

Resolve #123

### CODE REVIEW

**Comment by schmelto** [comment]
Some more thoughts on this. You could consider setting the state based on the browser preferences (an implementation with cookies you can take a look here https://github.com/DenverCoder1/github-readme-streak-stats/pull/91)

Further we need to check the content of the page like the Milestones or chips for users which are in this version really bright

**Comment by krishguptadev** [comment]
We can use the preferences-media to do that setting based of the browser config

**Comment by schmelto** [comment]
https://primetek.hashnode.dev/switch-your-react-app-between-material-bootstrap-and-custom-themes-at-runtime

**Comment by Shivansh-yadav13** [comment]
> 
> 
> Some more thoughts on this. You could consider setting the state based on the browser preferences (an implementation with cookies you can take a look here [DenverCoder1/github-readme-streak-stats#91](https://github.com/DenverCoder1/github-readme-streak-stats/pull/91))
> 
> Further we need to check the content of the page like the Milestones or chips for users which are in this version really bright

**Comment by schmelto** [comment]
image

**Comment by krishguptadev** [comment]
Hey there @Shivansh-yadav13 👋 Do you need any help?

**Comment by Shivansh-yadav13** [comment]
> Hey there @Shivansh-yadav13 👋 Do you need any help?

Yes, I need help. I have raised a discussion here 
https://github.com/EddieHubCommunity/LinkFree/discussions/740

**Comment by Shivansh-yadav13** [comment]
Can I close this PR, I will make a new one.

**Comment by Panquesito7** [comment]
> Can I close this PR, I will make a new one.

It's best to update the same PR, as the discussion will be kept and 
it will be easier for others to find this PR. Let us know if you need any help with anything! 😄

**Comment by Shivansh-yadav13** [comment]
I didn't know It will close the pr 😅mb

**Pull request closed without merging**
