### PR TITLE
feat:Added HackerRank Icon-Issue-1010

### LINKED ISSUE #1010: Add HackerRank Icon
### Description

I wanted to add my **HackerRank profile** link to my **LinkFree** page but I found there's no such icon present in the README.md file to be used . I request to add the HackerRank icon to the README.md file so that people like me can use it.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Susmita-Dey**
## Fixes Issue

Closes #1010  

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1012"></a>

### CODE REVIEW

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
The icons are listed in alphabetical order, please add hackerrank in the correct position in links.json and getIcons.js

**Comment by Susmita-Dey** [comment]
> The icons are listed in alphabetical order, please add hackerrank in the correct position in links.json and getIcons.js

I have listed the items in alphabetical order.

**Review by krshdev — APPROVED** [review]

**Review by emmalearnscode — APPROVED** [review]

**Review by qwel-exe — APPROVED** [review]
LGTM :rocket: thanks for your contrubutions

**Comment by Kartik2220** [comment]
hey

> The icons are listed in alphabetical order, please add hackerrank in the correct position in links.json and getIcons.js

hey can you help me from where i can get icon images  ???

**Comment by Susmita-Dey** [comment]
@Kartik2220 You can use favicon

**Comment by Kartik2220** [comment]
img src="https://user-images.githubusercontent.com/91655303/148160942-870fdbb4-a57c-4861-afaa-241835390645.png

from where i can copy this link for icons??

**Pull request merged**
