### PR TITLE
Added My details

### PR DESCRIPTION
**Pull request by Mrityunjay1**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1392"></a>

### CODE REVIEW

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
Your profile looks good. However, please revert the changes to the package lock file so that it is not part of the pull request.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Mrityunjay1** [comment]
Hello I have removed my package-lock . Please have a look into it

**Comment by Mrityunjay1** [comment]
Why build is getting failed

**Comment by emmalearnscode** [comment]
> Why build is getting failed

Because you added package lock to the gitignore file but it is needed for the CI/CD tests to pass.

Please undo the changes to the gitignore file and the package lock file. Only your profile should be added in the pull request. Let us know if you need help with reverting the files.

**Comment by kumarsonsoff3** [comment]
Hey @Mrityunjay1, let us know if you need any help in reverting the changes.

**Review by kabir0x23 — COMMENTED** [review]
Hey @Mrityunjay1 
 - If you need any help, feel free to ask here.
 - We all are here to help.

**Comment by EmmaDawsonDev** [comment]
I will close this for now since it’s been open for a while with no changes. Please feel free to create a new pull request containing only your profile addition.

**Pull request closed without merging**
