### PR TITLE
Added border radius style to Card component

### LINKED ISSUE #1480: Border Radius
### Description

Adding Border Radius to the Milestone Card holder.

### Screenshots

Screenshot (41)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by andrewkykoo**
## Fixes Issue
Closes #1480 

## Changes proposed

- Added border radius style to Card component in Milestones component

## Check List (Check all the applicable boxes) 

- [v] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [v] This PR does not contain plagiarized content.
- [v] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1485"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — APPROVED** [review]

**Comment by kumarsonsoff3** [comment]
Sorry @andrewkykoo, I just checked out! **20px** would look way much! 

It would be great to keep it around **8-10px**. So, please reduce it accordingly!

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
We currently use prime react CSS so the border radius should be added as a class, not it’s own separate inline style. Here’s a link to learn more https://www.primefaces.org/primeflex/borderradius

**Comment by eddiejaoude** [comment]
Thank you for your contribution @andrewkykoo could you add a screenshot to the PR please so we can get it merged

Note that we are working on version 2 in branch `nextjs` that is using NextJS + TailwindCSS

**Comment by eddiejaoude** [comment]
I could not see the border radius on the milestone card?

Screenshot 2022-09-15 at 06 36 53

**Pull request closed without merging**
