### PR TITLE
Update Charchitkumawat04.json

### PR DESCRIPTION
**Pull request by Charchitkumawat04**
## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3354"></a>

### CODE REVIEW

**Review by AbbeyIT — APPROVED** [review]
LGTM! Thank you for your contribution.

**Review by maharshi-sinha — APPROVED** [review]
Looks Good to Me !! ✅🚀

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
