### PR TITLE
Added profile to linkfree

### PR DESCRIPTION
**Pull request by hady68**
Added my data to Linkfree database

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1434"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — APPROVED** [review]

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please rename your file to `hady.json`. Looks like you're using a comma instead of a dot.
Let us know if you need any help doing this! Thank you. 🙂


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

**Comment by hady68** [comment]
@Panquesito7  Thanks for suggesting the changes  😃

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient

**Review by emmalearnscode — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by vincekashaka — COMMENTED** [review]
Thanks for contributing! 🚀

__

  Summary: 👌 This code looks good

**Pull request merged**
