### PR TITLE
Updated and added social links and updated file name

### PR DESCRIPTION
**Pull request by singh-vaibhav08**
File name: VaibhavSinghDev -> singh-vaibhav08
Twitter: VaibhavSinghDev -> singh_vaibhav08
LinkedIn: vaibhavsinghdev -> singh-vaibhav08
Github: VaibhavSinghDev -> singh-vaibhav08

Added Dev.to link

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4594"></a>

### CODE REVIEW

**Review by Hrishi5111998 — CHANGES_REQUESTED** [review]
hey @singh-vaibhav08 everything looks fine just minor change icon value of linkedin should be **FaLinkedin** not **FaLinkedIn** please update! thanks for contributing

**Review by priyankarpal — CHANGES_REQUESTED** [review]

**Review by sidharthviz — APPROVED** [review]
LGTM 👍🏼

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by maharshi-sinha — APPROVED** [review]
LGTM!

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good! 👍

**Pull request merged**
