### PR TITLE
data: DevYoma

### PR DESCRIPTION
**Pull request by DevYoma**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8130"></a>

### CODE REVIEW

**Comment by DevYoma** [comment]
Hello maintainer, 
I followed the instruction on the docs to the letter
Do I need to have a Gitpod account for the gitpod job to run

**Comment by DevYoma** [comment]
> Hello maintainer, I followed the instruction on the docs to the letter Do I need to have a Gitpod account for the gitpod job to run

So I created a gitpod account and the github action ran successfully.

**Comment by DevYoma** [comment]
So sorry, I already changed it and the check wasn't successful

**Comment by Vishrut19** [comment]
> So sorry, I already changed it and the check wasn't successful

Yes, I was confused. But, its fine. You should rename and upload it once again and I will approve it.

**Review by Vishrut19 — APPROVED** [review]
Thanks for Contributing 🎉 ! LGTM 👍

**Comment by SaraJaoude** [comment]
@Vishrut19 please review Profiles more carefully.  It is not the first time you have given incorrect information which is very confusing to the author and creates extra work and notifications for the maintainers.

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
