### PR TITLE
Update UserMilestone.js line color from multicolor to light gray.

### LINKED ISSUE #7047: [BUG] Milestone page remove colours from the items
## Problem Statement

Remove the colourful lines and change it to a default light colour. Possibly a light gray colour.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sanyamx**
## Fixes Issue 

fixes #7047

## Changes proposed
_changed the multicolor lines to light-gray_

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
_Before_
239694147-edb76ee0-f30b-4eac-a8ab-8aeddd562d8e

_After_
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7395"></a
Screenshot 2023-06-05 at 9 30 38 PM
>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you 👍 

Please update the relevant docs for the events data to remove the color as this will no longer be used `pages/docs/how-to-guides/events.mdx`

**Comment by sanyamx** [comment]
@eddiejaoude i did not understand your review. can you please provide with some more details?

**Comment by eddiejaoude** [comment]
> i did not understand your review. can you please provide with some more details?

Sure! The docs on this [page](https://linkfree.io/docs/how-to-guides/events) still refers to color property but if your PR is removing this functionality, it should be removed from the docs

**Comment by sanyamx** [comment]
@eddiejaoude will be right on it! Thanks👍🏼

**Comment by eddiejaoude** [comment]
Great 👍  please can you add a before and after screenshot to the PR description

**Comment by sanyamx** [comment]
Before
239694147-edb76ee0-f30b-4eac-a8ab-8aeddd562d8e
After
Screenshot 2023-06-05 at 9 30 38 PM


@eddiejaoude saw your comment a bit late. but yeah here is the difference

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
