### PR TITLE
Add link markdown style in bio

### LINKED ISSUE #7152: [BUG] links in bio with markdown do not have any visual identification
### Description

Links in the bio with markdown work but they don't have our app's link styles on it

> I believe in order to make this work, the `<a>` tag will need to be overridden in [react-markdown](https://github.com/remarkjs/react-markdown#appendix-b-components)

Suggested by Dan https://github.com/EddieHubCommunity/LinkFree/issues/7152#issuecomment-1560944413

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by harshpatel-r**
## Fixes Issue
where the links in the bio were lacking the app's link styles (see screenshot) #7152 

Closes #7152

## Check List (Check all the applicable boxes)
- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
fixed
bio-link-lightmode
bio-link-lightmode-hover
bio-link-darkmode

## Note to reviewers
@eddiejaoude @SaraJaoude 
Please review and merge this pull request. It addresses the issue where the links in the bio were not displaying the app's link styles. To fix this problem, I have overridden the `<a>` tag in react-markdown to ensure that the links in the bio have the correct styling.

I have thoroughly tested the changes and verified that the links now appear with the desired app-specific styles. Additionally, I have ensured that the changes do not introduce any regressions and that all existing tests pass successfully.

Your feedback and review are greatly appreciated. Thank you for your time and assistance in merging these improvements!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7339"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for your contribution.

I think you can change it for the plug-in globally here `components/mdx/ComponentStyle.js`

**Comment by harshpatel-r** [comment]
Hi @eddiejaoude , thank you for your feedback. Just to confirm, regarding the changes you mentioned, do you want me to:

1)Apply my styles globally to the Link component, or
2)Remove my custom styles and revert to using the existing global styles for the Link component?

Could you please provide further guidance on how to proceed with this?

**Comment by eddiejaoude** [comment]
Thanks @harshpatel-r , we would like to keep the current link style consistent, so option 2 please

**Comment by harshpatel-r** [comment]
Closes #7152 
hii @eddiejaoude ,
I have made updates to the code based on the feedback received. Please review the changes and provide your feedback on the following:
## Changes Made:
Updated the bio links style with the Link component.
## Screenshots
bio-link-style-darkmode
bio-link-style-lightmode

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
