### PR TITLE
mobile testimonial UI layout fix

### LINKED ISSUE #2454: [FEATURE] Improvement - mobile testimonial UI
### Description

In mobile the testimonial text isn't making good use of the visual "real estate" right now creating longer testimonial cards than necessary. This issue is to modify the mobile UI to allow the text to float below the avatar and span the full width of the card.

### Screenshots

mobile-testimonial-ui

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Aadarsh805**
## Fixes Issue
Closes #2454

## Changes proposed
Changed the testimonial layout, suitable for mobile screen

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Screenshots
Before: 
image

After: 
[screen-capture (3).webm](https://user-images.githubusercontent.com/95094057/209173332-14b8f361-8cf4-47c5-bf7f-80b183d49a6c.webm)

image

## Note to reviewers
used next `<Image /> `component in place of normal HTML img

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2458"></a>

This pr is a re-pr same as #2458 without package-lock.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2549"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you 👍 

- please add a photo for after also
- can you resolve conflicts (if you need help let us know)

**Comment by Aadarsh805** [comment]
> Thank you +1
> 
> * please add a photo for after also
> * can you resolve conflicts (if you need help let us know)

There's a video for better reference, added a photo too
conflicts resolved

**Comment by eddiejaoude** [comment]
Thank you 👍 

I think the break point happens too soon. What about changing to mobile layout later?

**Comment by Aadarsh805** [comment]
> Thank you +1
> 
> I think the break point happens too soon. What about changing to mobile layout later?

Yes it's much better now as the layout shift occurs at the same time as the tabs change into the select dropdown

[screen-capture (4).webm](https://user-images.githubusercontent.com/95094057/210135242-fb5edd68-ba67-4dcf-a2ea-96b0be0405e2.webm)

**Review by eddiejaoude — APPROVED** [review]
Looks good! Thank you

**Pull request merged**
