### PR TITLE
data:tiyabansal

### PR DESCRIPTION
**Pull request by tiyabansal**
## Changes proposed

Profile data added

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2954"></a>

### CODE REVIEW

**Review by Sativarsainath-26 — APPROVED** [review]
Looks Good with the changes!! Thanks for contributing.

**Review by ChinmayMhatre — APPROVED** [review]
Looks good!

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"></p>

**Comment by tiyabansal** [comment]
Thanks for merging my pull request!! :))

**Pull request merged**
