### PR TITLE
Map UI fix

### PR DESCRIPTION
**Pull request by Samit-prsl**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5509"></a>

### CODE REVIEW

**Comment by amandamartin-dev** [comment]
@Samit-prsl Hey! Thank you for contributing, but to help out the maintainers can you please fill out the pull request form at the top to connect this PR with the issue. 

This will help us assess the fix and will also allow the open issue to be closed automatically once the code has been merged.

If you need any help with this, please let us know!

**Comment by eddiejaoude** [comment]
In addition to Amanda's suggestions please include a before/after screenshot 

More information about creating issues first can be found in our contributing guide https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
In addition to Amanda's suggestions please include a before/after screenshot 

More information about creating issues first can be found in our contributing guide https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by eddiejaoude** [comment]
Thank you for your contribution 👍 I will close this PR as it is not related to an issue and there has been no activity for 2 weeks.

Please have a look at the issues page filtering by the label `status: ready for dev`

**Pull request closed without merging**
