### PR TITLE
data: Saan-king

### PR DESCRIPTION
**Pull request by Saan-king**
Added my profile

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8190"></a>

### CODE REVIEW

**Review by SaraJaoude — DISMISSED** [review]
Please make sure your file name matches your GitHub username exactly (it is case sensitive). Instead of `data/SathyaAnand.json`   it should be `data/Saan-king.json`.

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart-json to help you update this Pull Request.

**Comment by Saan-king** [comment]
image
Hi I have made the changes to Saan-king.json and updated the fork

**Comment by Saan-king** [comment]
Please kindly merge my request

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! 🎉

**Pull request merged**
