### PR TITLE
added a new json file

### PR DESCRIPTION
**Pull request by yogeshsumman**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1430"></a>

### CODE REVIEW

**Comment by yogeshsumman** [comment]
checklist checked

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
Your profile looks great but please revert the changes made to the package-lock file as that shouldn't have been committed.

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
Unfortunately deleting the file does not revert the changes but would lead to the file being deleted for everyone if we merged the PR. To revert the changes either you can go back to the commit where it was added and revert that, then re-add the other files or you can also try copying the contents of the file from the Eddiehub repo into yours because that way they will match.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by yogeshsumman** [comment]
I'll make the necessary changes, so thanks for suggesting.

**Comment by emmalearnscode** [comment]
Closing as you made a new pull request.

**Pull request closed without merging**
