### PR TITLE
Add Line Break To Docs

### LINKED ISSUE #2673: Mobile UI/UX Improvement
### Description

The link is flowing out of main section.
This can be improved!

### Screenshots

Screenshot_20230104_213646

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by LinuxGamer**
## Fixes Issue

Closes #2673

## Changes proposed

- Add `break-words` to `index.js` in `pages/docs` to fix the link going off the page.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2688"></a>

### CODE REVIEW

**Comment by LinuxGamer** [comment]
image
Here is a screenshot of the change.

**Comment by eddiejaoude** [comment]
I think it looks good 👍 and definitely an improvement 💯

**Comment by LinuxGamer** [comment]
Should I undraft the PR?

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
