### PR TITLE
data: tdogubo

### PR DESCRIPTION
**Pull request by tdogubo**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7767"></a>

### CODE REVIEW

**Comment by sandramsc** [comment]
File looks good tdogubo one suggestion:

Consider removing this line:
displaystatic

See discussion for reference: https://github.com/EddieHubCommunity/LinkFree/pull/5576#discussion_r1142347577

**Comment by tdogubo** [comment]
@sandramsc Thanks. Done.

**Comment by sandramsc** [comment]
> @sandramsc Thanks. Done.

File looks great! 🥳

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
