### PR TITLE
data: AbdulSamad

### PR DESCRIPTION
**Pull request by abdulsamad**

### CODE REVIEW

**Comment by SurajPratap10** [comment]
Suggestion: you can add few more social links like your `GitHub` and `LinkedIn`

**Review by SurajPratap10 — APPROVED** [review]
great

**Review by mahfuztbt — APPROVED** [review]

**Review by money8203 — APPROVED** [review]
LGTM

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good! 👍

**Pull request merged**
