### PR TITLE
Use secret file to pass Mongo URL to docker build

### PR DESCRIPTION
**Pull request by dan-mba**
## Changes proposed
use the `secret-files` option on the docker build action to pass the MongoDB URL in securely

Docker Documentation
https://docs.docker.com/engine/reference/commandline/buildx_build/#secret
https://docs.docker.com/engine/reference/builder/#run---mounttypesecret

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7031"></a>

### CODE REVIEW

**Comment by dan-mba** [comment]
It works https://github.com/EddieHubCommunity/LinkFree/actions/runs/5032531857
🥳

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge.

**Review by Pradumnasaraf — APPROVED** [review]
The changes look good to me.

**Comment by eddiejaoude** [comment]
Great work and awesome collab 💪

**Pull request merged**
