### PR TITLE
Add Polywork Icon

### LINKED ISSUE #1006: [FEATURE] Add Polywork as Link
### Description

I saw popular supported buttons but it would be great if we add the polywork.com link to the linkfree.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by parisioann**
## Fixes Issue
Closes #1006

## Changes proposed
Polywork Icon has been added, as requested by a user. Now by including -> "icon": "polywork" and "url": "", users will be able to connect their Polywork profile link.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
150656990-86fc8fb0-347e-4351-b4e3-348fcdbbc9fb

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1026"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍

**Review by vikasganiga05 — APPROVED** [review]
LGTM :+1:

**Review by emmalearnscode — APPROVED** [review]
Looks great! thanks for contributing!

**Comment by WarenGonzaga** [comment]
Thanks, @parisioann for adding the icon! I love it...

**Comment by parisioann** [comment]
@WarenGonzaga I am glad you like it! 💯  I will try to contribute more to requests from other users.

**Pull request merged**
