### PR TITLE
Krishna profile update

### PR DESCRIPTION
**Pull request by Krishnapro**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2430"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please revert the changes in the `CHANGELOG.md`, `package.json`, and `package-lock.json` files. Let us know if you need any help with that. 🙂

**Comment by eddiejaoude** [comment]
@Krishnapro I think you are making the branch without updating your fork, so that is why it always appears out of date with extra changes

**Comment by Krishnapro** [comment]
I synced the fork and then after fresh clone repo but somehow it did not work. if anyone can please help

**Comment by eddiejaoude** [comment]
I think a step might be missing. Can you share some screenshots?

The steps should be something like this...
1. update your fork (check the latest commit in your fork matches this repo)
2. create a new branch from the `main` branch
3. make changes in new branch

**Pull request closed without merging**
