### PR TITLE
fix: add tags, update bio, and add portfolio link

### PR DESCRIPTION
**Pull request by ronthetech**
- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4922"></a>

### CODE REVIEW

**Review by priyankarpal — DISMISSED** [review]
LGTM 🎉

**Review by Panquesito7 — DISMISSED** [review]
Thanks! 🎉

**Review by kumarsonsoff3 — DISMISSED** [review]

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Hey @ronthetech, you've merge conflicts here as your branch is outdated. 
Please update your fork to resolve the merge conflicts.

**Comment by ronthetech** [comment]
Hi @kumarsonsoff3 , I've updated my fork, but its not letting me see the conflict?

**Comment by kumarsonsoff3** [comment]
> Hi @kumarsonsoff3 , I've updated my fork, but its not letting me see the conflict?

Thanks @ronthetech, conflicts are resolved since you updated your fork! :)

Whenever there is a conflict, it's shown in the end of the PR just after GitHub actions checks.

**Review by kumarsonsoff3 — APPROVED** [review]

**Comment by ronthetech** [comment]
Ok I will keep that in mind for future pull requests, thank you for your help @kumarsonsoff3

**Pull request merged**
