### PR TITLE
data:Jacques-Murray

### PR DESCRIPTION
**Pull request by Jacques-Murray**
## Changes proposed

Created my LinkFree profile.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7338"></a>

### CODE REVIEW

**Comment by SaraJaoude** [comment]
Thank you for your PR.  You may wish to take a look at our [Available Icons](https://linkfree.io/icons) in Docs again as these are case sensitive.

For example rather than `fa-wordpress` it should be `FaWordpress`

**Comment by Jacques-Murray** [comment]
Thank you. I'll update.

**Comment by Jacques-Murray** [comment]
I've updated the icons and added a new commit to this PR.

**Review by Sindhuinti — APPROVED** [review]
Looks good 🎉

**Comment by Jacques-Murray** [comment]
Thank you.

**Review by SaraJaoude — APPROVED** [review]
looks good

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks for Contributing! 🎉 

<p align="center"><a href="https://linkfree.io/docs/how-to-guides/editing"></a></p>

**Pull request merged**
