### PR TITLE
data: CodingWithCard

### PR DESCRIPTION
**Pull request by CodingWithCard**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5368"></a>

### CODE REVIEW

**Review by SurajPratap10 — CHANGES_REQUESTED** [review]
Please remove `avatar` part as we don't need this after the update..

**Comment by CodingWithCard** [comment]
@SurajPratap10 Fixed

**Review by SurajPratap10 — APPROVED** [review]
looks good! Thanks for you contribution.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Welcome to LinkFree 🎉

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks for your Contribution! 🎉

**Pull request merged**
