### PR TITLE
MirzaBaig

### PR DESCRIPTION
**Pull request by I-MirzaBaig**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2762"></a>

### CODE REVIEW

**Review by accodes21 — APPROVED** [review]
Looks great, thanks for contributing.

**Comment by I-MirzaBaig** [comment]
> Looks great, thanks for contributing.

Thank you!
This was my first contribution, well!, I enjoined alot, got to learn lots of error etc!

**Review by dan-mba — CHANGES_REQUESTED** [review]
Remove the comma at the end of line 17

**Review by dan-mba — APPROVED** [review]
Looks good to me

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Please rename your filename to your `username.json`. 

It should be `I-MirzaBaig.json`. 🛠

**Comment by I-MirzaBaig** [comment]
> Please rename your filename to your `username.json`. 
> 
> It should be `I-MirzaBaig.json`. 🛠

OK!

**Comment by I-MirzaBaig** [comment]
> Please rename your filename to your `username.json`. 
> 
> It should be `I-MirzaBaig.json`. 🛠

Done

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! 👍

**Comment by I-MirzaBaig** [comment]
Thanks a lot!
Got to learn soo much!

**Pull request merged**
