### PR TITLE
Replace Switch with Routes

### PR DESCRIPTION
**Pull request by E-fais**
In  react-router-dom version 6,  'Switch' key word is replaced as 'Routes'

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1865"></a>

### CODE REVIEW

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Please also upgrade the package to version 6 and make sure all routes/navigation is updated so it still works. I think there were a few breaking changes that will need checking like use of navigate instead of history.

**Comment by EmmaDawsonDev** [comment]
How’s this pr going @E-fais ?

**Comment by E-fais** [comment]
Sorry @EmmaDawsonDev  , I was busy on my current projects.
Yesterday my  fourth  PR for hactoberfest was successfully merged. Wouldn’t it be better to give some others this chance ? 
i am still happy to work on this btw.

**Comment by EmmaDawsonDev** [comment]
No problem, I just wanted to check in. It's totally up to you if you wish to continue with the PR. If you'd rather give the issue to someone else then this PR can be closed.

**Comment by E-fais** [comment]
Okay , i will create an issue so that someone can work on it 👍

**Pull request closed without merging**
