### PR TITLE
Update GetIcons.js

### PR DESCRIPTION
**Pull request by krishguptadev**
HotFix 🚨 #823 removed #811 functionality, breaking a lot of files

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/851"></a>

### CODE REVIEW

**Comment by emmalearnscode** [comment]
Did it completely remove the code somehow or is the code still there but now not doing anything?

**Comment by nathgoutam93** [comment]
So, don't you have to remove the changes made with the PR #811 in this PR? 
Or, there is an easy way to do that. 
Just like unmerge  a PR?

**Comment by emmalearnscode** [comment]
Ok, just looking through the files. All the .toLowerCase code is still there in user profile component so I’m not sure why this has broken. Do we still need all the extra code in user profile component if the lower casing can be applied like this directly in getIcon?

**Comment by nathgoutam93** [comment]
> Ok, just looking through the files. All the .toLowerCase code is still there in user profile component so I’m not sure why this has broken. Do we still need all the extra code in user profile component if the lower casing can be applied like this directly in getIcon?

The lower casing can be directly done in get icons component , we can remove the lower casing code from user profile without any issues.

Btw, what kind of broken files you were referring to?
I didn't saw anything broken on live site. 🙄

**Comment by emmalearnscode** [comment]
> The lower casing can be directly done in get icons component , we can remove the lower casing code from user profile without any issues.

I’m not so sure as I think the icon name might also be used for styling, we’ll need to check it to make sure

**Comment by krishguptadev** [comment]
The issue is here afaik https://github.com/EddieHubCommunity/LinkFree/pull/846#issuecomment-999789484

**Review by krishguptadev — COMMENTED** [review]
Update: The issue was that there was no telegram icon 🤦

**Comment by emmalearnscode** [comment]
Can you add a telegram hover colour to the config/icons.json file also?

**Comment by Rupesh-1302** [comment]
You can also correct arrow left icon it is not lower cased instead It is camel cased in switch case

**Review by emmalearnscode — APPROVED** [review]

**Comment by emmalearnscode** [comment]
We now have two identical pull requests for the same issue. As this one is a bit all over the place in the discussion (as it refers to other issues to start with) I'll close this one to make sure the wrong issues don't get closed when the PR is merged. Thanks for contributing :)

**Pull request closed without merging**
