### PR TITLE
Replace custom CSS with prime-react tailwind classes for Home/Users.js

### LINKED ISSUE #940: [OTHER] Use prime-react classes on chip
### What would you like to share?

Instead of using custom CSS, where possible we should change to prime react.

Task: 
1. Remove the following 3 lines of css from Home.css:
Screenshot 2022-01-08 212923

2. Add the following classes to the <Chip> component in User.js:
Screenshot 2022-01-08 212951

### Additional information

_No response_

### LINKED ISSUE #941: [OTHER] Use prime react classes on chip text
### What would you like to share?

As we are using prime react we should remove the custom css and replace with prime react classes.

1. Remove the following CSS from Home.css:
Screenshot 2022-01-08 220523

2. Replace with these prime react classes in the User.js component
Screenshot 2022-01-08 220542

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eoinmurphy**
## Fixes Issues

Closes #940 & closes #941

## Changes proposed

- Replaces custom CSS for `<Chip>` component in favor of prime-react Tailwind
- Replaces `span.p-chip-text` in favor of prime-react Tailwind

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Main `<Chip>` styles:
linkfree

`span.p-chip-text`
 
span

## Note to reviewers

First ever PR to a public project (albeit teeny tiny)! 🎉 Let me know if you have any feedback. 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/944"></a>

### CODE REVIEW

**Comment by nathgoutam93** [comment]
Looks good to me but we try to keep PRs as specific as possible so, can you please separate These changes into two PRs as profile addition and removal of custom CSS . Please let us know if you need any help.

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
The code looks great 👍🏻 If you could delete your profile from this one and add it as a separate PR then we can get this one merged .

**Comment by eoinmurphy** [comment]
Thanks, both! `eoinmurphy.json` has been removed and PR description updated. I'll submit it in another PR later today. :)

**Review by emmalearnscode — APPROVED** [review]

**Comment by eoinmurphy** [comment]
Thanks @emmalearnscode! How does one go about merging, then? Do I just wait for someone with write access to process the PR?

**Comment by emmalearnscode** [comment]
> Thanks @emmalearnscode! How does one go about merging? Do I just wait for someone with write access to process the PR?

We usually try to wait for at least 2 maintainers to approve the PR and then a maintainer will merge it

**Review by nathgoutam93 — APPROVED** [review]

**Review by schmelto — APPROVED** [review]

**Comment by schmelto** [comment]
Currently only at my phone can some other maintainer merge it :)

**Pull request merged**
