### PR TITLE
Rename siddhesh.json to SiddheshBangar.json

### PR DESCRIPTION
**Pull request by SiddheshBangar**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2921"></a>

### CODE REVIEW

**Review by Njong392 — APPROVED** [review]
Looks amazing! Thank you for contributing :tada:

**Comment by SiddheshBangar** [comment]
@Njong392 I guess a maintainer approval is required to proceed forward? Am I right?

**Comment by Njong392** [comment]
> @Njong392 I guess a maintainer approval is required to proceed forward? Am I right?

Yes! Once a maintainer goes over it, they'll merge 😊

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍 

Great collaboration 💪 

You can also join us in the EddieHub Discord http://discord.eddiehub.org

**Pull request merged**
