### PR TITLE
data: OgeHub

### PR DESCRIPTION
**Pull request by OgeHub**
I added data for the creation of my profile on linkfree.eddiehub.io

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4583"></a>

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
Awesome 👍🏻 Thanks for your first contribution. Hope you will add more links to it.

**Review by Sindhuinti — CHANGES_REQUESTED** [review]
Please place your file in the data folder `data/OdeHub.json`

**Review by priyankarpal — CHANGES_REQUESTED** [review]
please add your file to `data/OgeHub.json` You can check the official doc https://linkfree.eddiehub.io/docs/quickstart ✌️

**Comment by OgeHub** [comment]
> Please place your file in the data folder `data/OdeHub.json`

Alright I will do that, thank you so much.

**Comment by OgeHub** [comment]
> please add your file to `data/OgeHub.json` You can check the official doc https://linkfree.eddiehub.io/docs/quickstart ✌️

Alright I will do that. I really appreciate you.

**Review by priyankarpal — APPROVED** [review]
Awesome 🎉 LGTM

**Review by Sindhuinti — APPROVED** [review]

**Review by Krishnapro — APPROVED** [review]
Awesome ! LGTM 🚀

**Review by kumarsonsoff3 — APPROVED** [review]
Great collaboration everyone! 👍

**Comment by OgeHub** [comment]
Thank you so much everyone...cheers🥂 to more collaborations! I am so excited!🤩

**Pull request merged**
