### PR TITLE
Fix tabs in mobile view by adding conditional in UserTabs.js

### LINKED ISSUE #3080: [FEATURE] If profile only has links then do not show dropdown or tab
### Description

Currently, a dropdown is rendered on mobile regardless of if it is needed or not.  This issue is to handle not rendering a dropdown for profiles that contain only links and only render a dropdown on 2 or more items.

### Screenshots

Current mobile view with links only, dropdown has been clicked in this image. Dropdown is not needed here
Screenshot Amanda profile on android with dropdown clicked showing it has one item only

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KaveriRai**
Closes #3080 

## Changes proposed

In UserTabs.js:

Modified the sm:hidden class div to remove the dropdown on mobile view if number of tabs for a user is less than 2 tabs
Added a conditional statement in sm:hidden to check if number of tabs is greater than 1

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
Original dropdown displayed on mobile view for just 1 tab
Screen Shot 2023-04-03 at 1 49 43 AM

New tabs display when user has less than 2 tabs on mobile view
Screen Shot 2023-04-03 at 1 50 10 AM

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5808"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Sorry @KaveriRai I think I merged in someone else's PR to fix this already as there was no activity from you for 2 weeks. Sorry for the confusion, I should have written something in the issue. I will close this as it is now a duplicate and fix already in the merge https://github.com/EddieHubCommunity/LinkFree/pull/5826

I apologise I messed up. Is there another issue you would like to work on?

**Comment by KaveriRai** [comment]
> Sorry @KaveriRai I think I merged in someone else's PR to fix this already as there was no activity from you for 2 weeks. Sorry for the confusion, I should have written something in the issue. I will close this as it is now a duplicate and fix already in the merge #5826
> 
> I apologise I messed up. Is there another issue you would like to work on?

Hi that's unfortunate to hear because I was the only one assigned to that issue and on #3080 you asked the person to not commit so I was wondering if my commit could still be merged and overwritten. Since this is a part of an assignment for a school project I would really appreciate it if this could still be merged. Thank you

**Comment by eddiejaoude** [comment]
The other reason is your PR had too many changes, it was much simpler than the changes made. Can you look at another issue?

**Comment by eddiejaoude** [comment]
What about writing an automated test for one of the pages https://github.com/EddieHubCommunity/LinkFree/issues/5787

**Comment by KaveriRai** [comment]
> What about writing an automated test for one of the pages #5787

Yes, I can look at that too. Thank you.

**Comment by eddiejaoude** [comment]
Thank you for understanding @KaveriRai , if you need any help, you ca ask in EddieHub Discord

**Pull request closed without merging**
