### PR TITLE
data: Alkaison

### PR DESCRIPTION
**Pull request by Alkaison**
## Changes proposed

- Added my details 

## Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5150"></a>

### CODE REVIEW

**Review by SurajPratap10 — APPROVED** [review]

**Comment by Alkaison** [comment]
image

what's the problem?

**Review by SurajPratap10 — COMMENTED** [review]
the maintainer with the write access will look into that, structure wise your data is correct

**Comment by Alkaison** [comment]
ok, Thanks!

**Review by Sindhuinti — APPROVED** [review]
Looks good 🎉

**Review by Hrishi5111998 — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Pull request merged**
