### PR TITLE
feat: add linkfree-cli support

### LINKED ISSUE #1686: [FEATURE] Add linkfree-cli support
#### 1) Add `linkfree-cli` as devDependencies

Steps: 

- Fork the repo
- Then run 
```
npm run linkfree-cli -D
```
---

#### 2) Add a script in the `package.json` file.

```json
"create": "npx linkfree-cli"
```

### Additional information

Link to CLI repo - https://github.com/Pradumnasaraf/LinkFree-CLI
Link to NPM rej - https://www.npmjs.com/package/linkfree-cli

### PR DESCRIPTION
**Pull request by Dun-sin**
## Changes proposed
- Added linkfree cli to dev dependency
- Added linkfree cli script to package.json

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1695"></a>

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
Was wondering if changes in the `package-lock` would be an issue.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge, thank you for the PR, Dunsin.:tada:

#### Note for reviews:
In this PR Linkfree version is updated to `"version": "0.71.1"`, which is good!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Reusable

**Comment by eddiejaoude** [comment]
@ChinmayMhatre good question, but because there are changes to `package.json` the changes in `package-lock.json` are required

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by eddiejaoude** [comment]
Q. Oh does the documentation need updating in the README so people know it is there to use? This can come in another PR

**Comment by Pradumnasaraf** [comment]
Sorry, @ChinmayMhatre I missed your query between the Action messages. Thank @eddiejaoude  for answering.

**Comment by Pradumnasaraf** [comment]
> Q. Oh does the documentation need updating in the README so people know it is there to use? This can come in another PR

Yes, Eddie, the document needs to be updated. Didn't added in this PR, so that one more person can involve in :)

**Comment by ChinmayMhatre** [comment]
> @ChinmayMhatre good question, but because there are changes to `package.json` the changes in `package-lock.json` are required

Got it ! Thanks!

**Comment by ChinmayMhatre** [comment]
> Sorry, @ChinmayMhatre I missed your query between the Action messages. Thank @eddiejaoude for answering.

No worries! Thanks!

**Pull request merged**
