### PR TITLE
Updated Shreyasri258.json

### PR DESCRIPTION
**Pull request by shreyasri258**
## Changes proposed

Added Profile Picture and another profile link.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2998"></a>

### CODE REVIEW

**Comment by Rishabh-Singh-Codes** [comment]
Why do you have two files?

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey, 

Please delete the file with the name `data/data:shreyasri258.json`, otherwise looks good. Also, resolve conflicts.
If you need any help feel to reach out.

**Comment by shreyasri258** [comment]
Hey, I deleted the file with the name data/data:shreyasri258.json and also resolved conflicts can you please check it out.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
