### PR TITLE
[Add] : Added Version badge and License badge

### PR DESCRIPTION
**Pull request by kartikgajjar7**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot (31) 2

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1552"></a>

### CODE REVIEW

**Comment by Kartik2220** [comment]
@Panquesito7

**Comment by Kartik2220** [comment]
@kumarsonsoff3

**Comment by kartikgajjar7** [comment]
@Panquesito7  hey can you review this ....

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thanks. :)


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Comment by kartikgajjar7** [comment]
@Panquesito7 can you suggest me which other badges should be added ?

**Review by vedanshi555 — APPROVED** [review]

**Review by kumarsonsoff3 — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Comment by Panquesito7** [comment]
> @Panquesito7 can you suggest me which other badges should be added ?

I think it's fine as-is. Too many badges may look spammy or bad.
Not sure what others think, though.

**Comment by kartikgajjar7** [comment]
> > @Panquesito7 can you suggest me which other badges should be added ?
> 
> I think it's fine as-is. Too many badges may look spammy or bad. Not sure what others think, though. We can ask for their opinion. :)

yes i think this much is enough

**Comment by kartikgajjar7** [comment]
@eddiejaoude take a look

**Comment by kumarsonsoff3** [comment]
> > @Panquesito7 can you suggest me which other badges should be added ?
> 
> I think it's fine as-is. Too many badges may look spammy or bad. Not sure what others think, though. We can ask for their opinion. :)

I think the same, Good to go in my opinion! 🚀

**Pull request merged**
