### PR TITLE
my branch is 30 commits ahead of EddieHub

### PR DESCRIPTION
**Pull request by abdussalam02**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1092"></a>

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
Hey! In order to update your fork, I'd recommend using `git pull` or using the [**Pull**](https://github.com/apps/pull) app. Just note that you should make your changes in multiple branches, otherwise, they'll be overwritten. Let us know if you need any help. Thanks. 😃

**Comment by KendallDoesCoding** [comment]
@abdussalam02 Have you edited any other branch in this repo?, do you need patch-1? If not, then I suggest you do what @Panquesito7 said, if you can't though, delete the fork and re-fork it and the issue will be fixed.

**Comment by KendallDoesCoding** [comment]
@abdussalam02 Now you can close this :)

**Comment by emmalearnscode** [comment]
I’ll close this as it’s not a PR. If you need additional help feel free to ask in the discord.

**Pull request closed without merging**
