### PR TITLE
Create lasse.json

### PR DESCRIPTION
**Pull request by lassv**
Created my own profile.

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1648"></a>

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge.

**Note** for reviews - Using line breaks in every property. I hope action will fix that.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thank you! 🎉

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Looks Good, but there is a typo in your link! 🔧 

- So please update your link 
- And update your filename to `username.json` which should be `lassv.json`.

image




__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by lassv** [comment]
> Looks Good, but there is a typo in your link! 🔧
> 
> * So please update your link
> * And update your filename to `username.json` which should be `lassv.json`.
> 
> image
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

updated file name and website link 👋

**Review by kumarsonsoff3 — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Pull request merged**
