### PR TITLE
Profile header 

### PR DESCRIPTION
**Pull request by ManishBisht777**
## Changes proposed

    new styles for profile header

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image
image

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2177"></a>

### CODE REVIEW

**Review by ManishBisht777 — COMMENTED** [review]
look good :)

**Comment by eddiejaoude** [comment]
This doesn't look correct, there are too many changes and many are not yours

**Comment by ManishBisht777** [comment]
I pushed the changes to `update_profile branch ` but it already contains many commits including the commits I have done yesterday I think I messed up something

**Comment by ManishBisht777** [comment]
I pushed the changes to `update_profile branch ` but it already contains many commits including the commits I have done yesterday I think I messed up something

**Comment by ManishBisht777** [comment]
how i do i fix it? should I close this and make a new pull request ?

**Pull request closed without merging**
