### PR TITLE
data: Panquesito7

### PR DESCRIPTION
**Pull request by Panquesito7**
## Changes proposed

- Update my profile.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

None.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7477"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — COMMENTED** [review]
Rest looks good to me, but I think we recently removed the color feature in milestones, and default it to grey. 

So, we might not need the color key in milestones anymore.

**Review by gambhirsharma — APPROVED** [review]

**Comment by Panquesito7** [comment]
> Rest looks good to me, but I think we recently removed the color feature in milestones, and default it to grey.
> 
> So, we might not need the color key in milestones anymore.

Should I remove them in this PR or?

**Comment by kumarsonsoff3** [comment]
> Should I remove them in this PR or?

Yep, it would be great if you remove those from this PR.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge.

**Pull request merged**
