### PR TITLE
updating my profile imran1509.json

### PR DESCRIPTION
**Pull request by imran1509**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2363"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Updating profile doesn't require changes in `lock` files. Please revert the changes from the `CHANGELOG.md`, `package-lock.json`, `package.json` files. Let us know if you need any help! 🛠

**Comment by imran1509** [comment]
> Updating profile doesn't require changes in `lock` files. Please revert the changes from the `CHANGELOG.md`, `package-lock.json`, `package.json` files. Let us know if you need any help! 🛠

But I have not changed anything else other than my profile file. Other changes are showing automatically.
Please help me how to resolve this conflict.

**Comment by eddiejaoude** [comment]
@imran1509 your [commit](https://github.com/EddieHubCommunity/LinkFree/pull/2363/commits/cf19c679592828634bbea9618dd86e7bc49febac) in this PR only has your changes which is correct 👍  but I think your branch might be out of date, which is why it is including another commit - try updating your fork and branch

**Comment by imran1509** [comment]
> @imran1509 your [commit](https://github.com/EddieHubCommunity/LinkFree/pull/2363/commits/cf19c679592828634bbea9618dd86e7bc49febac) in this PR only has your changes which is correct 👍  but I think your branch might be out of date, which is why it is including another commit - try updating your fork and branch

Okay but when I try to update the branch it says need to delete the commits.
Abd when i deleted the commits and updated my profile again.
Same happened.

**Comment by eddiejaoude** [comment]
I think it is because you are making changes in the default branch - you should always make a branch to make changes and not use the default branch - it will create conflicts

I would put your fork's default branch back to match the original repo (upstream) and then make a branch and make your changes ,then create the PR from your branch - you will have less problems

**Comment by imran1509** [comment]
Okay Thanks Eddie.
I Will delete the changes and will do it again in different branch.
I forgot to make a different branch this time. Sorry my bad.

**Comment by eddiejaoude** [comment]
No problem, it happens to us all

**Pull request closed without merging**
