### PR TITLE
Fixed: Layout issue for viewing docs in mobile view

### LINKED ISSUE #4120: Navbar width gets reduced when viewing docs in smaller screen
### Description

When viewing docs, the navbar width decreases as the screen size gets smaller, It should take up the full width of the screen.

### Screenshots

linkfree_docs_nav_issue

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by swagataroy30**
## Fixes Issue

Closes #4120 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

# Before

linkfree_docs_fix_before

# After
linkfree_docs_fix_snap

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4304"></a>

### CODE REVIEW

**Review by Aadarsh805 — COMMENTED** [review]
I hope this does not break anything, that's why a better approach would be to update the `DocsLayout.js` instead

**Comment by Aadarsh805** [comment]
@swagataroy30 You should also add before screenshot along with after screenshot

**Comment by swagataroy30** [comment]
> I hope this does not break anything, that's why a better approach would be to update the `DocsLayout.js` instead

Actually I was trying to target this div where i added min-w-fit
Screenshot from 2023-02-01 09-47-57
this div reduces in size in smaller screen so does the content alongwith, so i set a width to it to fit all it's content and also tried DocsLayout.js but it wasn't working out and i have checked nothing breaks tho!

**Comment by Aadarsh805** [comment]
@swagataroy30 try this and see how it looks

Screenshot from 2023-02-01 22-25-28

**Comment by swagataroy30** [comment]
@Aadarsh805 I did try this earlier and tried it again right now this doesn't seem to work, it's not taking up the full width this way. Did you try on all smaller devices? Here's a snap of it after i implemented as you said 
linkfree_docsLayout_issue

**Comment by Aadarsh805** [comment]
> @Aadarsh805 I did try this earlier and tried it again right now this doesn't seem to work, it's not taking up the full width this way. Did you try on all smaller devices? Here's a snap of how it looks on my mobile device after i implemented as you said linkfree_docsLayout_issue

Works fine on mine though 🤔

**Comment by swagataroy30** [comment]
> > @Aadarsh805 I did try this earlier and tried it again right now this doesn't seem to work, it's not taking up the full width this way. Did you try on all smaller devices? Here's a snap of how it looks on my mobile device after i implemented as you said linkfree_docsLayout_issue
> 
> Works fine on mine though thinking

Did you try other devices below 375? except my mobile i toggled all smaller devices it shows the same

**Comment by Aadarsh805** [comment]
> > > @Aadarsh805 I did try this earlier and tried it again right now this doesn't seem to work, it's not taking up the full width this way. Did you try on all smaller devices? Here's a snap of how it looks on my mobile device after i implemented as you said linkfree_docsLayout_issue
> > 
> > 
> > Works fine on mine though thinking
> 
> Did you try other devices below 375? except my mobile i toggled all smaller devices it shows the same

Oh I see it doesn't work for phone under 375
check out this pr though #4331

**Comment by eddiejaoude** [comment]
I like the simplicity of it, but on the docs page it breaks due to the images, can the images be made more responsive then I think it might work

Screenshot 2023-02-03 at 11 14 12



Screenshot 2023-02-03 at 11 12 46

**Comment by swagataroy30** [comment]
> I like the simplicity of it, but on the docs page it breaks due to the images, can the images be made more responsive then I think it might work
> 
> Screenshot 2023-02-03 at 11 14 12
> 
> Screenshot 2023-02-03 at 11 12 46

Hey, sure I will try to make changes on this! Thanks for the feedback! :+1:

**Comment by swagataroy30** [comment]
> I like the simplicity of it, but on the docs page it breaks due to the images, can the images be made more responsive then I think it might work
> 
> Screenshot 2023-02-03 at 11 14 12
> 
> Screenshot 2023-02-03 at 11 12 46

Hey, the visual changes of the navabar getting reduced in smaller screens can be fixed with 'min-w-fit' to the parent container and after applying this it doesn't break anymore but the navbar gets too small in it's overall height but I think it's happening because of the Clipboard as i was trying to check what was going wrong. I did make some changes to fix it - should i commit those changes. Thank You!

**Comment by eddiejaoude** [comment]
Thank you for your contribution. There have been multiple PRs for the same issue. I will close this PR for another one with a different solution https://github.com/EddieHubCommunity/LinkFree/pull/4448

Please have a look at our open issues that are not yet assigned, and ask for one of them to be assigned to you

**Pull request closed without merging**
