### PR TITLE
[FEATURE] Added support for adding Google Analytics tag for specific user profile.

### LINKED ISSUE #1798: [FEATURE] To add google tracking id for user profile.
### Description

It would be helpful for a user to see the analytics and if we support adding google analytics tracking id in json file.
It would be helpful.

Please confirm if this is a valid feature. 
I would love to do this.

---

By Eddie

- I think the field `gAnalytics` can be added to people's profiles
- if `gAnalytics` is available in the profile, then add to their profile page

### PR DESCRIPTION
**Pull request by Shubhdeep12**
Closes #1798 

## Changes proposed
Added scripts tag for users who have gAnalytics tag added in JSON file.
Scripts will be removed when the user profile component unmounts.

Added a UserMeta component.

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5724"></a>

### CODE REVIEW

**Review by amandamartin-dev — COMMENTED** [review]
Hey @Shubhdeep12 this update seems to require documentation changes so that folks would know how to add the tag to the profile, correct?

**Comment by Shubhdeep12** [comment]
> Hey @Shubhdeep12 this update seems to require documentation changes so that folks would know how to add the tag to the profile, correct?

Hi @amandamartin-dev, yes adding the docs.
Thanks.

**Comment by Shubhdeep12** [comment]
Hi @amandamartin-dev, can you please review now?
Thanks

**Comment by Shubhdeep12** [comment]
Sure @amandamartin-dev 

When a script tag is added with the necessary formatting and a GTM tag, Google Analytics is activated.

So, you can follow these steps to test it without creating a Google Analytics account.

1. Add a few random IDs to 2-3 local profiles.
2. Run locally and access one of the profiles with the random GTM tag. Opendevtools and in the Elements tab, there should be two Scripts tags with a GTM tag.
3. Return to the listing or any other page and check if the script tags have been deleted.
4. Open a profile once more, but this time choose one without a GTM tag inserted in the JSON. This time, there shouldn't be any script tags for Google Analytics.
5. Open another profile that has a different random GTM tag; this time, the new GTM tags will be accompanied by Script tags.


In this manner, Google Analytics will only gather data when the user profile is being seen and we can monitor whether the necessary Script tag is added to and deleted from the DOM tree.


I think this helps!

**Comment by Shubhdeep12** [comment]
Yes @eddiejaoude, but I think there is a limitation in `nextjs-google-analytics`

In the next app, if `NEXT_PUBLIC_GA_MEASUREMENT_ID` is present then `nextjs-google-analytics` will not accept custom `gaMeasurementId`.

Reference - https://github.com/MauricioRobayo/nextjs-google-analytics/blob/86b434f09d57ef7a591c4246ee532e52013d8118/src/components/GoogleAnalytics.tsx#L33

**Comment by eddiejaoude** [comment]
We removed `nextjs-google-analytics` as we are using Vercel analytics. I think this feature will come as part of the Premium version on LinkFree, so I will block it for a few more weeks until that part is finished

**Comment by eddiejaoude** [comment]
Sorry for my slow reply. This is great, but we have decided not to add this feature for the moment, so I will close the PR

Sorry for the inconvenience, I really appreciate your hard work and understanding

**Pull request closed without merging**
