### PR TITLE
fix: add margin to clear/reset btn on map page

### LINKED ISSUE #8194: [BUG] Improve Styling on Map
### Description

The Clear/ Reset and the Notification of it has been clashed, Which looks to be very bad.

Add some Margin & Padding on the box and the notification popup both.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by akshajb**
## Fixes Issue
Closes #8194 

## Changes proposed

1. Created a `div` as parent to the `Button` component. 
2. Added `margin`. 
3. Does not affect the `Badge` or `Button` component and is an implementation specific to this case.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot 2023-07-18 at 9 17 46 AM

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8239"></a>

### CODE REVIEW

**Review by amandamartin-dev — DISMISSED** [review]
Your updates have had an effect on all tags, not just the clear button.  Please take a look and if you have any trouble solving this, let us know! See my screenshot to see what I mean.

height

**Comment by akshajb** [comment]
> Your updates have had an effect on all tags, not just the clear button. Please take a look and if you have any trouble solving this, let us know! See my screenshot to see what I mean.
> 
> height

Unfortunately I am having trouble logging in and could find a way for filters/tags to show up on the map page, but after referencing the production version and other Badge components, i think my latest commit should solve the issue. Sorry for the inconvenience.

**Comment by eddiejaoude** [comment]
> Unfortunately I am having trouble logging in and could not find a way for filters/tags to show up on the map page, but after referencing the production version and other Badge components, i think my latest commit should solve the issue. Sorry for the inconvenience.

for the map you don't need to be logged in, but you can log in if you need to, here the are docs https://linkfree.io/docs/environments/local-development

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Please check your Prettier settings, it is very difficult to see the actual changes because the indentation has changed and it shows more lines have changed

VScode Prettier plugin should pick up the default Prettier settings for our project

**Comment by akshajb** [comment]
> Please check your Prettier settings, it is very difficult to see the actual changes because the indentation has changed and it shows more lines have changed
> 
> VScode Prettier plugin should pick up the default Prettier settings for our project

I used Gitpod for development. Is there anything specifc i need to do on Gitpod to make prettier take the appropriate settings?

**Comment by eddiejaoude** [comment]
> > Please check your Prettier settings, it is very difficult to see the actual changes because the indentation has changed and it shows more lines have changed
> > VScode Prettier plugin should pick up the default Prettier settings for our project
> 
> I used Gitpod for development. Is there anything specifc i need to do on Gitpod to make prettier take the appropriate settings?

Maybe try installing the Prettier VScode plugin, I think that should work

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
