### PR TITLE
added username.json

### PR DESCRIPTION
**Pull request by AnshuPathak-88825**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1403"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Awesome! Thanks.


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Elegant, Maintainable

**Comment by AnshuPathak-88825** [comment]
I'm not able acess my profile using this link https://linkfree.eddiehub.io/AnshuPathak-88825 t

**Comment by AnshuPathak-88825** [comment]
I'm not able acess my profile using this link https://linkfree.eddiehub.io/AnshuPathak-88825 pls help

**Comment by vincekashaka** [comment]
__
 
  Summary: 👌 This code looks good  |  Tags: Efficient

**Pull request merged**
