### PR TITLE
Added Tech Stack section in the README.md

### LINKED ISSUE #3000: [FEATURE] Tech Stack missing from README - request for inclusion
### Description

Adding the Tech Stack in the README can help other developers understand the technical requirements or dependencies of the project. If someone is interested in contributing to the project, they will know what tools or languages they need to be familiar with.

Sharing an example in the screenshots.

### Screenshots

tech stack

### Additional information

In the example given I was not able to verically align the text with the markdown badge otherwise it would have looked a bit clean.

### PR DESCRIPTION
**Pull request by Saadat-B**
## Fixes Issue

Closes #3000 

## Changes proposed

Added the Tech Stack section in the README file to assist potential contributors to know what tools or languages they need to be familiar with before contributing to the project.

I've also provided links to the official websites of the corresponding technologies in the markdown badges, for those who wish to learn more about them.

To align the badges with the text I've used a table. Please let me know if this works or I need to make some changes to it.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
tech stack

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3061"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
The table doesn't look quite right (please include a screenshot in the PR)

Screenshot 2023-01-11 at 20 33 38

**Comment by Saadat-B** [comment]
> The table doesn't look quite right (please include a screenshot in the PR)



Yes, I wasn't able to make a table without adding a heading to each column. So I thought by leaving the headers empty it would remove the top row which is blank. But it doesn't look quite well.

Should I add "Tech" and "description" as the heading for the two columns or should I remove the table altogether and use bullet points instead?

(I did include a screenshot in my PR when I raised it, please do let me know if it's not visible to you)

**Comment by eddiejaoude** [comment]
> (I did include a screenshot in my PR when I raised it, please do let me know if it's not visible to you)

Sorry, it is visible now, not why it didn't load before

> Should I add "Tech" and "description" as the heading for the two columns or should I remove the table altogether and use bullet points instead?

yes I think so. Could you try it and update the screenshot please

**Comment by Saadat-B** [comment]
> Should I add "Tech" and "description" as the heading for the two columns or should I remove the table altogether and use bullet points instead?

> yes I think so. Could you try it and update the screenshot please

I've made the changes and attached the screenshot as requested. Please let me know if this okay or I need to make a few changes to it.

tech stack

**Comment by eddiejaoude** [comment]
Hmm I am still not sure. Do you have some examples of how other repos do it?

**Comment by Saadat-B** [comment]
> Hmm I am still not sure. Do you have some examples of how other repos do it?

Here are some examples I was able find

- 1  - This utilizes Markdown badges exclusively


- 2  - This references the technology and its application within the project


- 3  - This describes the technology and includes a brief overview, as well as links to its homepage for further exploration


- 4  - This uses images and cites the technology's name


- 5  - This uses shields to present information about the utilized technology


- 6  - This simply uses bullet points to list the technology



We have the option to use one of the above styles, or combine a few to create a unique one

**Comment by eddiejaoude** [comment]
Thank you for the great example list 👍 

Let's start with number 3 first, and we can improve further later on

**Comment by Saadat-B** [comment]
> Let's start with number 3 first, and we can improve further later on

Sounds good 👍, I've made the neccessary changes. Please have a look.

tech stack

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
