### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SukeshRondla**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by SukeshRondla** [comment]
Changes Few Spelling Mistakes. Dont Mind.

**Comment by Opg56rus** [comment]
Отправлено с моего телефона HONOR-------- Исходное сообщение --------От: Sukesh Reddy Rondla ***@***.***>Дата: вс, 6 авг. 2023 г., 04:13Кому: EddieHubCommunity/LinkFree ***@***.***>Копия: Subscribed ***@***.***>Тема: [EddieHubCommunity/LinkFree] Update README.md (PR #8528)
Fixes Issue


Changes proposed



Check List (Check all the applicable boxes) 
 My code follows the code style of this project. My change requires changes to the documentation. I have updated the documentation accordingly. All new and existing tests passed. This PR does not contain plagiarized content. The title of my pull request is a short description of the requested changes.
Screenshots

Note to reviewers




You can view, comment on, or merge this pull request online at:
  https://github.com/EddieHubCommunity/LinkFree/pull/8528

Commit Summary
1981f72  Update README.md

File Changes  (1 file)

    M
    README.md
    (12)
  

Patch Links:
https://github.com/EddieHubCommunity/LinkFree/pull/8528.patchhttps://github.com/EddieHubCommunity/LinkFree/pull/8528.diff

**Review by sital002 — COMMENTED** [review]
You can't send PR without raising the issue and get assigned to you. I would highly recommend you to read our contributing guidelines https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Hey @SukeshRondla, I'm sorry but I couldn't find any valuable change here. The spellings you're changing are correct already. 

Another, `docker commands` are changed by you which might cause issues in local development for other contributors. 

--
I'll be closing this PR, and as suggested by @sital002, Please follow our contributing guidelines for future contributions.

**Pull request closed without merging**
