### PR TITLE
Alias imports

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

Resolved conflicts for https://github.com/EddieHubCommunity/LinkFree/pull/4543

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5579"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thanks for looking Amanda, yeah it is huge. Maybe checkout the branch and have a play with the web site and make sure nothing is broken - this has prompted me to write more automated tests that check all the main features

**Comment by eddiejaoude** [comment]
Thanks for looking Amanda, yeah it is huge. Maybe checkout the branch and have a play with the web site and make sure nothing is broken - this has prompted me to write more automated tests that check all the main features

**Review by amandamartin-dev — APPROVED** [review]
opened in gitpod, visited all areas except logging in which never worked for me in gitpod so that's not due to this pr

lgtm

**Comment by eddiejaoude** [comment]
Thank you Amanda 👍

**Comment by FrozenHearth** [comment]
Thank you @eddiejaoude for resolving the conflicts & merging this.
In my PR, I had added the path alias only for components folder, but we can add it for other folders too.
Also, since I'm new to testing, I'd love to see automated tests for this. Would be a great learning experience. :)

**Comment by eddiejaoude** [comment]
Thank you for starting these changes off, yes I added more folders because using aliases was a great idea 👍 

Yes we need to really have a basic test for each page to show that they display with no errors, then we can build on them further later - we use Playwright and we have this setup already with some examples. Any questions you can ask in Discord help channel in EddieHub

**Pull request merged**
