### PR TITLE
docs: add information on why user markers not appearing in local dev

### LINKED ISSUE #5473: [DOCS] Need more information on why user markers not appearing on map in local development mode
### Description

In the current implementation, a user's location information in MongoDB is only updated when they visit their specific profile page. This leads to the map page not displaying any user markers during local development since no user has their location information yet in the database. To display user markers on the map page, developers need to visit multiple user profiles to populate the database with location information.

It would be helpful to update the map page documentation to reflect this behavior and provide clear instructions on how to populate the database with location information.

### Screenshots

In the local development environment, the map snapshot will not display any user markers if no profiles have been visited. Therefore, it is necessary to visit at least one user profile to populate the map with user markers.

Initially, no user markers
image

After visiting some profiles:
image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by weilincheng**
## Fixes Issue
Closes #5473 

## Changes proposed

- Add information on why user markers not appearing in local dev to the [Map Information Doc](https://linkfree.io/docs/map)

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

The documentation now explains why user markers do not appear on the map page during local development and provide a solution to populate the database with location information. This change aims to help beginner developers who may face this issue while working on the project.

As discussed in issue #5473, I plan to create a new issue for adding a `seed` script to populate mock user location information to the database for local development purposes. This would make it easier for developers to test the map functionality without manually visiting multiple user profiles.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5766"></a>

### CODE REVIEW

**Comment by Ananya2001-an** [comment]
Hey @weilincheng The changes look good but I was wondering that some contributors might get confused as to what that script should be like if they want to try that way. So maybe we can provide a script for them to run. I saw your issue for the seed script. I guess in this info you can talk about that script to be run but of course first we need to add that script only then this can be merged. WDYT?

**Comment by weilincheng** [comment]
> Hey @weilincheng The changes look good but I was wondering that some contributors might get confused as to what that script should be like if they want to try that way. So maybe we can provide a script for them to run. I saw your issue for the seed script. I guess in this info you can talk about that script to be run but of course first we need to add that script only then this can be merged. WDYT?

Hi @Ananya2001-an, thanks for the review. That's a good point about not mentioning the seed script in the documentation until it's been implemented. In the meantime, I'll remove any mention of the script from the documentation PR to avoid confusion and ensure that it can be merged as soon as possible so that the current situation is documented well. 

Once the seed script has been added, we'll update the Map Information Doc and include instructions on how to run it.

Thank you for your feedback and please let me know if you have any further suggestions or comments.

**Comment by eddiejaoude** [comment]
We should mention running the automated tests and link to those docs will visit some profiles and create location information

**Comment by Ananya2001-an** [comment]
@weilincheng Thanks for considering the feedback 👍🏼

**Comment by weilincheng** [comment]
Hi Eddie, thank you for suggesting the use of automated tests to populate the database with location information. I tried the automated tests and found that they do visit some user profiles and create location information in the database. However, I noticed that only one of the profiles contains real location information, while the rest have unknown location information.

To address this issue, I think it would be helpful to add a few more real profile visits to the automated tests so that more location information can be added to the database. In the meantime, I have updated the documentation as follows:

---

`To display user markers on the map page during local development, you can run the automated tests. The automated tests will visit some user profiles and create location information in the database. This will allow the user markers to appear on the map. For more information on how to execute the automated tests, please refer to the [Automated Tests Doc](https://linkfree.eddiehub.io/docs/contributing/automated-tests). Alternatively, you can manually visit multiple user profiles to populate the database with location information.`

---

Thank you again for your feedback, and please let me know if you have any further suggestions or comments. If not, I will go ahead to push the changes.

**Comment by eddiejaoude** [comment]
Looks great 👍 

> To address this issue, I think it would be helpful to add a few more real profile visits to the automated tests so that more location information can be added to the database

Good idea, select a few profiles and create a test file for maps, and visit those profiles in that single test file 👍

**Comment by weilincheng** [comment]
> Looks great 👍

Great, thank you for reviewing the changes. I have pushed the update to the documentation.

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍 

Future improvements can come in another PR

**Pull request merged**
