### PR TITLE
fix: add Meet Mulik

### PR DESCRIPTION
**Pull request by MeetMulik**
## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/906"></a>

### CODE REVIEW

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
Thanks for contributing! Your profile looks good, if you can remove the package-lock.json file from your pull request that would be great.

**Review by Vyvy-vi — CHANGES_REQUESTED** [review]
Could you reset the `package-lock.json` file?

**Review by Panquesito7 — APPROVED** [review]

**Review by Vyvy-vi — APPROVED** [review]
Looks good to me!

**Review by emmalearnscode — APPROVED** [review]

**Comment by MeetMulik** [comment]
Thank you so much! @Panquesito7 @emmalearnscode @Vyvy-vi

**Pull request merged**
