### PR TITLE
Elishaokon13 patch 1

### PR DESCRIPTION
**Pull request by Elishaokon13**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3820"></a>

### CODE REVIEW

**Review by dan-mba — CHANGES_REQUESTED** [review]
To fix the JSON error you need a `,` at the end of line 11.

Please remove the file not in the data directory

**Comment by Elishaokon13** [comment]
Hi @dan-mba Thank you for that observation.
I have fixed it now

**Review by dan-mba — CHANGES_REQUESTED** [review]
You also need a `,` at the end of line 32

**Review by dan-mba — CHANGES_REQUESTED** [review]
Please remove the `,` at the end of line 41

**Review by dan-mba — APPROVED** [review]
Looks good to me.

You might want to change the icon on your LinkedIn link to `FaLinkedin`

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good, Thanks! 🎉

**Pull request merged**
