### PR TITLE
data: weilincheng

### PR DESCRIPTION
**Pull request by weilincheng**
## Changes proposed
Add new data for weilincheng

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5041"></a>

### CODE REVIEW

**Review by GauravKanwat — DISMISSED** [review]
Looks good. Welcome to LinkFree! :wave:

**Review by Panquesito7 — DISMISSED** [review]
Thanks! 🎉

**Comment by weilincheng** [comment]
I made some changes. Please review it again. Thanks!

**Review by Panquesito7 — APPROVED** [review]

**Review by SurajPratap10 — APPROVED** [review]
Great

**Review by Hrishi5111998 — APPROVED** [review]

**Review by SaraJaoude — APPROVED** [review]
looks good

**Comment by weilincheng** [comment]
Thanks everyone!☺️

**Pull request merged**
