### PR TITLE
data: RitaMwas

### PR DESCRIPTION
**Pull request by RitaMwas**

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by RitaMwas** [comment]
Hi,
How do I know I have received the custom url? Should I close the pull request?

**Comment by eddiejaoude** [comment]
A few minutes after the pull request is merged, your url will be available - it will be the linkfree.eddiehub.io url with your filename (GitHub username) appended

So yours will be https://linkfree.eddiehub.io/RitaMwas

I will merge your PR now 😉

**Comment by eddiejaoude** [comment]
Your profile is now live 🎉 https://linkfree.eddiehub.io/RitaMwas

Don't forget you can keep adding to your profile like `events`, `testimonials`, `milestones` etc

**Comment by RitaMwas** [comment]
Thanks.
I am really really new to open source and github and the entire contribution process. How do i keep adding to my profile? Do I repeat the entire process?

**Comment by eddiejaoude** [comment]
Yes you can repeat the process and amend your profile file.

But remember to update your fork first, and create a new branch from `main` here are the steps...
1. In your fork, update your `main` branch
2. create a new branch from `main` (not your previously used branch)
3. make changes in your new branch
4. create pull request

**Pull request merged**
