### PR TITLE
dx: gitpod first terminal

### LINKED ISSUE #3090: [DX]: Gitpod: Nextjs should be default open shell
### What would you like to share?

By default:

image

Since Mongo: mongod is the second shell it opens up, but really I think the main shell should open

We can change this behavior by switching the order

Also the names of the processes aren't very helpful (Install NPM Dependencies is the dev server? 😱)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by krshkun**
## Fixes Issue

closes #3090 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3092"></a>

### CODE REVIEW

**Comment by Ertan222** [comment]
> dx: gitpod fiirst terminal
Is multiple i intentional in PR's name or just typo? @krshkun

**Comment by eddiejaoude** [comment]
I have assigned to Cahl to review as he is the Gitpod expert

**Comment by krshkun** [comment]
Well, @eddiejaoude this does not make any other changes that reordering and renaming the open shells 😅

**Comment by eddiejaoude** [comment]
Thanks everyone 👍

**Pull request merged**
