### PR TITLE
Added new event - AWS Innovate

### PR DESCRIPTION
**Pull request by SandipPalit**
Added a new event.

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by SandipPalit** [comment]
Hi @Panquesito7 and @eddiejaoude , 

Thank You for reviewing and merging this PR.

Unfortunately, I am unable to see this event in my profile.

image

Kindly let me know, whether I made any mistake in filling the details.

**Comment by eddiejaoude** [comment]
Hi @SandipPalit , the date format is incorrect. I will fix for you now

**Comment by eddiejaoude** [comment]
This is now fixed and on your profile

Screenshot 2023-02-02 at 11 41 31

**Pull request merged**
