### PR TITLE
data:qwertyroop

### PR DESCRIPTION
**Pull request by qwertyroop**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ x] My change requires changes to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7173"></a>

### CODE REVIEW

**Review by khushalarora — CHANGES_REQUESTED** [review]
Hey @qwertyroop, thank you for contributing :tada: 
Please rename your file as with your GitHub username **`qwertyroop`**, [Here](https://github.com/qwertyroop/LinkFree/edit/qwertyroop-patch-1/data/RoopeshVetcha.json)
Your filename will look like **`data/qwertyroop.json`**

**Comment by qwertyroop** [comment]
done I did it.

**Comment by qwertyroop** [comment]
Hey I did that change and i found an issue and I want to resolve it and if
I did so then it will be my first contribution so kindly assign me this as
I opened it. Thx in advance

**Review by SaraJaoude — CHANGES_REQUESTED** [review]
> Hey I did that change and i found an issue and I want to resolve it and if I did so then it will be my first contribution so kindly assign me this as I opened it. Thx in advance
> […](#)

@qwertyroop you did not make the change that @khushalarora suggested (you changed the title of the Pull Request, not the file).  You might want to have a look at section 7 of the QuickStart Guide: https://linkfree.io/docs/quickstart

You are the author of the Pull Request so you can make changes to it.

A Pull Request is only assigned for reviewers.

**Comment by qwertyroop** [comment]
I can't find how to rename my data/roopeshvetcha.json so can I create a new
one? With my GitHub username?

**Comment by khushalarora** [comment]
Hey @qwertyroop, you can rename your file [Here](https://github.com/qwertyroop/LinkFree/edit/qwertyroop-patch-1/data/RoopeshVetcha.json).
It should look like **`data/qwertyroop.json`**

**Comment by qwertyroop** [comment]
Done.

**Review by Sindhuinti — APPROVED** [review]
Looks Good 👍🏻

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks for Contributing!! 🎉

**Pull request merged**
