### PR TITLE
added copy clipboard in "how-to-guides" under docs

### LINKED ISSUE #2559: [DOCS] Addition of a Click to Copy button to the docs bio page example code
### Description

The example code in the `bio` page (https://linkfree.eddiehub.io/docs/how-to-guides/bio) should have a Click to Copy button.

The `quickstart` page (https://linkfree.eddiehub.io/docs/quickstart) already has that component, can be used it as reference.

### Screenshots

_No response_

### Additional information

_No response_

### LINKED ISSUE #2561: [DOCS] Addition of a Click to Copy button to the docs links page example code
### Description

The example code in the `links` page (https://linkfree.eddiehub.io/docs/how-to-guides/links) should have a Click to Copy button.

The `quickstart` page (https://linkfree.eddiehub.io/docs/quickstart) already has that component, can be used it as reference.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Anan7Codes**
## Fixes Issue

Closes #2561
closes #2559 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Imported ClipboardCopy from the components folder and wrapped the code snippets inside it.

## Screenshots
linkfree-ss

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2565"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
@Anan7Codes thank you for the contribution, but these are in separate issues so multiple people could work on them and some of those issues were already assigned to people.

In the future please only do 1 issue per PR and issues that are not already assigned.

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Please remove changes to the `package-lock.json` file, these are not required

**Comment by Anan7Codes** [comment]
My bad @eddiejaoude! New to the open source world and didn't notice it was assigned to somebody else and the fact that I did more than what was requested. Will learn from this and be careful next time. Thank you!

Also wasn't sure if I modified the files the right way. I just went to files-changed and deleted package-lock.json. I can see it has been reflected under commits. Lmk if that was the right way, thanks.

**Review by Rishav-12 — COMMENTED** [review]
I think you should not _delete_ `package-lock.json`, rather you should revert it to the state it was in before you made your changes

**Comment by Anan7Codes** [comment]
> I think you should not _delete_ `package-lock.json`, rather you should revert it to the state it was in before you made your changes

Thanks @Rishav-12. Have reverted it.

**Comment by eddiejaoude** [comment]
> My bad @eddiejaoude! New to the open source world and didn't notice it was assigned to somebody else and the fact that I did more than what was requested. Will learn from this and be careful next time. Thank you!

Thank you

> Also wasn't sure if I modified the files the right way. I just went to files-changed and deleted package-lock.json. I can see it has been reflected under commits. Lmk if that was the right way, thanks.

The `package-lock.json`file should not be in your committed changes, because you did not make any changes to the `package.json` file. Once this file is no longer showing in the `files changed` tab we can merge your pull request.

**Comment by Anan7Codes** [comment]
> > My bad @eddiejaoude! New to the open source world and didn't notice it was assigned to somebody else and the fact that I did more than what was requested. Will learn from this and be careful next time. Thank you!
> 
> Thank you
> 
> > Also wasn't sure if I modified the files the right way. I just went to files-changed and deleted package-lock.json. I can see it has been reflected under commits. Lmk if that was the right way, thanks.
> 
> The `package-lock.json`file should not be in your committed changes, because you did not make any changes to the `package.json` file. Once this file is no longer showing in the `files changed` tab we can merge your pull request.

I've actually reverted the package-lock.json file. Under file changed it seems to show the difference on package-lock.json is a space if I'm not sure. Can you guide me on how I could possibly fix this? 🤔

**Comment by eddiejaoude** [comment]
There are a few ways you can fix it, I think because you made changes in your `main` branch it might be a bit trickier...

1. find the commit previous to your first commit
2. run this command with the updated `[commit ID]`
```
git checkout [commit ID] -- package-lock.json
```

I think that should fix it, I never tried before

**Comment by Anan7Codes** [comment]
> > > My bad @eddiejaoude! New to the open source world and didn't notice it was assigned to somebody else and the fact that I did more than what was requested. Will learn from this and be careful next time. Thank you!
> > 
> > 
> > Thank you
> > > Also wasn't sure if I modified the files the right way. I just went to files-changed and deleted package-lock.json. I can see it has been reflected under commits. Lmk if that was the right way, thanks.
> > 
> > 
> > The `package-lock.json`file should not be in your committed changes, because you did not make any changes to the `package.json` file. Once this file is no longer showing in the `files changed` tab we can merge your pull request.
> 
> I've actually reverted the package-lock.json file. Under files changed it seems to show the difference on package-lock.json is a space if I'm not wrong. Can you guide me on how I could possibly fix this? 🤔

linkfree-ss

Checked on "Display the rich diff" and it says "No dependencies changed" but I'm still curious to know how I can revert the file back 🤔

**Comment by Anan7Codes** [comment]
> There are a few ways you can fix it, I think because you made changes in your `main` branch it might be a bit trickier...
> 
> 1. find the commit previous to your first commit
> 2. run this command with the updated `[commit ID]`
> 
> ```
> git checkout [commit ID] -- package-lock.json
> ```
> 
> I think that should fix it, I never tried before

Cool will give this a shot

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by Anan7Codes** [comment]
> There are a few ways you can fix it, I think because you made changes in your `main` branch it might be a bit trickier...
> 
> 1. find the commit previous to your first commit
> 2. run this command with the updated `[commit ID]`
> 
> ```
> git checkout [commit ID] -- package-lock.json
> ```
> 
> I think that should fix it, I never tried before

Yes this worked. That was a good learning experience haha, thanks.

Also would you mind giving tips on a few things that I should keep in mind? I've learned I should get it assigned and stuff but maybe not use the main branch as well? anything else?

**Comment by eddiejaoude** [comment]
> Yes this worked. That was a good learning experience haha, thanks.

I learnt something new also 🎉 

> Also would you mind giving tips on a few things that I should keep in mind? I've learned I should get it assigned and stuff but maybe not use the main branch as well? anything else?

I have many tips on my YouTube channel, here are a few
- also check the changes before doing a commit and only commit files you changed
- yes always create a branch from `main` but make sure it is updated first with the upstream repo

I think we will learn more as we go along, keep going 💪

**Comment by Anan7Codes** [comment]
> > Yes this worked. That was a good learning experience haha, thanks.
> 
> I learnt something new also 🎉
> 
> > Also would you mind giving tips on a few things that I should keep in mind? I've learned I should get it assigned and stuff but maybe not use the main branch as well? anything else?
> 
> I have many tips on my YouTube channel, here are a few
> 
> * also check the changes before doing a commit and only commit files you changed
> * yes always create a branch from `main` but make sure it is updated first with the upstream repo
> 
> I think we will learn more as we go along, keep going 💪

Got it, thanks!

**Pull request merged**
