### PR TITLE
fix: update devgossips username

### LINKED ISSUE #1232: [OTHER] User `devgossips` not found
### What would you like to share?

[LinkFree](https://github.com/EddieHubCommunity/LinkFree)/[public](https://github.com/EddieHubCommunity/LinkFree/tree/main/public)/[data](https://github.com/EddieHubCommunity/LinkFree/tree/main/public/data)/devgossips.json
### User not found
image

### Solution

I think the new username is @heysagnik

### PR DESCRIPTION
**Pull request by anshulnegii**
updated Sagnik's GitHub'susername and profile picture

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1241"></a>

Resolves #1232

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey! Anshul, not quite sure if we allow modification to other people's profiles.
Yes, the profile link is broken, but still, we can't able to confirm the user updated username.

**Let's see what other reviews think of that**

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Review by vikasganiga05 — APPROVED** [review]
LGTM :+1:
Did you rename `devgossips` to `heysagnik` or created a new `heysagnik` file?
On his Twitter handle, he provided a website link https://bio.devgossips.vercel.app/ Where he updated the new Github link (https://github.com/heysagnik).

**Review by schmelto — APPROVED** [review]
## Looking good to me

Your suggested changes looking good to me.
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Comment by schmelto** [comment]
> Hey! Anshul, not quite sure if we allow modification to other people's profiles.
> 
> Yes, the profile link is broken, but still, we can't able to confirm the user updated username.
> 
> 
> 
> **Let's see what other reviews think of that**
> 
> 
> 
> __
> 
> [sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question
> 
> 
In the old commit of the file there is this changed username in this case I think we could merge these changes.

**Comment by schmelto** [comment]
> > Hey! Anshul, not quite sure if we allow modification to other people's profiles.
> > Yes, the profile link is broken, but still, we can't able to confirm the user updated username.
> > **Let's see what other reviews think of that**
> > __
> > [sema-logo](https://semasoftware.com/gh)  ❓ I have a question
> 
> In the old commit of the file there is this changed username in this case I think we could merge these changes.

Hey @Pradumnasaraf I found the old PR https://github.com/EddieHubCommunity/LinkFree/pull/831 there @heysagnik created the initial file.

**Review by kumarsonsoff3 — APPROVED** [review]
Changes you suggested looks Good to me! 🚀

**Comment by Pradumnasaraf** [comment]
> > > Hey! Anshul, not quite sure if we allow modification to other people's profiles.
> > > Yes, the profile link is broken, but still, we can't able to confirm the user updated username.
> > > **Let's see what other reviews think of that**
> > > __
> > > [sema-logo](https://semasoftware.com/gh)  ❓ I have a question
> > 
> > 
> > In the old commit of the file there is this changed username in this case I think we could merge these changes.
> 
> Hey @Pradumnasaraf I found the old PR #831 there @heysagnik created the initial file.

That is great Tom, but still, they are is changing someone's profile.

**Leaving up you and other maintainers for the decision** :smile:

**Comment by Pradumnasaraf** [comment]
> Thanks for updating my username 😊

Thanks for your reply, hey @schmelto I think we can merge now 🚀 


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Maintainable

**Comment by schmelto** [comment]
Thx

**Pull request merged**
