### PR TITLE
Add profile

### PR DESCRIPTION
**Pull request by rohansx**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5745"></a>

### CODE REVIEW

**Review by himanshu1221 — CHANGES_REQUESTED** [review]
Hey @rohansx kindly delete the file which is `outside` the `data` folder

**Comment by rohansx** [comment]
> Hey @rohansx kindly delete the file which is `outside` the `data` folder

Done. Thanks.

**Review by schmelto — DISMISSED** [review]

**Review by himanshu1221 — APPROVED** [review]
Awesome! LGTM :+1:

**Review by khushalarora — APPROVED** [review]
Looks good, thanks :tada:

**Review by schmelto — APPROVED** [review]

**Pull request merged**
