### PR TITLE
Mancoba

### PR DESCRIPTION
**Pull request by manq2010**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2050"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts [**here**](https://github.com/EddieHubCommunity/LinkFree/pull/2050/conflicts). If you need any help, you can ask for help here or on our [**Discord server**](http://discord.eddiehub.org). You can also check the [GitHub Docs](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) to make the process easier. 🙂

**Comment by manq2010** [comment]
@Panquesito7 merge conflicts are now resolved. Requesting approval for merge

**Comment by eddiejaoude** [comment]
@manq2010 the PR was closed, is that correct?

**Comment by manq2010** [comment]
@eddiejaoude  I closed it because I opened PR #2140 which has now been merged

**Comment by eddiejaoude** [comment]
ah ok, great, thank you 👍  

btw it is always good to leave a comment when closing

**Comment by manq2010** [comment]
Noted @eddiejaoude, thanks for the feedback, I will add a comment when closing a PR

**Comment by eddiejaoude** [comment]
Thank you, I think we all need to get better at this also 👍  (including me 🤓  )

**Pull request closed without merging**
