### PR TITLE
data:pritamrajput

### PR DESCRIPTION
**Pull request by pritamrajput**
I want to contribute to the linkfree project by creating my profile on Linkfree.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3124"></a>

### CODE REVIEW

**Review by Sativarsainath-26 — APPROVED** [review]
Looks good :thumbsup: . Thanks for Contributing.

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by pritamrajput** [comment]
My PR is not merged yet

**Comment by Panquesito7** [comment]
> My PR is not merged yet

Your PR will be merged once another maintainer approves it. 🙂

**Comment by pritamrajput** [comment]
> > My PR is not merged yet
> 
> Your PR will be merged once another maintainer approves it. 🙂

okay thanks for the reply 🙂

**Pull request merged**
