### PR TITLE
data: analizzi

### PR DESCRIPTION
**Pull request by analizzi**
Thank you ChatGPT for the bio

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5468"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by bkpecho — APPROVED** [review]
Lovely bio! Thanks for contributing! 😄

**Comment by SaraJaoude** [comment]
@analizzi Please resolve the conflicts. This is usually because your fork is out of date. 

You may wish to take a look at our Docs and the accompanying video: https://linkfree.eddiehub.io/docs/how-to-guides/editing

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Review by mahfuztbt — APPROVED** [review]

**Comment by analizzi** [comment]
> https://linkfree.eddiehub.io/docs/how-to-guides/editing

I clicked sync fork before i submitted the request

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
