### PR TITLE
Added Sri Satya data

### PR DESCRIPTION
**Pull request by SriSatyaT**
I have added my data :)
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/158"></a>

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
LGTM 👍

**Comment by SriSatyaT** [comment]
Had a doubt I haven't done any changes in any other files(except list.json and username.json) But isn't that showing in 4 files 🤔.  Maybe someone didn't committed them....

**Comment by Cahllagerfeld** [comment]
The changes were fine, dont worry (: . It just bumped the version in the lockfile and added a blankline at the end of package.json :D

**Comment by SriSatyaT** [comment]
> The changes were fine, dont worry (: . It just bumped the version in the lockfile and added a blankline at the end of package.json :D 

Ohk. Thanks Cahl 👍🏻🙌🏻.

**Pull request merged**
