### PR TITLE
ankita malik profile added

### PR DESCRIPTION
**Pull request by AnkitaMalik22**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1678"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Profile data looks good to me, but please update your filename to `username.json`, which should be `AnkitaMalik22.json`. 🛠

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Inelegant

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍. @kumarsonsoff3 Please re-review this PR. It looks good to merge.

**Comment by kumarsonsoff3** [comment]
Hey @AnkitaMalik22, you've committed 2 files! I believe you need to keep `AnkitaMalik22.json` and remove the other one! 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good to me! Thanks for contributing! 🚀 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🎉


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
