### PR TITLE
data: juanf1990

### PR DESCRIPTION
**Pull request by juanf1990**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5128"></a>

### CODE REVIEW

**Review by GauravKanwat — CHANGES_REQUESTED** [review]
Don't forget to validate the code on [jsonlint.com](url)

**Review by juanf1990 — COMMENTED** [review]
fixed code and shown no errors on link provided

**Review by GauravKanwat — APPROVED** [review]
LGTM :rocket:

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks for your Contribution. 🎉 

<p align="center"></p>

**Pull request merged**
