### PR TITLE
data:parveshsaini

### PR DESCRIPTION
**Pull request by parveshsaini**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3791"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — DISMISSED** [review]
Please move your file to data directory, and rename it as your `username.json`. 

It should be `data/parveshsaini.json`.

**Review by parveshsaini — COMMENTED** [review]
fix: moved .json file to data directory

**Review by Vyvy-vi — APPROVED** [review]
LGTM!

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
