### PR TITLE
fix(#1999) : color issue in the dark mode

### PR DESCRIPTION
**Pull request by skarthikeyan96**
Closes https://github.com/EddieHubCommunity/LinkFree/issues/1999

### Changes proposed

When the user hovers over the items in the list, box shadow of white was causing eye strain, and the text was not visible. Hence as part of this PR I have removed the box shadow and updated the color to black on hover which will fix the above issue. 

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

Before fix:

image

After fix:

image

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2014"></a>

### CODE REVIEW

**Comment by E-fais** [comment]
Looking Good 👍

**Comment by skarthikeyan96** [comment]
@eddiejaoude Can you please have a look at the PR

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍  Could you resolve conflicts then we can merge

**Comment by eddiejaoude** [comment]
I resolved them, so lets merge 🎉

**Pull request merged**
