### PR TITLE
Add Dark Mode Support

### LINKED ISSUE #1838: [FEATURE] Add Dark Mode
### Description

EddieHub is a community of developers and open-source enthusiasts. And who doesn't love dark mode more than them? I would like to add dark mode support. 

Please assign this issue to me and attach the Hackoberfest label.

### Screenshots

_No response_

### Additional information

🌚

### PR DESCRIPTION
**Pull request by Keshraf**
## Fixes Issue
Closes #1838 

## Changes proposed
1. Added Dark Mode Support in Tailwind Config File
2. Installed next-themes package which enables us to change to dark mode programmatically
3. Added Dark Mode Toggle Button
4. Fixed Text that weren't changing on switching

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot 2022-10-03 at 8 04 21 PM
Screenshot 2022-10-03 at 8 04 29 PM
Screenshot 2022-10-03 at 8 04 55 PM
Screenshot 2022-10-03 at 8 05 07 PM

## Note to reviewers

I found that the menu button for mobile-view doesn't work, should I create a new issue and PR for it?

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1874"></a>

### CODE REVIEW

**Comment by Keshraf** [comment]
How can I fix this? I

 would also be open to suggestions on my work

**Comment by eddiejaoude** [comment]
Sorry @Keshraf for my slow reply, I will take a look today

**Comment by eddiejaoude** [comment]
> I found that the menu button for mobile-view doesn't work, should I create a new issue and PR for it?

I just saw your comment @Keshraf, it would be better to fix it in this PR

**Comment by Keshraf** [comment]
Okay @eddiejaoude, I will fix it in this PR 👍

**Comment by Keshraf** [comment]
> Sorry @Keshraf I just realised we might be talking about different menu buttons. Are you talking about the light/dark mode or the "hamburger" one? If for the existing button that is not required for this PR, sorry I assumed you meant for your new button
> 
> 
> 
> Please clarify and we can hopefully get this merged soon, thanks 👍 

I was talking about the "hamburger menu" button. Should I add it to this PR?

**Comment by eddiejaoude** [comment]
Yes please, if you can add it to this PR as it is related to the changes here 👍 

Sorry you have some conflicts to resolve now because other PRs have been merged in

**Pull request closed without merging**
