### PR TITLE
Add My Profile JSON data

### PR DESCRIPTION
**Pull request by aldyadk**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1940"></a>

### CODE REVIEW

**Review by accodes21 — CHANGES_REQUESTED** [review]
Everything looks great.
Just change the typo at ```icon: LinkedIn```

**Comment by aldyadk** [comment]
> Everything looks great. Just change the typo at `icon: LinkedIn`

Hi @accodes21 thanks for the suggestion,
but I think from the docs, icons are intended to be written on lowercase
image
image

**Review by imran1509 — COMMENTED** [review]
Looks great.

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by Vyvy-vi — APPROVED** [review]
LGTM!

**Pull request merged**
