### PR TITLE
[feat]: Added react-icons and removed primeicons 

### LINKED ISSUE #819: [FEATURE]: Integrate React-Icons with the project
### Description

There's been a long delay in the choice of icon package used, and this can be mitigated by choosing something like react-icons, which makes it easier to swap through different icon packs, without needing to change the supporting library used.

What does success look like?:
- [ ] Having react-icons included amongst the packages installed on running `npm install`
- [ ] Replacement of primereact icons (or integrating those with react-icons, if possible), wherever we're using them.
- [ ] Adding support for the social link types that don't have any icons at the moment.

### Screenshots

NA

### Additional information

This issue is related to #242 and #417

### PR DESCRIPTION
**Pull request by Rupesh-1302**
## Fixes Issue
closes #819 and #757

## Changes proposed

- [X] Having react-icons included amongst the packages installed on running `npm install`.
- [X] Replacement of primereact icons (or integrating those with react-icons, if possible), wherever we're using them.
- [X] Adding support for the social link types that don't have any icons at the moment.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/823"></a>

### CODE REVIEW

**Comment by nathgoutam93** [comment]
Looks good to me ! 

Dose milestones icons looks good without applying custom size/CSS styles?

**Comment by Rupesh-1302** [comment]
> Dose milestones icons looks good without applying custom size/CSS styles?
 
Milestone-example

I think it looks good
> Also you can add graduation hat icon which will close some other issues as well with this one PR, Imo

Added

**Review by emmalearnscode — APPROVED** [review]
Looks good to me!

**Review by krishguptadev — APPROVED** [review]

**Review by Vyvy-vi — APPROVED** [review]
Looks good to me. Thanks for contributing to LinkFree!

**Pull request merged**
