### PR TITLE
Create Mihir-Raj-Singh.json

### PR DESCRIPTION
**Pull request by Mihir-Raj-Singh**
- Created my profile and added links.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6425"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — APPROVED** [review]
Your filename must be exact same as your username. Please rename your file [here](https://github.com/Mihir-Raj-Singh/LinkFree/edit/Mihir-Raj-Singh-patch-1/data/MihirRajSingh.json) to `data/Mihir-Raj-Singh.json`.

Let us know if you need any help with this.

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Your filename must be exact same as your username. Please rename your file [here](https://github.com/Mihir-Raj-Singh/LinkFree/edit/Mihir-Raj-Singh-patch-1/data/MihirRajSingh.json) to `data/Mihir-Raj-Singh.json`.

Let us know if you need any help with this. :hammer_and_wrench:

**Comment by Mihir-Raj-Singh** [comment]
Thank you for pointing out. I really did miss that one.😄

**Review by accodes21 — APPROVED** [review]

**Review by Sindhuinti — APPROVED** [review]
👍🏻

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! 🎉 

<p align="center"><a href="https://linkfree.io/docs/how-to-guides/editing"></a></p>

**Pull request merged**
