### PR TITLE
[FEATURE] Move community resources to a page in the app #5489

### LINKED ISSUE #5489: [FEATURE] Move community resources to a page in the app
### Description

Currently we have this file https://github.com/EddieHubCommunity/LinkFree/blob/main/NOCODE-CHANGELOG.md for community resources but I think it doesn't get the attention it deserves. 

I think having a new page in the app and it would encourage more people to get involved

Steps
- create file `pages/contributors-changelog.mdx`
- move the contents of `/NOCODE-CHANGELOG.md` to the new file (delete the `md` file)
- include imports and exports from other `mdx` files, for example `pages/docs/faqs.mdx`

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aryan-bhokare**
## Fixes Issue 

Closes #5489

## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5637"></a>

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
Hey @aryan-bhokare change the issue number in the description to closes #5489

**Comment by aryan-bhokare** [comment]
> Hey @aryan-bhokare change the issue number in the description to closes #5489

Yes thanks

**Review by weilincheng — APPROVED** [review]
Great job on this contribution! I tested it on Gitpod and it's working perfectly.

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you 👍 

Please remove the changes to `package-lock.json` these are not required, please only commit changes you have made

**Comment by aryan-bhokare** [comment]
> Great job on this contribution! I tested it on Gitpod and it's working perfectly.

thanks You @weilincheng

**Comment by eddiejaoude** [comment]
Thank you @aryan-bhokare for the changes, but the `package-lock` file still has changes. I made a video on how to revert this which might help https://www.youtube.com/watch?v=YUHS5Ana7Jw

**Comment by aryan-bhokare** [comment]
@eddiejaoude  tried a lot to do what you said but the git is throwing me a lot of errors.

**Comment by eddiejaoude** [comment]
> @eddiejaoude tried a lot to do what you said but the git is throwing me a lot of errors.

ok no problem, I can take a look tomorrow.

**Pull request merged**
