### PR TITLE
Add prettier pre-commit hook

### PR DESCRIPTION
**Pull request by dan-mba**
## Changes proposed

Run prettier as a pre-commit hook for JSON files in the data directory.
This is useful because at some point GitHub made updating files on a PR from a fork using an action not work.
This was done for security reasons.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2325"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thanks Dan 👍 

But if I remember correctly, `lint-staged` would only work for staged files, and not everyone (including me) don't stage files

I think we would want to run on non-staged files also

**Comment by dan-mba** [comment]
> Thanks Dan 👍
> 
> But if I remember correctly, `lint-staged` would only work for staged files, and not everyone (including me) don't stage files
> 
> I think we would want to run on non-staged files also

I thought all commits had to go through staging.
This Git [documentation](https://git-scm.com/about/staging-area) seems to imply that.
Running `git commit -a` just combines the staging & commit into a single command.
The reason for using `lint-staged` is to only run prettier on changes files & not all files in the data directory.

**Comment by dan-mba** [comment]
I tested this by editing `eddiejaoude.json` to change the spacing.
The commit output is as follows
``` 
git commit -a -m "test hook"

> linkfree@1.12.0 lint
> next lint

info  - Loaded env from ...
./pages/search.js
37:6  Warning: React Hook useEffect has a missing dependency: 'username'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
✔ Preparing lint-staged...
✔ Running tasks for staged files...
✖ Prevented an empty git commit!
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

  ⚠ lint-staged prevented an empty git commit.
  Use the --allow-empty option to continue, or check your task configuration

husky - pre-commit hook exited with code 1 (error)
```

It looks like it reverted my changes & errored out because there are no changes left.

**Comment by eddiejaoude** [comment]
I don't stage, I specify my files on my commit and many do that also, for example...

```
git commit -m "..." <file1> ...
```

I think there is something similar where it doesn't have to be staged

**Comment by dan-mba** [comment]
> I don't stage, I specify my files on my commit and many do that also, for example...
> 
> ```
> git commit -m "..." <file1> ...
> ```
> 
> I think there is something similar where it doesn't have to be staged

I will run a test doing that & see what happens

**Comment by dan-mba** [comment]
Here are my results from the latest test of modifying the spacing on `data/eddiejaoude.json`


```
git commit -m "test hook" data/eddiejaoude.json

> linkfree@1.13.0 lint
> next lint

info  - Loaded env from /home/dburkhar/github/LinkFree/.env

./pages/search.js
36:6  Warning: React Hook useEffect has a missing dependency: 'username'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/user/UserTestimonials.js
34:15  Warning: Do not use `<img>` element. Use `<Image />` from `next/image` instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
✔ Preparing lint-staged...
✔ Running tasks for staged files...
✖ Prevented an empty git commit!
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

  ⚠ lint-staged prevented an empty git commit.
  Use the --allow-empty option to continue, or check your task configuration

husky - pre-commit hook exited with code 1 (error)
```

It looks like the files always go through staging regardless of how they are committed

**Comment by dan-mba** [comment]
I tried editing a file that isn't part of the prettier glob and got the following results

```
git commit -m "test hook" package.json

> linkfree@1.13.0 lint
> next lint

info  - Loaded env from /home/dburkhar/github/LinkFree/.env

./pages/search.js
36:6  Warning: React Hook useEffect has a missing dependency: 'username'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/user/UserTestimonials.js
34:15  Warning: Do not use `<img>` element. Use `<Image />` from `next/image` instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
→ No staged files match any configured task.
[prettier a4e6294] test hook
 1 file changed, 2 insertions(+), 1 deletion(-)
```

**Comment by eddiejaoude** [comment]
Oh thanks for testing 👍 interesting, maybe it works differently to the last time I used it

**Review by eddiejaoude — APPROVED** [review]
LGTM 👍  Thank you Dan!

**Pull request merged**
