### PR TITLE
data: PanthSolanki

### PR DESCRIPTION
**Pull request by panthsolanki**
## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6335"></a>

### CODE REVIEW

**Review by Krishnapro — APPROVED** [review]
LGTM 🚀 It can be merge!

**Review by Arindam200 — APPROVED** [review]

**Review by khushalarora — APPROVED** [review]
Thank you for contributing :tada:

**Review by harshsingh32 — APPROVED** [review]
LGTM

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
