### PR TITLE
Corrected a typo in bio

### PR DESCRIPTION
**Pull request by Chamberezigbo**
## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1670"></a>

### CODE REVIEW

**Review by Kunal0007 — APPROVED** [review]
LGTM 🎉

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thanks! 🎉

**Review by schmelto — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Chamberezigbo** [comment]
My profile is yet to be displayed

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contributions :tada:

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

**Pull request merged**
