### PR TITLE
fix: uneven icon size in `icons.md`

### LINKED ISSUE #1290: [DOCS] uneven Icon size in `icons.md`
### Description

- Uneven size of the supported icon in linkfree

### Screenshots

Screenshot from 2022-05-12 07-34-08

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
## Fixes Issue

Closes #1290

## Changes proposed

 Removed the hardcoded image height and width in percentage, the table can auto-adjust the image size.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

<details>
<summary>Before Fix</summary>

Screenshot from 2022-05-12 07-34-08

</details>

<details>
<summary>After Fix</summary>

Screenshot from 2022-05-12 07-40-56

</details>

## Note to reviewers

**one to two icons may appear small or not properly aligned due to low res (low px), need to update the image, someone will fix that in a PR, more green squares :)**
Thank you!! 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1291"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Looks Good! 

But the icon of **codeforces** and **snapchat** are unevenly small, It would be great if you fix them!

**Comment by Pradumnasaraf** [comment]
> Looks Good! 
> 
> But the icon of **codeforces** and **snapchat** are unevenly small, It would be great if you fix them! 
> 

As I mentioned above in **Note for reviewers**, I will leave that for a good first issue 🙂.
Thank you for your suggestion.

**Comment by kumarsonsoff3** [comment]
> As I mentioned above in **Note for reviewers**, I will leave that for a good first issue 🙂. Thank you for your suggestion.

Oh, Thanks for the clarification, I actually didn't notice that!

Good to Goo! 🚀

**Review by kumarsonsoff3 — APPROVED** [review]

**Review by schmelto — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by Panquesito7 — APPROVED** [review]

**Review by emmalearnscode — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
