### PR TITLE
Create PoulavBhowmick.json

### PR DESCRIPTION
**Pull request by PoulavBhowmick**
### I have added my personal details in this json file
I have added my personal details in the data section. 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6758"></a>

### CODE REVIEW

**Review by khushalarora — CHANGES_REQUESTED** [review]
Hey @PoulavBhowmick, thank you for contributing :tada: 
Please rename your file as with your GitHub username **`PoulavBhowmick`**
It will look like **`data/PoulavBhowmick.json`** :+1:

**Comment by PoulavBhowmick** [comment]
Done!

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
What khushal mean is to change your filename, not the title of the PR. 

You can change your [filename here](https://github.com/PoulavBhowmick/LinkFree/edit/main/data/Poulav03B.json) as suggested above. 

Let us know if you need any help with this! :)

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! 🎉 

<p align="center"><a href="https://linkfree.io/docs/how-to-guides/editing"></a></p>

**Pull request merged**
