### PR TITLE
alignment of headings

### LINKED ISSUE #3596: Heading not aligned properly on mobile on discover page.
### Description

In mobile view, the second heading(random profiles) is centered and has small text while as the heading below it are normally aligned left with bigger font size like they were aligned on the desktop. I think this creates some  
 alignment issue as the whole page is not looking consistent.

https://user-images.githubusercontent.com/92542124/213004999-73a9a30d-422d-4ff2-af80-5b8e14936dae.mov

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rohinish404**
Solves the issue #3596 i created
## Fixes Issue

fix #3596 

## Changes proposed

Aligned the text properly. Attaaching a ss below to show proposed changes.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.
Screenshot 2023-01-18 at 2 44 08 AM

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3597"></a>

### CODE REVIEW

**Review by Aadarsh805 — CHANGES_REQUESTED** [review]
removing the `justify-between` caused this on desktop [ignore, I ran the code in a branch with old code]

image

**Comment by rohinish404** [comment]
But its looking perfectly fine when i open this in gitpod
Screenshot 2023-01-18 at 3 38 11 AM

**Comment by Aadarsh805** [comment]
> removing the `justify-between` caused this on desktop
> 
> image

Oh wait, i ran in wrong branch ig

**Comment by Aadarsh805** [comment]
@rohinish404 Hey Rohinish, could you try the suggested changes

**Comment by rohinish404** [comment]
@Aadarsh805 which changes??

**Comment by Aadarsh805** [comment]
> @Aadarsh805 which changes??

The alignment error that is being caused by the margin bottom

**Comment by rohinish404** [comment]
You are talking about the different margin bottom under the random profiles and the popular profiles right??
Screenshot 2023-01-20 at 12 22 29 PM

**Comment by Aadarsh805** [comment]
> You are talking about the different margin bottom under the random profiles and the popular profiles right?? Screenshot 2023-01-20 at 12 22 29 PM

No I'm talking about the `mb-4` on H2 and not the icon, so because of one of them having the margin bottom they are not aligned

**Comment by rohinish404** [comment]
Done..how it's looking now??

**Review by Aadarsh805 — DISMISSED** [review]
All good now

**Comment by eddiejaoude** [comment]
Please add a before and after screenshot

**Comment by rohinish404** [comment]
Yeah sure!!
Here's how this was looking before-

https://user-images.githubusercontent.com/92542124/213846899-a4d97fb5-d0c2-4631-8f7e-40baf2e64c41.mov

And now it's looking-

https://user-images.githubusercontent.com/92542124/213846963-f279a16e-70d9-4ed4-b7d7-91fd40f694b1.mov

**Comment by Aadarsh805** [comment]
> 

add screenshot too, these video sometimes don't play, like rn one of them is not working on mine

**Comment by rohinish404** [comment]
sure!!
Before-
Screenshot 2023-01-21 at 5 27 12 PM
After-
Screenshot 2023-01-21 at 5 16 28 PM

**Comment by Avi-88** [comment]
Hi, just sharing my thought, wouldn't it look better if the headings are center aligned for smaller screens instead of how it looks currently  ?

**Comment by rohinish404** [comment]
@Avi-88 yeah but the headings below and above it are left aligned so it being cener aligned is disturbing the whole flow of the page.

**Comment by Avi-88** [comment]
I was talking about making all the headings center aligned for smaller screens , what do you think about this ?

**Comment by rohinish404** [comment]
Thats also a good idea..i was thinking the same before making this pr. @Aadarsh805 what do u think about this?

**Comment by Aadarsh805** [comment]
> Thats also a good idea..i was thinking the same before making this pr. @Aadarsh805 what do u think about this?

Yep it'd be better to have all center aligned actually

left aligned looks weird on mobile
image

**Comment by rohinish404** [comment]
Okay, should i make the changes?

**Comment by Aadarsh805** [comment]
> Okay, should i make the changes?

Yeah go ahead

**Comment by eddiejaoude** [comment]
Great collaboration everyone 👍  I think the improvements are a step in the right direction, the refresh icon doesn't need to go to it's own line when on mobile  👍

**Comment by Avi-88** [comment]
Glad i could, help good luck with the PR @rohinish404 :+1:

**Comment by rohinish404** [comment]
> Great collaboration everyone 👍 I think the improvements are a step in the right direction, the refresh icon doesn't need to go to it's own line when on mobile 👍

Then i think we should go with all the headings being left aligned or if we want all the heading to be centered and the refresh icon to stay in the same line..it's looking like this👇
Which one will look better??
Screenshot 2023-01-23 at 6 28 34 PM

**Comment by Aadarsh805** [comment]
> > Great collaboration everyone +1 I think the improvements are a step in the right direction, the refresh icon doesn't need to go to it's own line when on mobile +1
> 
> Then i think we should go with all the headings being left aligned or if we want all the heading to be centered and the refresh icon to stay in the same line..it's looking like thispoint_down Which one will look better?? Screenshot 2023-01-23 at 6 28 34 PM

Yeah this one's good

**Comment by rohinish404** [comment]
> Glad i could, help good luck with the PR @rohinish404 👍

Thank you for bringing a fresh perspective🙂

**Comment by rohinish404** [comment]
> > > Great collaboration everyone +1 I think the improvements are a step in the right direction, the refresh icon doesn't need to go to it's own line when on mobile +1
> > 
> > 
> > Then i think we should go with all the headings being left aligned or if we want all the heading to be centered and the refresh icon to stay in the same line..it's looking like thispoint_down Which one will look better?? Screenshot 2023-01-23 at 6 28 34 PM
> 
> Yeah this one's good

okay, i'll commit the changes.

**Comment by rohinish404** [comment]
How it's looking now??

**Comment by Aadarsh805** [comment]
> How it's looking now??

Looks great to me

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
