### PR TITLE
data: s4shantanu

### PR DESCRIPTION
**Pull request by s4shantanu**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3686"></a>

### CODE REVIEW

**Review by dan-mba — CHANGES_REQUESTED** [review]
To fix the JSON error, add a comma at the end of lines 6 & 22

**Review by s4shantanu — COMMENTED** [review]
Now check and approve my pull request

**Review by dan-mba — APPROVED** [review]
Looks good to me

**Comment by eddiejaoude** [comment]
Thanks @dan-mba 👍 

> Now check and approve my pull request

@s4shantanu your comment comes across as rude and aggressive, please be more polite to the maintainers who give a lot of their time to help the community.

**Comment by s4shantanu** [comment]
Thank you @dan-mba for the guidance and sorry I didn't mean to be rude. 
@eddiejaoude  thanks for the amazing community.
Looking forward to learning from and giving back to this fantastic community.

**Comment by eddiejaoude** [comment]
Thanks @s4shantanu 👍

**Pull request merged**
