### PR TITLE
data:PunitBathija

### PR DESCRIPTION
**Pull request by punitbathija**
## Changes proposed

Added My own LinkFree jsonObject file to the data folder

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4631"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by Saadat-B — APPROVED** [review]
Looks good 👍
Thank you for contributing! 🎉

**Review by himanshu1221 — APPROVED** [review]
LGTM :+1:

**Review by Hrishi5111998 — APPROVED** [review]

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks for your Contribution! 🎉

**Pull request merged**
