### PR TITLE
Add ThiagoTatico Page

### PR DESCRIPTION
**Pull request by ThiagoTatico**
Creating a JSON file for the ThiagoTatico Page

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1462"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🎉


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

**Review by kumarsonsoff3 — APPROVED** [review]
LGTM 👍 
Thank you for your contribution! 🚀🚀

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge!!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Reusable

**Review by emmalearnscode — APPROVED** [review]
Looks great 👍🏼

**Pull request merged**
