### PR TITLE
Update loftwah.json

### PR DESCRIPTION
**Pull request by loftwah**
## Changes proposed

Add some more tags

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Just added a couple more tags

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4242"></a>

### CODE REVIEW

**Review by accodes21 — APPROVED** [review]
Good to go

**Review by Ananya2001-an — APPROVED** [review]
Looks good

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by rupali-codes — APPROVED** [review]
awesome! lgtm

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good! 👍

**Pull request merged**
