### PR TITLE
Enhancement : Added Profile

### PR DESCRIPTION
**Pull request by RyanWalker277**
Hey @mantianers , 
I have added my profile to the project.Hoping the PR gets merged soon.Please review.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4094"></a>

### CODE REVIEW

**Comment by swagataroy30** [comment]
Hey, you need to change your file name to RyanWalker277.json, 'r' and 'w' needs to be in caps as per your github profile name.

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Your filename should be exact same as your `username.json`, else some of the features may not work for you! 

Please change it from `ryanwalker277.json`  - > `RyanWalker277.json`

**Comment by RyanWalker277** [comment]
@kumarsonsoff3 I have made the necessary changes. Kindly review

**Review by swagataroy30 — APPROVED** [review]
LGTM

**Comment by swagataroy30** [comment]
You can also add tags to improve your linkfree profile !

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good, Thanks! 🎉

**Pull request merged**
