### PR TITLE
data: kedar1998

### PR DESCRIPTION
**Pull request by kedar1998**
## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6570"></a>

### CODE REVIEW

**Comment by Aniket1026** [comment]
Thanks for contributing.
Please move your file to the data folder.

I would suggest you look at the QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

**Review by HassanTanveer — CHANGES_REQUESTED** [review]
Hey, Please move this file into the **data** folder. You can look at the [Quick Start guide](https://linkfree.io/docs/quickstart) to help you with this.

**Comment by kedar1998** [comment]
I have moved file to data folder

**Comment by Aniket1026** [comment]
Looks good 🎉

**Review by Aniket1026 — APPROVED** [review]

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks for your Contribution! 🎉 

<p align="center"><a href="https://linkfree.io/docs/how-to-guides/editing"></a></p>

**Pull request merged**
