### PR TITLE
deleted:data/AliMora83.json

### PR DESCRIPTION
**Pull request by sital002**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8059"></a>

### CODE REVIEW

**Comment by akkshitgupta** [comment]
Hey @sital002, it would be great and much easier for the reviewers of the repo to review your PR if could provide the proper description of your PR/work by editing the template given by the maintainers of the repo

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Hey @sital002, You're not allowed to delete someone else's profile data. Please provide a proper description about `Why you're making these changes??`, or we'll close this PR.

**Comment by SaraJaoude** [comment]
@kumarsonsoff3 I agree with you - as we cannot modify anyone else's PR I am going to close this immediately.

**Comment by sital002** [comment]
This issue was created by the AliMora83 that's why created a pr.Here is  the issue link https://github.com/EddieHubCommunity/LinkFree/issues/8054

**Comment by eddiejaoude** [comment]
Thank you @sital002 for trying to help @AliMora83 , but they should create their own PR to delete their profile json file if they have now switched to forms - it becomes too difficult to manage if people edit/delete other people's json files

**Comment by AliMora83** [comment]
PR sent here: #8081
My apologies for the hassle 🥳

**Pull request closed without merging**
