### PR TITLE
Centered mascot on 404 page

### LINKED ISSUE #8616: [BUG] Mascot image should be centered
### Description

When you visit the 404 page, or on 404.js you will see that the mascot image is left-aligned, whereas it should be centered for good looking. You can visit 404 page by going to any pages and adding random text to the URL.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tausiq2003**
## Fixes Issue 

fixes #8616 

## Changes proposed

- Centered the mascot using mx-auto using tailwind css

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8623"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
We use Tailwind, please have a look at their classes

**Comment by Shivamdwivedi1403** [comment]
Update Readme Section

**Comment by tausiq2003** [comment]
> We use Tailwind, please have a look at their classes

do you mean mx-auto, its used for centering(margin: auto) https://tailwindcss.com/docs/container#basic-usage

**Comment by tausiq2003** [comment]
> Update Readme Section

can you please clarify, wdym?

**Comment by eddiejaoude** [comment]
Sorry @tausiq2003 you are correct, it is part of Tailwind class already 👍

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by tausiq2003** [comment]
> Sorry @tausiq2003 you are correct, it is part of Tailwind class already +1

thanks eddie it was pleasure to contribute.

**Pull request merged**
