### PR TITLE
style: format files

### PR DESCRIPTION
**Pull request by Panquesito7**
## Changes proposed

- Format files/fix CI.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/899"></a>

### CODE REVIEW

**Review by shreyaansjain06 — APPROVED** [review]

**Review by krishguptadev — APPROVED** [review]
Looks good, but why would you want to merge a PR with failing CI 😅

**Review by Pradumnasaraf — APPROVED** [review]
LGTM

**Review by syedsohan — APPROVED** [review]

**Review by Vyvy-vi — APPROVED** [review]
looks good to me!

**Comment by emmalearnscode** [comment]
I think this has already been fixed by prettier.

**Pull request closed without merging**
