### PR TITLE
Create  Medhavi2025.json

### PR DESCRIPTION
**Pull request by Medhavi2025**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6525"></a>

### CODE REVIEW

**Review by khushalarora — CHANGES_REQUESTED** [review]
Hey @Medhavi2025, thank you for contributing :tada: 
Please move your file into the **`data/`** folder.
It will look like **`data/Medhavi2025.json`**

**Review by harshsingh32 — COMMENTED** [review]
thanks for contributing

**Review by TRohit20 — APPROVED** [review]

**Review by Arindam200 — APPROVED** [review]

**Comment by SaraJaoude** [comment]
@TRohit20 and @Arindam200 Thank you for taking the time to review this Pull Request.  However you approved it when the comment history shows that changes still need to be made so that it can be merged.  This causes confusion for the author and maintainers as well as unnecessary notifications - please consider this in future reviews.

**Comment by amandamartin-dev** [comment]
hello @Medhavi2025 it has been 2 weeks with no movement on this PR so I will close.  Please feel free to open a new PR when you are ready to add your profile.

**Pull request closed without merging**
