### PR TITLE
Delete Obito9596.json

### PR DESCRIPTION
**Pull request by YashkShrivas4491**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3899"></a>

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

You are deleting a profile. Can you please give us more details about the PR and why you are trying to delete it? because the username of the file doesn't match yours.

By seeing the name matching (file and yours), I am guessing this is your old profile and you have changed your username.

**Comment by YashkShrivas4491** [comment]
> Hey,
> 
> You are deleting a profile. Can you please give us more details about the PR and why you are trying to delete it? because the username of the file doesn't match yours.
> 
> By seeing the name matching (file and yours), I am guessing this is your old profile and you have changed your username.

Yes, that's why I m removing the old username and again I will make a new PR with the new username ok.

**Comment by Pradumnasaraf** [comment]
Okay. But the best way is just to rename the file the same as your username, and modify the link accordingly.

**Comment by YashkShrivas4491** [comment]
> Okay. But the best would be to rename the file the same as your username and modify the links accordingly.

Sure, can I close this PR and Start with a new one?

**Comment by YashkShrivas4491** [comment]
> Okay. But the best would be to rename the file the same as your username and modify the links accordingly.

i don't know why this message (merging blocking showing instead of showing  issue is resolved).

**Comment by Pradumnasaraf** [comment]
> > Okay. But the best would be to rename the file the same as your username and modify the links accordingly.
> 
> Sure, can I close this PR and Start with a new one?

Yes sure

**Pull request closed without merging**
