### PR TITLE
data:HaroonHayat

### PR DESCRIPTION
**Pull request by hayatharoon**

### CODE REVIEW

**Review by Sindhuinti — APPROVED** [review]
Looks good 🎉

**Review by sidharthviz — APPROVED** [review]
LGTM 👍🏼

**Comment by hayatharoon** [comment]
Thank you for approving

**Review by himanshu1221 — APPROVED** [review]
LGTM :+1:

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Welcome to LinkFree! 🎉

**Comment by hayatharoon** [comment]
Thank you for mereged my PR.

**Pull request merged**
