### PR TITLE
feat: add scroll to top button in footer of the page

### PR DESCRIPTION
**Pull request by bharat5604**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2774"></a>

### CODE REVIEW

**Review by ManishBisht777 — COMMENTED** [review]
You can remove `package.json` and `package.lock.json`

**Comment by bharat5604** [comment]
> You can remove `package.lock.json`

I have removed package.lock.json

**Comment by eddiejaoude** [comment]
Please do not remove `package-lock.json` file, this file is needed. 

1. as you have made changes to `package.json` please also keep your changes to the lock file
2. please add a screenshot to your pull request 
3. please add the issue number to your pull request

**Comment by ManishBisht777** [comment]
> Please do not remove `package-lock.json` file, this file is needed.
> 
> 1. as you have made changes to `package.json` please also keep your changes to the lock file
> 2. please add a screenshot to your pull request
> 3. please add the issue number to your pull request

sorry my bad I thought only `package.json` is required

**Comment by eddiejaoude** [comment]
> sorry my bad I thought only package.json is required

no problem - if there are no changes to the `package.json` usually there should be no changes the lock file (unless specifically updating the dependencies)

**Comment by bharat5604** [comment]
Hi eddie i have added package.lock.json file again,
issue not is #2670

**Comment by eddiejaoude** [comment]
Please can you add the issue number to the PR description and also include a screenshot

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
I'm curious to know why you would use a package for this instead of creating an inbuilt component?

The button works fine but the CSS needs tweaking a little. The arrow needs to be centered and the button should have some space around it so it doesn't sit right on top of the help button.

**Comment by eddiejaoude** [comment]
Thank you for your contribution.

This pull request has many conflicts as it is getting out of date.

Please raise an issue first to discuss changes before making a pull request.

To make contributions, have a look at opened issues that are no assigned yet.

**Comment by ManashAnand** [comment]
Hey I would like to work on this issue without using a package and 
I will try to make design looks good.

It's my first issue in this project .
Please let me handle it .
Thanks for your time

**Comment by eddiejaoude** [comment]
Thank you @ManashAnand but this is not an issue and there was no issue for this pull request, that is what caused the confusion. Please have a look at the opened issues that are not assigned, you can learn more in our contribute guide https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by ManashAnand** [comment]
Okay , I will make sure to read the guide carefully

**Pull request closed without merging**
