### PR TITLE
Updated the Screenshots for the Quickstart guide.

### PR DESCRIPTION
**Pull request by MAYANKpandey14**
## Fixes Issue
Update screenshots on /docs/quickstart https://github.com/EddieHubCommunity/LinkFree/issues/4999

## Changes proposed
Added new Screenshots for the Quickstart guide.
Removed the old screenshots.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Screenshot 2023-03-10 at 12 56 00 AM

Screenshot 2023-03-10 at 1 02 21 AM

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5325"></a>

### CODE REVIEW

**Comment by MAYANKpandey14** [comment]
This is the for the issue mentioned as Update screenshots on /docs/quickstart #4999

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please create a separate PR for your profile addition.
Let us know if you need any help with that. Thanks. 🙂

**Comment by MAYANKpandey14** [comment]
> Please create a separate PR for your profile addition. Let us know if you need any help with that. Thanks. 🙂

Sorry for this I do not know why my profile addition also got attached to this . 
what do you think would have been the reason. How to Undo do this

**Comment by MAYANKpandey14** [comment]
I have created a separate pull request for the profile. Can you check if that is okay

**Pull request closed without merging**
