### PR TITLE
added jaya data

### PR DESCRIPTION
**Pull request by eddejayaklu**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1357"></a>

### CODE REVIEW

**Review by emmalearnscode — APPROVED** [review]
Looks good. Great that you managed to sort the package-lock issues 👍 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by kabir0x23 — APPROVED** [review]
Code looks great.🌠

**Review by kumarsonsoff3 — APPROVED** [review]

**Comment by eddejayaklu** [comment]
> Looks good. Great that you managed to sort the package-lock issues 👍
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 👌 This code looks good

Thank you. This is my First PR.

**Comment by eddejayaklu** [comment]
> Looks good. Great that you managed to sort the package-lock issues 👍
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 👌 This code looks good

Thanks!

**Review by Panquesito7 — APPROVED** [review]

**Pull request merged**
