### PR TITLE
fix headline to use less characters

### PR DESCRIPTION
**Pull request by loftwah**
## Changes proposed

Updating my bio to use less characters. This is because I've got my account into the popular profiles page and I've used too many characters for the card, making it look a bit odd.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

Just updating my bio.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2287"></a>

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey, 

Please revert cahnges from `CHANGELOG.md`, `package-lock.json`, and `package.json`, otherwise looks good.

If you need any help feel free to ping.

**Comment by loftwah** [comment]
Thanks for that, I just noticed the GitHub Action is putting those other changes there, and when I reverted my change, it also reverted the change again. I've turned them off at my end and will sort it out in the morning.

Cheers.

**Comment by Panquesito7** [comment]
Seems that your original changes are gone now. 👀

**Comment by dan-mba** [comment]
Making changes on a `main` branch of a fork is a bad idea.
This can cause actions to run even when they shouldn't.

**Comment by loftwah** [comment]
> Making changes on a `main` branch of a fork is a bad idea. This can cause actions to run even when they shouldn't.

I am guilty of not learning Git properly 😂 I've always just made changes directly in the main/master branches. TIL.

**Pull request closed without merging**
