### PR TITLE
UI fix in playground

### PR DESCRIPTION
**Pull request by Samit-prsl**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5507"></a>

### CODE REVIEW

**Comment by amandamartin-dev** [comment]
@Samit-prsl Hey! Thank you for contributing, but to help out the maintainers can you please fill out the pull request form at the top to connect this PR with the issue.

This will help us assess the fix and will also allow the open issue to be closed automatically once the code has been merged.

If you need any help with this, please let us know!

**Comment by Samit-prsl** [comment]
> @Samit-prsl Hey! Thank you for contributing, but to help out the maintainers can you please fill out the pull request form at the top to connect this PR with the issue.
> 
> This will help us assess the fix and will also allow the open issue to be closed automatically once the code has been merged.
> 
> If you need any help with this, please let us know!

*Yes , I had filled in the form , do give it a check*

**Comment by amandamartin-dev** [comment]
> _Yes , I had filled in the form , do give it a check_

Sorry, perhaps I wasn't clear.  For the linkfree repository, to have a PR considered you must first open an issue and it will go through triage.

Next, once the issue is approved and ready for dev you can submit the PR

in the issue form above, you will want to link the open issue that the PR is for. "closes #issueNumber"

**Comment by eddiejaoude** [comment]
@Samit-prsl what issue is this pull request related to?

**Comment by Samit-prsl** [comment]
> @Samit-prsl what issue is this pull request related to?

I worked on according to an issue , regarding the "clarity in the events page".

**Comment by Samit-prsl** [comment]
> > @Samit-prsl what issue is this pull request related to?
> 
> I worked  according to an issue , regarding the "clarity in the events page".

**Comment by eddiejaoude** [comment]
What is the issue number or url please?

**Comment by eddiejaoude** [comment]
Is it this issue? https://github.com/EddieHubCommunity/LinkFree/issues/5337

**Comment by eddiejaoude** [comment]
Thank you for your contribution but it looks like this is related to issue #5337 that was already assigned to someone else and their pull request was merged here https://github.com/EddieHubCommunity/LinkFree/pull/5554

Therefore unfortunately these changes are not required, please read our contributing guidelines so you don't duplicate efforts https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

Any questions let us know.

**Comment by Samit-prsl** [comment]
> Is it this issue? https://github.com/EddieHubCommunity/LinkFree/issues/5337

Yes yes

**Comment by Samit-prsl** [comment]
> Thank you for your contribution but it looks like this is related to issue #5337 that was already assigned to someone else and their pull request was merged here https://github.com/EddieHubCommunity/LinkFree/pull/5554
> 
> Therefore unfortunately these changes are not required, please read our contributing guidelines so you don't duplicate efforts https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md
> 
> Here are a list of issue not assigned to someone else https://github.com/EddieHubCommunity/LinkFree/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee
> 
> Any questions let us know.

Thank you ! I will definitely look forward to contribute in these issues 🙂

**Pull request closed without merging**
