### PR TITLE
FIX: Infinite map scroll

### PR DESCRIPTION
**Pull request by sanskar1306**
## Fixes Issue
#5108 

## Changes proposed

Infinite map scrolling fixed using maxBounds .

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot 2023-03-19 001846

## Note to reviewers

@amandamartin-dev  fixed the issue you can review on your side.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5545"></a>

### CODE REVIEW

**Review by amandamartin-dev — APPROVED** [review]
This is great! Thank you for your contribution.  Will require a second maintainer before we merge it.

**Comment by eddiejaoude** [comment]
Great collaboration everyone! 👍

**Comment by sanskar1306** [comment]
Hi, @amandamartin-dev can you review it again? There was a conflict I resolved it.

**Review by amandamartin-dev — APPROVED** [review]
lgtm!

**Pull request merged**
