### PR TITLE
Add responsiveness on quickstart-json page

### LINKED ISSUE #7918: [BUG] Quickstart-json page is not responsive
### Description

Hey, https://linkfree.io/docs/quickstart-json this page is not properly responsive. You can check below

### Screenshots

image
image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SubhamB2003**
## Fixes Issue
fixes #7918 

## Changes proposed
image
image

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8160"></a>

### CODE REVIEW

**Review by amandamartin-dev — COMMENTED** [review]
Something weird I noticed while testing this...

I am curious how this was originally triaged, bc from a phone I am not able to get to the page in question at all.

However, when testing from a browser if I click on this page first and then emulate a phone, I am able to check it.  So I think a subsequent issue needs to be opened that the mobile and web docs experience do not allow access to the same pages. cc @eddiejaoude 

The CSS change does appear to work, however, it won't be able to be tested from a phone in production to verify after deployment unless somehting is acting weird on my end

**Review by amandamartin-dev — CHANGES_REQUESTED** [review]
Please remove the package-lock file from this PR, it is not needed. Otherwise, testing in Gitpod this behaved as expected. Thank you for contributing

**Comment by SubhamB2003** [comment]
> Please remove the package-lock file from this PR, it is not needed. Otherwise, testing in Gitpod this behaved as expected. Thank you for contributing

Done. 
Happy to be a part of this community.

**Comment by eddiejaoude** [comment]
@amandamartin-dev good spot, yes the side nav needs an issue to change it to a dropdown for mobile, otherwise we can't reach the page - I was meant to raise it and forgot 🤦‍♂️ 

Great collaboration 💪

**Comment by eddiejaoude** [comment]
@Shubham185y the `package-lock.json` file should not be deleted, your changes to the file are not needed as part of your PR, please undo your changes to this file.

I made a video on how you can fix the lock file https://www.youtube.com/watch?v=jHkIXYVpMTo

**Comment by eddiejaoude** [comment]
@SubhamB2003 did you mean to close the PR?

**Comment by SubhamB2003** [comment]
> @SubhamB2003 did you mean to close the PR?

No sorry.

**Review by amandamartin-dev — DISMISSED** [review]
Looks good! Thanks for removing the lock file changes from the PR. Sorry for confusing you about deleting it versus removing the changes from the PR.  THanks for your contributions!

**Comment by SubhamB2003** [comment]
> Looks good! Thanks for removing the lock file changes from the PR. Sorry for confusing you about deleting it versus removing the changes from the PR. THanks for your contributions!

Yeah, It's alright.

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
We should not use fixed widths otherwise it does this jumping around with big gaps...

Screenshot 2023-07-18 at 14 56 25

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
