### PR TITLE
Improvement : Added maxwidth property to link bar

### LINKED ISSUE #208: [ Improvement ] Adding Max-width to Links Bar
When we see the links of profile in full screen the width don't look good. We can add a property max width so the width will not go beyond that and will be responsive also 

image

I will like to fix it

### PR DESCRIPTION
**Pull request by rohan-kulkarni-25**
Fixes #208 

## Proposed Changes

  -Added Property Max width so the link bar don't get expanded more.
  -
  -

## Screenshots
| BEFORE | AFTER | 
| :-: | :-: | 
| image | image | 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/209"></a>

### CODE REVIEW

**Comment by schmelto** [comment]
could you also provide a screenhot on how it look on mobile view

**Comment by rohan-kulkarni-25** [comment]
> could you also provide a screenhot on how it look on mobile view

Sure !! But it will not affect the mobile view as the width of mobile is already less than max width

**Comment by rohan-kulkarni-25** [comment]
image

**Comment by amittri1025** [comment]
hello @rohan-kulkarni-25 , mate your PR is not merged, right ?, but why , I am asking this because I want to contribute to issue #238

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts [**here**](https://github.com/EddieHubCommunity/LinkFree/pull/209/conflicts).

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍 I resolved merge conflicts

**Pull request merged**
