### PR TITLE
[chore]: added leetcode icon 

### PR DESCRIPTION
**Pull request by kartikgajjar7**
added leetcode icon as per order

### CODE REVIEW

**Review by kumarsonsoff3 — COMMENTED** [review]
## Note to Reviewers 
Since Kartik was getting difficulties in adding the icon to linkfree, he reached me for help. Hence the commits are mine, which I've created to his fork for explaining purposes! :)

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

**Comment by jaynarayan-vaishnav** [comment]
@kumarsonsoff3  just wanted to ask this was changing the spaces between the words really necessary? I think they are mostly the same as before. correct me if I am wrong

**Comment by kumarsonsoff3** [comment]
> @kumarsonsoff3 just wanted to ask this was changing the spaces between the words really necessary? I think they are mostly the same as before. correct me if I am wrong

@jaynarayan-vaishnav, If I'm getting you correct, you mean with the _spaces in the markdown of the table_ in `icon.md` file!?
They are just for **formatting purposes**, I mean they have nothing to do with the output of the markdown!

**Comment by jaynarayan-vaishnav** [comment]
Okay thanks for explaining @kumarsonsoff3

**Review by jaynarayan-vaishnav — COMMENTED** [review]
LGTM🚀
Keep up the good work.

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
The markdown table is breaking up somewhere. Please check the syntax.

If you need any help do let us know!

#### Screenshot
Screenshot from 2022-08-08 11-56-23

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by kartikgajjar7** [comment]
> The markdown table is breaking up somewhere. Please check the syntax.
> 
> If you need any help do let us know!
> 
> #### Screenshot
> Screenshot from 2022-08-08 11-56-23
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

cant find where is problem in syntax can you tell me where is need to change

**Review by Pradumnasaraf — APPROVED** [review]
Now it looks good. Might be a bug. 

Maintaniees note: 
The color of the logo is not black
CC @EmmaDawsonDev 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by EmmaDawsonDev — APPROVED** [review]
This looks fine to me 👍

**Pull request merged**
