### PR TITLE
Made profile names visible

### PR DESCRIPTION
**Pull request by Shivam-Katare**
## Fixes Issue 
#1928 

The text is now visible on hovering over the profiles.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.

## Screenshots

# Previous

Screenshot (91)
Screenshot (95)

# Now

Screenshot (92)
Screenshot (93)

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1936"></a>

### CODE REVIEW

**Review by schmelto — CHANGES_REQUESTED** [review]
Please do not delete the package-lock json

**Comment by Shivam-Katare** [comment]
> Please do not delete the package-lock json

Hey @schmelto I retrieved the package-lock.json file. You can review it now.

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Still it's showing changes in the `package-lock.json` file, You can follow this **[short guide ](https://gist.github.com/kumarsonsoff3/fbc6ecde519250a9f0a4d7ccc9993a1a)** if you're facing some issues in reverting the changes! 

Let us know if you need any help with this! :)
image

**Comment by Shivam-Katare** [comment]
> Still it's showing changes in the `package-lock.json` file, You can follow this **[short guide ](https://gist.github.com/kumarsonsoff3/fbc6ecde519250a9f0a4d7ccc9993a1a)** if you're facing some issues in reverting the changes!
> 
> Let us know if you need any help with this! :) image

Okay. I'll let you know if I face any issues.

**Pull request closed without merging**
