### PR TITLE
Closes Issue #7148 -- Changed parent div tag to header tag

### LINKED ISSUE #7148: Layout needs a html header
### Description

In the navbar component change the parent `div` to `header`

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sabrinalzbh**
## Fixes Issue
Closes #7148 

## Check List (Check all the applicable boxes) 

- [X ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X ] This PR does not contain plagiarized content.
- [X ] The title of my pull request is a short description of the requested changes.

## Screenshots
div-header-change-open-tag

div-header-change-close-tab

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7155"></a>

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Great job @sabrinalzbh! 😄 LGTM! 😄

**Comment by sabrinalzbh** [comment]
> Great job @sabrinalzbh! 😄 LGTM! 😄

Super! Love seeing your comments. Haha 😆

**Review by ChinmayMhatre — APPROVED** [review]

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by sabrinalzbh** [comment]
Sweet! ☺️

**Pull request merged**
