### PR TITLE
Profile update ( Twitter & Github)

### PR DESCRIPTION
**Pull request by abhaytaras7**
Changed my twitter && github profiles

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2158"></a>

### CODE REVIEW

**Review by accodes21 — COMMENTED** [review]
Looks good.

**Review by Panquesito7 — COMMENTED** [review]
You might want to update line 5 as well.

**Review by abhaytaras7 — COMMENTED** [review]
Updated ! ! line 5

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
