### PR TITLE
data: dev-rakeshshaw

### PR DESCRIPTION
**Pull request by dev-rakeshshaw**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4951"></a>

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
LGTM 🎉

**Comment by dev-rakeshshaw** [comment]
> LGTM 🎉

thanks

**Review by sansarmaske — APPROVED** [review]

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Welcome to LinkFree 🎉

**Comment by dev-rakeshshaw** [comment]
> Looks good to merge. Welcome to LinkFree 🎉

Thanks, Bro...For Merging.

**Pull request merged**
