### PR TITLE
Capitalize file name for contributing guidelines

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
## Fixes Issue
- In most repos the contributing guidelines file is usually capital like CONTRIBUTING.md, so I think it's better to to capitalize the file name.

## Changes proposed
- Update file name.

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1071"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
@KendallDoesCoding According to docs, the dir name should in full caps, and file in lower caps, yes it will work, but it's always good to keep as according to official docs. :D
Thanks for your contribution

Screenshot from 2022-02-06 22-40-52


**you can also check docs for [`that`](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)**

**Review by Pradumnasaraf — COMMENTED** [review]
Again @KendallDoesCoding Thank you for your contribution and valuable time,
@Panquesito7 we can close this PR :)

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding According to docs, the dir name should in full caps, and file in lower caps, yes it will work, but it's always good to keep as according to official docs. :D Thanks for your contribution
> 
> Screenshot from 2022-02-06 22-44-34
> 
> **you can also check docs for [`that`](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)**

In community standards, if you go and you don't have any guidelines and you tap add, it automatically names the file "CONTRIBUTING.md", and that's the way the file is in all repos, for the PR template, all repos have it in lowercase, which looks nice, but for README and CONTRIBUTING.md guidelines, it should be caps, according to me.

**Comment by Pradumnasaraf** [comment]
> > @KendallDoesCoding According to docs, the dir name should in full caps, and file in lower caps, yes it will work, but it's always good to keep as according to official docs. :D Thanks for your contribution
> > Screenshot from 2022-02-06 22-44-34
> > **you can also check docs for [`that`](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)**
> 
> In community standards, if you go and you don't have any guidelines and you tap add, it automatically names the file "CONTRIBUTING.md", and that's the way the file is in all repos, for the PR template, all repos have it in lowercase, which looks nice, but for README and CONTRIBUTING.md guidelines, it should be caps, according to me.

Thank you for your suggestion, but it will be good if we follow [`docs`](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**Comment by KendallDoesCoding** [comment]
> > > @KendallDoesCoding According to docs, the dir name should in full caps, and file in lower caps, yes it will work, but it's always good to keep as according to official docs. :D Thanks for your contribution
> > > Screenshot from 2022-02-06 22-44-34
> > > **you can also check docs for [`that`](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)**
> > 
> > 
> > In community standards, if you go and you don't have any guidelines and you tap add, it automatically names the file "CONTRIBUTING.md", and that's the way the file is in all repos, for the PR template, all repos have it in lowercase, which looks nice, but for README and CONTRIBUTING.md guidelines, it should be caps, according to me.
> 
> Thank you for your suggestion, but it will be good if we follow [`docs`](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

@Pradumnasaraf Yes, it will but the docs only talks about PR template, Github themselves mean for it to be CONTRIBUTING.MD as you I stated, will share a screen recording of the same shortly, I dont think PR template works if its upper case but Github themselves formats the guidelines as uppercase, Sorry for being harsh.

**Comment by Pradumnasaraf** [comment]
Hey @KendallDoesCoding, my bad i thought you were changing the PR template name, please delete above quote messges

**Comment by KendallDoesCoding** [comment]
> > > > @KendallDoesCoding According to docs, the dir name should in full caps, and file in lower caps, yes it will work, but it's always good to keep as according to official docs. :D Thanks for your contribution
> > > > Screenshot from 2022-02-06 22-44-34
> > > > **you can also check docs for [`that`](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)**
> > > 
> > > 
> > > In community standards, if you go and you don't have any guidelines and you tap add, it automatically names the file "CONTRIBUTING.md", and that's the way the file is in all repos, for the PR template, all repos have it in lowercase, which looks nice, but for README and CONTRIBUTING.md guidelines, it should be caps, according to me.
> > 
> > 
> > Thank you for your suggestion, but it will be good if we follow [`docs`](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
> 
> @Pradumnasaraf Yes, it will but the docs only talks about PR template, Github themselves mean for it to be CONTRIBUTING.MD as you I stated, will share a screen recording of the same shortly, I dont think PR template works if its upper case but Github themselves formats the guidelines as uppercase, Sorry for being harsh.

https://kapwi.ng/w/w1Oaf7z4w4

Github auto-setting it as caps for CONTRIBUTING.MD, for PR template, it's required to be lower-case as in the docs.

**Review by Pradumnasaraf — APPROVED** [review]

**Comment by Pradumnasaraf** [comment]
Hey @KendallDoesCoding, my bad I thought you were changing the PR template name, please delete the all the above quote messages, if possible

**Comment by KendallDoesCoding** [comment]
> Hey @KendallDoesCoding, my bad I thought you were changing the PR template name, please delete the above quote messages, if possible

No problem, I can delete my comments but not yours, so ig it's ok to leave them for now. Sorry again for being harsh, I just thought it was weird coz github themselves format it like that and your saying the docs says it shouldn't be like that LOL

**Comment by Pradumnasaraf** [comment]
> > Hey @KendallDoesCoding, my bad I thought you were changing the PR template name, please delete the above quote messages, if possible
> 
> No problem, I can delete my comments but not yours, so ig it's ok to leave them for now. Sorry again for being harsh, I just thought it was weird coz github themselves format it like that and your saying the docs says it shouldn't be like that LOL

you can delete the quote reply, this one also

**Comment by KendallDoesCoding** [comment]
> > > Hey @KendallDoesCoding, my bad I thought you were changing the PR template name, please delete the above quote messages, if possible
> > 
> > 
> > No problem, I can delete my comments but not yours, so ig it's ok to leave them for now. Sorry again for being harsh, I just thought it was weird coz github themselves format it like that and your saying the docs says it shouldn't be like that LOL
> 
> you can delete the quote reply, this one also

I can't delete your comments.

**Comment by KendallDoesCoding** [comment]
@Pradumnasaraf Also btw, the PR template is in uppercase too lol, will make it lowercase as the docs say, in a new PR

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf Also btw, the PR template is in uppercase too lol, will make it lowercase as the docs say, in a new PR

Great, Again sorry for miss understanding.

**Comment by KendallDoesCoding** [comment]
> > @Pradumnasaraf Also btw, the PR template is in uppercase too lol, will make it lowercase as the docs say, in a new PR
> 
> Great, Again sorry for miss understanding.

No problem :)

**Review by schmelto — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
@Panquesito7 Thanks for merging, but I realized a glitch, will make a PR shortly.

**Pull request merged**
