### PR TITLE
Fixed mobile view margin issue

### LINKED ISSUE #2466: Spacing in profile submenu
### Description

We can add a margin top and bottom of the submenu to prevent them from sticking to the QR code and the section below it

image

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yrs147**
## Fixes Issue
Closes #2466 and  #2468 issue 

## Changes proposed

Removed the sm breakpoint for the margin 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Before 
bef

After 
after

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2489"></a>

### CODE REVIEW

**Review by Aadarsh805 — APPROVED** [review]
this works great

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for the contribution and improvement 👍 

Please can you remove the changes to the lock file as these are not required and then we can get this merged

**Comment by yrs147** [comment]
@eddiejaoude should I raise a new PR for the changes?

**Comment by eddiejaoude** [comment]
If that is easier for you, then yes go for it 👍 

If you raise a new PR, please close this one and also check you only commit changes you made

**Comment by yrs147** [comment]
> If that is easier for you, then yes go for it 👍
> 
> If you raise a new PR, please close this one and also check you only commit changes you made

Sure I'll close this one and raise a new one

**Pull request closed without merging**
