### PR TITLE
Create bello-olalekan.json

### PR DESCRIPTION
**Pull request by bello-olalekan**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3133"></a>

### CODE REVIEW

**Review by Aadarsh805 — CHANGES_REQUESTED** [review]
Hey @bello-olalekan this file needs to be inside the `data` directory, you can just change it's name to `data/dbello-olalekan.json` and it'll work

**Review by dan-mba — CHANGES_REQUESTED** [review]
Please move your profile to the data directory

**Review by dan-mba — APPROVED** [review]
Looks good to me

**Comment by bello-olalekan** [comment]
Thanks dan-mba

**Comment by bello-olalekan** [comment]
@dan-mba please is there any other thing I need to do?

**Comment by dan-mba** [comment]
> @dan-mba please is there any other thing I need to do?

No, this PR looks good and should be merged sometime today.

**Pull request merged**
