### PR TITLE
data: StarKnightt

### PR DESCRIPTION
**Pull request by StarKnightt**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5892"></a>

### CODE REVIEW

**Review by khushalarora — APPROVED** [review]
Looks good, thanks :tada:

**Comment by StarKnightt** [comment]
> Looks good, thanks 🎉
I have added tags, but where are my tags?
image

**Comment by kumarsonsoff3** [comment]
Hey StarKnightt, don't worry, your tags will be shown once this PR is merged and deployed.

**Review by kumarsonsoff3 — APPROVED** [review]

**Comment by StarKnightt** [comment]
> Hey StarKnightt, don't worry, your tags will be shown once this PR is merged and deployed. 

Thank you

**Pull request merged**
