### PR TITLE
data: AshishThakur

### PR DESCRIPTION
**Pull request by ashishMECHA**

### CODE REVIEW

**Comment by chetannada** [comment]
> _ No description provided. _

The name of your json file needs to match your GitHub username exactly (it is different). So instead of `data/AshishThakur.json` please change this to `data/ashishMECHA.json`

**Review by Krishnapro — COMMENTED** [review]
LGTM except file name changes it to your GitHub username.

**Comment by ashishMECHA** [comment]
> > _ No description provided. _
> 
> The name of your json file needs to match your GitHub username exactly (it is different). So instead of `data/AshishThakur.json` please change this to `data/ashishMECHA.json`

Okay, I'll change it

**Review by imbeshat — APPROVED** [review]

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
