### PR TITLE
data:tobySolutions

### PR DESCRIPTION
**Pull request by tobySolutions**
## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers
Add tobySolutions' profile 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2509"></a>

### CODE REVIEW

**Comment by tobySolutions** [comment]
Please review @Panquesito7, @krshkun, @eddiejaoude!! :smile: :smile:

**Review by Aadarsh805 — APPROVED** [review]
it's all good 👍

**Comment by tobySolutions** [comment]
> it's all good 👍

Thanks @Aadarsh805!!

**Comment by tobySolutions** [comment]
Is someone going to merge this?

**Comment by Aadarsh805** [comment]
> Is someone going to merge this?

It'll be merged don't worry

**Comment by tobySolutions** [comment]
> > Is someone going to merge this?
> 
> It'll be merged don't worry

Thanks Aadarsh!!

**Comment by eddiejaoude** [comment]
@tobySolutions please be patient and give the maintainers more than a few minutes to go through our notifications, we all live in different timezones and have other responsibilities. 

Please note, we get the notifications of the pull request and we work through these in order, tagging us creates more notifications and does not help but actually gives us more work to do, making us slower. 

Of course we sometimes do miss notifications and if a few days pass then by all means please tag us.

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
