### PR TITLE
🎨 Write better code using async await

### PR DESCRIPTION
**Pull request by max-programming**

### CODE REVIEW

**Comment by krishguptadev** [comment]
## Congratulations

Congratulations on making your first pull request to our project. I think your changes are perfect 🚀 Good Work

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.

**Comment by eddiejaoude** [comment]
`async` is beter to read, but from the official docs they recommend this style. We should stick to the official docs so that people can understand the code https://reactjs.org/docs/faq-ajax.html

**Comment by max-programming** [comment]
Your point is valid too @eddiejaoude. But I think many people know the latest syntax.

If they don't understand it, and they want to contribute, it'll be a challenge for them to learn it and that will increase their knowledge.

I leave the decision to you 🙂.

**Comment by eddiejaoude** [comment]
Let's stick to the official docs for now, thank you though 👍

**Pull request closed without merging**
