### PR TITLE
Krishna profile update

### PR DESCRIPTION
**Pull request by Krishnapro**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3750"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please revert the changes in the other files and keep your profile changes only.
To prevent this, you might have to update your branch with the latest upstream.

If you need any help with this, let us know! 🙂

**Comment by Krishnapro** [comment]
Hey, @Panquesito7 I am using `git checkout main --package-lock.json` in my current branch but it's not working. why it's not working?

**Review by Krishnapro — COMMENTED** [review]
I think now conflict will resolve, please let me know

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good, Should be good to go! 🎉

**Comment by Krishnapro** [comment]
@kumarsonsoff3 thank you!

**Pull request merged**
