### PR TITLE
change buttons to links #1016

### LINKED ISSUE #1016: [FEATURE] Change buttons to links
### Description

I have experience with SEO and buttons are bad for

* UX
* Accessibility
* SEO

If something is a link to another website it should be a real link, not a button.

Also, real links (without `rel="nofollow"`) can really help Open Source projects. If someone will create a profile with links to his project's official websites.

I'm not sure how much in this community are actual FOSS authors and maintainers.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jcubic**
It's better for SEO, UX, and Accessibility

## Fixes Issue
Closes #1016

## Changes proposed
Repaced button with links

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1025"></a>

### CODE REVIEW

**Comment by jcubic** [comment]
I was not able to run cypress tests locally, I hope they will run in CI.

**Comment by emmalearnscode** [comment]
The tests in integration/user.feature are failing because they are looking for content inside button elements which are now links. Are you able to update the tests to get them passing?

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
I'm not sure button is the correct name to use for the component since we may then run into problems later where we actually want a button and not a link but someone adds this component thinking that it is a button. I think something along the lines of StyledLink may be more descriptive.

**Comment by jcubic** [comment]
Yes, I will update tests.

**Comment by jcubic** [comment]
What kind of tests are failing now? They pass locally.

**Review by emmalearnscode — APPROVED** [review]
Looks good to me!

**Review by krshdev — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]

**Pull request merged**
