### PR TITLE
data: aarkaynegi

### PR DESCRIPTION
**Pull request by aarkaynegi**

### CODE REVIEW

**Review by imbeshat — APPROVED** [review]
LGTM

**Review by bkpecho — APPROVED** [review]
Good luck on your open-source journey! 🎉 Have a great day ahead.

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Review by mahfuztbt — APPROVED** [review]

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good & Good luck for your upcoming opportunities. 🎉 

<p align="center"></p>

**Pull request merged**
