### PR TITLE
Create RohitGhumare.json

### PR DESCRIPTION
**Pull request by rohitg00**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=_EsdzyY)
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=_qy5521)

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4446"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Your new file must be in the `data` directory, not in the root.
Please update accordingly. If you need any help, let us know. 🙂

**Comment by rohitg00** [comment]
@Panquesito7 Please check now

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Your filename must match your GitHub username.
In this case, it should be `rohitg00`.

**Review by Panquesito7 — DISMISSED** [review]
Thanks! 🎉

**Review by Panquesito7 — APPROVED** [review]

**Review by priyankarpal — APPROVED** [review]
LGTM 👍🏻 Thanks for your contribution.

**Comment by rohitg00** [comment]
When can I expect it to be merged? @priyankarpal

**Comment by priyankarpal** [comment]
@rohitg00 I can't tell. 😢

**Review by amandamartin-dev — APPROVED** [review]

**Pull request merged**
