### PR TITLE
Added website

### PR DESCRIPTION
**Pull request by fluentmoheshwar**
## Changes proposed

[x] Added website link

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2609"></a>

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
Looks good!

**Review by imran1509 — COMMENTED** [review]
looks good to me.
welcome to linkfree.

**Review by schmelto — APPROVED** [review]

**Review by stephenokyere233 — APPROVED** [review]
Looks good man!

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good! 👍

**Pull request merged**
