### PR TITLE
docs, fix: add missing comma

### LINKED ISSUE #1248: [DOCS] add missing comma
### Description

In readme.md in the example profile which users can copy, there is a missing comma in the milestone section between description and url

```
 "milestones": [
    {
      "title": "Started Freelancing",
      "date": "December 2021",
      "icon": "dollar",
      "color": "grey",
      "description": "Started freelancing" // add comma at the end of this line
      "url": "https://www.eddiejaoude.io/"
    }
```

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by PeroHub**
Closes #1248 

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### I made changes to profile section on the read.me file---added the text and comma as required

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1249"></a>

### CODE REVIEW

**Review by schmelto — CHANGES_REQUESTED** [review]
Please revert the changes made in package json lock

**Comment by emmalearnscode** [comment]
Don’t delete anything. The easiest way to fix this is to go to the package lock file in the eddiehub repo and copy the entire contents into your package lock file so that the two are identical, then commit the changes.

**Comment by PeroHub** [comment]
> Don’t delete anything. The easiest way to fix this is to go to the package lock file in the eddiehub repo and copy the entire contents into your package lock file so that the two are identical, then commit the changes.

Okay, thank you!!

**Review by kumarsonsoff3 — APPROVED** [review]
LGTM 👍 Thank you for your contribution! 🚀

**Review by schmelto — APPROVED** [review]
## Looking good to me

Your suggested changes looking good to me.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
