### PR TITLE
fix: Mobile UI alignment or sizing

### LINKED ISSUE #7917: [BUG] Mobile UI alignment or sizing
### Description

When viewing LinkFree via mobile, the UI doesn't entirely take up the entire screen or isn't aligned to the centre.

### Screenshots

Screenshot_20230702_134020_Chrome
Screenshot_20230702_134025_Chrome
Screenshot_20230702_134031_Chrome

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Tejasvp25**
## Fixes Issue

Closes #7917

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8242"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
I can't replicate to test, hopefully another maintainer can

**Comment by pushkaraj2007** [comment]
> I can't replicate to test, hopefully another maintainer can

The error only occurs on screen width less than 250 px.

You can try using browser dev tools to recreate the issue.

**Comment by loftwah** [comment]
Before:
image

After:
image

Looks good to me

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
From the Tailwind docs, I am not sure this is the best approach, as it is a single column

I now get this bug...

Screenshot 2023-07-20 at 10 17 52

**Review by sital002 — COMMENTED** [review]
This issue has already been solved so you can close this PR as completed. Here is the PR link https://github.com/EddieHubCommunity/LinkFree/pull/8552

**Comment by SaraJaoude** [comment]
Good spot @sital002 - I will close.

**Pull request closed without merging**
