### PR TITLE
[DOCS] update project install method

### LINKED ISSUE #1629: [DOCS] update npm clean install
### Description

Changed `npm install` to `npm ci` for clean installation of the dependencies.

### PR DESCRIPTION
**Pull request by RakeshSangem**
## Fixes Issue
closes #1629

### CODE REVIEW

**Review by EmmaDawsonDev — APPROVED** [review]
Looks good!

**Comment by RakeshSangem** [comment]
> Looks good!

Thank you, Emma😍

**Comment by EmmaDawsonDev** [comment]
I just realised someone else got there first with this same issue. Thanks for contributing and feel free to take another issue.

**Comment by RakeshSangem** [comment]
> I just realised someone else got there first with this same issue. Thanks for contributing and feel free to take another issue.

Sorry, I didn't see the PR.

**Pull request closed without merging**
