### PR TITLE
data: krushnarout

### PR DESCRIPTION
**Pull request by krushnarout**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7683"></a>

### CODE REVIEW

**Review by SaraJaoude — CHANGES_REQUESTED** [review]
Please move your file to the `data` folder. 

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

**Comment by krushnarout** [comment]
I'm sorry for the mistake.  I saw the guide and did it but the data was accidentally deleted from me.

**Review by SaraJaoude — APPROVED** [review]

**Review by krishstwt — APPROVED** [review]
LGTM

**Review by krishstwt — APPROVED** [review]
LGTM

**Comment by SaraJaoude** [comment]
> I'm sorry for the mistake. I saw the guide and did it but the data was accidentally deleted from me.

@krushnarout no problem at all - thanks for fixing. I will merge your PR now.

**Comment by krushnarout** [comment]
Thank you

**Pull request merged**
