### PR TITLE
Add MongoDB .env error handler

### PR DESCRIPTION
**Pull request by mkubdev**
## Changes proposed

Added a check in `config/mongo.js` to check if the `LINKFREE_MONGO_CONNECTION_STRING` mongo connection string is present inside `env.local` :

```js
// config/mongo.js
if (!process.env.LINKFREE_MONGO_CONNECTION_STRING) {
  throw new Error(
    "Please define LINKFREE_MONGO_CONNECTION_STRING to .env.local"
  );
}
```

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Hello 😁

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2193"></a>

### CODE REVIEW

**Comment by mkubdev** [comment]
> Thank you 👍 Maybe the message would be better to say `...environment variable` as it could be deployed somewhere else

Oops, sure! Something like this? 
```js
 throw new Error(
       "Please define LINKFREE_MONGO_CONNECTION_STRING environment variable inside .env file"
  );
  ```

**Comment by eddiejaoude** [comment]
Thanks @mkubdev 

I am still not sure if we should mention `.env` because when deploying we don't use that, maybe

```
"Please define the LINKFREE_MONGO_CONNECTION_STRING environment variable (if local add to .env file)"
```

**Comment by mkubdev** [comment]
> Thanks @mkubdev
> 
> I am still not sure if we should mention `.env` because when deploying we don't use that, maybe
> 
> ```
> "Please define the LINKFREE_MONGO_CONNECTION_STRING environment variable (if local add to .env file)"
> ```

Sounds good! Updating..

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍  thanks

**Pull request merged**
