### PR TITLE
data: Panquesito7

### PR DESCRIPTION
**Pull request by Panquesito7**
## Changes proposed

- Add an event to my profile.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3325"></a>

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by eddiejaoude** [comment]
Why remove the label? It helps us filter for profile changes

**Comment by Panquesito7** [comment]
> Why remove the label? It helps us filter for profile changes

Oh, sorry. I thought that was only for profile additions and not changes.

**Comment by eddiejaoude** [comment]
no worries, we should probably edit it to just say `chore: profile`

**Pull request merged**
