### PR TITLE
revert

### PR DESCRIPTION
**Pull request by Matthieu-ui**
I created a profile and mistakenly merged without a pull request! I am trying to revert that commit and try again properly.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1174"></a>

### CODE REVIEW

**Review by schmelto — CHANGES_REQUESTED** [review]
Hey @Matthieu-ui ,

due to the revert there are no more changes in this PR.
image

If you need any help to add your profile please let us know.

**Comment by emmalearnscode** [comment]
@Matthieu-ui Don’t worry, you can’t merge directly into Eddiehub without a pull request, only into your own repo.

**Comment by KarlGusta** [comment]
You can delete your current repo in your settings, folk the LinkFree repository, then create a branch that you can use to create a pull request.

**Comment by emmalearnscode** [comment]
I'll close this PR for now as it's empty but please feel free to create a new one with your profile when you're ready :)

**Pull request closed without merging**
