### PR TITLE
data: MuhammadNoorani

### PR DESCRIPTION
**Pull request by MuhammadNoorani**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5897"></a>

### CODE REVIEW

**Review by khushalarora — CHANGES_REQUESTED** [review]
Hi @MuhammadNoorani, thank you for contributing :tada: 
Please rename your file and add **`data/`** in the beginning :+1: 
It will look like **`data/MuhammadNoorani.json`**

**Comment by MuhammadNoorani** [comment]
> 

Done

**Comment by SaraJaoude** [comment]
> Done

It seems you have changed the title of the Pul Request.  However what Khushalarora meant was to change the file path to add `data`.

Screenshot 2023-04-08 at 10 07 37

**Comment by MuhammadNoorani** [comment]
> > Done
> 
> It seems you have changed the title of the Pul Request. However what Khushalarora meant was to change the file path to add `data`.
> 
> Screenshot 2023-04-08 at 10 07 37

I think now it is done. Thanks for this @SaraJaoude, BTW it is not in the docs.
4F21A636-0BF9-4627-8B9A-46DE2612A320

**Comment by SaraJaoude** [comment]
> I think now it is done. Thanks for this @SaraJaoude, BTW it is not in the docs. 

You will find this in Step 7 of the QuickStart Guide in our Docs which have been available since last year. I will now merge your Pull Request.

Screenshot 2023-04-08 at 13 27 41

**Comment by MuhammadNoorani** [comment]
Thanks, I missed that part in the docs.

**Pull request merged**
