### PR TITLE
data: krshkun testimonials

### PR DESCRIPTION
**Pull request by krshkun**
Added testimonials for @Pradumnasaraf @avie-dev @eddiejaoude @loftwah @thebarshblog @tobySolutions @WebXDAO/core-team, if anyone of you would like to add it to your linkfree profile, please refer: [docs](https://linkfree.eddiehub.io/docs/how-to-guides/testimonials)

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3101"></a>

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
Thank you so much for the testimonial for me and others. Also, you tagged the wrong handle @thebarshablog (Barsha)

Looks good to merge. Thank you for your contribution! :tada:

**Comment by thebarshablog** [comment]
> Added testimonials for @Pradumnasaraf @avie-dev @eddiejaoude @loftwah @thebarshblog @tobySolutions @WebXDAO/core-team, if anyone of you would like to add it to your linkfree profile, please refer: [docs](https://linkfree.eddiehub.io/docs/how-to-guides/testimonials)
> 
> [](https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3101)

Hey Krish! Did you write me a testimonial? Well, my handle is @thebarshablog . Thank you!

**Comment by tobySolutions** [comment]
Thank you so much Krish!!

**Comment by thebarshablog** [comment]
> Added testimonials for @Pradumnasaraf @avie-dev @eddiejaoude @loftwah @thebarshblog @tobySolutions @WebXDAO/core-team, if anyone of you would like to add it to your linkfree profile, please refer: [docs](https://linkfree.eddiehub.io/docs/how-to-guides/testimonials)
> 
> [](https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3101)

Thank you for the testimonial @krshkun

**Comment by thebarshablog** [comment]
How To Include A Testimonial In My Profile

Please elaborate this method! How do I include it? Where do I put the .json code?

**Comment by krshkun** [comment]
@thebarshablog create a testimonials array in your linkfree file's JSON and enter my username it it 👍

**Pull request merged**
