### PR TITLE
feat: add snapchat and codeforces

### PR DESCRIPTION
**Pull request by krishguptadev**
## Fixes Issue

closes

## Changes proposed

- Snapchat Icon
- Codeforces Icon

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/898"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍

**Review by shreyaansjain06 — APPROVED** [review]

**Review by Pradumnasaraf — APPROVED** [review]
LGTM

**Comment by emmalearnscode** [comment]
Please also update the readme with the new icons. Is there a reason you committed the package-lock file? If not, please remove it from the pull request

**Review by syedsohan — APPROVED** [review]

**Review by Vyvy-vi — CHANGES_REQUESTED** [review]
> https://github.com/EddieHubCommunity/LinkFree/pull/898#issuecomment-1003911546
The `package-lock.json` in this PR needs to be reset, and after that I think we should be good to go.

**Review by schmelto — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]

**Review by emmalearnscode — APPROVED** [review]

**Pull request merged**
