### PR TITLE
data: foss2cyber

### PR DESCRIPTION
**Pull request by foss2cyber**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4505"></a>

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
LGTM 👍🏻

**Review by himanshu1221 — APPROVED** [review]
LGTM :+1:

**Review by Hrishi5111998 — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
