### PR TITLE
data: tejas-raskar

### PR DESCRIPTION
**Pull request by tejas-raskar**

### CODE REVIEW

**Review by sidharthviz — APPROVED** [review]

**Review by himanshu1221 — APPROVED** [review]
**LGTM :+1:**

**Review by SurajPratap10 — APPROVED** [review]
looks good. Thanks for contributing!!

**Review by bkpecho — APPROVED** [review]
Great job on your contribution! 🎉 Good luck on your open-source journey! I hope you have a great day ahead.

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
