### PR TITLE
data: Update Michelle031.json

### PR DESCRIPTION
**Pull request by Angelsmartchain**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2791"></a>

### CODE REVIEW

**Comment by Panquesito7** [comment]
Hmm, I don't think you should update others' profiles. 🤔

**Comment by eddiejaoude** [comment]
Thank you @Angelsmartchain 👍 but we do not allow the modification of other people's profiles. Let me tag the profile owner and see if they approve the pull request. Have you created your own profile yet?

@Michelle031 you have a typo in your profile and @Angelsmartchain has kindly fixed it. If you approve the changes we can get it merged.

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Could you also please update the name of your file to match your github username.

**Comment by SaraJaoude** [comment]
This profile belongs to @Michelle031 so only they can update it.  If you have multiple accounts then please use the relevant account to update the relevant user in a new Pull Request.

**Pull request closed without merging**
