### PR TITLE
Fix:#3420 bubble text color

### PR DESCRIPTION
**Pull request by JunDevHarsh**
## Fixes Issue
Fix: #3420 by changing the text color to white so that can be seen more clearly if it was white

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation as needed.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3423"></a>

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
Hey @JunDevHarsh , make sure to have a discussion on the issue before creating a PR next time, so that the maintainers can assign it to you, in case the issue was not needed or was not approved by the maintainers the effort would be wasted. Also it is a good practise so that everyone gets to contribute to the project.

**Comment by JunDevHarsh** [comment]
@ChinmayMhatre apologies for not mentioning this before making a PR. I think I have skipped the major step. I will take care of it in the future.

**Comment by HarshDeep61034** [comment]
Looks Good to me, let see what others say 👍.

**Review by devvsakib — APPROVED** [review]

**Review by ManishBisht777 — COMMENTED** [review]
LGTM

**Comment by EmmaDawsonDev** [comment]
What is the color contrast between the white text and the orange background?

**Comment by ChinmayMhatre** [comment]
> What is the color contrast between the white text and the orange background?

I checked the contrast it is 3.38:1

**Comment by EmmaDawsonDev** [comment]
Unfortunately that’s not a high enough contrast ratio.

**Comment by ChinmayMhatre** [comment]
> Unfortunately that’s not a high enough contrast ratio.

Oh okay! Thank you for your feedback. I'll check it next time before creating an issue. We can close these ones

**Comment by ChinmayMhatre** [comment]
@JunDevHarsh Please close this issue since the contrast ratio between the colours are not high enough. Thank you!

**Pull request closed without merging**
