### PR TITLE
changes made in the code issue number #7591

### PR DESCRIPTION
**Pull request by devagya-rattan**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7595"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
What issue is this related to? Please fill out the PR template with the issue number

**Comment by devagya-rattan** [comment]
issue number specified .

**Comment by eddiejaoude** [comment]
> issue number specified .

Issue number is not in the PR description, it has a template for you to fill in

**Comment by SaraJaoude** [comment]
@devagya-rattan I will be closing this Pull Request as the Issue that it relates to is not assigned to you.  Please see my comments on: https://github.com/EddieHubCommunity/LinkFree/issues/7591

**Pull request closed without merging**
