### PR TITLE
Fix login page

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

fixed PR https://github.com/EddieHubCommunity/LinkFree/pull/6016

**light mode**

Screenshot 2023-05-03 at 09 16 56

**dark mode**

Screenshot 2023-05-03 at 09 16 48

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6578"></a>

### CODE REVIEW

**Comment by NiazMorshed2007** [comment]
Wow! This looks a lot better

**Review by NiazMorshed2007 — APPROVED** [review]

**Comment by eddiejaoude** [comment]
> Wow! This looks a lot better

lol thank you @NiazMorshed2007 but I didn't do much, you did all the hard work already 💪

**Comment by NiazMorshed2007** [comment]
> lol thank you @NiazMorshed2007 

Thanks for the appreciation @eddiejaoude 😁.

**Comment by shubhsharma19** [comment]
Looks great!

**Pull request merged**
