### PR TITLE
Create PratikPatel.json

### PR DESCRIPTION
**Pull request by pratik227**
Created new Profile

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6067"></a>

### CODE REVIEW

**Review by imbeshat — COMMENTED** [review]
The filename should be the same as your `GitHub username`. Please, change it.

**Comment by pratik227** [comment]
> The filename should be the same as your `GitHub username`. Please, change it.

Done

**Review by khushalarora — APPROVED** [review]
Thank you for contributing :tada:

**Review by kumarsonsoff3 — APPROVED** [review]
Looks awesome. Great collaboration everyone. 👍

**Pull request merged**
