### PR TITLE
Data:Jainex17

### PR DESCRIPTION
**Pull request by Jainex17**

### CODE REVIEW

**Review by ChinmayMhatre — CHANGES_REQUESTED** [review]
Please rename the json file to your username `Jainex17`

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
The way linkfree works to create profiles, the name of your file needs to exactly match your github username. As soon as you've update the file name this can be merged. Let us know if you need any help.

**Comment by Jainex17** [comment]
> The way linkfree works to create profiles, the name of your file needs to exactly match your github username. As soon as you've update the file name this can be merged. Let us know if you need any help.

I need to open new PR for that?

**Comment by EmmaDawsonDev** [comment]
No, you can just make the changes to your local branch and push them to this one

**Comment by Jainex17** [comment]
> No, you can just make the changes to your local branch and push them to this one

ohk done👍

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by EmmaDawsonDev — APPROVED** [review]

**Pull request merged**
