### PR TITLE
feat: add snapchat and mastodon icon

### LINKED ISSUE #886: Add mastodon Icon
### Description

https://mastodon.social/about

### Screenshots

_No response_

### Additional information

_No response_

### LINKED ISSUE #888: Add snapchat icon
## Hey,In the social media icons we can add ***Snapchat*** icon too in that 

* Because snapchat can outreach to many other people who want to use linkfree

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piyush-1234**
Fixes #888

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/890"></a>

closes #886

### CODE REVIEW

**Review by nathgoutam93 — CHANGES_REQUESTED** [review]
add these icons in links.json and assign appropriate colors , ./src/config/links.json

**Comment by emmalearnscode** [comment]
@piyush-1234 Please don’t submit pull requests for an issue that someone else has already requested to work on. @krishguptadev had already asked to be assigned which means that either you or Krish end up doing work unnecessarily. Feel free to take an issue that’s not already taken.

**Comment by emmalearnscode** [comment]
@piyush-1234 I assigned #886 to you so please remove the snapchat icon from your PR as someone else is already working on that. 

As @nathgoutam93 please also add a color for the icon the the links.json files and please also update the readme with the icon so that others know that it's available for use.

**Comment by piyush-1234** [comment]
> @piyush-1234 Please don’t submit pull requests for an issue that someone else has already requested to work on. @krishguptadev had already asked to be assigned which means that either you or Krish end up doing work unnecessarily. Feel free to take an issue that’s not already taken.

ok. thanks for the guidance as i am new to the opensource.

**Comment by piyush-1234** [comment]
> @piyush-1234 I assigned #886 to you so please remove the snapchat icon from your PR as someone else is already working on that.
> 
> As @nathgoutam93 please also add a color for the icon the the links.json files and please also update the readme with the icon so that others know that it's available for use.

yes.

**Comment by emmalearnscode** [comment]
> ok. thanks for the guidance as i am new to the opensource.

Let us know if you need any help :)

**Pull request closed without merging**
