### PR TITLE
Escape special characters

### LINKED ISSUE #4930: [DOCS] Special entities ( <, > ) are rendered incorrectly
### Description

In the testimonials guide, some of the special entities like (`<`, `>`) are not being rendered correctly. It's showing the syntax instead of the exact symbols. 

### Screenshots

It should be something like this `data/<username>/testimonials/<your-username>.json`

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rghdrizzle**
This pr solves the issue where the symbols such as < and > are being displayed by their entity name .

## Fixes Issue

Closes #4930 

## Changes proposed

Changed the symbols and used the entity names instead 

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4943"></a>

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by eddiejaoude** [comment]
I merged without testing 🤦‍♂️  it still appears to be a bug

Screenshot 2023-02-20 at 05 47 01

**Comment by eddiejaoude** [comment]
I will fix by updating the style of how we demonstrate this

**Comment by rghdrizzle** [comment]
Ahh my bad that the bug still persists , can you try using backslash behind the sign and check if its works( like \< .....\> ? I

**Comment by eddiejaoude** [comment]
No problem, I solved it a different, thank you though

**Pull request merged**
