### PR TITLE
data: FozanGardezi

### PR DESCRIPTION
**Pull request by FozanGardezi**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4933"></a>

### CODE REVIEW

**Review by accodes21 — COMMENTED** [review]
Looks good

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Please rename your [file here](https://github.com/FozanGardezi/LinkFree/edit/FozanGardezi-patch-1-2/data/Fozan.Gardezi.json) to exact same as your username. It should be `FozanGardezi.json` 

Let us know if you need any help with this! :)

image

**Review by himanshu1221 — CHANGES_REQUESTED** [review]
Please change file name from `Fozan.Gardezi` to yor github username `FozanGardezi`

**Review by himanshu1221 — APPROVED** [review]
**LGTM:+1:**

**Review by priyankarpal — APPROVED** [review]
LGTM 🎉

**Review by Sindhuinti — APPROVED** [review]
Looks good 👍🏻

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! 🎉

**Pull request merged**
