### PR TITLE
Added WeAreDevelopers to events

### PR DESCRIPTION
**Pull request by TRohit20**
Added WeAreDevelopers World Congress to the list of upcoming Community events and Open CFPs!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4982"></a>

### CODE REVIEW

**Comment by TRohit20** [comment]
Thank you! :)

**Review by amandamartin-dev — COMMENTED** [review]
While it's not required, would you like to add your status so folks know if you plan to speak or attend for meetups?

userStatus can be attending or speaking

**Comment by TRohit20** [comment]
Absolutely, but the reason I didn't mention anything is because I submitted the CFP but waiting on the decision. :)

**Review by dev-rakeshshaw — APPROVED** [review]
LGTM 🎉

**Comment by amandamartin-dev** [comment]
> Absolutely, but the reason I didn't mention anything is because I submitted the CFP but waiting on the decision. :)

Ahhh! Good luck! Can always edit later once you know

**Comment by TRohit20** [comment]
> > Absolutely, but the reason I didn't mention anything is because I submitted the CFP but waiting on the decision. :)
> 
> Ahhh! Good luck! Can always edit later once you know

Thank you, Amanda! That's the plan. :)

**Pull request merged**
