### PR TITLE
Gitlab icon

### PR DESCRIPTION
**Pull request by kaxada**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1066"></a>

### CODE REVIEW

**Review by emmalearnscode — APPROVED** [review]
Looks great! Thanks for contributing 👍

**Comment by KendallDoesCoding** [comment]
@kaxada Thanks a lot, the issue #1045 didnt get linked though, please add this in the description:

Fixes #1045

**Review by vikasganiga05 — APPROVED** [review]
LGTM :+1: Thanks for adding the GitLab icon :pray:

**Review by Panquesito7 — APPROVED** [review]

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Because, github and gitlab are kinda similar, I think its better to add the gitlab icon immediately after GitHub's icon, unless the icons are added in README.md as the order the icons were added in the project. but this is my preferance.

**Review by KendallDoesCoding — COMMENTED** [review]
Because, github and gitlab are kinda similar, I think its better to add the gitlab icon immediately after GitHub's icon, unless the icons are added in README.md as the order the icons were added in the project. but this is my preference.

Also, please remove line 122 and 123 from README.md

**Comment by emmalearnscode** [comment]
> Because, github and gitlab are kinda similar, I think its better to add the gitlab icon immediately after GitHub's icon, unless the icons are added in README.md as the order the icons were added in the project. but this is my preferance.

There is an issue open and assigned for someone to alphabetize the readme

**Comment by KendallDoesCoding** [comment]
> > Because, github and gitlab are kinda similar, I think its better to add the gitlab icon immediately after GitHub's icon, unless the icons are added in README.md as the order the icons were added in the project. but this is my preferance.
> 
> There is an issue open and assigned for someone to alphabetize the readme

Ok. I'll be down to do that.

**Comment by emmalearnscode** [comment]
> Ok. I'll be down to do that.

Then you should ask the assignee if they’re happy for you to take over.

**Comment by KendallDoesCoding** [comment]
> > Ok. I'll be down to do that.
> 
> Then you should ask the assignee if they’re happy for you to take over.

Done that already [😂](https://emojipedia.org/face-with-tears-of-joy/)

**Pull request merged**
