### PR TITLE
data: krshkun

### PR DESCRIPTION
**Pull request by krshkun**
Added BMC to my profile <3

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4917"></a>

### CODE REVIEW

**Review by himanshu1221 — APPROVED** [review]
**LGTM:+1:**

**Review by priyankarpal — APPROVED** [review]
☕

**Review by Panquesito7 — APPROVED** [review]
Awesome. Thanks! 🎉

**Comment by Panquesito7** [comment]
Nice! You already got one supporter! 👀

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good! 🎉

**Pull request merged**
