### PR TITLE
added my profile to public

### PR DESCRIPTION
**Pull request by eddejayaklu**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1308"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please add back the `package-lock.json` file. You can copy the contents from the original file in [our repository](https://github.com/EddieHubCommunity/LinkFree), paste it into your fork, commit, then push. Do let us know if you need any help! 😄

**Comment by eddejayaklu** [comment]
> Please add back the `package-lock.json` file. You can copy the contents from the original file in [our repository](https://github.com/EddieHubCommunity/LinkFree), paste it into your fork, commit, then push. Do let us know if you need any help! 😄

Thanks for your feedback😊.
I have added package-lock.json in addprofile branch right. This is what i pushed and did PR.
package-lock

**Comment by eddejayaklu** [comment]
> Currently the package-lock and the package.json files in your repo do not match the ones in the main Eddiehub linkfree repo and are still showing up as part of the PR. Please copy the file contents from here: https://github.com/EddieHubCommunity/LinkFree/blob/main/package-lock.json and try again. There should only be 1 file in this pull request and the package-lock and package.json files should disappear from the PR when the files are identical.
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

Thanks😊
I have copied the contents of package-lock.json. Hope so now it works well.

**Comment by eddejayaklu** [comment]
> > > Currently the package-lock and the package.json files in your repo do not match the ones in the main Eddiehub linkfree repo and are still showing up as part of the PR. Please copy the file contents from here: https://github.com/EddieHubCommunity/LinkFree/blob/main/package-lock.json and try again. There should only be 1 file in this pull request and the package-lock and package.json files should disappear from the PR when the files are identical.
> > > __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  🛠️ This code needs a fix
> > 
> > 
> > Thanks😊 I have copied the contents of package-lock.json. Hope so now it works well.
> 
> Unfortunately it hasn't worked as there are still 3 files in the pull request. Try again to copy the contents of the package-lock file and package.json files from the Eddiehub/Linkfree repo into your own repo then commit and push your code. If you are successful there will only be 1 file in this pull request.__ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

Thank you for your feedback. As you can see i did modified for package.json and package-lock.json. I am hoping this time it works well. Please don't annoy me if it does not work well, As I am very new to open source. If it does not work well can you just tell me like whats the difference between my package-lock.json and  the original package-lock.json cuz i dont find any difference between them. when i did commit there are same lines of code between my package-lock.json and the original package-lock.json.

**Comment by emmalearnscode** [comment]
You can see the differences in the files if you look at the Files changed tab at the top of this pull request. There you can see there are still 3 files in the pull request so modifying them has not yet worked.

I think part of the problem may be that you have not updated your fork in a while so it's currently 37 commits behind Eddiehub/main. Try fetching and merging all the changes from upstream into your repo and then into your branch, then copy the 2 files again to see if this helps.

We're here to help beginners get started in open source but small glitches can come up along the way. It's the nature of version control and you will no doubt come across similar problems in the future. It's necessary to have patience and understand that it can be difficult to explain things in written form but with some perseverance you will no doubt succeed.

**Comment by eddejayaklu** [comment]
> You can see the differences in the files if you look at the Files changed tab at the top of this pull request. There you can see there are still 3 files in the pull request so modifying them has not yet worked.
> 
> I think part of the problem may be that you have not updated your fork in a while so it's currently 37 commits behind Eddiehub/main. Try fetching and merging all the changes from upstream into your repo and then into your branch, then copy the 2 files again to see if this helps.
> 
> We're here to help beginners get started in open source but small glitches can come up along the way. It's the nature of version control and you will no doubt come across similar problems in the future. It's necessary to have patience and understand that it can be difficult to explain things in written form but with some perseverance you will no doubt succeed.

Thank you for your kind feedback. Actually I think so I am messed up with package.json and package-lock.json so i am closing this PR, and have created new PR.

**Pull request closed without merging**
