### PR TITLE
data:amandamartin-dev

### PR DESCRIPTION
**Pull request by amandamartin-dev**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2510"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thanks Amanda 👍 

I think your branch might be out of date with `main` because you have `CHANGELOG.md` and other changes in your PR

**Comment by amandamartin-dev** [comment]
Oh weird. I'll take a look soon. Thanks!

**Comment by eddiejaoude** [comment]
No problem, any questions let me know - maybe your fork was up to date when you created your branch

**Comment by amandamartin-dev** [comment]
everything should be good now, let me know!

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍

**Pull request merged**
