### PR TITLE
Added my Profile username.BoneNzy

### PR DESCRIPTION
**Pull request by BoneNzy**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
changes

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1714"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thanks! 🎉
Not sure why the CI is failing, though. 👀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by BoneNzy** [comment]
I have no idea  maybe I did some mistake in the process

**Comment by Panquesito7** [comment]
> I have no idea maybe I did some mistake in the process

It seems it's also failing in other PRs, though. 🤔

**Comment by BoneNzy** [comment]
> > I have no idea maybe I did some mistake in the process
> 
> It seems it's also failing in other PRs, though. thinking

yep ok got it I will wait until it's reported what's going wrong

**Comment by eddiejaoude** [comment]
Sorry for the failing CI, I am looking into it

**Review by EmmaDawsonDev — APPROVED** [review]
Looks good and thanks for letting us know about the failing issue, it should all be fixed now.

**Pull request merged**
