### PR TITLE
added hovering effect to social-icons

### LINKED ISSUE #951: [FEATURE]Hovering the social media icons
### Description

The icons shown in the ss are not having any hovering styles.

### Screenshots

Screenshot from 2022-01-10 00-04-15

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by digambar-t7**
## Fixes Issue

closes #951

Added Hovering effect to the social media icons

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/952"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Could you please show any screenshots of how does it look with and without this PR? Let us know if you need any help! 😃

**Comment by digambar-t7** [comment]
Yeah you are right. We can do it very easily using the ` :hover`  pseudo selector. I think I was trying to do it in the react way (hahaha). My bad I will correct it :

#Before After transformation:

Screenshot from 2022-01-11 13-14-07
Screenshot from 2022-01-11 13-13-30

**Comment by digambar-t7** [comment]
Hey there, I have implemented it using css `:hover` pseudo selectors now and cleared the previous files. But now I am not able to push it. How should I do it?

**Comment by digambar-t7** [comment]
Yes first I did hard reset of my branch to make it same as the master branch. Then I made the changes and made a commit. And then I was not able to merge it.

**Comment by nhcarrigan** [comment]
You might need to force push.

**Comment by digambar-t7** [comment]
Ok I'll give it a try

**Comment by digambar-t7** [comment]
Oh yeah, that did work.
THANK YOU!

**Review by Pradumnasaraf — COMMENTED** [review]
LGTM 🎉

**Review by krishguptadev — APPROVED** [review]

**Review by Pradumnasaraf — APPROVED** [review]

**Review by emmalearnscode — APPROVED** [review]

**Comment by digambar-t7** [comment]
> Could you please show any screenshots of how does it look with and without this PR? Let us know if you need any help! smiley
Hey @Panquesito7  can you review it so that this pr can proceed :)

**Review by krishguptadev — APPROVED** [review]

**Review by ssensalo — APPROVED** [review]

**Review by schmelto — APPROVED** [review]

**Pull request merged**
