### PR TITLE
[fix] : change my username

### PR DESCRIPTION
**Pull request by vedanshi555**
## Changes proposed
changed my username of twitter and github

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1563"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Rename your `filename` to your new `username.json`. ⚙

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Also update your **Avatar link** with your new `username`!

**Comment by kartikgajjar7** [comment]
change  avatar link to this 

https://github.com/vedanshi555.png

**Review by Panquesito7 — APPROVED** [review]
Thank you! 🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

**Pull request merged**
