### PR TITLE
data: Pal-Sandeep

### PR DESCRIPTION
**Pull request by Pal-Sandeep**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3160"></a>

### CODE REVIEW

**Review by Panquesito7 — DISMISSED** [review]
Thanks! 🎉

**Comment by Pal-Sandeep** [comment]
@Panquesito7 please review

**Comment by Aadarsh805** [comment]
@Pal-Sandeep Hey, I see that the file name doesn't match your username, the capital `p` and `s`, the file name must match your GitHub username

**Comment by Pal-Sandeep** [comment]
@Aadarsh805 please review

**Review by Aadarsh805 — APPROVED** [review]
everything looks great to me now 👍

**Review by Abdulwahid7027 — APPROVED** [review]
Looks great.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"></p>

**Pull request merged**
