### PR TITLE
Added j-barreiros

### PR DESCRIPTION
**Pull request by j-barreiros**

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Hey there! Thanks for submitting a PR! 😄 Please rename the filename to `j-barreiros.json`. Let us know if you need any help with that. Thanks. 🙂

**Comment by j-barreiros** [comment]
Edited the file name. thx for the help.

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍

**Review by Pradumnasaraf — APPROVED** [review]
LGTM! Thank you for your contribution. :smile:

**Review by ssensalo — APPROVED** [review]

**Pull request merged**
