### PR TITLE
Rohitg00 patch 1

### PR DESCRIPTION
**Pull request by rohitg00**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=_EsdzyY)

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4522"></a>

### CODE REVIEW

**Comment by rohitg00** [comment]
I missed the name of the conference. Sorry for the inconvenience.

**Review by priyankarpal — CHANGES_REQUESTED** [review]
There is a conflict error please resolve it.

**Comment by rohitg00** [comment]
Solved, @priyankarpal

**Review by priyankarpal — APPROVED** [review]
LGTM

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
