### PR TITLE
updated Stevenovak123.json

### PR DESCRIPTION
**Pull request by stevenovak123**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2299"></a>

### CODE REVIEW

**Comment by stevenovak123** [comment]
I dont know why the whole file is reformatted, just added  "displayStatsPublic" "tags""socials"

**Comment by senali-d** [comment]
> I dont know why the whole file is reformatted, just added "displayStatsPublic" "tags""socials"

Do you use any auto formatting on save? Sometimes it will be the reason.

**Comment by stevenovak123** [comment]
I dont. Still it failed

**Comment by stevenovak123** [comment]
What  should I do? Anyupdates?!!

**Comment by eddiejaoude** [comment]
Not sure why it is showing the whole file has changed, but I formatted the file and it should look like this to make the GitHub action pass (I think)

```json
{
  "name": "Steve Dsouza",
  "type": "personal",
  "displayStatsPublic": true,
  "bio": "Software Developer | Web Developer",
  "tags": [
    "Open Source",
    "javascript",
    "typescript",
    "nextjs",
    "Web-Development"
  ],
  "avatar": "https://github.com/stevenovak123.png",
  "socials": [
    { "platform": "twitter", "url": "https://twitter.com/stevenovak123" },
    { "platform": "github", "url": "https://github.com/stevenovak123" }
  ],
  "links": [
    {
      "name": "Follow me on GitHub",
      "url": "https://github.com/stevenovak123",
      "icon": "github"
    },
    {
      "name": "Follow me on Twitter",
      "url": "https://twitter.com/stevenovak123",
      "icon": "twitter"
    },
    {
      "name": "Follow me on LinkedIn",
      "url": "https://www.linkedin.com/in/stevenovak123/",
      "icon": "linkedin"
    },
    {
      "name": "Follow me on Instagram",
      "url": "https://www.instagram.com/stevenovak123/",
      "icon": "instagram"
    }
  ]
}
```

**Comment by eddiejaoude** [comment]
We probably need to improve this process, so the GitHub Action shows more information or automatically reformats the file - I think having it automatically reformatting the file is best but might be some challenges when in a fork

**Comment by Panquesito7** [comment]
> but might be some challenges when in a fork

As long as the checkbox `Allow edits from maintainers` is enabled, it should work, I think. 🙂
Or we could directly push to the `main` branch of the repository and make the changes there.

**Comment by eddiejaoude** [comment]
Json is valid, so I will merge and the GitHub Action will reformat correctly

**Comment by stevenovak123** [comment]
Thank you!

**Pull request merged**
