### PR TITLE
data: vikaskumar2703

### PR DESCRIPTION
**Pull request by vikaskumar2703**
## Changes proposed

   CREATES VIKAS KUMAR LINKFREE PROFILE

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2924"></a>

### CODE REVIEW

**Comment by vikaskumar2703** [comment]
Can I get someone to review my PR and suggest me any issues .

**Review by schmelto — APPROVED** [review]

**Comment by Aadarsh805** [comment]
@schmelto he has a testimonials field added in there too, is it supposed to be there if there aren't any testimonials

**Review by vikaskumar2703 — COMMENTED** [review]
ok

**Review by vikaskumar2703 — COMMENTED** [review]
changed file name to the correct required name.

**Comment by vikaskumar2703** [comment]
i think i have corrected all the mistakes after having discussion on discord . pl review my pr and merge the same.

**Comment by Aadarsh805** [comment]
> i think i have corrected all the mistakes after having discussion on discord . pl review my pr and merge the same.

It'll be reviewed and merged, you need not worry about that. Maintainers must be busy with other things, give them time

**Comment by vikaskumar2703** [comment]
Actually this is kind of my first pr so i have less idea how things work.

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by vikaskumar2703** [comment]
Thank u

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by vikaskumar2703** [comment]
> Looks good +1

Thank u , learned from u only.

**Pull request merged**
