### PR TITLE
data update

### PR DESCRIPTION
**Pull request by souravsk**
#### Updated the Social media and some user IDs which are not working now.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2759"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
There are too many file changes, here are some suggestions...

- update your fork/branch and update your pull request, this will remove the autogenerate file changes
- `public/data/souravsk.json` file is not needed, you have it in the correct place `data`

**Comment by souravsk** [comment]
Sorry Eddie for troubling you but I have updated the fork which also removes the public/data/souravsk.json file too 
So I just have to update the pull request.

**Comment by souravsk** [comment]
it showing to create a new pull request should I create any new one or not

**Comment by eddiejaoude** [comment]
No problem. Yes it might be easier to create a new pull request 👍 

Any questions let us know in the EddieHub Discord http://discord.eddiehub.org

**Pull request closed without merging**
