### PR TITLE
feat:  updated avatar display image 

### PR DESCRIPTION
**Pull request by Soham041201**
Hey , Sorry added the lock.json as well by mistake . Was not able to remove it after commit :(

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/117"></a>

### CODE REVIEW

**Review by nhcarrigan — CHANGES_REQUESTED** [review]
Hey there,

Please remove your changes to the package.json and package-lock.json to avoid conflicts. 

Let us know if you need any assistance with this.

**Review by Soham041201 — COMMENTED** [review]
Not able to remove the files. Would be great if a little bit help was provided

**Comment by nhcarrigan** [comment]
https://www.nhcarrigan.com/notes/#/git-commands/rebase-branch

You can perform a rebase 🙂

**Review by FayasNoushad — APPROVED** [review]

**Review by rohan-kulkarni-25 — COMMENTED** [review]
The same changes are also included in PR #143

**Comment by Soham041201** [comment]
Okay So, Let me close this PR.

**Pull request closed without merging**
