### PR TITLE
update_user kdpuvvadi

### PR DESCRIPTION
**Pull request by kdpuvvadi**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4576"></a>

### CODE REVIEW

**Review by accodes21 — APPROVED** [review]

**Review by priyankarpal — APPROVED** [review]
Awesome 🎉 Thanks for your contribution

**Review by Hrishi5111998 — APPROVED** [review]
thanks for contributing!

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good! 👍

**Pull request merged**
