### PR TITLE
Improved Wording

### LINKED ISSUE #8512: [DOCS] Improve wording in roadmap
### Description

Change the wording in roadmap.js to "Features that are currently being worked on or will be soon.",

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by TomMirfin**
https://github.com/EddieHubCommunity/LinkFree/commit/9fed57a817251651e8dfd5a8f3b4f10c0547f2bb
## Fixes Issue

Fixes #8512 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8499"></a>

### CODE REVIEW

**Review by sital002 — COMMENTED** [review]
You can't send PR without raising a issue and getting assigned. I would recommend you to read our contributing guidelines https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by SaraJaoude** [comment]
> You can't send PR without raising a issue and getting assigned. I would recommend you to read our contributing guidelines https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

@sital002 thank you for raising this point.

**Review by SaraJaoude — APPROVED** [review]
looks good

**Comment by eddiejaoude** [comment]
@TomMirfin please do not add submodules in the future - check your pull request only has the changes you want to include

**Pull request merged**
