### PR TITLE
fix : #911 Center when only one milestone

### LINKED ISSUE #911: [OTHER] Center when only one milestone (on large screen)
### What would you like to share?

If someone includes only one milestone on larger screens eg desktops it's positioned to the right which looks slightly odd (IMO). I suggest we add a check to see how many milestones there are and if there's only one then the milestone should be centered, more than one the styling can remain as it is currently.

Screenshot 2022-01-04 160238

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Yoshemith**
## Fixes Issue

Closes #911 

## Changes proposed

* If there is only one milestone, the content should be centered (as suggested on #911 ).

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Large Screen:

Screen Shot 2022-07-10 at 21 49 05

## Note to reviewers

This is my first contribution to the project. I'll appreciate your comments/review.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1474"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — COMMENTED** [review]
Code looks good to me!! 👍 

But the huge white space in sides is looking a bit weird, wouldn't it be great to reduce it's width a bit, and add a little padding on top.

**Comment by Yoshemith** [comment]
Sure @kumarsonsoff3 I just made the changes. I changed the width of the milestone to 80%. And changed the top-padding to 0.6rem. Let me know if that works better. 

Screen Shot 2022-07-11 at 19 08 13

**Comment by Yoshemith** [comment]
Hi @EmmaDawsonDev sorry for the late response. I appreciate your feedback a lot. I tried what you told me, though the "center" in align is not a valid value according to [primereact](https://www.primefaces.org/primereact/timeline/#:~:text=events%20to%20display.-,align,-string).

I'm gonna try a couple of things to come up with a better solution. I'm thinking of using useRef instead of useEffect, or maybe I'll try to avoid using either of those. But, I'll continue doing some more research about it, so I'll keep you posted :)

**Comment by Yoshemith** [comment]
Hi again 🙋‍♂️ @EmmaDawsonDev. I found another solution (a better one I think). I removed useEffect and chose to use CSS Combinators, so this way I could add styles to the Timeline without affecting the dom directly (as before).

_Milestones.js_
Screen Shot 2022-08-01 at 18 30 26

_Milestones.css_
Screen Shot 2022-08-01 at 18 30 43

Hope this is the expected solution for this issue. I learned a lot more about CSS combinators, so thank you for your prior feedback btw. If there's something else to fix about this PR, please let me know :)

**Comment by eddiejaoude** [comment]
Great collaboration! Thank you for your contribution 👍 

@EmmaDawsonDev if you are happy you can merge this.

@Yoshemith note that we are working on version 2 in branch `nextjs` that is using NextJS + TailwindCSS

**Review by eddiejaoude — APPROVED** [review]
Thanks 👍

**Pull request merged**
