### PR TITLE
data: iamravi1

### PR DESCRIPTION
**Pull request by iamravi1**
## Check List (Check all the applicable boxes) 

- [ :heavy_check_mark: ] My code follows the code style of this project.
- [ :heavy_check_mark: ] My change requires changes to the documentation.
- [:heavy_check_mark:  ] I have updated the documentation accordingly.
- [:heavy_check_mark: ] All new and existing tests passed.
- [:heavy_check_mark: ] This PR does not contain plagiarized content.
- [:heavy_check_mark: ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Sindhuinti — APPROVED** [review]
Thanks 🎉

**Review by AbbeyIT — APPROVED** [review]
LGTM!

**Review by priyankarpal — APPROVED** [review]
Looks great. Thanks for your contribution.

**Review by Hrishi5111998 — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good! 👍

**Pull request merged**
