### PR TITLE
Created samadpls.json

### PR DESCRIPTION
**Pull request by samadpls**
added a json file

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1772"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Hey there! Please add `.json` at the end of the filename.
We need to do this so that the formatter can check if your file is fine, register it, and add it to LinkFree's website.

Let us know if you need any help doing that! 🙂

**Comment by Njong392** [comment]
I think it's okay to close this pull request, seeing as @samadpls has deleted the file and opened another pull request [here](https://github.com/EddieHubCommunity/LinkFree/pull/1775) :+1:

**Comment by samadpls** [comment]
> I think it's okay to close this pull request, seeing as @samadpls has deleted the file and opened another pull request [here](https://github.com/EddieHubCommunity/LinkFree/pull/1775) :+1: 

Yes i delete it

**Comment by samadpls** [comment]
> I think it's okay to close this pull request, seeing as @samadpls has deleted the file and opened another pull request [here](https://github.com/EddieHubCommunity/LinkFree/pull/1775) 👍
yes I done changes thankyou

**Pull request closed without merging**
