### PR TITLE
[NextJS] Change UserLink to use anchor tag instead of button

### PR DESCRIPTION
**Pull request by dan-mba**
## Changes proposed

The UserLink component was using buttons for links.
This has accessibility (a11y) concerns.
You can find more about it by searching "link button a11y"
This PR changes UserLink to use anchor tags.
It also takes advantage of the anchor tag ability to open links in a new tab. 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2028"></a>

### CODE REVIEW

**Comment by dan-mba** [comment]
I have tested this with Firefox, Chrome, & Edge.

I could use someone with a Mac to test this on Safari.
`window.open()` can cause pop-up blocker issues if the browser doesn't equate the call with an onClick event.

**Comment by eddiejaoude** [comment]
Thanks Dan! On Safari this did trigger the popup blocker, after I allowed it, it opened in a new window (not tab)

**Comment by dan-mba** [comment]
> Thanks Dan! On Safari this did trigger the popup blocker, after I allowed it, it opened in a new window (not tab)

I made changes to avoid the pop-up blocker. 
The thing I need to make sure of on Safari now is that it correctly opens in a new tab & the link count is updated

**Review by eddiejaoude — APPROVED** [review]
Thank you! It worked great on Safari 👍

**Pull request merged**
