### PR TITLE
Added aliraza944.json

### PR DESCRIPTION
**Pull request by aliraza944**
## Changes proposed
Added my profile by creating a new file named aliraza944.json

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/967"></a>

### CODE REVIEW

**Review by RonenTGreat — CHANGES_REQUESTED** [review]
Please do not added the package.json to the commit

**Comment by aliraza944** [comment]
Just the `pakage.json` or `pakage.lock.json` too?

**Comment by emmalearnscode** [comment]
> Just the `pakage.json` or `pakage.lock.json` too?

Please remove both from your commit but don’t delete the files from the project.

**Comment by aliraza944** [comment]
> > Just the `pakage.json` or `pakage.lock.json` too?
> 
> Please remove both from your commit but don’t delete the files from the project.

I have removed those files from my Pull request

**Review by Panquesito7 — APPROVED** [review]

**Review by emmalearnscode — APPROVED** [review]

**Pull request merged**
