### PR TITLE
add lloydlobo.json

### PR DESCRIPTION
**Pull request by lloydlobo**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

- I added "package.json" and "package-lock.json "files too—along with "lloydlobo.json". 

- Currently unsure if it's required for submitting one's name to http://linkfree.eddiehub.org/

- Curious to know if those were required.... Thanks

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1042"></a>

### CODE REVIEW

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
Please remove package-lock.json and package.json files from your PR (don't delete them from the project, just remove them from the commit)

**Comment by lloydlobo** [comment]
> Please remove package-lock.json and package.json files from your PR (don't delete them from the project, just remove them from the commit)

@emmalearnscode Thanks for the update. I reverted the commit that added the files mentioned above. Does that work?|
 
Ps. Looked around and couldn't find a workaround to removing commits from a PR (history). I'd be grateful if you could point me in the right direction with this as I am new to this workflow. Thanks again.

**Review by Pradumnasaraf — APPROVED** [review]
LGTM!, Thanks for your contribution :)

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍

**Comment by lloydlobo** [comment]
> LGTM!, Thanks for your contribution :)

> LGTM 🚀 Thank you for your contribution! 😄👍

Thank you for the opportunity. 🙏

**Pull request merged**
