### PR TITLE
Fixed #4944 - [FEATURE] hover effect on docs page - Border added

### LINKED ISSUE #4944: [FEATURE] Card and hover effect on docs page
### Description

We could create card elements or some background effects for different docs elements because now the user is not sure that the element is clickable or not
image
 Later we could apply a hover effect for those cards then it gonna look more attractive as UI.

### Screenshots

image
Similarly in these

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by akashIsCoding**
## Fixes Issue 

closes #4944

## Changes proposed
Added a border to different doc elements to make them look interactive

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers
Please do give me a feedback on the changes! :) 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5125"></a>

### CODE REVIEW

**Review by priyankarpal — DISMISSED** [review]
LGTM 🎉

**Comment by akashIsCoding** [comment]
hey @priyankarpal is anyone else also going to review this before closing?

**Comment by priyankarpal** [comment]
> hey @priyankarpal is anyone else also going to review this before closing?

wait for a maintainer.

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
I think it would look better to have no border and only on hover show a border

**Comment by akashIsCoding** [comment]
Hi @eddiejaoude, 

New change requested has been completed.
- [x]  No border and only on hover show a border  

Screenshot: 

image


Requesting review.

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍 

note: it has some coding standing issues but I will fix after the merge - please check for next time

**Pull request merged**
