### PR TITLE
Update RishikeshYadav95.json

### PR DESCRIPTION
**Pull request by RishikeshYadav95**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8662"></a>

### CODE REVIEW

**Comment by RishikeshYadav95** [comment]
Just made changes to the description.

**Review by chetannada — APPROVED** [review]
Looks cool!

**Comment by RishikeshYadav95** [comment]
Thank you! Looking forward to getting it merged.

**Review by amandamartin-dev — APPROVED** [review]
lgtm! Thanks for the submission

**Pull request merged**
