### PR TITLE
data:AasthaShahCodes

### PR DESCRIPTION
**Pull request by aasthashahcodes**
It's my first contribution. Edits are appreciated.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2776"></a>

### CODE REVIEW

**Review by dan-mba — CHANGES_REQUESTED** [review]
Add a comma after the `}` on line 22

**Comment by aasthashahcodes** [comment]
> Add a comma after the `}` on line 22

Done. Thank you. How can I improve my profile code?

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by aasthashahcodes** [comment]
> Looks good to merge. Thank you for your contribution! 🎉
> 
> Also, congrats on your 1st contribution.

Thank you so much Pradumna!! ✨
Feels great.

**Comment by eddiejaoude** [comment]
Welcome @aasthashahcodes 

Btw your filename does not match the case of your GitHub username - this will still work now but might break in the future. I suggest making a new pull request and rename the file to avoid any issues in the future

**Comment by aasthashahcodes** [comment]
> Welcome @aasthashahcodes
> 
> Btw your filename does not match the case of your GitHub username - this will still work now but might break in the future. I suggest making a new pull request and rename the file to avoid any issues in the future

Thank you Eddie.
Looks good now?

**Pull request merged**
