### PR TITLE
Hide the Reoreder button when there's no links (issue #8282)

### LINKED ISSUE #8282: Hide Reorder button when there is no link added
### Description

We can hide the reorder button when there is no link added.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jesliu-27**
## Fixes Issue

Fixes #8282 

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8349"></a>

### CODE REVIEW

**Comment by SaraJaoude** [comment]
@jesliu-27 can you please update the description to reflect the Issue number this Pull Request relates to.

**Comment by jesliu-27** [comment]
> @jesliu-27 can you please update the description to reflect the Issue number this Pull Request relates to.

Thanks for reminding me!

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you 👍 I left an inline comment

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Reorder seems to not appear when there are links, please test

Screenshot 2023-07-25 at 10 10 03

**Comment by eddiejaoude** [comment]
Thank you for your contribution, but as there has been no activity for 2 weeks, I will close the pull request

**Pull request closed without merging**
