### PR TITLE
Make filename lowercase for PR template

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
## Fixes Issue
- Usually in all repos the file is in lowercase, and the [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) recommend it being lowercase too.

## Changes proposed
- Make PR template file-name lowercase.

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1074"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]

**Review by Pradumnasaraf — APPROVED** [review]
LGTM!

**Review by syedsohan — APPROVED** [review]

**Review by ssensalo — APPROVED** [review]

**Review by vikasganiga05 — APPROVED** [review]
LGTM :+1: 
I saw many repos use uppercase filename for the PR template. Is this make any difference in PR template? or is it just a naming convention?

**Review by krshdev — CHANGES_REQUESTED** [review]
GitHub by default makes it Uppercase and it is recommended to keep it uppercase 🙂 Also lowercasing doesn't make any difference to the PR template.

**Comment by vikasganiga05** [comment]
> GitHub by default makes it Uppercase and it is recommended to keep it uppercase slightly_smiling_face Also lowercasing doesn't make any difference to the PR template.

Okay, Thanks Krish for the info :slightly_smiling_face:

**Comment by KendallDoesCoding** [comment]
> GitHub by default makes it Uppercase and it is recommended to keep it uppercase 🙂 Also lowercasing doesn't make any difference to the PR template.

I thought that was only for CONTRIBUTING.MD in the repo, you cant make a PR going into settings, you need to create the file yourself, in the docs its lowercase, in other repos its lowercase, I made a PR recently to make the CONTRIBUTING.MD file uppercase, becuase ik github recommends that. For PR template though, both ways work tbh. So yall don't need to merge this if yall dont want :)

**Review by schmelto — APPROVED** [review]

**Pull request merged**
