### PR TITLE
data:Anjuli08

### PR DESCRIPTION
**Pull request by Anjuli08**
I want to add my profile to the linkFree. 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2929"></a>

### CODE REVIEW

**Comment by dan-mba** [comment]
> I've removed the comma. How can I move my profile to data directory?

If you are editing on GitHub, there is a box at the top with the filename.
Type `data/` in the box before your filename & it should be moved.

**Comment by Anjuli08** [comment]
> > I've removed the comma. How can I move my profile to data directory?
> 
> If you are editing on GitHub, there is a box at the top with the filename. Type `data/` in the box before your filename & it should be moved.

done! please review if it's alright

**Review by dan-mba — APPROVED** [review]
Looks good to me

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍 

Great collaboration 💪 

You can also join us in the EddieHub Discord http://discord.eddiehub.org

**Pull request merged**
