### PR TITLE
[Updated] user testimonials and added new feature solving issue #2444

### LINKED ISSUE #2444: [FEATURE] Linked testimonial profiles
### Description

From the testimonials tab, clicking on the users avatar (or wherever makes sense) that provided the testimonial could lead to their GH profile.

Potential use case:
An employer lands on your linkfree, is reading testimonials
Wants to reach out to that person for a recommendation

Use case 2:
easy access to others connected to the main profile user for collaboration and/or connection

Future considerations:
Should non-GH users be able to submit testimonials in the future, what profile is linked?

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by adityassharma-ss**
I have updated the user testimonials.js file & added a feature solving the issue #2444. You can review it accordingly.

## Fixes Issue

Closes #2444 

## Check List (Check all the applicable boxes) 

- [ X ] My code follows the code style of this project.
- [ X ] My change requires changes to the documentation.
- [ X ] I have updated the documentation accordingly.
- [ X ] All new and existing tests passed.
- [ X ] This PR does not contain plagiarized content.
- [ X ] The title of my pull request is a short description of the requested changes.

## Screenshots

Eddie Jaoude - Brave 12_25_2022 6_14_23 PM

## Note to reviewers

I have reviewed all the changes & the update feature works fine. So you can add it to the deployment without any hesitation.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2487"></a>

### CODE REVIEW

**Review by accodes21 — COMMENTED** [review]
Looks great would need a review from a maintainer to be able to merge.

**Comment by adityassharma-ss** [comment]
Hey @eddiejaoude
Can you please review this.

**Comment by eddiejaoude** [comment]
Thank you for contributing but I think there are too many changes in one Pull Request. Can you break them down into individual PRs please.

**Comment by adityassharma-ss** [comment]
Hello again @eddiejaoude, Can you check the same again here `https://github.com/EddieHubCommunity/LinkFree/pull/2503`
There was an issue with the last request, So I updated it.

**Comment by eddiejaoude** [comment]
Sure 👍

**Pull request closed without merging**
