### PR TITLE
Renamed events folder to match GitHub username

### PR DESCRIPTION
**Pull request by WasiqB**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2922"></a>

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by eddiejaoude** [comment]
It seems you created a new folder and now have 2 folders, please remove the older folder in this pull request also
https://github.com/EddieHubCommunity/LinkFree/blob/f7bfa039be7b812c6bc40bc341dcb6ce9dbf6fbd/data/wasiqb/events/2022-12-20-webinar.json

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Duplicate folder, rename or remove old folder

**Comment by WasiqB** [comment]
@eddiejaoude , thanks for pointing it out, the old folder was not showing up on my local, but it was there in my fork, so I deleted the old one from the repository directly.

**Comment by WasiqB** [comment]
Changes are done.

**Review by eddiejaoude — APPROVED** [review]
Thanks 👍

**Pull request merged**
