### PR TITLE
Create Nikhil202003.json

### PR DESCRIPTION
**Pull request by Nikhil202003**
## Check List (Check all the applicable boxes) 

- [X ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ X] This PR does not contain plagiarized content.
- [X ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

  You all are doing great job. I would like my LinkFree profile be updated

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6205"></a>

### CODE REVIEW

**Comment by SaraJaoude** [comment]
You have conflicts in your file, please resolve. This is usually because your fork is not up to date.  

You may wish to have a look at the following Docs and video: https://linkfree.eddiehub.io/docs/how-to-guides/editing

**Review by harshsingh32 — APPROVED** [review]

**Comment by SaraJaoude** [comment]
@harshsingh32 and @iamthecloverly thank you for reviewing the Pull Request.  However as there are conflicts these are not the final changes and your approvals will be dismissed by GitHub after these are resolved.  Plus these temporary approvals create more notifications and potentially confusion for the author.

**Review by SaraJaoude — CHANGES_REQUESTED** [review]
Please resolve conflicts (see my previous comment on how)

**Comment by SaraJaoude** [comment]
We look forward to seeing your Profile on LinkFree, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at the following Docs which will help with the suggested changes the maintainers have proposed:

Quickstart: https://linkfree.io/docs/quickstart

Editing your Profile: https://linkfree.io/docs/how-to-guides/editing

**Pull request closed without merging**
