### PR TITLE
data:NitishRawat123

### PR DESCRIPTION
**Pull request by NitishRawat123**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4969"></a>

### CODE REVIEW

**Comment by NitishRawat123** [comment]
Thanks for your lovely wishes!!

**Review by swagataroy30 — COMMENTED** [review]
Hey, thanks for your contribution. But you haven't added any links to your profile. You can refer to this docs - https://linkfree.eddiehub.io/docs/quickstart to add links. Thank You!

**Review by swagataroy30 — COMMENTED** [review]
You need to move your json file to the `data` folder. it should be `data/NitishRawat123.json`. Thank you!

**Review by iamthecloverly — APPROVED** [review]

**Review by devvsakib — APPROVED** [review]
LGTM, but there are so many things you can add, like social, links, milestone

**Review by priyankarpal — CHANGES_REQUESTED** [review]
hey @NitishRawat123, you mistakenly added your json file to the main folder. You have to change it to `data/NitishRawat123.json`


image

**Review by dev-rakeshshaw — COMMENTED** [review]
Add more info about yourself.
For help you can visit: https://linkfree.eddiehub.io/docs

**Review by mahfuztbt — APPROVED** [review]
It's looks good to me but you haven't add any links or milestone, you can view this [profile](https://github.com/EddieHubCommunity/LinkFree/blob/main/data/eddiejaoude.json) for an example

**Review by SurajPratap10 — APPROVED** [review]

**Comment by SaraJaoude** [comment]
@NitishRawat123 not having any links is not a blocker for merging.  I will merge your Pull Request now. 

When you are ready to add links you might want to check out the Edit guide in our Docs: https://linkfree.eddiehub.io/docs/how-to-guides/editing

**Comment by swagataroy30** [comment]
But @SaraJaoude the `json` file is not in the `data` folder .

**Comment by NitishRawat123** [comment]
Ok I will

**Comment by NitishRawat123** [comment]
Is their any other option

**Pull request merged**
