### PR TITLE
Description should be a textarea

### LINKED ISSUE #7970: Description should be a textarea
### Description

We can change make the description as a text area on both the Milestone and Events form pages instead of a text box. Please assign it to me and I can fix it.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sumitunique777**
## Fixes Issue 

closes #7970

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8060"></a>

### CODE REVIEW

**Comment by SaraJaoude** [comment]
@sumitunique777 please add to the description the issue number this PR relates to

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you 👍  But line breaks are not displayed correctly - it looks like they are ignored

Screenshot 2023-07-10 at 09 31 30

**Review by Sagargupta16 — APPROVED** [review]

**Comment by ChinmayMhatre** [comment]
@Sagargupta16 Please do not approve changes without verifying, You can see changes suggested in the conversation. This can be confusing to the contributor.

**Comment by Sagargupta16** [comment]
> @Sagargupta16 Please do not approve changes without verifying, You can see changes suggested in the conversation. This can be confusing to the contributor.

I'll keep than in mind @ChinmayMhatre .. sorry for it!!!

**Comment by sumitunique777** [comment]
image

The result should look like this. Please check the attached snapshot for reference.

**Comment by eddiejaoude** [comment]
> image
> 
> The result should look like this? Please check the attached snapshot for reference.

Yes the line break should be represented in the output

**Comment by eddiejaoude** [comment]
Close PR as a newer PR has been created https://github.com/EddieHubCommunity/LinkFree/pull/8218

**Pull request closed without merging**
