### PR TITLE
data: JyothiKumar03

### PR DESCRIPTION
**Pull request by JyothiKumar03**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers
requested the pr with the json file which contains links of different platforms. Kindly accept the pr!!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2504"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
The name of the file does not match your GitHub username

**Comment by JyothiKumar03** [comment]
Hey EddieHubCommunity/LinkFree
Thanks for pointing that out, I will change it. I committed the file
instead of creating the branch by mistake. Kindly sort the issue. Sorry for
the trouble!
Thank You

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍 Thank you for updating the filename

**Comment by JyothiKumar03** [comment]
Thanks for the merge Eddie!! I look forward to actively participate towards
open source community!!

**Pull request merged**
