### PR TITLE
data:sooraj-s

### PR DESCRIPTION
**Pull request by Sooraj-s-98**
Sooraj S profile added

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6105"></a>

### CODE REVIEW

**Review by Ananya2001-an — CHANGES_REQUESTED** [review]
You need to rename your file to `data/Sooraj-s-98.json` since the filename should be same as your github username.

**Comment by Ananya2001-an** [comment]
I am talking about the filename, not the name in your json profile. You have named it as `SoorajS.json` in data folder but it should be your github username instead.

**Review by Ananya2001-an — APPROVED** [review]
Thanks for making the changes 👍🏼 Looks good!

**Review by imbeshat — APPROVED** [review]

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
