### PR TITLE
Fix: User milestones descending

### LINKED ISSUE #5945: [FEATURE] order milestones descending
Please only make changes after PR https://github.com/EddieHubCommunity/LinkFree/pull/5765 has been merged (or branch from this PR to make the changes)

### Description

I'd order the milestones in descending order (as suggested in Twitter DM chat with @eddiejaoude on April 8, 2023.

note: Sort by date desc

### Screenshots

milestones_linkfree

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sanskar1306**
## Fixes Issue
Fixes #5945 

## Changes proposed
Milestones order set to descending

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

milestones_descending

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6085"></a>

### CODE REVIEW

**Comment by lokesh3097** [comment]
Hi @sanskar1306! Not blocking the PR but according to the last conversation I had with @eddiejaoude on Discord, there isn't any restricted format for the user while they enter the dates for their milestones into the JSON file. So, we might encounter a few invalid dates (For JavaScript Date Object) sometimes.

**Comment by pratham-yuxo** [comment]
> Hi @sanskar1306! Not blocking the PR but according to the last conversation I had with @eddiejaoude on Discord, there isn't any restricted format for the user while they enter the dates for their milestones into the JSON file. So, we might encounter a few invalid dates (For JavaScript Date Object) sometimes.

Then we should make a format to enter date.

**Comment by sanskar1306** [comment]
> > Hi @sanskar1306! Not blocking the PR but according to the last conversation I had with @eddiejaoude on Discord, there isn't any restricted format for the user while they enter the dates for their milestones into the JSON file. So, we might encounter a few invalid dates (For JavaScript Date Object) sometimes.
> 
> Then we should make a format to enter date.

Yes there should be a pre-defined format.

**Comment by eddiejaoude** [comment]
I think the docs specify the format, but we don't valid it, this will change when we more to forms

What is the worst case if there is an invalid date? Does it just add it to the beginning or end? or does it break?

We should maybe wrap it in a try/catch, so worst case the data is not sorted and remains the same

**Comment by amandamartin-dev** [comment]
All, it has been 3 weeks with no additional movement on this PR since my last comment.  I am going to close this PR for now and unassign the issue so that someone else may take a look.  Thank you for your time on this so far!

**Comment by zaidahmad25** [comment]
Hi, I would like to work on this issue.

If I am correct, all I have to do is add a try/catch to the code in the pull request made by @ Sanskar?

**Pull request closed without merging**
