### PR TITLE
Separated the events files to make them work

### PR DESCRIPTION
**Pull request by ibilalkayy**
## Changes proposed

Previously the events were not showing up on my LinkFree page. Now I made separate files for each of the events and I hope they will work fine.

I deleted this file **2022-10-24-kubecon.json** and created the following two files. 👇

- 2023-04-18-kubecon-cloudnativecon-europe-2023.json
- 2022-10-24-kubecon-cloudnativecon-north-america-2022.json

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6288"></a>

### CODE REVIEW

**Comment by loftwah** [comment]
Cheers for that. I haven't checked the JSON but assuming it is what we spoke about this should be okay.

**Comment by ibilalkayy** [comment]
I have deleted this file **"2022-10-24-kubecon.json"** and created two more files but now it is asking me to resolve the merge conflicts but the resolve conflicts button is not showing up. Maybe I don't have the write access. It is not clear to me.

**Review by SaraJaoude — APPROVED** [review]
looks good

**Comment by loftwah** [comment]
Works great cheers.

**Pull request merged**
