### PR TITLE
data: sindhuinti

### PR DESCRIPTION
**Pull request by Sindhuinti**
## Check List (Check all the applicable boxes) 

- [✅ ] My code follows the code style of this project.
- [✅ ] My change requires changes to the documentation.
- [ ✅] I have updated the documentation accordingly.
- [ ✅] All new and existing tests passed.
- [ ✅] This PR does not contain plagiarized content.
- [✅ ] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3903"></a>

### CODE REVIEW

**Review by Tejender1521 — DISMISSED** [review]
Everything looks good to me

**Review by SaraJaoude — DISMISSED** [review]
looks good

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
The name of your file needs to match your GitHub name exactly, so please change sindhuinti to Sindhuinti

**Comment by Sindhuinti** [comment]
@EmmaDawsonDev modified the name of this file 👍🏻

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good, Thanks! 👍

**Pull request merged**
