### PR TITLE
data: AyushSarode.json

### PR DESCRIPTION
**Pull request by AyushSarode**
Created AyushSarode.json file with personal Data
Thank you!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2715"></a>

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

Please fix your JSON profile naming. It should be `AyushSarode07.json` and it is case-sensitive.

If you need any help feel free to ask.

**Comment by AyushSarode** [comment]
I think it's fine now.

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey, 
The file name is still now fixed. Please see above comments

**Comment by eddiejaoude** [comment]
@AyushSarode did you mean to close the PR? If you need any help let us know

**Comment by AyushSarode** [comment]
> @AyushSarode did you mean to close the PR? If you need any help let us know

I made mistake in this PR so I made new one, good that you closed this one,
The other one got merged!!
Thank you @eddiejaoude

**Comment by AyushSarode** [comment]
This one is mine data/AyushSarode.json

**Pull request closed without merging**
