### PR TITLE
Removes unnecessary scrollbars from homepage

### LINKED ISSUE #1415: Unnecessary scroll bars on the home page
### Description

The homepage of LinkFree has an unnecessary vertical scroll bar even though there is on content below it. And on a smaller width screen, there is an unnecessary horizontal scroll bar because of the image overflowing.

This does not have a good impact on the user experience.

### Screenshots

Vertical scrollbar:
image

Horizontal scrollbar:
image

Both at same time:
image

### Additional information

I am up for solving this issue.

### PR DESCRIPTION
**Pull request by Dharmik48**
## Fixes Issue

Closes #1415 

## Changes proposed

Removes those unwanted scrollbars from the homepage for LinkFree. Both horizontal and vertical scrollbars.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Vertical scroll bar removed:
vertical scroll bar removed screenshot

Horizontal scroll bar removed:
horizontal scroll bar removed screenshot

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1421"></a>

### CODE REVIEW

**Comment by Dharmik48** [comment]
Can someone please review this pull request?

**Review by emmalearnscode — APPROVED** [review]
Looks good to me 👍 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by kumarsonsoff3 — APPROVED** [review]

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Hey there, we apologize for the delays in merging, but here **merge conflicts** arises due to your another PR **#1457** merged before this! 

Could you please resolve the merge conflicts **[here](https://github.com/EddieHubCommunity/LinkFree/pull/1421/conflicts)?** Let us know if you need any help with that! You can also check the **[GitHub Docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)** to have an idea of how to do it. 🙂

__
🛠️ **Summary:** This code needs a fix  |  Tags: Not maintainable

**Comment by Dharmik48** [comment]
I resolved the conflicts! Hope it's better now😄

**Review by kumarsonsoff3 — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your valuable contribution, Dharmik 🎉.

**Comment by Dharmik48** [comment]
It was my pleasure to contribute 😄

**Pull request merged**
