### PR TITLE
data: sunilsinghrana

### PR DESCRIPTION
**Pull request by sunilsinghrana**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6289"></a>

### CODE REVIEW

**Review by harshsingh32 — CHANGES_REQUESTED** [review]
Hi, thank you for contributing.
Please rename your file and add .json at the end.
Your filename will look like data:sunilsinghrana.json

**Comment by Sindhuinti** [comment]
> Hi, thank you for contributing. Please rename your file and add .json at the end. Your filename will look like data:sunilsinghrana.json

I think no modification needed. Everything is fine

**Comment by sandramsc** [comment]
Hi @harshsingh32 ,

- the file looks good from my end
- if **sunilsinghrana.json** is a new file it will not appear in **EddieHubCommunity/LinkFree/data**

**Comment by sandramsc** [comment]
> Hi, thank you for contributing. Please rename your file and add .json at the end. Your filename will look like data:sunilsinghrana.json

Hi @harshsingh32 ,

the file looks good from my end
if sunilsinghrana.json is a new file it will not appear in EddieHubCommunity/LinkFree/data

**Comment by shyamtawli** [comment]
@harshsingh32 No changes required, filename, path and JSON all are correct.

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
