### PR TITLE
data:nithin999989

### PR DESCRIPTION
**Pull request by nithin999989**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6146"></a>

### CODE REVIEW

**Review by NiazMorshed2007 — APPROVED** [review]

**Comment by kumarsonsoff3** [comment]
You'd merge conflicts here. Please resolve! These generally occur due to an outdated branch. 

You might want to look at these docs: https://linkfree.io/docs/how-to-guides/editing

**Review by himanshu1221 — APPROVED** [review]
Awesome **LGTM:+1:**
Welcome to Linkfree @nithin999989 :tada:

**Review by sidharthviz — APPROVED** [review]

**Review by harshsingh32 — APPROVED** [review]

**Review by Sindhuinti — APPROVED** [review]
Looks good 🎉

**Comment by kumarsonsoff3** [comment]
Hey @harshsingh32, @sidharthviz, @himanshu1221, @Sindhuinti. 

Please avoid approving a PR with unresolved conversations & requested changes, it creates confusion among the contributor that the changes have been approved & need not to make the previously requested changes. 

@nithin999989, let us know if you need any help in resolving conflicts. These docs might help you with that: https://linkfree.eddiehub.io/docs/how-to-guides/editing

**Comment by himanshu1221** [comment]
> Hey @harshsingh32, @sidharthviz, @himanshu1221, @Sindhuinti. 
> 
> Please avoid approving a PR with unresolved conversations & requested changes, it creates confusion among the contributor that the changes have been approved & need not to make the previously requested changes. 
> 
> @nithin999989, let us know if you need any help in resolving conflicts. These docs might help you with that: https://linkfree.eddiehub.io/docs/how-to-guides/editing

Sore for making chaos
Will surely keep in mind!

**Comment by SaraJaoude** [comment]
We look forward to seeing your Profile on LinkFree, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at the following Docs which will help with the suggested changes the maintainers have proposed:

Quickstart: https://linkfree.io/docs/quickstart

Editing your Profile: https://linkfree.io/docs/how-to-guides/editing

**Pull request closed without merging**
