### PR TITLE
Remove reviewpad action

### PR DESCRIPTION
**Pull request by dan-mba**
## Changes proposed
The reviewpad action no longer exists.
This PR removes the reviewpad action

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8251"></a>

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
We can also delete the config file for Reviewpad, as it is used by the Action, and it will get removed with this PR.
https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/config/reviewpad.yml

**Comment by dan-mba** [comment]
> We can also delete the config file for Reviewpad, as it is used by the Action, and it will get removed with this PR. https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/config/reviewpad.yml

Do we know if the reviewpad app uses config files? I was leaving it here in case we started using the app.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge.

**Comment by eddiejaoude** [comment]
Thank you 👍

**Pull request merged**
