### PR TITLE
docs(governance): use fallback coc

### PR DESCRIPTION
**Pull request by krishguptadev**
needs https://github.com/EddieHubCommunity/.github/pull/20

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/716"></a>

### CODE REVIEW

**Review by Vyvy-vi — CHANGES_REQUESTED** [review]
I'm not sure if we want to delete this coc
🤔

**Comment by Panquesito7** [comment]
> needs [EddieHubCommunity/.github#20](https://github.com/EddieHubCommunity/.github/pull/20)
> 
> [](https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/716)

I had a PR that did that in that repository. Please look for other PRs before making another one.

**Review by Panquesito7 — COMMENTED** [review]
I think we can keep it as-is as Vyom said. Let's see what the other maintainers think, though.

**Comment by krishguptadev** [comment]
Closed in favor of updating the COCs in all repos rather than deleting them.

**Pull request closed without merging**
