### PR TITLE
Nav bar fix

### LINKED ISSUE #4120: Navbar width gets reduced when viewing docs in smaller screen
### Description

When viewing docs, the navbar width decreases as the screen size gets smaller, It should take up the full width of the screen.

### Screenshots

linkfree_docs_nav_issue

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SyedImam1998**
## Fixes Issue

closes #4120 

## Changes proposed

Last time changes that I proposed was confusing. But as per the suggestion i received from the @eddiejaoude i.e to use mdx custom elements here [link](https://nextjs.org/docs/advanced-features/using-mdx#custom-elements) So I have done it now content that is coming from the mdx files can be styled in our own.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### Before:
image

### After
ezgif com-gif-maker

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4448"></a>

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
LGTM 👍🏻

**Comment by SyedImam1998** [comment]
> LGTM 👍🏻

Thanks for the Feedback Mate. I really Appreciate that. 🤗

**Comment by swagataroy30** [comment]
Hey it works great now with the minimal changes :smile: :+1:

**Comment by SyedImam1998** [comment]
> Hey it works great now with the minimal changes 😄 👍

Thanks for the Feedback Mate. I really Appreciate that. 😘🥰

Let's throw this Bug out of the universe.
giphy (1)

**Comment by swagataroy30** [comment]
Hehe :sweat_smile: really appreciate your work and passion. :+1:

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
This works really well, thank you 👍

**Pull request merged**
