### PR TITLE
Make surname capital for aayush89890.json

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
## Fixes Issue
In the profiles list, everyone's surname is in caps, only for Aayush, it isn't so it looks a little weird, according to me.

## Changes proposed
Make surname upper-case

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1107"></a>

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@aayush89890 Please confirm if this is ok with you.... Thanks

**Review by Panquesito7 — APPROVED** [review]

**Review by emmalearnscode — COMMENTED** [review]
I don’t think we should go messing with other people’s profiles. We try not to be too picky about grammar because as a new contributor it’s hard enough to learn how to fork, clone, push, pull etc. Feel free to contact the original contributor to see if they want to update it but I am not happy about profiles being updated by someone other than the owner unless there is explicit agreement.

**Review by vikasganiga05 — APPROVED** [review]
LGTM :+1: 
Let's see what @aayush89890 thoughts on this change :thinking:

**Comment by aayush89890** [comment]
LGTM thanks for updating @KendallDoesCoding

**Review by krshdev — COMMENTED** [review]
I agree with emma

**Comment by nhcarrigan** [comment]
Yeah, I'm going to close this.

People are welcome to style their profiles however they prefer. We shouldn't be modifying other folks' information.

**Comment by nhcarrigan** [comment]
Ah hold on, just saw that the profile author agreed to this in the comments.

**Comment by KendallDoesCoding** [comment]
> I don’t think we should go messing with other people’s profiles. We try not to be too picky about grammar because as a new contributor it’s hard enough to learn how to fork, clone, push, pull etc. Feel free to contact the original contributor to see if they want to update it but I am not happy about profiles being updated by someone other than the owner unless there is explicit agreement.

Yup completely understand that, that's why I said 
> @aayush89890 Please confirm if this is ok with you.... Thanks

If he wasn't ok with it, I would've closed the issue. Just in my personal opinion, it looked a little weird, that only his surname was in lowercase and the other peoples were in uppercase. But, I understand that most of the contributors are new coders, and do find it hard to do the following, like you mentioned.

**Comment by KendallDoesCoding** [comment]
@bhargav794 your profile's surname is lowercase too. I'm not gonna make a PR as per what Emma said about this, but if you think its a good idea to make your surname capital for formatting purposes, please make a PR. Thanks

**Pull request merged**
