### PR TITLE
added hover effects to the card

### PR DESCRIPTION
**Pull request by whitedevil-glitch**
Added shadows hover effects (mainly scaling up the cards), removed the hover border color, and made the profile username font a bit light and color black

## Changes proposed

added shadows,
added hover effect,
changed profile username text on the card to light and black

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

image

It's a hover effect so moving the cursor pointer on it will show you the changes, although you may see the change I made in the profile username text

## Note to reviewers
Made these changes to make the UI better than before.

The suggestion is to remove the orange box containing profile view numbers which are on the top right of the profile picture. Instead what you can do is:
suggestion

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3893"></a>

### CODE REVIEW

**Comment by whitedevil-glitch** [comment]
here's the video, if needed we can add colors to hover transition or more shadow-drops 

https://user-images.githubusercontent.com/73755149/214341944-769c6bd5-b74e-4c30-ab1f-49981f595303.mp4

**Review by ManishBisht777 — COMMENTED** [review]
The original one looks good it me as there is a clear separation between cards also the UserName is of different color so it stood out from the rest of the information.

The views on the bottom would be a little problematic as it is giving less space for the description of the profile

**Comment by whitedevil-glitch** [comment]
so, we can increase the font weight for UserName instead of using ''text-bold''... which will make the heading separate from the description down below and the orange color can be lighter for eg. #F0A500 or RGB(240, 165, 0)
Is the hover transition fine?

**Comment by whitedevil-glitch** [comment]
that less space for description can be solved by adding an anchor tag of *more...* If a user wants to read the remaining part of the description he can click on the *more* hyperlink which will redirect to the profile link of the user. In this way, the user will also get more views on his profile.

**Comment by stevenovak123** [comment]
I'd just wait and let Eddie or the maintainers make a call on this!. Thanks for the contribution <3

**Comment by whitedevil-glitch** [comment]
Okay! Cool

**Comment by eddiejaoude** [comment]
I think the orange border looks great also 👍  maybe try with the orange border and the new effects and see how it looks?

**Comment by whitedevil-glitch** [comment]
Oh! I made the change! I think it looks good. Here's the video:


https://user-images.githubusercontent.com/73755149/215020539-e48a64c7-c114-46ed-a4b0-fdc1d200d447.mp4

**Comment by ManishBisht777** [comment]
> @eddiejaoude Oh! I made the change! I think it looks good. Here's the video:
> 
>  Untitled.mp4 
> should I change the code? and it looks slow in the video(because of compression) but it's good when tested on website

looks good to me :)

**Review by stevenovak123 — APPROVED** [review]
lgtm

**Comment by whitedevil-glitch** [comment]
thank you!! when it will be merged? 😃

**Comment by stevenovak123** [comment]
Hey. One of the maintainers will look into it and take a decision

**Comment by whitedevil-glitch** [comment]
Okay, got it! 👍🏼

**Comment by whitedevil-glitch** [comment]
@eddiejaoude can you please check the changes and merge if it's looking good?

**Comment by stevenovak123** [comment]
Hey. Give it a few days before mentioning. A good period would be 7 days, post that you can reach out to the maintainers on the discord server

**Comment by whitedevil-glitch** [comment]
> Hey. Give it a few days before mentioning. A good period would be 7 days, post that you can reach out to the maintainers on the discord server

Oh okay, thanks for the info.

**Review by eddiejaoude — APPROVED** [review]
Looks good, great collaboration 👍

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
There is a falling GitHub Action for accessibility, please fix so we can merge?

**Comment by whitedevil-glitch** [comment]
@stevenovak123  I just committed a change to the profile username... the username will be underlined once hovered on it. what do you think about that?

**Comment by stevenovak123** [comment]
Imo it is a good addition, I'm just a person that helps maintainers review. Its the maintainers call if its a good addition to be merged into repo. So make the contribution and wait until a maintainer takes a decision

**Comment by whitedevil-glitch** [comment]
> There is a falling GitHub Action for accessibility, please fix so we can merge?

done. 👍🏼

**Comment by eddiejaoude** [comment]
Please can you add a screenshot of the latest changes

**Comment by whitedevil-glitch** [comment]
> Please can you add a screenshot of the latest changes

the latest change was the bold black username and underline transition when hovering

image

and hover effect can be seen in the video I sent earlier in the conversation :)

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍 

Next time please raise an issue first so it can be triaged by the maintainers before raising a pull request

**Pull request merged**
