### PR TITLE
Update Akshaykumar05.json

### PR DESCRIPTION
**Pull request by Akshaykumar05**
Updated my profile.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2983"></a>

### CODE REVIEW

**Comment by Aadarsh805** [comment]
@Akshaykumar05 the file you created has your username starting with a small case `a` while your username actually has a capital `A`, GitHub still works with but I'm not sure if it would work fine here too
It should but it'd be better to rename just in case

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
The changes look good 👍 

But as suggested please also rename the file to match your GitHub username exactly, as this may break features in the future

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good, Thanks! 👍

**Review by eddiejaoude — APPROVED** [review]

**Pull request merged**
