### PR TITLE
Closes #6101 Updated 'Search by Tags' Image

### LINKED ISSUE #6101: [OTHER]
### What would you like to share?

Search by Tags picture is too old. Can I change it?

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geeky-sambhav**
## Changes proposed

--> Updated the "Search by tags" image in the homepage with the image that matches the current UI

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Before:
before

After:
after

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6382"></a>

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by eddiejaoude** [comment]
please can you resolve conflicts, I think you just need to accept your changes - I can't seem to do it via the GitHub UI

**Comment by geeky-sambhav** [comment]
> conflicts, I think you just need to a

Actually its showing conflict on the issue that I have resolved.So Im looking for a way to solve this

**Comment by geeky-sambhav** [comment]
Just saw that the issue I was working on it already been resolved by someone🥲
image

**Comment by eddiejaoude** [comment]
Yes the other pull request chanted the image, it made an improvement as part of another issue, but your pull request is still valid because it has the new design - please resolve conflicts or create a new pull request and we will merge it

**Pull request closed without merging**
