### PR TITLE
data: VardaanAggarwal

### PR DESCRIPTION
**Pull request by VardaanAggarwal**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5267"></a>

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Review by SurajPratap10 — APPROVED** [review]
LGTM , Thanks! 🎉

**Review by schmelto — APPROVED** [review]

**Comment by VardaanAggarwal** [comment]
Hey, is there any reason for the delay in merging the PR?
Just want to confirm.

**Comment by Atharv181** [comment]
LGTM

**Pull request merged**
