### PR TITLE
test for navigation of popular profile.

### LINKED ISSUE #2085: [OTHER] Test for popular profile navigation  to profile page.
### What would you like to share?

add a test for popular profile so that when we click on the profile it opens the profile page.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jaynarayan-vaishnav**
## Fixes Issue
 Closes #2085 

## Changes proposed

- Added skeleton to navigate to profile page while clicking on the popular profile.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

test popular

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2090"></a>

### CODE REVIEW

**Comment by jaynarayan-vaishnav** [comment]
Ready for review Thanks for letting me contribute to this repo 😌

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
This test needs to go in the `popular.spec.js` file not `search` test file

**Comment by jaynarayan-vaishnav** [comment]
ohkay thanks for the help i will do the changes now 😅

**Comment by jaynarayan-vaishnav** [comment]
is it okay now @eddiejaoude ??

**Review by eddiejaoude — APPROVED** [review]
LGTM 👍

**Pull request merged**
