### PR TITLE
data: AamirxShaikh

### PR DESCRIPTION
**Pull request by aamirxshaikh**
## Changes proposed

Create AamirxShaikh.json file

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2717"></a>

### CODE REVIEW

**Review by krupalitrivedi — APPROVED** [review]
Looks good to me!

Thank you for contributing! The journey seems awesome!

**Comment by aamirxshaikh** [comment]
> Looks good to me!
> 
> Thank you for contributing! The journey seems awesome!

Thanks @krupalitrivedi

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

Please change your file name and GitHub URL according to your GitHub username (The app may be case-sensitive).

 It should be 
 - `data/aamirxShaikh.json`
 - `https://github.com/aamirxShaikh`

**Review by Pradumnasaraf — COMMENTED** [review]
Yes, 100%, GitHub usernames are case in-sensitive, but there are functionalities in the app that can be sensitive. Also, for sanity and uniformness we keep it this way. So, please do the changes suggested

Thank you for understanding.

**Review by Pradumnasaraf — DISMISSED** [review]

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
The filename should probably be `aamirxshaikh.json` as the GitHub username is all in lower-case.

**Comment by aamirxshaikh** [comment]
> The filename should probably be `aamirxshaikh.json` as the GitHub username is all in lower-case.
> 
> 

Sure. I'll make the changes and update the pr.

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good to me! 👍

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by Pradumnasaraf — APPROVED** [review]

**Pull request merged**
