### PR TITLE
data:DiggajUpadhyay

### PR DESCRIPTION
**Pull request by diggajupadhyay**
DiggajUpadhyay-patch-1

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6149"></a>

### CODE REVIEW

**Review by Sindhuinti — CHANGES_REQUESTED** [review]
Please change your filename to your github username. also move it to data folder
`data/diggajupadhyay.json`

**Review by himanshu1221 — CHANGES_REQUESTED** [review]
1) Please move your JSON file to `/data` folder
2) Rename your file to your `GitHub username`

**Comment by SaraJaoude** [comment]
> * Please move your JSON file to `/data` folder
> * Rename your file to your `GitHub username`

@himanshu1221 thank you for reviewing, but this has already been mentioned just in the comment above.  In future, please read through historic comments on a Pull Request, to avoid duplication, more work for maintainers and confusion for the author

**Comment by himanshu1221** [comment]
> > * Please move your JSON file to `/data` folder
> > * Rename your file to your `GitHub username`
> 
> @himanshu1221 thank you for reviewing, but this has already been mentioned just in the comment above.  In future, please read through historic comments on a Pull Request, to avoid duplication, more work for maintainers and confusion for the author

Sure sorry for creating confusion @SaraJaoude i just forgot to read the previous comments I'll keep it in my mind

**Comment by SaraJaoude** [comment]
Given the length of time this PR has been open, I will merge and fix in a temporary branch.

**Pull request merged**
