### PR TITLE
LinkFree Adding my profile

### PR DESCRIPTION
**Pull request by HarshDeep61034**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2938"></a>

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
Hey @HarshDeep61034 , I noticed you made some changes in the readme too. When you want to suggest any change in the project. You could create an issue so the maintainers can see it then you could create a separate PR for the changes. Since you want to just add you profile I suggest just committing your json file in this PR. Thanks!

**Comment by ChinmayMhatre** [comment]
Hey @HarshDeep61034 , I noticed you made some changes in the readme too. When you want to suggest any change in the project. You could create an issue so the maintainers can see it then you could create a separate PR for the changes. Since you want to just add you profile I suggest just committing your json file in this PR. Thanks!

**Comment by HarshDeep61034** [comment]
my bad @ChinmayMhatre thanks for the guidance

**Comment by HarshDeep61034** [comment]
Can you tell me what can i do to fix this, im not even able to remove older commits from this PR

**Comment by ChinmayMhatre** [comment]
Hey @HarshDeep61034 , I am not completely sure but I think you can do `git checkout main ---README.md` to return the readme file to its previous state

**Comment by ChinmayMhatre** [comment]
Hey @eddiejaoude , Could you help out here on how to remove the file from the PR?

**Comment by HarshDeep61034** [comment]
@ChinmayMhatre can i close the PR and start from scratch?

**Comment by HarshDeep61034** [comment]
i think i should clos this one and start another its really confusing

**Comment by HarshDeep61034** [comment]
I think i should close this one and start another

**Comment by eddiejaoude** [comment]
Here are the docs for getting started
https://linkfree.eddiehub.io/docs/quickstart

Any questions please ask in the EddieHub Discord 
http://discord.eddiehub.org

**Comment by HarshDeep61034** [comment]
@eddiejaoude  thanks i made another PR for Adding my profile, following the docs

**Pull request closed without merging**
