### PR TITLE
fix speaker details should be hidden in mobile

### PR DESCRIPTION
**Pull request by Shaikh-Danish**
fix speaker details should be hidden in mobile

Before:
linkfree

After:
linkfreefix

closes: #5869

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5962"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for your pull request. It looks like your fork is not up to date, so you have conflicts.

Please could resolve the conflicts. Any questions you can ask in the `help` channel in EddieHub Discord

**Comment by eddiejaoude** [comment]
@Shaikh-Danish did you mean to close your PR? You can add add more commits to your fork/branch and GitHub will add it to the PR automatically

**Comment by Shaikh-Danish** [comment]
I tried to sync fork with the repo and the PR got closed

**Comment by eddiejaoude** [comment]
Strange, not heard of that before. You can create a new PR if easier

**Pull request closed without merging**
