### PR TITLE
Added my profile Json file

### PR DESCRIPTION
**Pull request by umaresso**
Package file is deleted now 😅

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1101"></a>

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
> Package file is deleted now 😅
> 
> [](https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1101)

image

**Comment by umaresso** [comment]
bro , have i committed the mistake again?

**Comment by KendallDoesCoding** [comment]
> bro , have i committed the mistake again?

Yes, the issue is you made all the mistakes in your main branch, I suggest you delete your fork, make a new fork, make a new branch in the fork called umaresso-profile or patch-1 and do the required edits.

**Comment by umaresso** [comment]
okey ! Let me do that

**Pull request closed without merging**
