### PR TITLE
data: AtharvaRaut

### PR DESCRIPTION
**Pull request by AtharvaRaut2002**

### CODE REVIEW

**Review by accodes21 — COMMENTED** [review]
Everything is great only change your filename to your github username i.e. ```AtharvaRaut2002.json```

**Review by sidharthviz — CHANGES_REQUESTED** [review]
Hi @AtharvaRaut2002  Please remove the comma from line no. 42 and 49 
Use this for better reference :-   <https://jsonlint.com/>

**Review by sidharthviz — APPROVED** [review]
🎉

**Review by himanshu1221 — APPROVED** [review]
LGTM :+1:

**Comment by eddiejaoude** [comment]
Great collaboration 🎉

**Comment by AtharvaRaut2002** [comment]
Thank You so much @himanshu1221 and @eddiejaoude for approving my changes 🙏.

**Pull request merged**
