### PR TITLE
Fix: Memoize user profile for performance improvement

### LINKED ISSUE #5003: Tab switching on a user's page is causing the user details section to flicker
### Description

When we're switching between Milestones and My Links tabs, the user details flickers. I believe this is due to the whole component re-rendering on tab switch. 

I think a fix would be to prevent the whole [username.js] page from re-rendering.

### Screenshots

https://user-images.githubusercontent.com/27160715/220416770-756d8b8d-8629-44f5-b46a-e06ab4dfd777.mov

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by psavan1655**
## Fixes Issue
Closes #5003 

## Changes proposed
- Navigating to different tabs ("My Links", "Milestones", .... ) in user profile. Top hero section of user  flickers. 
- Cause: As navigating to different tabs cause re-rendering of userProfile component.
- Solution: Memoize userProfile component, as user data doesn't change on a simple tab change. So no need to re-render component on every change.

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
https://www.loom.com/share/c0b4d8c001734d86931668b43d53e51f

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5158"></a>

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by FrozenHearth** [comment]
Hi @psavan1655
One edge case got missed. When clicking on the sort icon in the My Links tab in the profile page, the flickering still happens.

**Comment by psavan1655** [comment]
Hi @FrozenHearth, Thanks for pointing out, WIll surely take a look into it.

@eddiejaoude Should i work on it? I have reproduced the issue and verified it.

**Comment by eddiejaoude** [comment]
Sure, but please also raise an issue (bug)

**Comment by psavan1655** [comment]
#5535 Created this issue. You can assign me there.

**Pull request merged**
