### PR TITLE
Moves menubar in header

### LINKED ISSUE #1437: Move the menu bar out of main and into a header component
### Description

At the moment the menu bar is inside the main element on the homepage and search page but on the profile page it is sitting outside of the main element. 

All 3 should ideally be moved out of the main element and into a header element that sits above the main element.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Dharmik48**
## Fixes Issue

Closes #1437 

## Changes proposed

Moves the menu bar in all three pages (home, search and profile) outside the main element and into the header element.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Home page:
homepage code

Search page:
search page code

Profile page:
profile page code

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1457"></a>

### CODE REVIEW

**Review by emmalearnscode — APPROVED** [review]
Looks good! thanks for your contribution 👍 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by emmalearnscode** [comment]
Oh, there appears to be a merge conflict in the Home component. If you could fix that then this should be good to merge.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Dharmik48** [comment]
I will get fixing!

**Comment by Dharmik48** [comment]
I have resolved the conflicts! It should be good to merge it now👍🏻

**Review by eddiejaoude — APPROVED** [review]
LGTM 👍

**Pull request merged**
