### PR TITLE
Changed PowerOff icon to FaSuperpowers icon

### PR DESCRIPTION
**Pull request by SandipPalit**
## Changes proposed

The PowerOff icon beside **Powered by Eddiefub** looks a bit odd as it resembles the shutdown icon.

image

A better alternative would be to use the FaSuperpowers icon, which will bring a positive perspective.

image

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3474"></a>

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3782"></a>

### CODE REVIEW

**Comment by stevenovak123** [comment]
The icon looks pretty good to me. @eddiejaoude what do you think about this.

**Comment by stevenovak123** [comment]
This looks good to me. I'd still wait for Eddie and maintainers to take a decision on this

**Comment by SandipPalit** [comment]
Thank You so much @stevenovak123 for your feedback ☺

**Comment by rohinish404** [comment]
@SandipPalit The new icon looks fine but i think the previous one was also good. Like the first thing that comes to mind on seeing the shut down button is power so it was depicting the text beside it. Can u explain why it was looking odd?

**Comment by SandipPalit** [comment]
Hi @rohinish404 , Thank You for your feedback. I agree that the previous icon was also good, but generally, we shut down at the end of something, like we shut down our PC after completing our tasks. The new icon will bring more positive perspective to it.

**Comment by amandamartin-dev** [comment]
Is there an open issue for this item? Can you please link it in the PR?

**Comment by eddiejaoude** [comment]
Not sure that the new icon is any clearer? What about a rock `FaRocket` or something?

**Comment by SandipPalit** [comment]
Thanks @eddiejaoude for your feedback. Can I change it to **FaRocket** ?

**Comment by eddiejaoude** [comment]
Sure 👍

**Comment by SandipPalit** [comment]
Done the changes. ☺

**Review by amandamartin-dev — APPROVED** [review]

**Pull request merged**
