### PR TITLE
Share Profile Icon Fix

### LINKED ISSUE #1596: [FEATURE] Share profile icon need hover effect
### Description

Share profile icon don't give the feel of a clickable item. It needs some kind of hover effect like increasing its size.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Amyx000**
## Fixes Issue 
closes #1596

## Changes Made

1. Added FiShare2 icon in Geticon.js file.
2. Replace the SVG path icon with an icon from the React-icon pack in the ShareProfile.js file.
3. Added CSS to the icon in the Profile.css file, like the slight greyish colour to the icon and on Hover increasing the size of the icon which gives it the feel of a clickable icon.
4. Added a div and class to the ShareProfile component in the Profile.js file.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

linkfree

## Note to reviewers

Hey! this is my very first pull request, let me know if I need to make any changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1597"></a>

### CODE REVIEW

**Comment by Amyx000** [comment]
Dear maintainers, do check my PR, added a hover effect to the share profile icon.

**Comment by Amyx000** [comment]
@eddiejaoude pls do review my PR

**Review by kumarsonsoff3 — COMMENTED** [review]
Looks Good to me! 👍

**Review by eddiejaoude — APPROVED** [review]
Sorry for the delay! Looks good to me 👍

**Pull request merged**
