### PR TITLE
chore: add aviralsharma07

### PR DESCRIPTION
**Pull request by aviralsharma07**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1748"></a>

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
Looks good!

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please add `.json` at the end of your filename.
It seems your file is missing the JSON format.

Let us know if you need any help! 🙂


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

**Comment by aviralsharma07** [comment]
Thanks, @Panquesito7 and @Pradumnasaraf  for your Help !!

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thanks! 🎉


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Pull request merged**
