### PR TITLE
Updated vishrut19.json file

### PR DESCRIPTION
**Pull request by Vishrut19**

### CODE REVIEW

**Comment by Vishrut19** [comment]
How to fix this review pad thing? Can someone please explain me? @EddieHubCommunity/ambassadors

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Please revert the changes to the package-lock file, then this looks good to merge.

**Comment by EmmaDawsonDev** [comment]
> How to fix this reviewpad issue? Can someone please explain me? @EddieHubCommunity/ambassadors

What issues are you seeing?

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Still it's showing some changes in `package-lock.json` file. Do you need any help in reverting the changes from `lock` file!?

**Comment by Vishrut19** [comment]
> Still it's showing some changes in `package-lock.json` file. Do you need any help in reverting the changes from `lock` file!?

Yes! If you can help then that would be great

**Comment by Vishrut19** [comment]
I will create a new one!

**Comment by kumarsonsoff3** [comment]
No need to close the PR, you just need to remove the `empty endline` from the `package-lock.json`, then it should be good to go. 

You can add more commits to this one to revert the changes!

**Pull request closed without merging**
