### PR TITLE
Add slide animations to links

### LINKED ISSUE #1455: [FEATURE] Add revealing animations to links
### Description

We can add some animations to links when we open a profile. It will enhance the look of the page.

> react-awesome-reveal is a npm package which provides one line code to add animations.

### Screenshots

Slide animation

### Additional information

[Link to package](https://www.npmjs.com/package/react-awesome-reveal).

I would like to work on it.

### PR DESCRIPTION
**Pull request by Aayushd18**
## Fixes Issue #1455 

 Closes #1455  

## Changes proposed

- Add sliding animations to links when a profile is opened

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Slide animation

## Note to reviewers

[Link to package](https://www.npmjs.com/package/react-awesome-reveal).

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1498"></a>

### CODE REVIEW

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Please separate your profile into a separate pull request.

Also, if we are going to have animations then we also need to add a media query for those that don't wish to have animations for health reasons so please add a prefers-reduced-motion: reduce media query that turns animation off.

**Comment by schmelto** [comment]
Kind of strange is, that there is a scrollbar at the bottom when the animation is started.

**Comment by Aayushd18** [comment]
> 

Hi, yeah I just noticed that, I am using a library for the animation, and this is happening for just one kind of animation, I also did not understand but will try to fix it.

**Review by Aayushd18 — COMMENTED** [review]
Hi, I have now added the media query for reduced motion

**Comment by eddiejaoude** [comment]
@Aayushd18 we are creating a version 2 of LinkFree with NextJS, you might want to move the changes to that branch `nextjs` instead so they are not lost. 

In v2 we are using TtailwindCSS, I think you could achieve this without the need for the extra library.

Let us know what you think

**Comment by Aayushd18** [comment]
> @Aayushd18 we are creating a version 2 of LinkFree with NextJS, you might want to move the changes to that branch `nextjs` instead so they are not lost.
> 
> In v2 we are using TtailwindCSS, I think you could achieve this without the need for the extra library.
> 
> Let us know what you think

Hi Eddie, yeah for sure I can try using tailwind and move the changes to nextjs branch as well.

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by eddiejaoude** [comment]
Thanks @Aayushd18, I will close this PR, as we are merging the `nextjs` branch to `main` today

**Comment by Aayushd18** [comment]
Yes @eddiejaoude you can close this now as I was not able to do this, was busy with some other things. I will surely try to contribute more in this project in future.

**Comment by eddiejaoude** [comment]
Great, look forward to your future contributions! Thanks @Aayushd18

**Pull request closed without merging**
