### PR TITLE
feat: order milestones descending (5945)

### LINKED ISSUE #5945: [FEATURE] order milestones descending
Please only make changes after PR https://github.com/EddieHubCommunity/LinkFree/pull/5765 has been merged (or branch from this PR to make the changes)

### Description

I'd order the milestones in descending order (as suggested in Twitter DM chat with @eddiejaoude on April 8, 2023.

note: Sort by date desc

### Screenshots

milestones_linkfree

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AJcodes42**
## Fixes Issue

Closes #5945 

## Changes proposed

1) Used javascript sort method to sort milestones based on date
2) Valid dates will be sorted in descending order
3) While comparing invalid date with invalid date or comparing invalid date with valid date, both the values will be considered equal and hence order will not be changed.
4) Let me know if we require to add invalid dates in the beginning or at end. It can be easily done but most of the profiles are already having them in order and few profiles are using combination of both valid/invalid dates and if we make invalid dates at beginning/end then it will change the order provided by user.
5) try catch is not required as it will not throw exception instead it will treat it as NaN and will work as mentioned in point no. 3

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Before ordering:
Screenshot 2023-05-21 at 5 09 32 PM
Screenshot 2023-05-21 at 5 10 05 PM

After ordering:
Screenshot 2023-05-21 at 5 10 49 PM
Screenshot 2023-05-21 at 5 10 39 PM

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7076"></a>

### CODE REVIEW

**Comment by lokesh3097** [comment]
Heyy @AJcodes42!! Can you provide any references for your point 3 if you have found that from any documentation or any other articles? Or did you find it by trial and error?

PS: Asking to improve my knowledge on error in JS.

**Comment by AJcodes42** [comment]
Hi @lokesh3097, Below given article tells invalid date will return as NaN.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
and hence the sort method will also return NaN if any of the two dates being compared is invalid. When it is returning NaN order is not changing this I found by trial and error. 

We can make invalid dates to come in beginning by modifying the sorting logic as below. 

`  data.milestones.sort(function (a, b) {
    // return new Date(b.date) - new Date(a.date);
    const dateA = new Date(a.date);
    const dateB = new Date(b.date);

    if (isNaN(dateA)) {
      return -1;
    }
    if (isNaN(dateB)) {
      return 1;
    }

    return dateB - dateA;
  });`

**Comment by Harrish-Selvarajah** [comment]
I think it's better to add validation for the wrong date as the input is via a JSON file by a human; may be this is out of scope for this task, but an error sign indicating to the user to fix the date issue may be?

**Comment by eddiejaoude** [comment]
> I think it's better to add validation for the wrong date as the input is via a JSON file by a human; may be this is out of scope for this task, but an error sign indicating to the user to fix the date issue may be?

When we move to forms this will have validation 👍

**Review by eddiejaoude — APPROVED** [review]
Looks good, thank you 👍

**Pull request merged**
