### PR TITLE
SohamRatnaparkhi

### PR DESCRIPTION
**Pull request by SohamRatnaparkhi**
Updated some links and data related to my profile

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers
Made small non-breaking changes

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3797"></a>

### CODE REVIEW

**Review by dan-mba — CHANGES_REQUESTED** [review]
Please move your profile out of the public directory.
It should be in the data directory off the root of the project.
`data/SohamRatnaparkhi.json`

**Comment by SohamRatnaparkhi** [comment]
> Please move your profile out of the public directory. It should be in the data directory off the root of the project. `data/SohamRatnaparkhi.json`

Hi, I have committed the requested changes.

**Review by dan-mba — CHANGES_REQUESTED** [review]
The icons need to come from the available [icons list](https://linkfree.eddiehub.io/icons).<br>
I would strongly advise against using a mailto link with your gmail. This gives spammers / scammers access to you email address.

**Comment by SaraJaoude** [comment]
I will close this as your fork is out of date.  Please update your fork by following the Editing guide in Docs: https://linkfree.eddiehub.io/docs/how-to-guides/editing

**Pull request closed without merging**
