### PR TITLE
data:midhundevasia1

### PR DESCRIPTION
**Pull request by midhundevasia1**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4295"></a>

### CODE REVIEW

**Comment by midhundevasia1** [comment]
All Good

**Comment by kumarankit999** [comment]
If you don't mind Can I work on this

**Comment by midhundevasia1** [comment]
> 

I have done everything right still not loading https://linkfree.eddiehub.io/midhundevasia1

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"></p>

**Comment by Pradumnasaraf** [comment]
> > 
> 
> I have done everything right still not loading https://linkfree.eddiehub.io/midhundevasia1

The PR was not merged this is why the profile was not showing up. I have merged it, it will be live in a couple of mins

**Pull request merged**
