### PR TITLE
Krishna profile update - milestore added

### PR DESCRIPTION
**Pull request by Krishnapro**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3685"></a>

### CODE REVIEW

**Review by SaraJaoude — CHANGES_REQUESTED** [review]
The generated files `CHANGELOG.md` and `package-lock.json` should not be part of your Pull Request.

These have probably happened because you are running the GitHub Actions in your fork. 

Please disable GitHub Actions running in your fork to avoid these files being generated in your Pull Request in the future. 

Please revert these files. This can be done with the `git checkout` command for each file if you are working in a branch, for example...

```
git checkout main -- CHANGELOG.md
git checkout main -- package-lock.json
```

**Review by Tejender1521 — CHANGES_REQUESTED** [review]
Just delete all the files except your data file.

**Comment by kumarsonsoff3** [comment]
> Just delete all the files except your data file.

Need not to delete the files, you can just follow the steps **SaraJaoude** mentioned above. If you need any other help, you can refer this video by Eddie. https://youtu.be/YUHS5Ana7Jw

**Comment by Krishnapro** [comment]
I mesh with all the changes with conflict. so don't mind I'm closing this pull request and will open a fresh one.

**Pull request closed without merging**
