### PR TITLE
feat: clear filters for map (#5312)

### LINKED ISSUE #5312: [FEATURE] Clear filters for map
### Description

Create a clear filters tag/button for the map page to be able to reset the data. Currently the only path to do this is refreshing the browser.

### Screenshots

clearmap

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by weilincheng**
## Fixes Issue
Closes #5312 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

Firstly, I've added a button that allows for the clearing of existing filters by setting setFilteredUsers with an empty array. Additionally, there have been some file format changes made by the prettier.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5396"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
I think a `Button` would be better?

https://github.com/EddieHubCommunity/LinkFree/blob/main/components/Button.js

**Comment by weilincheng** [comment]
> I think a `Button` would be better?
> 
> https://github.com/EddieHubCommunity/LinkFree/blob/main/components/Button.js

Thanks for the suggestion, Eddie. Let me make the change to use `Button` component instead.

**Comment by weilincheng** [comment]
Rewritten to use the Button component and also added a line of code to remove the tag filter highlights when resetting.

Furthermore, I noticed that the previous tag highlight is not being removed when selecting a second tag, as the previous tag highlight is not being removed. I am uncertain if this is the intended behavior.
image

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by eddiejaoude** [comment]
> Furthermore, I noticed that the previous tag highlight is not being removed when selecting a second tag. I am uncertain if this is the intended behavior.

It should add the tags together, similar to the search page, the toggle does not toggle off, I raise an issue for this bug https://github.com/EddieHubCommunity/LinkFree/issues/5420

**Pull request merged**
