### PR TITLE
data:zakafan

### PR DESCRIPTION
**Pull request by zakafan**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3728"></a>

### CODE REVIEW

**Review by Aadarsh805 — CHANGES_REQUESTED** [review]
Hey, you file name is incorrect, change it to `data/zakafan.json`
without any quotes or `` these

**Comment by zakafan** [comment]
done I changed it

**Comment by Aadarsh805** [comment]
> done I changed it

wrong slash, use the other one forward one `/` this

**Comment by zakafan** [comment]
done

**Comment by Aadarsh805** [comment]
> done

Aight all good  👍

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
