### PR TITLE
Himanshu1221 patch 1

### PR DESCRIPTION
**Pull request by himanshu1221**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3311"></a>

### CODE REVIEW

**Review by Aadarsh805 — CHANGES_REQUESTED** [review]
delete the `data/himanshu1221` without the `.json` one

**Comment by senali-d** [comment]
> > delete the `data/himanshu1221` without the `.json` one
> 
> done !

@himanshu1221 Still the `data/himanshu1221` without the `.json` file is there. Please remove it.

**Comment by himanshu1221** [comment]
> > > delete the `data/himanshu1221` without the `.json` one
> > 
> > 
> > done !
> 
> @himanshu1221 Still the `data/himanshu1221` without the `.json` file is there. Please remove it.

removed it maam yo can check it

**Review by senali-d — COMMENTED** [review]
Look Good. Thank you for the contribution 🎉

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"></p>

**Pull request merged**
