### PR TITLE
feat: added a lot of icons

### PR DESCRIPTION
**Pull request by krishguptadev**
## Changes proposed

I've added a lot of icons. **This PR is WIP rn**

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/854"></a>

### CODE REVIEW

**Comment by emmalearnscode** [comment]
Do we really need all these icons? Also, I think it would help others get green squares if people could raise an issue for the specific icon they’d like added and then make a small pull request for that icon. This is a lot of icons - lots of green squares to share with the community and a great first time issue.

**Comment by krishguptadev** [comment]
> Do we really need all these icons? Also, I think it would help others get green squares if people could raise an issue for the specific icon they’d like added and then make a small pull request for that icon. This is a lot of icons - lots of green squares to share with the community and a great first time issue.

there is still a lot to be added 😅 Plus the fact that adding one icon by one, isn't efficient.

**Comment by emmalearnscode** [comment]
> there is still a lot to be added 😅 Plus the fact that adding one icon by one, isn't efficient.

It doesn’t have to be efficient, it’s better to collaborate and help others learn than just be efficient. And adding lots of icons that nobody asked for or will use just bloats the project.

**Comment by CodingSpecies** [comment]
@krishguptadev @emmalearnscode  also, if we were to put this idea forward, we would have to add all the icon images and the description of each to the readme, which would be a huge update, I think is not really neccesary right now. In my opinion, if we did them by collaborating and agreeing to certain icons,  is far more excitable, as this is the org for open source and collaborating! This is what I think, thank you.

**Comment by Panquesito7** [comment]
I agree with @emmalearnscode and @CodingSpecies. It's best to leave green squares for others, even if it's not that efficient. 🙂

**Pull request closed without merging**
