### PR TITLE
data: lmac01

### PR DESCRIPTION
**Pull request by lmac-1**
## Changes proposed
Updates my LinkFree profile that was created with the previous version of LinkFree

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

I followed all of the instructions on the [editing guide docs](https://linkfree.eddiehub.io/docs/how-to-guides/editing). 

I only edited the JSON file directly in GitHub (`data/lmac1.json`) but I don't understand why it's saying that there are other files changed - are these automatic actions from GitHub?

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3126"></a>

### CODE REVIEW

**Review by Sativarsainath-26 — COMMENTED** [review]
please revert the changes in package-lock.json, CHANGELOG.md and package.json file it is not needed in profile update.

**Comment by lmac-1** [comment]
I didn't make these changes, they were automatically added by GitHub. Will try to revert them. Can I do that here on GitHub, or do I have to check out the project locally?

(sorry just did extra commit to add one extra link)

**Comment by Aadarsh805** [comment]
> I didn't make these changes, they were automatically added by GitHub. Will try to revert them. Can I do that here on GitHub, or do I have to check out the project locally?
> 
> (sorry just did extra commit to add one extra link)

Yes you can go into your commit and delete all those files which you did not intend to commit
image

**Comment by lmac-1** [comment]
Thanks! 

Dan in the EddieHub Discord advised me to merge from EddieHub main into my branch. I just did that and now there's only one file changed. Hope it's okay, let me know if I'm missing anything else

**Comment by Aadarsh805** [comment]
> Thanks!
> 
> Dan in the EddieHub Discord advised me to merge from EddieHub main into my branch. I just did that and now there's only one file changed. Hope it's okay, let me know if I'm missing anything else

yep that works fine as well, you did great 😇

**Comment by lmac-1** [comment]
Thanks so much for your help @Aadarsh805 🤩

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
