### PR TITLE
Update almel19.json

### PR DESCRIPTION
**Pull request by almel19**
some updates and tests

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6236"></a>

### CODE REVIEW

**Comment by SaraJaoude** [comment]
You have conflicts in your file, please resolve. This is usually because your fork is not up to date.  

You may wish to have a look at the following Docs and video: https://linkfree.eddiehub.io/docs/how-to-guides/editing

**Comment by almel19** [comment]
I don't know what happened. I clicked sync fork before editing the file, passed the checks and there where no conflicts with the base branch

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Hey @almel19, you can test your profile on [LinkFree Playground](https://linkfree.io/playground) & play around it there. 

But please update your `json` with your info. (Tags, bio & links).

**Comment by SaraJaoude** [comment]
I will merge as there are no longer any conflicts.

**Pull request merged**
