### PR TITLE
data: AdityaAgrawal

### PR DESCRIPTION
**Pull request by adityaiiitL**
## Changes proposed

Added the profile data

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2823"></a>

### CODE REVIEW

**Review by dan-mba — CHANGES_REQUESTED** [review]
Please rename the file to match your GitHub id.
`adityaiiitL.json`

**Comment by adityaiiitL** [comment]
> Please rename the file to match your GitHub id. `adityaiiitL.json`

**Comment by eddiejaoude** [comment]
@adityaiiitL did you mean to close this pull request? I think we can merge it but you will need to reopen it

**Comment by adityaiiitL** [comment]
> @adityaiiitL did you mean to close this pull request? I think we can merge it but you will need to reopen it

Yeah I've reopened it

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
