### PR TITLE
Malishkapandey patch 1

### PR DESCRIPTION
**Pull request by malishkapandey**

### CODE REVIEW

**Review by himanshu1221 — APPROVED** [review]
LGTM :+1:

**Comment by malishkapandey** [comment]
> 

Thank you @himanshu1221

**Comment by malishkapandey** [comment]
> LGTM
Thank you @himanshu1221

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
You filename should be exact same as your username + your file should be in the data directory. 

Change `MalishkaPandey.json`  - >  `data/malishkapandey.json` [here](https://github.com/malishkapandey/LinkFree/edit/malishkapandey-patch-1/MalishkaPandey.json). Let us know if you need any help with this! 

image

**Review by Ananya2001-an — APPROVED** [review]
Looks good except the file name change as requested.

**Comment by malishkapandey** [comment]
Thank you @Ananya2001-an @kumarsonsoff3

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
