### PR TITLE
added a slide in theme toggel button

### PR DESCRIPTION
**Pull request by adarsh1215**
## Fixes Issue

Closes #7474

## Changes proposed

made toggel theme button interactive

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7474"></a>

### CODE REVIEW

**Comment by SaraJaoude** [comment]
What Issue does this relate to? @adarsh1215 please amend your description to include the Issue number.

**Review by SaraJaoude — CHANGES_REQUESTED** [review]
What Issue does this relate to? @adarsh1215 please amend your description to include the Issue number.

**Comment by anirudhp26** [comment]
Ig you need to create an issue regarding this change requested, then create a PR addressing that particular issue @adarsh1215

**Comment by eddiejaoude** [comment]
No guessing required, we have a contributing guide including a video https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by SaraJaoude** [comment]
I will close this, see https://github.com/EddieHubCommunity/LinkFree/issues/7528 for reasons.

**Pull request closed without merging**
