### PR TITLE
Update priyankarpal.json

### PR DESCRIPTION
**Pull request by priyankarpal**
## Changes proposed
Changed an icon and fixed a spelling mistake

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Screenshot from 2023-01-26 23-12-44

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4069"></a>

### CODE REVIEW

**Review by Njong392 — APPROVED** [review]
The updates look great! 🎉

**Comment by priyankarpal** [comment]
@Njong392 thanks.

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
