### PR TITLE
data: sumitmukharjee

### PR DESCRIPTION
**Pull request by sumitishere**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

You are doing a great job, I would like my Linkfee profile to be updated.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4952"></a>

### CODE REVIEW

**Review by senali-d — CHANGES_REQUESTED** [review]
Rename file name as `data/sumitmukharjeeeeee.json`.
Don't forgot to move it into data folder

**Comment by sumitmukharjeeeeee** [comment]
> Rename file name as `data/sumitmukharjeeeeee.json`. Don't forgot to move it into data folder

changed as specified

**Review by senali-d — CHANGES_REQUESTED** [review]
File name should be same as `data/sumitmukharjeeeeee.json`.

It will need to be match with the github username.

**Comment by Pradumnasaraf** [comment]
They already fixed that, @senali-d. Thanks for always reviewing and adding value to LInkFree.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Welcome to LinkFree 🎉

**Pull request merged**
