### PR TITLE
Gaurav kanwat patch 2

### PR DESCRIPTION
**Pull request by GauravKanwat**
Few changes in JSON file.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4994"></a>

### CODE REVIEW

**Review by dev-rakeshshaw — APPROVED** [review]
LGTM

**Review by Hrishi5111998 — APPROVED** [review]

**Review by mahfuztbt — APPROVED** [review]

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Welcome to LinkFree 🎉

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! 🎉

**Comment by GauravKanwat** [comment]
Thank you! Glad to a part of this community.

**Pull request merged**
