### PR TITLE
Fix table overflow

### LINKED ISSUE #4657: [BUG] Mobile responsiveness issue: Navbar not covering full screen width
### Description

The Navbar in the statistics page does not seem to cover the full width of the screen on mobile in the deployed version of LinkFree, however the navbar seems to cover the full width of the screen on mobile when I tried to recreate it locally.
 
Screenshot of the page on the `Deployed version`

navbar-bug-deployed

Screenshot of the page on the `Local Build`

navbar-bug-local

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Saadat-B**
## Fixes Issue

Closes #4657 

## Here are the steps to reproduce the bug:

1. Click a link on your profile
2. Go to the statistics page under the bar chart to see the generated table with the link
3. Go to mongodb > linkfree > links
4. Edit the URL of the link
5. Increase the length of the URL by adding characters
6. Run `npm run dev` to build the project again to see the changes 
7. Observe that the table overflows and causes the bug to occur

## Changes proposed

The problem is caused by the `whitespace-nowrap` class [here](https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/account/statistics.js#L149)

I have replaced the class `whitespace-nowrap` with `md:whitespace-nowrap` which will set the nowrap to only happen on larger screens thus resolving the bug.
I'm attaching comparison screenshots of `before` and `after` for your review

### Before

navbar-bug-found

### After

table-bug-fix

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4695"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Please recheck this is still an issue as I can't reproduce

**Comment by eddiejaoude** [comment]
Any reason this is still in draft?

**Comment by Saadat-B** [comment]
Yes actually you weren't able to reproduce this bug and had said to recheck it. I was still able to reproduce it so I left a comment on the issue of this pull request and was waiting for your response on it. Therefore it's still in the draft.

**Comment by Saadat-B** [comment]
I have rechecked the issue and was able to reproduce this issue so I'm marking it ready for review now. If anyone is unable to reproduce it then please let me know.

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
