### PR TITLE
Added filter to show free and paid events

### LINKED ISSUE #2901: [FEATURE] Events page - add a cost identifier
### Description

This feature is to add a legend item for cost to events so that folks can easily identify free vs paid events.

To keep things simple proposing only
Free Event (possible icon tbd or simply put Free as text)
Paid Event (possible icon FaMoneyBill)

Consideration: If the event has a free and a paid portion, do we need a way to show that?

We could get more granular with this in the future if people find it more useful to know precise cost without clicking through to the event

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by shyam0705**
## Fixes Issue
closes #2901

## Changes proposed
1)Added filter to show all free and paid events.
2)Modified documentation to suggest adding the startingFrom field in events

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

https://user-images.githubusercontent.com/72148710/218325819-59e11c2d-0787-44fc-aa68-3a760e1608de.mp4

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4759"></a>

### CODE REVIEW

**Comment by amandamartin-dev** [comment]
Hi! Thank you for working on this. I have a few questions (I have not pulled the code to test yet)

What does the mobile experience look like with the added filters?
What happens in the case of cost not provided? How will the filters handle this scenario?

Also, one of the build tests is failing if you are able to take a look at the error

**Comment by shyam0705** [comment]
> Hi! Thank you for working on this. I have a few questions (I have not pulled the code to test yet)
> 
> What does the mobile experience look like with the added filters? What happens in the case of cost not provided? How will the filters handle this scenario?
> 
> Also, one of the build tests is failing if you are able to take a look at the error

- I am attaching a video of the mobile view.
-  In case of cost is not provided for any of the events, then both free and paid events will be zero. 
- I don't know why one test case is failing. Can you re-run it  


https://user-images.githubusercontent.com/72148710/218520205-3847d381-ee46-4d12-b80e-c3a232f446d7.mp4

**Comment by shubhsharma19** [comment]
The code looks mostly correct, but there is a potential issue with `page.waitForLoadState("networkidle")`

`waitForLoadState()` method is a part of the Puppeteer library, and it waits for the page to reach a particular load state before continuing with the code execution. However, the valid values for the loadState parameter are "load", "domcontentloaded", and "networkidle", but not "networkidle" alone.

The waitForLoadState("networkidle") method should be changed to either waitForLoadState("networkidle0") or waitForLoadState("networkidle2") to indicate the level of network activity before considering the page loaded.

if you are using an older version of Puppeteer, `waitForLoadState()` may not be available, and you may need to use `page.waitForNavigation()` instead.

I could be wrong let me know if I am :)

**Comment by amandamartin-dev** [comment]
> I could be wrong let me know if I am :)

Hi, the code you are commenting on is part of the playwright tests and not changes included in this PR.  To decrease confusion for folks, make sure to only comment on parts of the application and code relevant to this PR. If you believe there are better ways to implement some of the tests you may propose them in a new issue, or start a conversation in ideas in Discord.

**Comment by amandamartin-dev** [comment]
Hello @shyam0705 thank you so much for your patience on our reviews of this issue.  It got pushed down in priority a bit, but would love to move forward and continue working. 

You may notice that the branch is now out of date and their are conflicts in a few files.  Please pull in main to your branch and see if you are able to fix the merge conflicts.

If you are uncomfortable figuring out how to do that or no longer have time to work on this issue please comment and another maintainer will be able to help collaborate on getting this ready for review again.

Thank you!!!

**Comment by eddiejaoude** [comment]
I have resolved the conflicts

**Comment by eddiejaoude** [comment]
I will merge into a temporary branch and fix the error and failing test etc

**Pull request merged**
