### PR TITLE
[Bug fix]: move tab nav to the top #7875

### LINKED ISSUE #7875: [BUG] On profile page move tabs nav to top
### Description

image
image

The tabs should always be in the same position

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ZeeMonk-pixel**
Closes #7875

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7931"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Please add a screenshot of the before and after changes, to give context and easier for the reviewers

**Comment by ZeeMonk-pixel** [comment]
Screenshot 2023-07-03 064414
Before changes.
Screenshot 2023-07-03 064321
After changes. 
Nav move to top of page

**Comment by ZeeMonk-pixel** [comment]
Sorry, I noticed I'm getting no statistics when launching from my gitpod but I have statistics on the live app. Why is that pls?

**Comment by eddiejaoude** [comment]
> Sorry, I noticed I'm getting no statistics when launching from my gitpod but I have statistics on the live app. Why is that pls?

Because you will have no data in your Gitpod environment - it only shows when there is data, if you log out and click on your project and get some data, then the graph will appear

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
