### PR TITLE
Edited my LinkFree profile

### PR DESCRIPTION
**Pull request by Vishrut19**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5811"></a>

### CODE REVIEW

**Comment by SaraJaoude** [comment]
The generated files `package-lock.json` should not be part of your Pull Request.

Please revert these files. This can be done with the `git checkout` command for each file if you are working in a branch, for example...

```
git checkout main -- package-lock.json
```

**Review by Vishrut19 — COMMENTED** [review]
Removed package-lock.json file

**Comment by eddiejaoude** [comment]
> Removed package-lock.json file

@Vishrut19 removing the file is still making a change, the file is still required, but the changes you made are not. Please see Sara's comment on how to fix this without deleting the file and removing your additional changes, that way the file should not appear in your PR because there are no changes

**Comment by Vishrut19** [comment]
Okay got it I will do that. Also should I make another pull request?

**Comment by eddiejaoude** [comment]
> Okay got it I will do that. Also should I make another pull request?

You can update this PR as Sara suggested with the command shared. But if easier for you, yes you can make a new pull request, but please remember to close this one first

**Comment by Vishrut19** [comment]
> > Okay got it I will do that. Also should I make another pull request?
> 
> You can update this PR as Sara suggested with the command shared. But if easier for you, yes you can make a new pull request, but please remember to close this one first

Sure I will try to update this one only.

**Comment by Vishrut19** [comment]
Hey! If everything is fine then please merge my PR.

**Comment by eddiejaoude** [comment]
> Hey! If everything is fine then please merge my PR.

The maintainers will get notified that you pushed more changes to your profile, so you don't need to create extra notifications.

Looking at your pull request, you still have the same problem, please look at the `files changed` tab and you will see the lock file is still there

Sara gave you the command to fix this, please share your terminal if you are getting any errors when you try this. I suggest updating your fork and branch first. I also created a video on this if it helps

**Comment by Vishrut19** [comment]
> > Hey! If everything is fine then please merge my PR.
> 
> The maintainers will get notified that you pushed more changes to your profile, so you don't need to create extra notifications and chase them - you can speed up the merging of your pull request by checking what you commit first and not commit extra files you did not make changes to.
> 
> Looking at your pull request, you still have the same problem, please look at the `files changed` tab and you will see the lock file is still there
> 
> Sara gave you the command to fix this, please share your terminal if you are getting any errors when you try this. I suggest updating your fork and branch first. I also created a video on this if it helps

okay and I will close this PR and raise another one.

**Comment by eddiejaoude** [comment]
Sure if that is easier for you 👍 

Make sure you only commit files you want to include in your PR

**Pull request closed without merging**
