### PR TITLE
data: AbdulrahmonBabatunde

### PR DESCRIPTION
**Pull request by abdulrahmonbb**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7233"></a>

### CODE REVIEW

**Comment by RohanSasne** [comment]
lgtm!

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Your filename should be exact same as your GitHub username. Please [rename your file here](https://github.com/abdulrahmonbb/LinkFree/edit/AbdulrahmonBabatunde-patch-1/data/AbdulrahmonBabatunde.json) to `abdulrahmonbb.json`

Change `AbdulrahmonBabatunde.json`  -->  `abdulrahmonbb.json`

Let us know if you need any help with this! :)

**Comment by abdulrahmonbb** [comment]
> Please change the filename to your github username which is :abdulrahmonbb

Done. I just commited the changes

**Comment by abdulrahmonbb** [comment]
> f

Just commited the changes.

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks for Contributing! 🎉 

<p align="center"><a href="https://linkfree.io/docs/how-to-guides/editing"></a></p>

**Comment by abdulrahmonbb** [comment]
> Looks good, Thanks for Contributing! 🎉
> 
> [](https://linkfree.io/docs/how-to-guides/editing)

Thanks Kumar!

**Pull request merged**
