### PR TITLE
himanshu.json

### PR DESCRIPTION
**Pull request by imhimansu28**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3015"></a>

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
Please close this PR since you have created a new one

**Comment by imhimansu28** [comment]
New Pr is open

**Comment by eddiejaoude** [comment]
Thank you @ChinmayMhatre and @imhimansu28 👍  btw it is usually best practice to reference the other PR when mentioning it with a link

**Comment by ChinmayMhatre** [comment]
> Thank you @ChinmayMhatre and @imhimansu28 👍  btw it is usually best practice to reference the other PR when mentioning it with a link

Got it! Will keep that in mind next time.

**Pull request closed without merging**
