### PR TITLE
chore: update qwel-exe

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
## Fixes Issue
Current PR #1024 doesn't work as @ImgBotApp messed up something

## Changes proposed
changed @qwel-exe GitHub name and few of the icons

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1073"></a>

### CODE REVIEW

**Review by KendallDoesCoding — COMMENTED** [review]
@qwel-exe According to me, if the file name is Qwelexe.json or qwelexe.json it will look better, what do you say?

**Comment by emmalearnscode** [comment]
@qwel-exe can you check everything is as you want it?

**Comment by qwel-exe** [comment]
> qwelexe.json

 qwelexe.json would be good

**Comment by qwel-exe** [comment]
> @qwel-exe can you check everything is as you want it?

yep everything i wanted :) thanks @KendallDoesCoding

**Review by qwel-exe — APPROVED** [review]
LGTM :rocket:

**Comment by KendallDoesCoding** [comment]
> > @qwel-exe can you check everything is as you want it?
> 
> yep everything i wanted :) thanks @KendallDoesCoding

welcome :)

**Comment by KendallDoesCoding** [comment]
> > qwelexe.json
> 
> qwelexe.json would be good

Will update.

**Review by schmelto — APPROVED** [review]

**Review by ssensalo — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]

**Pull request merged**
