### PR TITLE
Add Seth Addo

### PR DESCRIPTION
**Pull request by seths10**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1658"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🎉


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by Njong392 — APPROVED** [review]
Looks great! Thanks for contributing :100: 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Reusable

**Comment by seths10** [comment]
please is my submission merged?

**Comment by Njong392** [comment]
> please is my submission merged?

Not yet no. But soon :+1:

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contributions :tada:

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
