### PR TITLE
feat: added my profile

### PR DESCRIPTION
**Pull request by rohitdasu**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1750"></a>

### CODE REVIEW

**Comment by rohitdasu** [comment]
can we get this merged @EmmaDawsonDev ?

**Comment by EmmaDawsonDev** [comment]
> can we get this merged @EmmaDawsonDev ?

Just waiting on a second approval

**Comment by rohitdasu** [comment]
> > can we get this merged @EmmaDawsonDev ?
> 
> Just waiting on a second approval

sure 👍

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good to me!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Pull request merged**
