### PR TITLE
Update loftwah.json

### PR DESCRIPTION
**Pull request by loftwah**
## Changes proposed

Updating profile

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Updating profile

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4602"></a>

### CODE REVIEW

**Review by stevenovak123 — APPROVED** [review]

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good to me. 🎉 

Filename check is failing probably because you'd an outdated branch, make sure to update your branch. Then we are good to go. 🚀

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by loftwah** [comment]
It should be resolved now.

Newcomers wouldn't have been able to solve this without instruction.

**Review by Sindhuinti — APPROVED** [review]

**Comment by kumarsonsoff3** [comment]
Agreed, but it's not a problem from contributor side, new release of [tj-actions/changed-files](https://github.com/tj-actions/changed-files) made the action more eractic cause this issue. 

We have rolled to a stable version of the action, and now it works fine. 🙂

**Pull request merged**
