### PR TITLE
fix: LinkedIn icon

### PR DESCRIPTION
**Pull request by qwe123coder**

### CODE REVIEW

**Review by krishguptadev — CHANGES_REQUESTED** [review]
I think this has to be linkedin, because we will be adding the icon

**Comment by qwe123coder** [comment]
> I think this has to be linkedin, because we will be adding the icon

it would take a while to make a pr and that getting merged so i was thinking as of now we can keep it as global
 after you folks add linkedin logo i can make a pr to change it back to the same

**Comment by qwe123coder** [comment]
ooo found this pr #366 if we merg that then i think the problem will be solved

**Review by Pradumnasaraf — COMMENTED** [review]
> Yes, it will take a little while to add the LinkedIn logo.

**I don't think we need to change it to `globe`. Because after addition (LinkedIn Logo), we have to again change it back to `LinkedIn`. So, doesn't sound lucrative to me.**

Love to hear other reviewers thoughts on this :)

**Comment by emmalearnscode** [comment]
I agree with @Pradumnasaraf , the icon pack is currently being discussed and this change would just cause problems later when the LinkedIn icon becomes available.

**Comment by krishguptadev** [comment]
btw github provides a single button to revert a whole PR: 
image

**Review by Panquesito7 — COMMENTED** [review]
As discussed above, I think it's best to wait until a change is made. 🙂

**Review by krishguptadev — COMMENTED** [review]
+1 to @Panquesito7's comment

**Comment by qwe123coder** [comment]
> +1 to @Panquesito7's comment

cool

**Comment by Vyvy-vi** [comment]
> btw github provides a single button to revert a whole PR: image

Even though the button exists, our project has been moving quite fast and leaving PRs around for a while makes it tough for the original contributor as well as the maintainers, since the project changes too many aspects, and thus the PRs original purpose gets lost...

**Review by Vyvy-vi — COMMENTED** [review]
Thanks for contributing to Linkfree!
While this addition _can_ add some value, I don't think this is needed especially considering that there's a very extended discussion on icons going on, and this is going to be one of the changes that are going to stick around if merged in, and would probably be a lot of manual work to edit...

This does remind us that we should probably resolve the icons discussion soon...

**Comment by Vyvy-vi** [comment]
While this PR is being closed, we really appreciate that you took the time to go through all the files and edit them(I certainly hope that it was a script, rather than something done manually 😬 ). Though, in these cases, I think it could have benefited everyone if this was discussed on an issue like #106 or a new one.

Feel free to check out other issues on LinkFree, if they interest you!

**Pull request closed without merging**
