### PR TITLE
data:rayeesrather99

### PR DESCRIPTION
**Pull request by rayeesrather99**
Done

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3677"></a>

### CODE REVIEW

**Review by dan-mba — CHANGES_REQUESTED** [review]
To fix the JSON problem, add a comma at the end of lines 6, 12, 17, & 22

**Comment by rayeesrather99** [comment]
Added commas at the end of line of 6, 12, 17, & 22 .

**Review by dan-mba — CHANGES_REQUESTED** [review]
I'm assuming you want the LinkedIn icon (FaLinkedin) and the GitHub icon (FaGithub) for those links instead of the Instagram icon

**Comment by rayeesrather99** [comment]
changed the fa linkedin icon . now it's fine.

**Review by dan-mba — APPROVED** [review]
Looks good to me

**Review by SaraJaoude — APPROVED** [review]
looks good

**Comment by rayeesrather99** [comment]
Thank u : )

**Pull request merged**
