### PR TITLE
added ni5arga.json

### PR DESCRIPTION
**Pull request by ni5arga**
Added ni5arga.json file!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5326"></a>

### CODE REVIEW

**Review by schmelto — APPROVED** [review]

**Comment by ni5arga** [comment]
Thanks.

**Review by SurajPratap10 — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by ni5arga** [comment]
You're welcome!!

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
