### PR TITLE
Animated gif in the quickstart guide

### PR DESCRIPTION
**Pull request by shubhsharma19**
## Fixes Issue
Closes Issue #4175

## Changes proposed
Added a gif 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
base repo

## Note to reviewers
Have a great weekend :)

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4177"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you, some suggestions...

- please include before and after clicking `compare across forks`
- use light mode to be consistent and it is easier to read
- remove duplicate image

**Comment by Avi-88** [comment]
Hi @shubhsharma19 , I have made a similar PR #3825 , I had just updated the image in that. I was thinking about maintaining consistency across the guide by just using images as we dont use gif anywhere else, would love to hear your thoughts on it,thanks

**Comment by shubhsharma19** [comment]
Good idea @Avi-88, I think the image will be a better idea so go ahead 👍 
Should I delete this PR?

**Comment by shubhsharma19** [comment]
Good idea @Avi-88, I think the image will be a better idea so go ahead 👍 
Should I delete this PR?

**Comment by Avi-88** [comment]
> Good idea @Avi-88, I think the image will be a better idea so go ahead +1 Should I delete this PR?

Thanks @shubhsharma19 , I think we should wait on some more reviews because this PR also seems pretty helpful. You can update it with the requested changes for the final review.

**Comment by shubhsharma19** [comment]
Ok I will update @Avi-88 :)

**Comment by eddiejaoude** [comment]
Great discussion and collaboration! 

@shubhsharma19 thank you for updating your PR, and apologies for not noticing their was a duplicate already. I think for now as suggested let's keep to screenshots

Sorry again for the confusion

**Comment by shubhsharma19** [comment]
Thank-you @eddiejaoude and sorry for being a bit late in reply.

**Pull request closed without merging**
