### PR TITLE
data: goketech

### PR DESCRIPTION
**Pull request by Goketech**
## Changes proposed
Added goketech.json to data directory

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5707"></a>

### CODE REVIEW

**Review by Sindhuinti — CHANGES_REQUESTED** [review]
Please change your file name with your github username `data/
Goketech.json`

**Comment by Goketech** [comment]
> Everything's great just change your filename to your github username.

Thanks, I have updated my file name

**Comment by Goketech** [comment]
> Please change your file name with your github username `data/ Goketech.json`


Thanks, I have updated my file name

**Review by khushalarora — APPROVED** [review]
Thank you for contributing  :tada:

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! 🎉

**Pull request merged**
