### PR TITLE
Gaurav burande patch 1

### PR DESCRIPTION
**Pull request by GauravBurande**
## Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4213"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by Ananya2001-an — APPROVED** [review]

**Review by Sindhuinti — APPROVED** [review]
Thanks 👍🏻

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good to merge. Thanks for your Contribution! 🎉 

<p align="center"></p>

**Comment by GauravBurande** [comment]
Thanks, everyone🙏🏻

**Pull request merged**
