### PR TITLE
data:navharsh

### PR DESCRIPTION
**Pull request by navharsh**
## Changes proposed
Created LinkFree profile

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4558"></a>

### CODE REVIEW

**Review by himanshu1221 — APPROVED** [review]
LGTM :+1:

**Review by rahulpandey70 — CHANGES_REQUESTED** [review]
Hey, @navharsh please move your json file in data folder.

**Comment by navharsh** [comment]
@rahulpandey70 moved!

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by navharsh** [comment]
not sure why checks are failing

**Comment by navharsh** [comment]
Sorry about multiple requests, its some glitch

**Review by rahulpandey70 — APPROVED** [review]
Hey, @navharsh everything looks good, Ask help to eddie.

**Comment by navharsh** [comment]
there's some check thats failing and we dont know whats the problem. can you help @eddiejaoude ?

**Comment by kumarsonsoff3** [comment]
> there's some check thats failing and we dont know whats the problem. can you help @eddiejaoude ?

Failing because you had an outdated branch, try updating your fork!

**Comment by navharsh** [comment]
@kumarsonsoff3 did that still something is failing

**Comment by kumarsonsoff3** [comment]
Please don't worry about this one. The filename issue is resolved, and this is an issue from Reviewpad. 
We have reported this problem to reviewpad's team and they are working to fix it.

**Review by kumarsonsoff3 — APPROVED** [review]

**Pull request merged**
