### PR TITLE
data: alicalimli

### PR DESCRIPTION
**Pull request by alicalimli**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4802"></a>

### CODE REVIEW

**Review by Krishnapro — DISMISSED** [review]
LGTM 🚀

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Please move your file to data directory, to do so, you need to rename your **[file here](https://github.com/alicalimli/LinkFree/edit/alicalimli-patch-1/alicalimli)** to `data/alicalimli.json`

Change `alicalimli`  - >  `data/alicalimli.json` here.

Let us know if you need any help with this! :)

image

**Comment by alicalimli** [comment]
Thanks, It's done

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
The type of your newly added file must be `.json`.
Please update accordingly. If you need any help, let us know. 🙂

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by alicalimli** [comment]
> 

thank you as well

**Pull request merged**
