### PR TITLE
Fixed: [BUG] The Profile Pictures On Testimonials And Profiles Don't Match #8642

### LINKED ISSUE #8642: [BUG] The Profile Pictures On Testimonials And Profiles Don't Match
### Description

On a particular profile page (linked below), under the testimonials in the person's profile, there is a testimonial from the name "CJ LinuxGamer" in LinkFree, with the username being "LinuxGamer", their placeholder shows "AA" while on their profile page, it shows "Li"

The links to these pages:

- The profile with the testimonial: https://linkfree.io/krishstwt
- The link to the profile: https://linkfree.io/LinuxGamer

### Screenshots

This is the screenshot of the testimonial, where the profile picture is a placeholder saying "AA"

a screenshot of a testimonial on linkfree with special emphasis on the profile picture/avatar

This is the screenshot of the same person's profile on Linkfree:

a screenshot of a profile on Linkfree with particular emphasis on the profile picture/avatar

### Additional information

~~We should have a standard helper function to generate these so there is no inconsistency.~~

Edit: I noticed there is a helper function, it is just not being used properly in the testimonial component

## Solution

https://github.com/EddieHubCommunity/LinkFree/blob/44e67d806f690299782e24e68cd1ad090189444d/components/user/UserTestimonials.js#L19-L27

This code will have to be changed:

```diff
<FallbackImage
  width={100} // just to pass nextjs error
  height={100}
  src={`https://github.com/${testimonial.username}.png`}
  alt={testimonial.username}
+ fallback={testimonial.username}
  className="rounded-full bg-primary-low"
  />
```

But because the UserPage component has access to the username, we might want to change:

https://github.com/EddieHubCommunity/LinkFree/blob/44e67d806f690299782e24e68cd1ad090189444d/components/user/UserProfile.js#L46 to:

```diff
- fallback={data.name}
+ fallback={data.username}
```

### PR DESCRIPTION
**Pull request by Pravesh-Sudha**
## Fixes Issue

Edit:
fixes #8642 

## Changes proposed
This PR apply the changes proposed in Issue/Bug by @xkrishguptaa.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8644"></a>

### CODE REVIEW

**Review by sital002 — COMMENTED** [review]
Since this is not labeled ```status: ready for dev``` you aren't allowed to send PR without getting issue assigned to you. I would recommend you to read our contributing guidelines https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md .

**Comment by Pravesh-Sudha** [comment]
Okay

**Comment by SaraJaoude** [comment]
@sital002 thank you for comments and linking. 

@Pravesh-Sudha as the issue's label how now changed to `status: ready for dev` and as no one has requested it, on this occasion I will assign it to you.  However in future please take on board @sital002 comments and how the project is run.

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
