### PR TITLE
Create ayobamiseun.json

### PR DESCRIPTION
**Pull request by ayobamiseun**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1650"></a>

### CODE REVIEW

**Review by PIYUSH-MISHRA-00 — APPROVED** [review]

**Review by EmmaDawsonDev — APPROVED** [review]
Looks good 👍🏼

**Comment by ayobamiseun** [comment]
Thanks please kindly follow and star my pin.

**Comment by ayobamiseun** [comment]
> Looks good 👍🏼

**Comment by ayobamiseun** [comment]
> Looks good 👍🏼 


Thanks please kindly follow and star my pin.

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🎉


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

**Pull request merged**
