### PR TITLE
fix: Update `link` to `globe`

### PR DESCRIPTION
**Pull request by Panquesito7**
## Changes proposed

- Update `link` to `globe`.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/699"></a>

### CODE REVIEW

**Review by thepranaygupta — APPROVED** [review]
LGTM 🚀

**Review by emmalearnscode — APPROVED** [review]

**Review by schmelto — APPROVED** [review]

**Comment by schmelto** [comment]
do we have also change all profiles which are using `link`

**Comment by Panquesito7** [comment]
> do we have also change all profiles which are using `link`

I think that was done in #694.
If I missed any, let me know! 😄

**Comment by emmalearnscode** [comment]
We should probably update the readme list of available icons

**Review by krishguptadev — COMMENTED** [review]
LGTM!

**Pull request merged**
