### PR TITLE
added my profile

### PR DESCRIPTION
**Pull request by Rounak-28**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1769"></a>

### CODE REVIEW

**Review by kalyan-vurugonda — APPROVED** [review]
LGTM!

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Hey there! Please revert the changes in the `package-lock.json` file.
Let us know if you need any help doing that! 🙂


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

**Comment by kalyan-vurugonda** [comment]
> Hey there! Please revert the changes in the `package-lock.json` file. Let us know if you need any help doing that! 🙂
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  🛠️ This code needs a fix  |  

Yes sorry I didn't notice that. @Rounak-28. Revert the changes made in the package-lock.json file.__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

**Comment by Rounak-28** [comment]
@kalyan-vurugonda @Panquesito7 I guess everything's fine now

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good! 👍 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🎉


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
