### PR TITLE
Added Coding Species

### LINKED ISSUE #220: Add CodingSpecies
#219

### PR DESCRIPTION
**Pull request by CodingSpecies**
Fixes #220

## Proposed Changes

  -  Added json file, with my data.
  -  Consists of name, and bio, profile.
  -  Added github link.

I am not too sure how to get correct image url though, with the `.png` ending. Thank you

## Screenshots

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/219"></a>

### CODE REVIEW

**Comment by CodingSpecies** [comment]
I fixed image url

**Review by FayasNoushad — APPROVED** [review]

**Review by voidz7 — CHANGES_REQUESTED** [review]
You need to use .json file type to add your files , so renaming  this file from 
image
to `CodingSpecies.json` should be done .

**Review by FayasNoushad — COMMENTED** [review]
Add `.json` in file name

**Comment by CodingSpecies** [comment]
@voidz7 @FayasNoushad changed file name thanks.

**Review by FayasNoushad — APPROVED** [review]

**Review by schmelto — APPROVED** [review]

**Pull request merged**
