### PR TITLE
data:Drabzit

### PR DESCRIPTION
**Pull request by Drabzit**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3225"></a>

### CODE REVIEW

**Review by dan-mba — CHANGES_REQUESTED** [review]
Please move your profile to the data directory

**Comment by loftwah** [comment]
You can check out [mine](https://github.com/EddieHubCommunity/LinkFree/blob/main/data/loftwah.json) as an example.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by eddiejaoude** [comment]
Great collaboration everyone 👍

**Pull request merged**
