### PR TITLE
Created codewithfan LinkFree

### PR DESCRIPTION
**Pull request by codewithfan**
## Changes proposed

- Created codewithfan LinkFree.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Screen Shot 2022-03-23 at 10 59 45 AM

## Note to reviewers

Thank you for the opportunity!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1194"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please revert the changes in the `package-lock.json` file. Let us know if you need any help. :)

**Comment by codewithfan** [comment]
@Panquesito7 I will need assisstance on that.

**Review by krshdev — COMMENTED** [review]
@codewithfan replace [he package file in your pr with the one in the repo, and it should be fixed. Thanks.

**Comment by abh139** [comment]
@krshdev Yes

**Comment by abh139** [comment]
Looks good to me, Thank you for contributing.

**Review by emmalearnscode — APPROVED** [review]
Looks great 👍🏼

**Review by vikasganiga05 — APPROVED** [review]
LGTM :+1: Thank You for your contribution!

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍

**Pull request merged**
