### PR TITLE
Create 2022-08-27-Cloud-Community-Days-2022-Kolkata.json

### PR DESCRIPTION
**Pull request by SandipPalit**
Created 2022-08-27-Cloud-Community-Days-2022-Kolkata.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4721"></a>

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
LGTM 🎉

**Review by krshkun — COMMENTED** [review]
Looks good to me

**Comment by SandipPalit** [comment]
Hi @priyankarpal , @krshkun ,

Even after the merge. I am unable to see the event details in my profile. Can you please let me know where I made the mistake?

Thank You for your time!!

**Comment by eddiejaoude** [comment]
The events are in the past, currently we only show future events, we have a Pull Request open to allow showing of the historic events - so keep the data, it will show soon

**Pull request merged**
