### PR TITLE
data:MdMoinuddin

### PR DESCRIPTION
**Pull request by Blaize15**
New data:profile.json file added

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3594"></a>

### CODE REVIEW

**Review by Nelsonomotuyole — APPROVED** [review]
Good👍

**Comment by AwesomeArunava** [comment]
I am don't get my link

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please add your file under the `data` directory.
The filename must match your GitHub username as well.

Let us know if you need any help with that. Thanks. 🙂

**Review by Aadarsh805 — CHANGES_REQUESTED** [review]
change your file name to `data/Blaize15.json`

**Comment by Blaize15** [comment]
Thanks @Panquesito7 and @Aadarsh805 for the correction...

**Pull request closed without merging**
