### PR TITLE
Adding my profile

### PR DESCRIPTION
**Pull request by Aryan-Srivastava**

### CODE REVIEW

**Review by qwe123coder — APPROVED** [review]
hey, nice work :rocket: keep making pr like this :)
LGTM

**Review by voidz7 — APPROVED** [review]

**Review by Nikhil-1503 — APPROVED** [review]

**Review by krishdevdb — APPROVED** [review]

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
File extension is needed `.json`

**Review by voidz7 — COMMENTED** [review]
fix the extension it should be `AryanSrivastava.json`

**Comment by qwe123coder** [comment]
@Aryan-Srivastava why did you close this pr

**Pull request closed without merging**
