### PR TITLE
data: surendhar-palanisamy

### PR DESCRIPTION
**Pull request by surendhar-palanisamy**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5941"></a>

### CODE REVIEW

**Review by tangorishi — APPROVED** [review]
@surendhar-palanisamy good going! 👍🏻

**Comment by surendhar-palanisamy** [comment]
> @surendhar-palanisamy good going! 👍🏻

@tangorishi 😃

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by surendhar-palanisamy** [comment]
> Looks good to merge. Thank you for your contribution! 🎉

Thank you so much @Pradumnasaraf ❤️

**Pull request merged**
