### PR TITLE
chore: add RealSollyM

### LINKED ISSUE #1589: [OTHER] Add RealSollyM Profile
### What would you like to share?

I would like to add my profile here on LinkFree, thank you.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by RealSollyM**
Closes #1589

## Changes proposed

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Please add RealSollyM profile to LinkFree

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1590"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — APPROVED** [review]
LGTM! 👍 Thanks for contributing! 🚀

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant, Maintainable

**Review by krshkodes — APPROVED** [review]
Looks great! Thank you

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Reusable

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant, Maintainable

**Pull request merged**
