### PR TITLE
data: yashpreet2707

### PR DESCRIPTION
**Pull request by yashpreet2707**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6997"></a>

### CODE REVIEW

**Review by khushalarora — CHANGES_REQUESTED** [review]
Hey @yashpreet2707, thank you for contributing :tada: 
Your filename have an **'s'** missing in it.
Please rename your file to **`data/yashpreet2707.json`**  [Here](https://github.com/yashpreet2707/LinkFree/edit/yashpreet2707/data/yahpreet2707.json)

**Comment by yashpreet2707** [comment]
Thanks a lot @khushalarora, I've made the desired change.

**Comment by yashpreet2707** [comment]
@khushalarora, if it is correct now, can you please merge it?

**Comment by khushalarora** [comment]
Hey @yashpreet2707, I don't have the access to merge pull requests. 
Please wait for another maintainer to merge this pull request :+1:

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
