### PR TITLE
Updated links in readme

### LINKED ISSUE #1297: [DOCS] Update links in readme
**this issue is first timer friendly**

### Description

Links in the readme are outdated due Domain changed. 

New domain https://linkfree.eddiehub.io/

### Screenshots

175044A1-6F48-4E41-86B6-E59DBFBDD39E

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ioanat94**
## Fixes Issue

Closes #1297 

## Changes proposed

Changed outdated domain in readme links (eddiehub.org -> eddiehub.io).

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1299"></a>

### CODE REVIEW

**Review by schmelto — APPROVED** [review]
LGTM

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by kumarsonsoff3 — APPROVED** [review]
LGTM, Thanks for your Contribution! 🚀

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
Please also update them to https instead of http

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by ioanat94** [comment]
@emmalearnscode Done! :)

**Review by emmalearnscode — APPROVED** [review]
Thanks! looks great!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

**Pull request merged**
