### PR TITLE
fix: backticks not getting rendered in Docs

### LINKED ISSUE #2562: backticks not getting rendered in Docs
### Description

On the website, the backticks are not getting rendered. It's bolding just bolding up the text. 

**It should look something like** `sample-text` 

- Link to Docs folder - https://github.com/EddieHubCommunity/LinkFree/tree/main/pages/docs
- Link to the hosted site -  https://linkfree.eddiehub.io/docs

### Screenshots

Screenshot 2023-01-01 at 3 49 46 PM

Above Screenshot hosted link - https://linkfree.eddiehub.io/docs/contributing/hacktoberfest

### PR DESCRIPTION
**Pull request by AldrinSeanPereira**
this fix is for issue #2562 where I have set transformInLineCode to true

closes #2562

## Fixes Issue
#2562 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers
I need more advice for this PR to check if it is correct

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2566"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you Sean! Can you add a screenshot of before and after please

**Comment by AldrinSeanPereira** [comment]
just to clarify: 
do you want me to add screenshots of the code changes?
I'm not sure what to screenshot otherwise

**Comment by eddiejaoude** [comment]
Sorry for the confusion. Not the code changes because I can see the code changes in the `files changed` tab. But it would be useful to see what effect the change the config file had to the docs that are created to see if the inline code is now rendered and the issue #2562 is resolved.

**Comment by AldrinSeanPereira** [comment]
Ah I got it! I shall do that. Thank you Eddie!

**Comment by AldrinSeanPereira** [comment]
im stuck in finding the new (and correct) stuff to be displayed
 
the old error which @Pradumnasaraf had shown is in this link: 
https://linkfree.eddiehub.io/docs/contributing/hacktoberfest

**Review by dan-mba — CHANGES_REQUESTED** [review]
This line should look like:
```
remarkPlugins: [remarkGfm, [remarkPrism, {transformInlineCode: true}]],
```

**Comment by dan-mba** [comment]
In order for this to work correctly, the following code needs to be added to `styles/globals.css` before the tailwind imports:
```css
code.language-unknown::before, code.language-unknown::after {
  content: ""
}
```

Then the hacktoberfest docs will look like the following:
hacktoberfest

**Comment by AldrinSeanPereira** [comment]
Hey @dan-mba 
I have now updated the `styles/global.css` file as you have specified. 
Is it correct?

**Comment by dan-mba** [comment]
> Hey @dan-mba I have now updated the `styles/global.css` file as you have specified. Is it correct?

@AldrinSeanPereira  The styles change looks good.
Now you need to fix `next.config.mjs` like I mentioned [here](https://github.com/EddieHubCommunity/LinkFree/pull/2566#pullrequestreview-1233448008)

**Review by schmelto — APPROVED** [review]

**Comment by AldrinSeanPereira** [comment]
Thank you @schmelto for getting this fixed.
Thank you @dan-mba for your help 🙌🏼
I had been busy with work and unfortunately forgot to get back to this.

**Review by Panquesito7 — APPROVED** [review]

**Comment by eddiejaoude** [comment]
Great collab everyone 👍

**Pull request merged**
