### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by VardaanAggarwal**
Changed a word in README file which looks little better for the sentence.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1336"></a>

### CODE REVIEW

**Review by schmelto — APPROVED** [review]
## Looking good to me

Your suggested changes looking good to me.
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Review by emmalearnscode — COMMENTED** [review]
As an English speaker I think greatly sounds better. Truly is very formal.

**Comment by VardaanAggarwal** [comment]
> As an English speaker I think greatly sounds better. Truly is very formal.

Yes I agree with you on this point, but I created this PR under the thought of making it more formal.
Lemme know if it's worth merging this, or should I close this PR.

**Review by krshkodes — APPROVED** [review]
This sounds much better - thank you so much!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Comment by jaynarayan-vaishnav** [comment]
```Any contributions you make are **truly appreciated**.```
it looks good but can bbe better if we use this in my opinion 
```Any useful contributions you make are **truly appreciated**.```

**Review by jaynarayan-vaishnav — COMMENTED** [review]
```Any contributions you make are **truly appreciated**.```
it looks good but can bbe better if we use this in my opinion 
```Any useful contributions you make are **truly appreciated**.```

**Comment by VardaanAggarwal** [comment]
> `Any contributions you make are **truly appreciated**.`
> it looks good but can bbe better if we use this in my opinion
> `Any useful contributions you make are **truly appreciated**.`

Hey @jaynarayan-vaishnav , that was smooth !😆
I will keep that in mind !
Thanks for the review !

**Review by kumarsonsoff3 — COMMENTED** [review]
I agreed with your point, that **Truly** looks more formal. 
But here **Greatly appreciated** feels kind of way more rewarding to the Reader, isn't it!? 🤩

> Like **Truly Appreciated** 🙂 or **Greatly Appreciated** 🤩

So I think **Greatly** is fine as just it is. Probably I would not suggest making any change in this. 
What do other Reviewers think about this!?

**Comment by kumarsonsoff3** [comment]
> `Any contributions you make are **truly appreciated**.` it looks good but can bbe better if we use this in my opinion `Any useful contributions you make are **truly appreciated**.`

Buddy keep it simple. We are here to decide whether the contribution is useful to the project or not. 
But what I think is that adding like `"Any useful contribution"` will step the first-time contributor a step backward. 

He might think "Will such a small think be useful for this project."

**Comment by jaynarayan-vaishnav** [comment]
@kumarsonsoff3  Thanks for your input on this 🙂  it was just an opinion to make the guidelines more clear

**Review by Vyvy-vi — APPROVED** [review]
Thanks for the change 👍 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Reusable

**Pull request merged**
