### PR TITLE
Aravindraveendran7 patch 6

### PR DESCRIPTION
**Pull request by aravindraveendran7**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4529"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Looks good 👍 

But please remove all other changes 
1. check your fork is up to date
2. check GitHub actions are not running on your fork

**Comment by aravindraveendran7** [comment]
Thank you @eddiejaoude.
Could you also please brief the other changes preventing this PR merging from being blocked?
I am not running GitHub actions on my fork and also forked repo is up to date. Please find the screenshot
fork repo

**Comment by eddiejaoude** [comment]
It looks like you have GitHub Actions running on your fork which is causing the issue https://github.com/aravindraveendran7/LinkFree/actions - please turn these off (they should be off by default - I will try to find a way to make sure they don't run on forks in the future)

I think the easiest way is to delete your fork and recreate your changes

**Comment by aravindraveendran7** [comment]
Thank you for the feedback @eddiejaoude.I have disabled them from Actions. However, on the safer side deleted the old repo and forked a new one. PR #4539  has been raised.

**Pull request closed without merging**
