### PR TITLE
chore: Added Krish Gupta

### PR DESCRIPTION
**Pull request by krshkodes**
## Fixes Issue

Added my profile to linkfree

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1595"></a>

### CODE REVIEW

**Comment by krshkodes** [comment]
I created this profile to create this workflow, please have a look and tell me if it looks fine: https://app.tango.us/app/workflow/How-to-create-a-LinkFree-Profile-b57e1bccb3674c3fb1840a6fc031a921

Also PLEASE DO NOT MERGE this PR, I will create a bump commit to fix #1594 in the same PR

**Review by imlakshay08 — APPROVED** [review]

**Review by RealSollyM — APPROVED** [review]
LGTM : Clear to merge.

**Review by RealSollyM — CHANGES_REQUESTED** [review]
Please consider updating the README or proposing a new file that would support the CREATE NEW PROFILE workflow as part of this project, rather than an outside service.

**Review by Vyvy-vi — APPROVED** [review]
LGTM!

**Pull request merged**
