### PR TITLE
increases the font size of feature section

### LINKED ISSUE #7297: Font size is too small for Feature section description on MainPage (Desktop)
### Description

Font size is too small for the Feature Section (Heading/Description) on Main page.
We can increase it a little more to make it look good.

### Screenshots

image

### Additional information

Please make sure the Mobile view in not impacted, handle it too.

### PR DESCRIPTION
**Pull request by KushagraVarshney05**
## Fixes Issue

Closes #7297 
## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Increases the size of the feature section heading and description without affecting the mobile view. 
As I am new to open source please let me know if I have done any mistake.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7342"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Please remove the changes to the `package-lock.json` file, these changes are not required

**Comment by KushagraVarshney05** [comment]
I have undo all changes in package-lock.json

**Comment by KushagraVarshney05** [comment]
still waiting for review

**Comment by eddiejaoude** [comment]
> still waiting for review

@KushagraVarshney05 it has only been a few hours, please remember we all live in different timezones and have other responsibilities

Did you mean to close your PR?

**Comment by eddiejaoude** [comment]
New PR raised here https://github.com/EddieHubCommunity/LinkFree/pull/7367

**Pull request closed without merging**
