### PR TITLE
0x prakhar g patch 2

### PR DESCRIPTION
**Pull request by 0xPrakharG**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2988"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by 0xPrakharG** [comment]
> Thanks! 🎉

> When will this branch get merged?

**Comment by Panquesito7** [comment]
> > Thanks! 🎉
> 
> When will this branch get merged?

Once it gets approved by another maintainer, it will be merged into the `main` branch. 🙂

**Comment by 0xPrakharG** [comment]
> > > Thanks! 🎉
> > 
> > 
> > When will this branch get merged?
> 
> Once it gets approved by another maintainer, it will be merged into the `main` branch. 🙂

Okay Cool✌🏻

**Pull request merged**
