### PR TITLE
data: RitaMwas

### PR DESCRIPTION
**Pull request by RitaMwas**

### CODE REVIEW

**Review by dan-mba — CHANGES_REQUESTED** [review]
Please remove the comma at the end of line 19 and add a `],` on the next line before the links section.

**Review by dan-mba — APPROVED** [review]
Looks good to me

**Comment by RitaMwas** [comment]
awesome. Who should close this? Also, does the changes reflect on my profile or I have to wait for changes to take effect?

**Comment by dan-mba** [comment]
> awesome. Who should close this? Also, does the changes reflect on my profile or I have to wait for changes to take effect?

I am a new maintainer, so I like to get a double check from someone else before merging.
All the maintainers are in different time zones (I am 8 hours behind you) but someone else should get it merged sometime today.
After merge, the updates should get pushed to the site within10-15 minutes.

**Review by kumarsonsoff3 — APPROVED** [review]
Look Good, Thanks! 👍

**Pull request merged**
