### PR TITLE
fix(update-profile): new pic

### PR DESCRIPTION
**Pull request by krishguptadev**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/712"></a>

### CODE REVIEW

**Review by schmelto — COMMENTED** [review]
Not a fan of not using github images 🙈

**Comment by krishguptadev** [comment]
> Not a fan of not using github images 🙈

I am gonna do something crazy maybe with my github pic that is why... 😅

**Review by Vyvy-vi — APPROVED** [review]
LGTM!

**Review by Panquesito7 — COMMENTED** [review]
LGTM! 🚀

**Pull request merged**
