### PR TITLE
Ayush sarode patch 1 2

### PR DESCRIPTION
**Pull request by AyushSarode**
added personal data in AyushSarode.json

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2824"></a>

### CODE REVIEW

**Review by Njong392 — APPROVED** [review]
Good thing correcting the link! Looks okay to me :confetti_ball:

**Comment by AyushSarode** [comment]
> Good thing correcting the link! Looks okay to me 🎊

how can I delete my previous account in linkfree?

**Comment by Njong392** [comment]
If by account you mean profile, then you'll have to delete the `json` file related to your profile.

**Comment by AyushSarode** [comment]
> If by account you mean profile, then you'll have to delete the `json` file related to your profile.

It is not showing in this repo, eddie closed that one, still it's showing

**Comment by Njong392** [comment]
I'm sorry, but I'm a little lost. I can see the `json` file attributed to your profile in this repo.

**Comment by AyushSarode** [comment]
https://github.com/EddieHubCommunity/LinkFree/pull/2715#issuecomment-1374133869

> I'm sorry, but I'm a little lost. I can see the `json` file attributed to your profile in this repo.

**Comment by AyushSarode** [comment]
Thanks for help!, I did!

**Comment by Njong392** [comment]
I see you created a PR in #2825 that deletes your `json` file. The maintainers will close this PR.

**Comment by AyushSarode** [comment]
Thanks for help, I'll figure it out later!

**Comment by eddiejaoude** [comment]
Hi @AyushSarode, when we merge this pull request, it will update your profile, you don't need to delete the file. I have closed your other pull request that deletes the file. 

I will merge this now, I hope that gives you what you are looking for, but I mis-understand please let me know and we will find a way to solve it.

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by AyushSarode** [comment]
> Hi @AyushSarode, when we merge this pull request, it will update your profile, you don't need to delete the file. I have closed your other pull request that deletes the file.
> 
> I will merge this now, I hope that gives you what you are looking for, but I mis-understand please let me know and we will find a way to solve it.
> 
> Thanks for helping @Njong392 👍

Thanks a lotttt @eddiejaoude  and @Njong392!
Very helpful community.

**Comment by eddiejaoude** [comment]
You are welcome, you should see all your changes on your profile here https://linkfree.eddiehub.io/AyushSarode

**Pull request merged**
