### PR TITLE
Portfolio URL changed

### PR DESCRIPTION
**Pull request by JoBaHP**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1789"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts [here](https://github.com/EddieHubCommunity/LinkFree/pull/1789/conflicts).
Let us know if you need any help with this! 🙃

**Comment by JoBaHP** [comment]
fixed

**Review by EmmaDawsonDev — APPROVED** [review]
Looks good 👍

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thank you! 🎉

**Pull request merged**
