### PR TITLE
Profile customisation options

### LINKED ISSUE #133: Add accent color for the user profile
Add accent color for the user profile. So they can change the badge color.

### PR DESCRIPTION
**Pull request by nasrob**
## Fixes Issue

Closes #133

## Check List (Check all the boxes which are applicable) 

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/466"></a>

### CODE REVIEW

**Review by krishguptadev — CHANGES_REQUESTED** [review]
@nasrob can you resolve the merge conflicts?

**Comment by nasrob** [comment]
@krishguptadev, I think it's better to close this pull request since it's not up to date with the project structure any more.

**Comment by emmalearnscode** [comment]
I think this change could lead to some accessibility issues with colour contrast. The example with orange text on purple background is pretty much unreadable for me and not everyone will check their colours are accessible before adding them. @nasrob if you don’t want to fix the merge conflicts feel free to close the pr.

**Comment by Vyvy-vi** [comment]
> @krishguptadev, I think it's better to close this pull request since it's not up to date with the project structure anymore.

@nasrob would you be interested in continuing working on #133, and transferring these changes onto an updated version of the project?

Thank you for contributing to LinkFree!

**Pull request closed without merging**
