### PR TITLE
Update 0rigin-c0de.json

### PR DESCRIPTION
**Pull request by 0rigin-c0de**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5167"></a>

### CODE REVIEW

**Review by sidharthviz — APPROVED** [review]
Looks Good 👍🏼

**Review by SurajPratap10 — APPROVED** [review]
looks ok

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts [**here**](https://github.com/EddieHubCommunity/LinkFree/pull/5167/conflicts). If you need any help, you can ask for help here or on our [**Discord server**](http://discord.eddiehub.org). You can also check the [GitHub Docs](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) to make the process easier. 🙂

**Comment by SaraJaoude** [comment]
Given the length of time this Pull Request has been open and the conflicts have not been resolved, I will be closing it. 

If you wish to make changes to your Profile I suggest you look at our Editing Guide in Docs which also contains a video as to how to avoid conflicts: https://linkfree.eddiehub.io/docs/how-to-guides/editing

**Pull request closed without merging**
