### PR TITLE
updated wasiqb profile

### PR DESCRIPTION
**Pull request by WasiqB**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2819"></a>

### CODE REVIEW

**Review by Njong392 — CHANGES_REQUESTED** [review]
Thank you very much for contributing to LinkFree! Your contribution came with a change to the `package-lock.json` file. You need to revert this.

You can check [here](https://gist.github.com/kumarsonsoff3/fbc6ecde519250a9f0a4d7ccc9993a1a) for easy steps on reverting.

**Comment by WasiqB** [comment]
@Njong392 , I have reverted the changes to `package-lock.json` file by copy-pasting content from base branch. Kindly check and let me know if it's fine.

**Comment by eddiejaoude** [comment]
@WasiqB your base branch might be out of date as it is still showing changes.

I would suggest
1. update the `main` branch in your fork
2. in your PR branch use the command `git checkout main -- package-lock.json`
3. this will remove any changes to the lock file ad put back to what is in `main`

**Comment by WasiqB** [comment]
Thanks @eddiejaoude , I was able to successfully revert `package-lock.json` file.

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍 

Btw your filename does not match your GitHub username exactly with case - this will work now, but may break in the future. I recommend creating a new pull request updating the filename to be case sensitive to match your GitHub username

**Pull request merged**
