### PR TITLE
data: YashPimple

### PR DESCRIPTION
**Pull request by YashPimple**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2883"></a>

### CODE REVIEW

**Comment by Aadarsh805** [comment]
@YashPimple there's a typo in your LinkedIn icon it should be `FaLinkedin`

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good to me! 👍

**Comment by kumarsonsoff3** [comment]
> @YashPimple there's a typo in your LinkedIn icon it should be `FaLinkedin`

Great catch aadarsh, didn't notice in the past changes! 👍 
@YashPimple Please update your LinkedIn icon as suggested by Aadarsh!

**Comment by YashPimple** [comment]
@Aadarsh805 made the changes do have a look 😊

**Review by Aadarsh805 — APPROVED** [review]
All good 👍

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
