### PR TITLE
Create chidubem.json profile page

### PR DESCRIPTION
**Pull request by Duks31**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1934"></a>

### CODE REVIEW

**Comment by Duks31** [comment]
Happy to Join the community 
My first opensource PR :)

**Review by AryanBabber — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thanks! 🎉

**Review by accodes21 — CHANGES_REQUESTED** [review]
Thanks for contributing.
Everything looks good but just change the small typo at ```icon : LinkedIn```

**Comment by Duks31** [comment]
Thanks 
Changing that right away

**Comment by Duks31** [comment]
Sorry, 
I am having a problem, I cant see my file ( chidubem.json ) in either my fork or in the EddieHub fork 

I dont know what is wrong

**Comment by Panquesito7** [comment]
> Sorry, I am having a problem, I cant see my file ( chidubem.json ) in either my fork or in the EddieHub fork
> 
> I dont know what is wrong

Try checking the `Duks-patch-1` branch https://github.com/Duks31/LinkFree/tree/Duks31-patch-1

**Comment by Duks31** [comment]
OK 
Thanks, I found it 👍

But it hasnt been merged to EddieHubCommunity

**Comment by Panquesito7** [comment]
> OK Thanks, I found it 👍
> 
> But it hasnt been merged to EddieHubCommunity

If you want to update this PR, it doesn't have to be merged.

**Comment by Duks31** [comment]
OK Thanks 

But the LinkFree webite doesnt have link yet, Thats why i am asking about the merging.

**Comment by Panquesito7** [comment]
> OK Thanks
> 
> But the LinkFree webite doesnt have link yet, Thats why i am asking about the merging.

Hmm, what do you mean? 🤔

**Comment by Duks31** [comment]
I addem my json file chidubem.json to the LinkFree/public/data  folder, 

According to the instructions which i followed up to this point i have made a PR and it has been approved so i am waiting for the merge

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good to me! 🎉

**Comment by Duks31** [comment]
Thanks for the Merge 🤩

**Pull request merged**
