### PR TITLE
Update sejosephmartin.json

### PR DESCRIPTION
**Pull request by sejosephmartin**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6402"></a>

### CODE REVIEW

**Review by harshsingh32 — DISMISSED** [review]
lgtm

**Comment by Aniket1026** [comment]
Looks good but i think the file is not formatted 🙂

**Comment by Aniket1026** [comment]
> > Looks good but i think the file is not formatted 🙂
> 
> what do you mean? can you give example on how can i fix the format? thank you!

If you are using VS code as editor you can use `shift+alt+f ` keys to format your file. Also you can try using the feature in Linkfree to format and preview your profile.
*  visit the  Linkfree playground -> https://linkfree.eddiehub.io/playground
* Enter your github user name in the input field and paste the json file in the field below like this
 
image

* Then click the format button on the bottom right  and your file will be formatted 🎉

* Aditionally,you can also validate by clicking the validate button on the bottom right

image

* You can also see how your profile will look to others by clicking the preview button which will appear after the validation

image

* This is how my profile will look to others same way you can format and see , how your profile will look to others

image

If you want any further help let me know 🙂

**Comment by sejosephmartin** [comment]
> > > Looks good but i think the file is not formatted 🙂
> > 
> > 
> > what do you mean? can you give example on how can i fix the format? thank you!
> 
> If you are using VS code as editor you can use `shift+alt+f ` keys to format your file. Also you can try using the feature in Linkfree to format and preview your profile.
> 
> * visit the  Linkfree playground -> https://linkfree.eddiehub.io/playground
> * Enter your github user name in the input field and paste the json file in the field below like this
> 
> image
> 
> * Then click the format button on the bottom right  and your file will be formatted 🎉
> * Aditionally,you can also validate by clicking the validate button on the bottom right
> 
> image
> 
> * You can also see how your profile will look to others by clicking the preview button which will appear after the validation
> 
> image
> 
> * This is how my profile will look to others same way you can format and see , how your profile will look to others
> 
> image
> 
> If you want any further help let me know 🙂

can you check if the format was correct? thank you for helping me out! : )

**Review by sidharthviz — APPROVED** [review]
LGTM

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
