### PR TITLE
Yet another branch

### PR DESCRIPTION
**Pull request by xperience001**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2634"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
There are 2 PR that almost have the same changes, please close the one you don't want to keep

Here is the other PR https://github.com/EddieHubCommunity/LinkFree/pull/2633

You cannot change someone else's profile, please only change your json that matches you GitHub username

**Comment by xperience001** [comment]
Done

**Comment by eddiejaoude** [comment]
Thank you for closing the other PR.

This PR still cannot be merge though because you have made changes to someone else's profile `data/yashsharma999.json` and this is not allowed

**Comment by xperience001** [comment]
> Thank you for closing the other PR.
> 
> This PR still cannot be merge though because you have made changes to someone else's profile `data/yashsharma999.json` and this is not allowed

Changes have been reversed

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
