### PR TITLE
Create Ali Reza

### PR DESCRIPTION
**Pull request by AliReza1083**
I made a JSON file and it's about me

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1619"></a>

### CODE REVIEW

**Review by 2802AdityA — APPROVED** [review]
Looks good to me 👍🏼

**Comment by AliReza1083** [comment]
@Panquesito7 
It's been updated.

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🎉


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant, Maintainable

**Review by kumarsonsoff3 — APPROVED** [review]
LGTM! Thanks for contributing! 🚀 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Pull request merged**
