### PR TITLE
Add Vedant Pople profile to LinkFree

### PR DESCRIPTION
**Pull request by vedantpople4**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1333"></a>

### CODE REVIEW

**Review by Shivansh-yadav13 — APPROVED** [review]
LGTM :+1: 
but remove the `package-lock.json` file from the commit :)

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please revert the changes in the `package-lock.json` file. Let us know if you need any help! :)

**Comment by vedantpople4** [comment]
package-lock.json file removed as instructed.

**Comment by kumarsonsoff3** [comment]
> LGTM 👍 but remove the `package-lock.json` file from the commit :)

**Note to the Reviewer:** @Shivansh-yadav13 Please don't suggest people to **"remove the `package-lock.json` file from commit"**, because the way you say, people take it wrong and delete the file from their fork!

You can say like @Panquesito7 said to **"Revert the changes from the `Package-lock.json` File!!"** 🙂

**Comment by kumarsonsoff3** [comment]
> package-lock.json file removed as instructed.

Unfortunately, you have deleted the `package-lock.json` file, you have to just revert the changes from it!

Now just copy the content from the main [Package-lock.json](https://github.com/EddieHubCommunity/LinkFree/blob/main/package-lock.json), and add it to your fork to avoid the conflicts with the main branch!!
Let us know if you need any help.

**Comment by Shivansh-yadav13** [comment]
> > LGTM +1 but remove the `package-lock.json` file from the commit :)
> 
> **Note to the Reviewer:** @Shivansh-yadav13 Please don't suggest people to **"remove the `package-lock.json` file from commit"**, because the way you say, people take it wrong and delete the file from their fork!
> 
> You can say like @Panquesito7 said to **"Revert the changes from the `Package-lock.json` File!!"** slightly_smiling_face

Really sorry for that 😅

**Comment by vedantpople4** [comment]
> > package-lock.json file removed as instructed.
> 
> @vedantpople4 Unfortunately, you have deleted the `package-lock.json` file, you have to just revert the changes from it!
> 
> Now just copy the content from the main [Package-lock.json](https://github.com/EddieHubCommunity/LinkFree/blob/main/package-lock.json), and add it to your fork to avoid the conflicts with the main branch!! Let us know if you need any help.

The file has been added as instructed. No conflicts with the main branch !

**Comment by emmalearnscode** [comment]
You need to copy the package-lock file from the Eddiehub repo, and paste it into your package-lock file. Check that the version in your file is the same as the version in Eddiehub then push the changes. There should only be 1 file in this pull request if you do it correctly.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by vedantpople4** [comment]
Even in the latest commit, only the data folder was committed but still it shows that 2 files have been changed

**Pull request closed without merging**
