### PR TITLE
Added code to quick copy all env vars

### LINKED ISSUE #6114: [DOCS] Quick copy all required env vars
### Description

The variables documentation has a nice table of all the variables and what they mean, but you must copy/paste individually into your project.  The idea for this issue would be to create a button on that page to copy the required variable to be able to quickly post them to your local .env file.

docs page: https://linkfree.io/docs/environments/environment-variables

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by PratikDey**
Closes #6114 

## Fixes Issue
Added code as per the issue suggestion

## Changes proposed
Added Clipboard copy to environment docs to quick copy all environment variables

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6594"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
The lock file changes are not required. Please remove these changes

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Please do not delete the package lock file, it is required. 

Your changes to the file are not needed though, I made a video on why this is and how to fix https://www.youtube.com/watch?v=jHkIXYVpMTo

**Comment by eddiejaoude** [comment]
The table is copied not the environment variables

Got this...

```
| variable                         | example                            | required | description                                         |
| :------------------------------- | :--------------------------------- | :------- | :-------------------------------------------------- |
| LINKFREE_MONGO_CONNECTION_STRING | mongodb://localhost:27017/linkfree | true     | Database connection string                          |
| NEXT_PUBLIC_GA_MEASUREMENT_ID    | -                                  | false    | Google analytics id                                 |
| NEXT_PUBLIC_BASE_URL             | http://localhost:3000              | true     | Hosting url                                         |
| NODE_ENV                         | development                        | true     | -                                                   |
| GITHUB_ID                        | abcedfghil12345                    | true     | GitHub OAuth ID                                     |
| GITHUB_SECRET                    | a1b2c3e4f5e6                       | true     | GitHub OAuth Secret                                 |
| NEXTAUTH_SECRET                  | afsfdsafadsf                       | true     | Next Auth Secret, this can be any random characters |
```

But was expecting this...

```
LINKFREE_MONGO_CONNECTION_STRING="mongodb://localhost:27017/linkfree"
NEXT_PUBLIC_GA_MEASUREMENT_ID=""
NEXT_PUBLIC_BASE_URL="http://localhost:3000"
NODE_ENV="development"

GITHUB_ID=""
GITHUB_SECRET=""
NEXTAUTH_SECRET=""
NEXTAUTH_URL="http://localhost:3000"
```

**Comment by PratikDey** [comment]
Hi, I think I made some big mistake.

**Comment by eddiejaoude** [comment]
no problem @PratikDey , as you have closed your PR would you like me to unassign the issue from you?

**Comment by PratikDey** [comment]
No @eddiejaoude , I was trying to fix the package-lock issue and I did some updates on my branch, discarded changes and saw that the PR got closed. I'm sorry for doing mistakes like this.

**Comment by eddiejaoude** [comment]
no problem, it happens, let us know in Discord if you need any help - I will leave the issues assigned to you

**Pull request closed without merging**
