### PR TITLE
Patelrahul4884 patch 1

### PR DESCRIPTION
**Pull request by Patelrahul4884**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2710"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
You have merge conflicts with yourself on your json file. Make sure you update your fork before making changes. 

Please resolve merge conflicts on `data/Patelrahul4884.json`.

**Comment by Patelrahul4884** [comment]
@kumarsonsoff3 where is the conflict?

**Comment by Panquesito7** [comment]
> @kumarsonsoff3 where is the conflict?

You can check them here: https://github.com/EddieHubCommunity/LinkFree/pull/2710/conflicts
Should be at the bottom of every PR if there are conflicts.

**Comment by Patelrahul4884** [comment]
@Panquesito7 @kumarsonsoff3  how to resolve conflict?

**Comment by eddiejaoude** [comment]
You have a conflict with yourself because you made changes without updating your fork. Your file already exists here https://github.com/EddieHubCommunity/LinkFree/blob/main/data/Patelrahul4884.json

We have docs here to update your profile https://linkfree.eddiehub.io/docs/how-to-guides/editing

It is probably easier for you to close your pull request, and follow the docs

**Pull request closed without merging**
