### PR TITLE
Data: mustafaansarii

### PR DESCRIPTION
**Pull request by mustafaansarii**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5113"></a>

### CODE REVIEW

**Review by Panquesito7 — DISMISSED** [review]
Thanks! 🎉

**Review by mahfuztbt — APPROVED** [review]
looks good

**Review by SurajPratap10 — APPROVED** [review]
looks good

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
