### PR TITLE
FEATURE to Add events validation in playground

### LINKED ISSUE #5457: [FEATURE] Add events validation in playground
### Description

Add another option in the playground for events just like profile:

   - validates json
   - formats json
   - shows event card

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by vibronst**
Closes #5457 

## Changes proposed

Modified Playground.js to allow for event validation
Added EventPreview.js file

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

Screen Shot 2023-04-05 at 6 08 27 PM

Screen Shot 2023-04-05 at 6 08 53 PM

Screen Shot 2023-04-05 at 6 09 16 PM

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5865"></a>

### CODE REVIEW

**Comment by vibronst** [comment]
I wanted to let you know that my partner Kaveri made a pull request for an issue that we worked together on for this issue! Please refer to her pull request rather than this one! Her pull request is #5866

**Comment by vibronst** [comment]
Could you close this pull request and assign it to 5866?  We worked together on it.

**Comment by eddiejaoude** [comment]
@vibronst you are able to close your own pull request, this will help maintainers.

It is great you are both collaborating together on an issue and pull request 👍  but please have the issue assigned to you both and you can both work on the same pull request to avoid confusion

**Comment by eddiejaoude** [comment]
> Could you close this pull request and assign it to 5866? We worked together on it.

ok

**Pull request closed without merging**
