### PR TITLE
fix-cont

### PR DESCRIPTION
**Pull request by xperience001**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2740"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]

**Comment by eddiejaoude** [comment]
@xperience001 you already have your profile there, I think you created a new branch from your previous branch, so that is why this Pull Request contains your previous commits

I suggest, closing this PR and creating a new one, but when you create a new PR try these steps
1. change back to the main branch
2. update the main branch
3. create your new branch
4. make changes to your new branch
5. create new PR

I hope that helps. Any questions come and ask in the EddieHub Discord

**Comment by eddiejaoude** [comment]
You already have your profile here https://github.com/EddieHubCommunity/LinkFree/blob/main/data/xperience001.json, you don't need to create it again but edit your profile to make changes

Here are the documentation to edit your profile https://linkfree.eddiehub.io/docs/how-to-guides/editing

**Comment by eddiejaoude** [comment]
I think this is a duplicate pull request of https://github.com/EddieHubCommunity/LinkFree/pull/2795 please close any pull requests you no longer need

**Comment by SaraJaoude** [comment]
closing as a duplicate

**Pull request closed without merging**
