### PR TITLE
data:fatimakay

### PR DESCRIPTION
**Pull request by fatimakay**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [] My change requires changes to the documentation.
- [] I have updated the documentation accordingly.
- [] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

image_2023-01-08_164602863

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2863"></a>

### CODE REVIEW

**Review by ad3rinto — APPROVED** [review]
This is brilliantly done.
Well done Fatima.

**Review by debasishbsws — APPROVED** [review]
Looks Good!

**Comment by fatimakay** [comment]
Thank you!

> Looks Good!



> This is brilliantly done. Well done Fatima.

Thank you so much! Appreciate the feedback

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
