### PR TITLE
data: AussieDev81

### PR DESCRIPTION
**Pull request by AussieDev81**
## Changes proposed

- [x] Added data profile for AussieDev81

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3773"></a>

### CODE REVIEW

**Review by Tejender1521 — APPROVED** [review]
Everything looks good and ready to be merged

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by AussieDev81** [comment]
Thank you 😊

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good to merge, Thanks for your Contribution! 🎉
<p align="center"></p>

**Pull request merged**
