### PR TITLE
data:ikembakwem

### PR DESCRIPTION
**Pull request by ikembakwem**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by rahulpandey70 — APPROVED** [review]
Everything looks good.

**Review by priyankarpal — APPROVED** [review]
Awesome 🎉 Thanks for your first contribution. You can add more links here.

**Comment by kumarsonsoff3** [comment]
Hey @ikembakwem, Your PR #4478 to add profile has already been **merged**, and your profile is live at https://linkfree.eddiehub.io/ikembakwem 

So you can close this one, and if you need to make any changes in your profile you can follow the [editing docs here](https://linkfree.eddiehub.io/docs/how-to-guides/editing).

**Comment by SaraJaoude** [comment]
I am closing this issue as @kumarsonsoff3 is correct. 

@ikembakwem if you would like to make changes to your Profile then please follow @kumarsonsoff3 suggestion

**Pull request closed without merging**
