### PR TITLE
ci: lighthouse

### PR DESCRIPTION
**Pull request by krshkodes**
Successor of #927

This is not the final copy of the action probably, this is just to get started, we can improve it as we use :D

@eddiejaoude you need to do this before this PR can be merged: https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md#github-app-method-recommended

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1152"></a>

### CODE REVIEW

**Review by schmelto — APPROVED** [review]
lgtm

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by ahmed82 — APPROVED** [review]
Duplicate

**Comment by eddiejaoude** [comment]
Can we use an existing Action like this one? https://github.com/marketplace/actions/lighthouse-audit

**Comment by krshkodes** [comment]
It seems to not be maintained well @eddiejaoude 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

**Comment by EmmaDawsonDev** [comment]
I'm going to close this for now, hopefully we can find an action that does something similar instead.

**Pull request closed without merging**
