### PR TITLE
created my profile to be added

### PR DESCRIPTION
**Pull request by SanDiego2049**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1831"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🎉

**Comment by SanDiego2049** [comment]
> Thanks for contributing! 🎉

do i close the pr now for it to be final?

**Review by imlakshay08 — APPROVED** [review]

**Comment by imlakshay08** [comment]
> > Thanks for contributing! tada
> 
> do i close the pr now for it to be final?

You do not need to close the PR. Maintainers will merge the PR first and then it will be closed on it's own

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good to me! 🚀

**Pull request merged**
