### PR TITLE
Simple cursor fix

### LINKED ISSUE #2411: QR code button on profile doesnt have cursor: pointer
### Description

QR code button on user profile doenst display cursor:pointer when hoverin over it.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by furkanmutlu**
## Fixes Issue

Closes #2411 

## Changes proposed

Added cursor-pointer class to wrapping div.

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2412"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
The changes look good; thanks! 🎉 You just need to revert the changes in the `CHANGELOG.md`, `package-lock.json`, and `package.json` files.
To make it easier/quicker, you can just copy the contents from the original files in the repository.

If you need any help, let us know! 🙂

**Review by schmelto — CHANGES_REQUESTED** [review]
please revert the changes made in CHANGELOG.md, package-lock.json and package.json other wise the change in UserProfile.js looking goof to me

**Comment by furkanmutlu** [comment]
@schmelto @Panquesito7 no idea how those changes went through, but I fix it. Thanks

**Review by schmelto — APPROVED** [review]

**Comment by Panquesito7** [comment]
> @schmelto @Panquesito7 no idea how those changes went through, but I fix it. Thanks

It seems to be happening in other PRs. Probably when building or such? Not sure. 🤔

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🚀

**Pull request merged**
