### PR TITLE
data: panwar8279

### PR DESCRIPTION
**Pull request by panwar8279**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7381"></a>

### CODE REVIEW

**Review by krishstwt — APPROVED** [review]
Looks good!

**Review by Alkaison — APPROVED** [review]
Looks Good!

**Comment by katzjeff** [comment]
Looks good to me.

**Review by SaraJaoude — DISMISSED** [review]
Please move your file to the `data` folder and make sure that your file name matches your GitHub username exactly. Instead of `pratigya.json` it should be `data/panwar8279.json`

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

**Comment by SaraJaoude** [comment]
@krishstwt @Alkaison and @katzjeff thank you for taking the time to review this Pull Request, but as you can see from my comment above this is not ready to be merged.  In future please can you take extra care before approving with "looks good" - incorrect approvals cause confusion for maintainers and the author.

**Comment by katzjeff** [comment]
> @krishstwt @Alkaison and @katzjeff thank you for taking the time to review this Pull Request, but as you can see from my comment above this is not ready to be merged.  In future please can you take extra care before approving with "looks good" - incorrect approvals cause confusion for maintainers and the author.

@SaraJaoude Noted on this. Sorry for the oversight. Will take note on future reviews

**Comment by Alkaison** [comment]
@SaraJaoude Noted. Will make sure next time.

**Comment by krishstwt** [comment]
@SaraJaoude Noted. I missed looking at the file name, sorry about that

**Comment by SaraJaoude** [comment]
> Please move your file to the `data` folder and make sure that your file name matches your GitHub username exactly. Instead of `pratigya.json` it should be `data/panwar8279.json`
> 
> I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

@panwar8279 please let us know if you need any help with this so that we can get this Pull Request merged and you can have your LinkFree Profile.

**Pull request merged**
