### PR TITLE
data: flexzy2011

### PR DESCRIPTION
**Pull request by flexzy2011**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Hello EddieHubCommunity maintainers, my name is Felix. This is my first time contributing to this project and I think I've followed the required steps needed to contribute to this project.  I will be so glad if it gets merged. Thanks

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8174"></a>

### CODE REVIEW

**Review by Sindhuinti — APPROVED** [review]
LGTM 🎉

**Review by accodes21 — CHANGES_REQUESTED** [review]
No need for ```displayStatsPublic``` and ```type``` Please refer to the new format.

**Comment by flexzy2011** [comment]
> No need for `displayStatsPublic` and `type` Please refer to the new format.

@accodes21 Can you please put me through on how to go back to the j.son file and make these changes?

**Comment by accodes21** [comment]
> > > > No need for `displayStatsPublic` and `type` Please refer to the new format.
> > > 
> > > 
> > > @accodes21 Can you please put me through on how to go back to the j.son file and make these changes?
> > 
> > 
> > Open the JSON file you just created and edit it by referring to the new format https://linkfree.io/docs/quickstart-json. after that push those changes to the same PR.
> 
> @accodes21 thanks I’ve just made the changes, Can you please check to confirm I did it right?

Yup everything looks good, still ```avatar``` is not required remove it and then it will be ready to merge

**Comment by flexzy2011** [comment]
> > > > > No need for `displayStatsPublic` and `type` Please refer to the new format.
> > > > 
> > > > 
> > > > @accodes21 Can you please put me through on how to go back to the j.son file and make these changes?
> > > 
> > > 
> > > Open the JSON file you just created and edit it by referring to the new format https://linkfree.io/docs/quickstart-json. after that push those changes to the same PR.
> > 
> > 
> > @accodes21 thanks I’ve just made the changes, Can you please check to confirm I did it right?
> 
> Yup everything looks good, still `avatar` is not required remove it and then it will be ready to merge

Ok thanks, I’ve just removed it. 🙏🏾

**Review by SaraJaoude — APPROVED** [review]
thank you for making the changes - looks good

**Comment by flexzy2011** [comment]
Thanks @SaraJaoude and @accodes21

**Pull request merged**
