### PR TITLE
Added NodeJs & Laravel Icons

### PR DESCRIPTION
**Pull request by dev-vinny**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1275"></a>

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
There is a **vertical bar** ( `|` ) missing between the two elements of the table. That's why both social and icon get merged into a single cell.

<details>

<summary>Screenshot - Click here for the preview </summary>

Screenshot from 2022-05-07 09-24-54

<details>


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Icons should be Alphabetically arranged in icon.md file!

**Comment by dev-vinny** [comment]
This was my first contribution and pull request.
Thank you for your support and time in fixing them.

**Comment by kumarsonsoff3** [comment]
> This was my first contribution and pull request. Thank you for your support and time in fixing them.

I've rearranged the icons for you, you just need to merge the PR [#2](https://github.com/dev-vinny/LinkFree/pull/2) to your fork!

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good to me! 👍 Thank you for your contribution! 🚀

**Review by emmalearnscode — APPROVED** [review]
Great, thank you so much for your contribution!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

**Review by ahmed82 — APPROVED** [review]
looks good

**Pull request merged**
