### PR TITLE
Create VishalPrakash.json

### PR DESCRIPTION
**Pull request by prakashvishal93**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6165"></a>

### CODE REVIEW

**Review by himanshu1221 — CHANGES_REQUESTED** [review]
1) Please move your JSON file to `/data` folder
2) Rename your file to your `GitHub username`

**Review by harshsingh32 — COMMENTED** [review]
Looks fine

**Comment by SaraJaoude** [comment]
> Looks fine

@harshsingh32 I would suggest looking at historic conversation before writing this type of comment, as I have seen that you have commented "looks fine" and "LGTM" in other PRs when changes still need to be made by the author before the PR can be merged.  This causes confusion not just for the author but for everyone else, as well as unnecessary notifications for the maintainers.

**Comment by SaraJaoude** [comment]
Given the length of time this PR has been open, I will merge and fix in a temporary branch.

**Pull request merged**
