### PR TITLE
Added my profile 

### PR DESCRIPTION
**Pull request by adilwahla**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1805"></a>

### CODE REVIEW

**Review by adilwahla — COMMENTED** [review]
created new json file with my unique name & added data accordingly

**Review by schmelto — APPROVED** [review]
## Looking good to me

Your suggested changes looking good to me.

---
**Summary:** :ok_hand: This code looks good

**Review by adilwahla — COMMENTED** [review]
Looks good now what do you all think? :)

**Review by Panquesito7 — APPROVED** [review]
Looks great. Thanks! 🎉

**Pull request merged**
