### PR TITLE
docs: Formatted some lines of README file

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
## Changes proposed

I have added a **NOTE block** for the _note_ written in **GitHub UI** section and added _links_ to _specific sections_ of the README file for **better accessibility**.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5614"></a>

### CODE REVIEW

**Review by himanshu1221 — COMMENTED** [review]
great catch @SaptarshiSarkar12 I found these changes useful :100:

**Comment by SaptarshiSarkar12** [comment]
> great catch @SaptarshiSarkar12 I found these changes useful 💯

Thank you @himanshu1221 for reviewing this PR.

**Comment by SaptarshiSarkar12** [comment]
@eddiejaoude Please review this PR.

**Comment by eddiejaoude** [comment]
> @eddiejaoude Please review this PR.

@SaptarshiSarkar12 I know you are excited, but please be patient, the extra notifications do not help. The maintainers will review soon

**Comment by SaptarshiSarkar12** [comment]
> > @eddiejaoude Please review this PR.
> 
> @SaptarshiSarkar12 I know you are excited, but please be patient, the extra notifications do not help. The maintainers will review soon

Okay @eddiejaoude . I apologise for my impatience.

**Review by kumarsonsoff3 — APPROVED** [review]
Changes looks good to me! 🎉 

But found that your PR is not attached with any issue. It's hard to manage non profile PRs with no issue attached. They reason why is:
- Maybe someone else created an issue for this, and working on it. (It might disturb their workflows)
- Maybe there is an issue to optimize Readme already. 

Those issues will be then meaning less or remain uncompleted, if I'd merge this one and even we'll not be unaware if that. 😲

-- 
What is highly recommended is to: 
- Create an issue first for a change you wanted to make. If not already exists.
- Discuss it there if it is required, and the best practices to do it.
- Get assigned by maintainers.
- Then start working on that feature. 

This way, it will save everyone's time & efforts. Also, will make open-source more inclusive for everyone. 🤗

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by SaptarshiSarkar12** [comment]
Thank you @Panquesito7 @eddiejaoude for your reviews. 😃

**Pull request merged**
