### PR TITLE
Create aliencoder-75.json

### PR DESCRIPTION
**Pull request by Aliencoder-75**

### CODE REVIEW

**Review by voidz7 — APPROVED** [review]
good pr ⚡ gg

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Your links and profile url have not been updated

**Review by schmelto — APPROVED** [review]

**Comment by eddiejaoude** [comment]
I was about to merge but you have now added other changes not related to your profile. Please separate out the README changes to another PR

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
PR now contains 2 types of changes, README changes should be in another PR to the user data changes

**Pull request closed without merging**
