### PR TITLE
Organize codebase and fix: axe wcag accessibility test

### PR DESCRIPTION
**Pull request by JunDevHarsh**
## Fixes Issue

Organized codebase by separating the `UserCard.js` component into its `./components/Card` for better readability

## Changes proposed

- Added `Card` folder in `components` to add all components that represent cards or can be used as a card.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3223"></a>

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3249"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for your contribution, but please separate them into separate pull requests, there is too much going on to review

- accessibility improvements should be in its own PR
- refactor of code should be in its own PR

**Comment by JunDevHarsh** [comment]
Actually, the accessibility issue was raised after my first commit. Then I make some changes according to the test rules that show to follow WCAG e.g. 'wcag2a', 'wcag2aa', 'wcag21a', and 'wcag21aa'.

**Review by eddiejaoude — COMMENTED** [review]
- Naming convention is not the same, `components/Card/UserCard.js` should be `components/card/UserCard.js` but we only have 1 card in there, so do we need a new directory for it? Maybe this could come later as I think it needs some more thought

- are the changes to `package-lock.json` file required?

Maybe make accessibility improvements PR and we can get that merged, as multiple things have changed it is blocking the PR

**Comment by JunDevHarsh** [comment]
I guess you are right as you mentioned above that multiple things are going on in this PR. I will take care of raising a PR only for a specific issue. I am closing this PR to be merged.

**Comment by eddiejaoude** [comment]
Thank you @JunDevHarsh 👍  (plus you get more green squares this way 😉 )

**Pull request closed without merging**
