### PR TITLE
data: dev-rakeshshaw

### PR DESCRIPTION
**Pull request by dev-rakeshshaw**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4990"></a>

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
LGTM 🎉

**Comment by dev-rakeshshaw** [comment]
> LGTM 🎉

Thanks

**Review by himanshu1221 — APPROVED** [review]
**LGTM :+1:**

**Comment by dev-rakeshshaw** [comment]
> **LGTM 👍**

Thanks

**Review by iamthecloverly — APPROVED** [review]
LGTM

**Review by mahfuztbt — APPROVED** [review]

**Comment by dev-rakeshshaw** [comment]
when will my PR get merged?

**Review by iamthecloverly — APPROVED** [review]

**Review by amandamartin-dev — APPROVED** [review]

**Pull request merged**
