### PR TITLE
Aman git010 patch 1

### PR DESCRIPTION
**Pull request by AmanGit010**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1807"></a>

### CODE REVIEW

**Review by imlakshay08 — APPROVED** [review]
Congratulations on your first PR! This PR looks fantastic. Keep up the good work buddy!

**Review by Rahul-Prasad-07 — APPROVED** [review]
You can add more links i.e. LinkedIn , Leetcode , Twitter

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🎉

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good to me! 👍

**Comment by AmanGit010** [comment]
Thank you guys!

**Pull request merged**
