### PR TITLE
data: yashpandey002

### PR DESCRIPTION
**Pull request by yashpandey002**
## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

PR for Profile addition

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5266"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks for your contribution! 🎉

**Review by accodes21 — APPROVED** [review]

**Review by TRohit20 — APPROVED** [review]

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Review by devvsakib — APPROVED** [review]
LGTM

**Comment by yashdev9274** [comment]
Don't over review a particular PR if it been reviewed by couple of people, until unless if there is required changes only then provide you review.

**Comment by yashpandey002** [comment]
> Don't over review a particular PR if it been reviewed by couple of people, until unless if there is required changes only then provide you review.

Really sorry @yashdev9274, will take care of that

**Review by iamthecloverly — APPROVED** [review]

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Welcome to LinkFree 🎉

**Pull request merged**
