### PR TITLE
data: Infinite8loop

### PR DESCRIPTION
**Pull request by infinite8loop**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8540"></a>

### CODE REVIEW

**Review by sital002 — CHANGES_REQUESTED** [review]
You can't add two files. You need to delete the file that doesn't have .json extension.

**Comment by infinite8loop** [comment]
Hello @sital002, I have delete the non .json file please approve.

**Review by sital002 — APPROVED** [review]
Looks Good 👍

**Review by kumarsonsoff3 — APPROVED** [review]
Great collaboration everyone. Looks good! 🎉

**Pull request merged**
