### PR TITLE
CODE_OF_CONDUCT has been modified by the insertion of numerical points instead of dashes

### PR DESCRIPTION
**Pull request by IAMSKJha**
…s instead of dash

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/891"></a>

### CODE REVIEW

**Comment by IAMSKJha** [comment]
I am very grateful to EddieHub Community for providing such beginner-friendly projects in order to practice my initial PRs.

**Review by krishguptadev — CHANGES_REQUESTED** [review]
I think we should follow the Contributor Covenant Standard

**Comment by emmalearnscode** [comment]
I'm not sure that this is a change that needs to be made as the items have no hierarchy to them. If you are looking for a simple first issue then please let us know and we will help you find something that needs updating in the docs @IAMSKJha

**Comment by Panquesito7** [comment]
I agree with @krishguptadev: we should keep the file *exactly* how it was provided.

**Pull request closed without merging**
