### PR TITLE
Data:Abhay-raj19

### PR DESCRIPTION
**Pull request by abhay-raj19**
## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3626"></a>

### CODE REVIEW

**Review by dan-mba — CHANGES_REQUESTED** [review]
The last link looks like an event.
Events need to be included in a separate file.
See the [events documentation](https://linkfree.eddiehub.io/docs/how-to-guides/events)
In your event make sure to put `https://` before the url.

**Comment by abhay-raj19** [comment]
> The last link looks like an event. Events need to be included in a separate file. See the [events documentation](https://linkfree.eddiehub.io/docs/how-to-guides/events) In your event make sure to put `https://` before the url.

Hey @dan-mba  Sir, i have to remove  the events form this main file 'abhay-raj19.json'.

As i have created a PR #3650  for events file ,pls check to it.

**Comment by dan-mba** [comment]
> Hey @dan-mba Sir, i have to remove the events form this main file 'abhay-raj19.json'.
> 
> As i have created a PR #3650 for events file ,pls check to it.

There is no need to open a separate PR for profile related updates.
Please close the other PR and add the event file to the branch for this PR.

**Comment by abhay-raj19** [comment]
Done. @dan-mba

**Review by dan-mba — CHANGES_REQUESTED** [review]
Please remove the event that is in the separate file from the links section of your profile file.

**Comment by abhay-raj19** [comment]
Finally made those changes .👍

**Review by dan-mba — CHANGES_REQUESTED** [review]
Please remove the `'` from the event filename.
This may work, but using an apostrophe or any form of quotation mark in a filename can cause problems.

**Comment by abhay-raj19** [comment]
Done sir . @dan-mba

**Review by dan-mba — APPROVED** [review]
Looks good to me

**Comment by abhay-raj19** [comment]
Sir , but who will merge my PR , Just asking sir.😥

**Comment by dan-mba** [comment]
> Sir , but who will merge my PR , Just asking sir.😥

It should get merged by another maintainer later today.

**Comment by abhay-raj19** [comment]
Okay sir , that's great.

Thankyou very much for suggesting all those changes @dan-mba .

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
