### PR TITLE
Issue #7072 | Rename "users" API endpoints to "profiles"

### LINKED ISSUE #7072: [BUG] Rename "users" API to "profiles"
### Description

We use the model `profile` but the api path is `users`, this should be renamed to `profiles`

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by daxitpatel**
## Fixes Issue

We use the model profile, but the API path is users. This PR address this improvement and renames "users" API endpoints to "profiles".

Closes #7072

## Changes proposed

Endpoints below are now updated from "users" to "profiles" and the FE code has been updated accordingly to invoke the latest paths,
- `/api/profiles/{username}links/{endocedURL}`
- `/api/profiles/{username}`
- `/api/profiles` 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

rename-user-endpoints

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7355"></a>

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by eddiejaoude** [comment]
Please can you resolve the conflicts and then we can get this merged

**Review by krishstwt — APPROVED** [review]
Looks good!

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
