### PR TITLE
fix: use event propogation to stop changeTab function to reset tabs

### PR DESCRIPTION
**Pull request by prajapati55**
## Fixes Issue
Fixes tab sorting issue

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2553"></a>

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by eddiejaoude** [comment]
This worked great! Thank you @prajapati55

**Comment by prajapati55** [comment]
Thank you for giving me this opportunity.

**Comment by eddiejaoude** [comment]
You are welcome, you saved me a lot of time, I was so happy I shared and tagged you on twitter  https://twitter.com/eddiejaoude/status/1609205002546839552

**Pull request merged**
