### PR TITLE
Changed placeholder and spacing between label and input

### PR DESCRIPTION
**Pull request by Saikat-Mandal**
Closes 
 - #5337 

## Fixes Issue

1) spacing between label and input
2) json placeholder addition

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

**Before**

old

**After**

new

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5554"></a>

### CODE REVIEW

**Review by stevenovak123 — APPROVED** [review]
LGTM

**Comment by psavan1655** [comment]
@Saikat-Mandal  Any reason for using top: 4 and bottom: 5?

If not, then you can use my-4. For y-axis spacing in just one class.

**Comment by Saikat-Mandal** [comment]
@psavan1655 Yeh i know. Actually it was looking a little bit odd when i pressed format and the json alert came in.

**Comment by E-fais** [comment]
Looking  more beginner friendly  👍

**Comment by Saikat-Mandal** [comment]
Hey @eddiejaoude can you please review this PR , Its been open for a while .

**Review by amandamartin-dev — APPROVED** [review]
lgtm!

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
