### PR TITLE
created my profile

### PR DESCRIPTION
**Pull request by kamalishere**
Testing for my youtube video
## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by kamalishere** [comment]
Hi @eddiejaoude i had created this test PR for a live youtube video on how to create a linkfree profile step by step for begineers .

https://youtu.be/3MUI3_QXRUo

**Comment by kamalishere** [comment]
Hence, You may close this PR :) Thanks.

**Comment by eddiejaoude** [comment]
Oh I see. Ok I will close.

Thank you for creating the video about LinkFree, I will watch now while having my breakfast 👍

**Comment by eddiejaoude** [comment]
The video was great @kamalishere 🔥 if you tweeted about your video, send me the twitter link and I will retweet it

**Pull request closed without merging**
