### PR TITLE
data: rohitt-gupta

### PR DESCRIPTION
**Pull request by rohitt-gupta**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5018"></a>

### CODE REVIEW

**Review by senali-d — COMMENTED** [review]
Look Good.

**Comment by rohitt-gupta** [comment]
> Look Good.

@senali-d whats the next step?
will it merge the PR automatically?

**Review by SaraJaoude — APPROVED** [review]
looks good

**Comment by SaraJaoude** [comment]
> > Look Good.
> 
> @senali-d whats the next step? will it merge the PR automatically?

@rohitt-gupta the PR will not merge automatically, it needs to be looked at by one of the maintainers.  I have done this and I will merge your PR now.  Shortly Profile should appear on the LinkFree website, you will need to search for it here: https://linkfree.eddiehub.io/search

**Pull request merged**
