### PR TITLE
Fixes[#5870] Card UX Improvement Mobile

### LINKED ISSUE #5870: Event card UX improvement mobile
### Description

On mobile, the event cards "depress" on click but nothing happens.  The user must click on the event title to navigate to the event.  This creates confusion in the user experience.

This can be addressed in 1 of 2 ways (to be discussed)
1. ~~remove the click event on the entire card and make it clear that the event title is clickable visually~~
2. adjust the click event so that on click of the event card, navigation to the event takes place

### Screenshots

See this video for the card click interactions

https://user-images.githubusercontent.com/97615019/230390611-ed5a55a8-3fe5-46d4-9230-4c86666ff2a5.mov

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Noothan-am**
## Fixes Issue

Closes #5870 

#5970 

This is new pr for https://github.com/EddieHubCommunity/LinkFree/pull/6629#issue-1698024564 since it closed 

## Changes proposed

Fixed it by wrapping whole card Under the `Link` Component.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6671"></a>

### CODE REVIEW

**Review by amandamartin-dev — APPROVED** [review]
LGTM! Thanks for picking this up

**Review by HassanTanveer — APPROVED** [review]

**Review by iamthecloverly — APPROVED** [review]

**Comment by Noothan-am** [comment]
Hey @SaraJaoude, I notice that this pull request has not been merged yet. Is there anything that needs to be changed in it?

**Comment by amandamartin-dev** [comment]
> Hey @SaraJaoude, I notice that this pull request has not been merged yet. Is there anything that needs to be changed in it?

Hey! I can answer this.  In general for items that are not profile updates we wait for two maintainer approvals.  You. have one from me, but I did not merge so that another maintainer could also review as well.

**Comment by Noothan-am** [comment]
> > Hey @SaraJaoude, I notice that this pull request has not been merged yet. Is there anything that needs to be changed in it?
> 
> Hey! I can answer this. In general for items that are not profile updates we wait for two maintainer approvals. You. have one from me, but I did not merge so that another maintainer could also review as well.

hey @amandamartin-dev, ig @iamthecloverly and @HassanTanveer approved it already

**Comment by amandamartin-dev** [comment]
> hey @amandamartin-dev, ig @iamthecloverly and @HassanTanveer approved it already

For this repository we require 2 maintainers to approve all merges that are not linkfree profiles with some caveats to that of course but I have consulted with @EmmaDawsonDev who had provided the second approval verbally so I will merge this.

I will also open a new issue to continue to improve the accessibility of these cards per Emmas suggestion. 

Thanks all!

**Comment by eddiejaoude** [comment]
Sorry I missed this in my notifications @Noothan-am - btw if you add a before and after screenshot, it is more likely to get merged faster

Thank you everyone for the great collaboration 💪

**Pull request merged**
