### PR TITLE
Add personal profile - Amit

### PR DESCRIPTION
**Pull request by amitturare**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1143"></a>

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@amitturare package-lock.json got messed up, please revert that commit.

**Comment by amitturare** [comment]
My bad, I accidentally used 'git add .', will try to revert back!

**Comment by amitturare** [comment]
Please review :D

**Comment by KendallDoesCoding** [comment]
> My bad, I accidentally used 'git add .', will try to revert back!

Thanks

**Review by KendallDoesCoding — APPROVED** [review]

**Review by ssensalo — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]

**Comment by amitturare** [comment]
Hey, I was checking the site for the profile, but it's just saying not found! Is there any mistake?

**Comment by KendallDoesCoding** [comment]
Hey Amit,

A release needs to be created to deploy these changes, usually releases are
created within 1 week depending on when new features get added. So please
wait for that. For now, if you got the stuff running remotely, you can test
it on localhost and make sure everything is working :)

**Comment by amitturare** [comment]
Thanks for the reply Kendal :D

**Comment by KendallDoesCoding** [comment]
> Thanks for the reply Kendal :D

:) Happy to help you!

**Pull request merged**
