### PR TITLE
data: usmangt

### PR DESCRIPTION
**Pull request by usmangt**
added social links

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6854"></a>

### CODE REVIEW

**Review by Aniket1026 — DISMISSED** [review]
Looks good to me 🎉

**Comment by SaraJaoude** [comment]
You have conflicts in your file, please resolve. This is usually because your fork is not up to date.  

You may wish to have a look at our Editing Guide in Docs: https://linkfree.io/docs/how-to-guides/editing

**Comment by usmangt** [comment]
> You have conflicts in your file, please resolve. This is usually because your fork is not up to date.
> 
> You may wish to have a look at our Editing Guide in Docs: https://linkfree.io/docs/how-to-guides/editing

Thank you. I have now fixed the conflicts and also sync the fork.

I am done with the editing and would request you to merge it so that my profile gets updated

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
