### PR TITLE
Chrissy

### PR DESCRIPTION
**Pull request by CBID2**
I added the suggestions Eddie made during a Linkfree Profile review video. 
## Fixes Issue
[#6455](https://github.com/EddieHubCommunity/support/issues/6455)

## Changes proposed

1. Added some tags
2. Added colors to some of my milestones.  

## Check List (Check all the applicable boxes) 

- [X ] My code follows the code style of this project.
- [X ] My change requires changes to the documentation.
- [ X] I have updated the documentation accordingly.
- [X ] All new and existing tests passed.
- [X ] This PR does not contain plagiarized content.
- [ X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Any feedback is welcomed 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4190"></a>

### CODE REVIEW

**Comment by loftwah** [comment]
You've added a few extra files here with GitHub Actions. If you want to do this without committing them, you'll need to disable GitHub Actions or use a branch other than main.

**Comment by CBID2** [comment]
> You've added a few extra files here with GitHub Actions. If you want to do this without committing them, you'll need to disable GitHub Actions or use a branch other than main.

Noted

**Comment by loftwah** [comment]
I did this when I first created my profile too :) We talk about it in one of the videos.

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Please resolve merge conflicts [here](https://github.com/EddieHubCommunity/LinkFree/pull/4190/conflicts). You can also refer these docs on [resolving merge conflicts](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line). Let us know if you need any help with this. :)

**Comment by CBID2** [comment]
> Please resolve merge conflicts [here](https://github.com/EddieHubCommunity/LinkFree/pull/4190/conflicts). You can also refer these docs on [resolving merge conflicts](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line). Let us know if you need any help with this. :)

I need help @kumarsonsoff3, as I don't have access to VS Code at the moment

**Pull request merged**
