### PR TITLE
[DOCS]

### PR DESCRIPTION
**Pull request by ShorunTech**
Docs folder created

## Changes proposed

-- Docs folder created in the root directory
-- Contributing folder created in the docs folder
-- CONTRIBUTING.md file moved to Contributing folder
-- Changes was made in the README File

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot (161)

Screenshot (160)
ble

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1893"></a>

### CODE REVIEW

**Review by EmmaDawsonDev — APPROVED** [review]
Looks good to me 👍

**Review by mkubdev — APPROVED** [review]
Well spotted! LGTM :rocket:

**Comment by schmelto** [comment]
One thing about this now the community standards are not fullfiled anymore.
https://github.com/EddieHubCommunity/LinkFree/community

**Comment by EmmaDawsonDev** [comment]
Oh that’s weird that it can’t be in a folder

**Pull request merged**
