### PR TITLE
data: Mutai-Gilbert

### PR DESCRIPTION
**Pull request by Mutai-Gilbert**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3603"></a>

### CODE REVIEW

**Review by Pradumnasaraf — DISMISSED** [review]
Hey,

You have created the JSON file at the root of the project. Please add your file to the `data` directory -> `data./Mutai-Gilbert.json`. If you need any kind of help, feel free to ask.

**Review by Tejender1521 — CHANGES_REQUESTED** [review]
Everything looks good but you have to move your file into data folder then again commit it.

**Review by s4shantanu — COMMENTED** [review]
Looks good to me.

**Comment by SaraJaoude** [comment]
It is no longer necessary to fix this as found out the file already exists: https://github.com/EddieHubCommunity/LinkFree/pull/4134

@Mutai-Gilbert in future, please can you close any open Pull Requests if they are no longer needed.  This helps maintainers manage the project.

**Pull request merged**
