### PR TITLE
data: methlox

### PR DESCRIPTION
**Pull request by methlox**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4794"></a>

### CODE REVIEW

**Review by sidharthviz — APPROVED** [review]
LGTM 👍🏼

**Review by Ananya2001-an — APPROVED** [review]
Looks good.

**Review by priyankarpal — APPROVED** [review]
LGTM 🎉

**Review by Hrishi5111998 — APPROVED** [review]

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"></p>

**Pull request merged**
