### PR TITLE
Update my profile

### PR DESCRIPTION
**Pull request by Sajiyah-Salat**
I have update my profile with new features and content. Please review.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4015"></a>

### CODE REVIEW

**Review by sidharthviz — APPROVED** [review]
Looks good now @Sajiyah-Salat

**Review by devvsakib — APPROVED** [review]
LGTM

**Comment by devvsakib** [comment]
hey @Sajiyah-Salat  , your pr has a conflict. you can resolve the conflict

**Comment by loftwah** [comment]
GitHub Actions has added a bunch of extra files.

**Comment by Sajiyah-Salat** [comment]
I got that but I am unable to resolve conflicts. what should I do?

**Comment by loftwah** [comment]
I have done this before and haven't learnt how to fix it yet (it is still on the list). My solution was to delete my version of the repo and start again, but I'm sure there is a better way.

**Comment by Sajiyah-Salat** [comment]
I got the same idea but at some point we need to learn that. I would like to know that better solution from other maintainers members and active contributors. Kindly help me to fix it.

**Review by amandamartin-dev — CHANGES_REQUESTED** [review]
Hello! It looks like you may need to pull main into your branch and when you push again no need to add the package-lock and package file for a profile update.

**Comment by eddiejaoude** [comment]
I like the idea of you trying to fix it, to avoid these issues in the future it is better to always use a branch to make changes and not the default branch `main`

**Pull request closed without merging**
