### PR TITLE
added card for coder-XX04

### PR DESCRIPTION
**Pull request by coder-XX04**
## Check List (Check all the applicable boxes) 

- [ X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X ] All new and existing tests passed.
- [ X] This PR does not contain plagiarized content.
- [X ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4856"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by coder-XX04** [comment]
> Thanks! tada

Actually, I closed the previous PR because it contained some error, I rectified all the error and opened again the new PR. Can you tell how much time it takes to merge the PR.

**Comment by Panquesito7** [comment]
> > Thanks! tada
> 
> Actually, I closed the previous PR because it contained some error, I rectified all the error and opened again the new PR. Can you tell how much time it takes to merge the PR.

It will be merged once two or more maintainers approve it. 🙂

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
