### PR TITLE
Updating my LinkFree page

### PR DESCRIPTION
**Pull request by VarchasvH**
Added some new links to my LinkFree page.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5044"></a>

### CODE REVIEW

**Review by SurajPratap10 — APPROVED** [review]

**Comment by SurajPratap10** [comment]
just remove the `,` from line 43

**Review by SurajPratap10 — APPROVED** [review]

**Comment by VarchasvH** [comment]
> just remove the `,` from line number 43

Did that just now, thanks for correcting.

**Comment by SurajPratap10** [comment]
> > just remove the `,` from line number 43
> 
> Did that just now, thanks for correcting.

cool

**Review by mahfuztbt — APPROVED** [review]

**Review by Hrishi5111998 — APPROVED** [review]

**Review by Sindhuinti — APPROVED** [review]

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
