### PR TITLE
data: singh1203

### PR DESCRIPTION
**Pull request by singh1203**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

The community is awesome and all of you are doing an absolutely great job. I would love to have my link-free profile created and updated. Thank you :)

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5099"></a>

### CODE REVIEW

**Review by imbeshat — COMMENTED** [review]
The filename should be the same as your GitHub username i.e, ```singh1203.json```

**Comment by singh1203** [comment]
Thank You @imbeshat for pointing this out.

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Comment by TRohit20** [comment]
LGTM!

**Review by Sindhuinti — APPROVED** [review]
Nice 👍🏻

**Review by mahfuztbt — APPROVED** [review]

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! 🎉

**Comment by singh1203** [comment]
Thankyou..

**Pull request merged**
