### PR TITLE
Refactor: Refactor the Components , Utils ,Constant and pages

### LINKED ISSUE #605: [Refactoring] Refactor the Components , Utils ,Constant and pages.
### What would you like to share?

Currently, We are just following a random folder structure but we should change it.

We should refactor our application like this.

Page
 - it only contains the API calls and components to render 
 - no business logic

components
 - It will receive the props from the parent component and render the UI
 - it will include the business logic 
 
Utils
  - it will include the utility file for our application

Constant
 - it will include the constant that we are using in our application.
 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Closes #605

### CODE REVIEW

**Comment by krishguptadev** [comment]
@Sachin-chaurasiya just a slight reminder, PRs merged/approved after 12am GMT-12 would not be counted for Hacktoberfest 🙂

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya just a slight reminder, PRs merged/approved after 12am GMT-12 would not be counted for Hacktoberfest 🙂

@krishguptadev thank you, but I have already completed hacktoberfest challenge 😊.

**Comment by eddiejaoude** [comment]
This looks great @Sachin-chaurasiya 👍

**Comment by Sachin-chaurasiya** [comment]
Closing this PR as lost the track of it.

**Pull request closed without merging**
