### PR TITLE
addded ch-jaswanth

### PR DESCRIPTION
**Pull request by jaswanth187**

### CODE REVIEW

**Review by accodes21 — CHANGES_REQUESTED** [review]
- Update your filename to your ```username.json``` i.e to ```jaswanth187.json```
- Correct the typo in LinkedIn

**Comment by jaswanth187** [comment]
I think I had already changed the file name to **ch-jaswanth.json** and I am assuming that the typo mistake is at the icon, I have to change it to LinkedIn.

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thanks! 🎉

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good to me! 👍

**Pull request merged**
