### PR TITLE
Added my file sauradip.json to linkfree

### PR DESCRIPTION
**Pull request by sauradip007**
## Changes proposed

Added my profile by creating a new file named sauradip.json

## Check List (Check all the applicable boxes) 

- [ X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X ] This PR does not contain plagiarized content.
- [ X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

created a new file and added created this PR to show my first code contribution to LinkFree

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/959"></a>

### CODE REVIEW

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
Profile looks good. Please remove the package.json and package-lock.json files from the commit.

**Comment by sauradip007** [comment]
alright , I've made the requested changes. Please find the "changes made" commit. Thanks

**Review by Panquesito7 — APPROVED** [review]

**Review by Shivansh-yadav13 — APPROVED** [review]
Welcome :smile:

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
It's better to revert the `package.json` file

**Review by Panquesito7 — APPROVED** [review]

**Pull request merged**
