### PR TITLE
data/Dev-Ahmadubah

### PR DESCRIPTION
**Pull request by Dev-Ahmadubah**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3988"></a>

### CODE REVIEW

**Comment by rahulpandey70** [comment]
Hey @Dev-Ahmadubah you must put your json file in data directory.

**Review by Sindhuinti — DISMISSED** [review]
It should be data/Dev-Ahmadubah.json

**Comment by Dev-Ahmadubah** [comment]
> It should be data/Dev-Ahmadubah.json

Thanks man

**Comment by Sindhuinti** [comment]
Please follow these instructions https://linkfree.eddiehub.io/docs/quickstart

**Review by amandamartin-dev — APPROVED** [review]
looks good!

**Review by amandamartin-dev — CHANGES_REQUESTED** [review]
Sorry, I spoke too soon. I saw you changed the name of your PR to say data/Dev-Ahmadubah but what the other commenter meant was to actually move your json file into the data/ folder within the repo and then push that change.  It looks to me to not be in the correct location yet. WOuld you check?

**Comment by Dev-Ahmadubah** [comment]
> Sorry, I spoke too soon. I saw you changed the name of your PR to say data/Dev-Ahmadubah but what the other commenter meant was to actually move your json file into the data/ folder within the repo and then push that change. It looks to me to not be in the correct location yet. WOuld you check?

Yes, I checked it and make the correction. Thanks.

**Pull request closed without merging**
