### PR TITLE
data: d4community

### PR DESCRIPTION
**Pull request by Sagar0-0**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8725"></a>

### CODE REVIEW

**Review by amandamartin-dev — CHANGES_REQUESTED** [review]
Your file name must match your github username (case sensitive)

**Comment by Sagar0-0** [comment]
I have to add one for my community organization

**Comment by amandamartin-dev** [comment]
> I have to add one for my community organization

If you create an account for your community org on GitHub, you will want to close this PR attached to your personal account and then open it while logged in as your community. You cannot submit a profile on behalf of another github account.  Let me know if this makes sense or if you need anymore help!

**Comment by Sagar0-0** [comment]
Make sense, but creating the community profile only for this is maybe not a good idea. Anything else is possible?

**Comment by amandamartin-dev** [comment]
> Make sense, but creating the community profile only for this is maybe not a good idea. Anything else is possible?

I am not sure there is any other way to have a separate linkfree for your community other than having the separate github account, but looping in @eddiejaoude to confirm as perhaps there is a newer feature I am not aware of yet or something coming that would allow for you to have these accounts separated

**Pull request closed without merging**
