### PR TITLE
feat: group links #2437

### LINKED ISSUE #2437: [FEATURE] Group links together
### Description

Sometimes we want to group links together.

Maybe all links can fall in `default` but then people could add other groups like `community` or `business` etc

I think this could be done with a group name property in the links section and if not set use `default`

```js
"links": [
   {
      ...
      "group": "business",
      ...
   }
]
```

**OR**

Have a field in the link object for the group, for example

```js
"links": [
   {
      "group": "Socials",
      ...
   }
]
```

Similar to @madzadev's profile on BioLink https://bio.link/madza

Screenshot 2023-01-22 at 17 26 33

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

fixes #2437 

NO GROUPs

Screenshot 2023-01-25 at 10 10 33

WITH GROUPs

Screenshot 2023-01-25 at 10 10 20

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
There is not Gitpod button for this PR 🤔

**Comment by eddiejaoude** [comment]
Oh that is strange. It happens sometimes. I still think it can be opened in Gitpod by prepending their url

**Comment by ChinmayMhatre** [comment]
This looks Great! I was wondering since there are around 1k users with profiles already created, could we actually check if there are any groups and skip the groups entirely if none are present instead of adding them to `others` ?

**Comment by ChinmayMhatre** [comment]
> Oh that is strange. It happens sometimes. I still think it can be opened in Gitpod by prepending their url

Yes! Just checked. This looks great!

**Comment by eddiejaoude** [comment]
Thank you for reviewing @ChinmayMhatre 👍

**Pull request merged**
