### PR TITLE
mobile testimonial UI layout fix

### LINKED ISSUE #2454: [FEATURE] Improvement - mobile testimonial UI
### Description

In mobile the testimonial text isn't making good use of the visual "real estate" right now creating longer testimonial cards than necessary. This issue is to modify the mobile UI to allow the text to float below the avatar and span the full width of the card.

### Screenshots

mobile-testimonial-ui

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Aadarsh805**
## Fixes Issue
Closes #2454

## Changes proposed
Changed the testimonial layout, suitable for mobile screen

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Screenshots
Before: 
image

After: 
[screen-capture (3).webm](https://user-images.githubusercontent.com/95094057/209173332-14b8f361-8cf4-47c5-bf7f-80b183d49a6c.webm)

## Note to reviewers
I used next <Image /> component in place of normal HTML img

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2458"></a>

### CODE REVIEW

**Review by amandamartin-dev — COMMENTED** [review]
LGTM!

Love the video, nice/smooth transition. One of the maintainers of this repo will do final approval/merge.  Thanks for jumping on this issue 🥳

**Review by schmelto — APPROVED** [review]

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Looks great 👍 sorry I am slow to comment

Please can you remove the changes to the `package-lock.json` I don't think these are needed

**Comment by Aadarsh805** [comment]
@eddiejaoude Did it work, I don't think it did
I would need some help here

**Comment by Aadarsh805** [comment]
I think it did something just now

**Comment by Aadarsh805** [comment]
I might as well make a new pr with the same changes ig, if required

**Comment by eddiejaoude** [comment]
> I might as well make a new pr with the same changes ig, if required

Sure, if that is easier feel free to create a new PR (but please close this one if you do)

**Comment by Aadarsh805** [comment]
made new pr for this change #2549 
closing this one

**Pull request closed without merging**
