### PR TITLE
Add my profile

### PR DESCRIPTION
**Pull request by marianaWest**
## Changes proposed

I hope you can add my profile now. thanks!

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2694"></a>

### CODE REVIEW

**Comment by marianaWest** [comment]
Hi everybody, it was easier to open a new PR. However, I think what happened the last time was that I followed the instructions described in the "Commands" topic right above the explanation to add a new profile. I believe that interferes with package-lock.json and might cause conflicts that newbies won't know how to resolve. If that makes sense, I think we should add a note there, something telling that you don't need to follow those instructions if you're only adding a new profile. What do you think?

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by eddiejaoude** [comment]
> it was easier to open a new PR

No problem

> I think what happened the last time was that I followed the instructions described in the "Commands" topic right above the explanation to add a new profile. I believe that interferes with package-lock.json and might cause conflicts that newbies won't know how to resolve. If that makes sense, I think we should add a note there, something telling that you don't need to follow those instructions if you're only adding a new profile

Do you have a link/screenshot to which docs you are referring to?

**Comment by marianaWest** [comment]
Sure Eddie, here's a screenshot: 

linkFree

I suggest we put a note under 'Commands' similar to this: 
Note: You don't need to follow these steps right now if you only want to add your profile. 

Let me know if that makes sense.

**Comment by eddiejaoude** [comment]
Thanks Mariana! Yes that sis confusing. We have new docs in the documentation section so I think we need to improve the readme as you suggested https://linkfree.eddiehub.io/docs/quickstart

**Comment by eddiejaoude** [comment]
It has screenshots! Let us know if anything is missing or confusing. Thank you 👍

**Pull request merged**
