### PR TITLE
Adding more links to the profile

### PR DESCRIPTION
**Pull request by legendarykamal**
## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [ x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by legendarykamal** [comment]
@eddiejaoude please review 🙌🏻

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
I think because your fork/branch is not up to date, you have extra file changes from generated files 

Here are the docs on how to update your profile by keeping your fork updated and creating a new branch https://linkfree.eddiehub.io/docs/how-to-guides/editing

**Comment by legendarykamal** [comment]
thankyou @eddiejaoude I created a new PR for this https://github.com/EddieHubCommunity/LinkFree/pull/2992 .

**Comment by eddiejaoude** [comment]
Please close this PR if it is no longer needed

**Pull request closed without merging**
