### PR TITLE
keyboard shortcut added for seachbox

### LINKED ISSUE #1937: [OTHER]-keyboard shortcut for seachbox
### What would you like to share?

'ctrl+k' should take us to the search box 

### Additional information

@EmmaDawsonDev Can I take start working on this issue?

### PR DESCRIPTION
**Pull request by Manmohan11**
closes #1937

## Fixes Issue
shortcut key for searchbox

## Changes proposed
Made changes in Home.js & Searchbar.js

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers
On main page shortcut key 'ctrl+k' takes us to the search box.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1971"></a>

### CODE REVIEW

**Comment by Manmohan11** [comment]
@eddiejaoude please review this pr 
I've made relavent changes
everything is working fine on local

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Please revert changes to the package-lock file.

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍 

note: the `package-lock.json` should not be committed

**Comment by Manmohan11** [comment]
@EmmaDawsonDev please review, I've reverted changes made into package-lock.json

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
