### PR TITLE
Create sidharthviz.json

### PR DESCRIPTION
**Pull request by sidharthviz**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3966"></a>

### CODE REVIEW

**Comment by sidharthviz** [comment]
chore: profile addition

**Review by eddiejaoude — DISMISSED** [review]
File should be in the `data` directory, you can learn more in the quickstart guide in the docs https://linkfree.eddiehub.io/docs/quickstart

**Comment by sidharthviz** [comment]
I will create new file..totally messed up sorry

**Review by sidharthviz — COMMENTED** [review]
sorry for the messed up..   syntax fixed

**Review by iamthecloverly — APPROVED** [review]

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"></p>

**Pull request merged**
