### PR TITLE
data:fatimakay

### PR DESCRIPTION
**Pull request by fatimakay**
image_2023-01-08_164214153

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2862"></a>

### CODE REVIEW

**Comment by fatimakay** [comment]
forgot to check the marks

**Comment by eddiejaoude** [comment]
Hi @fatimakay, did you mean to close this pull request?

**Comment by eddiejaoude** [comment]
I see you created a new pull request 👍  https://github.com/EddieHubCommunity/LinkFree/pull/2863

**Comment by eddiejaoude** [comment]
No problem, it happens

**Pull request closed without merging**
