### PR TITLE
data: samthatcode

### PR DESCRIPTION
**Pull request by samthatcode**

### CODE REVIEW

**Review by SaraJaoude — CHANGES_REQUESTED** [review]
Please move your file to the `data` folder and make sure that your file name matches your GitHub username exactly (it is case sensitive). Instead of `Samthatcode.json` it should be `data/samthatcode.json`.

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

**Comment by samthatcode** [comment]
Moved the file to the data folder and renamed it as "samthatcode.json" to match my GitHub username exactly.

**Comment by samthatcode** [comment]
> Please move your file to the `data` folder and make sure that your file name matches your GitHub username exactly (it is case sensitive). Instead of `Samthatcode.json` it should be `data/samthatcode.json`.
> 
> I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

Moved the file to the data folder and renamed it as "samthatcode.json" to match my GitHub username exactly.

**Review by SaraJaoude — APPROVED** [review]

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
