### PR TITLE
adding DHCJS profile

### PR DESCRIPTION
**Pull request by DHCJS**
I am adding my profile into the JSON file by using the Git command. I wonder if I am doing it right due to the YT video using other than VS code.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1839"></a>

### CODE REVIEW

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Your profile looks file but you seem to have committed an extra empty file at the same time. Please remove that from the pull request.

**Comment by DHCJS** [comment]
Hmm, strange, let me try another way then. Is closing the PR = removing from PR?

**Comment by EmmaDawsonDev** [comment]
You should be able to remove one file from the commit without closing the pr but if you find it easier you can always close the pr and start again.

**Review by krshkodes — COMMENTED** [review]
I think it is easier to delete it, just go to the Files Changed tab and 
image

**Comment by DHCJS** [comment]
I'll just close it and redo it then.
Thank you for helping me out!

**Pull request closed without merging**
