### PR TITLE
data: vishnu-mouli-102408

### PR DESCRIPTION
**Pull request by vishnu-mouli-102408**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4410"></a>

### CODE REVIEW

**Review by sidharthviz — CHANGES_REQUESTED** [review]
Hi @vishnu-mouli-102408 
  In the latest version you do not need to include avatar: as it will be automatically fetched 
  from your profile. Please do remove. Updated docs are available at <https://linkfree.eddiehub.io/docs/quickstart>

**Comment by priyankarpal** [comment]
delete the last semicolon

Screenshot from 2023-02-03 13-49-20

**Review by priyankarpal — CHANGES_REQUESTED** [review]
Just delete the last semicolon

**Comment by vishnu-mouli-102408** [comment]
> Just delete the last semicolon

thanks i did it.

**Comment by vishnu-mouli-102408** [comment]
> > Just delete the last semicolon
> 
> thanks i did it.

please tell me if there is anything wrong so i can fix it.

**Review by priyankarpal — APPROVED** [review]
LGTM

**Review by Sindhuinti — APPROVED** [review]

**Review by himanshu1221 — APPROVED** [review]
LGTM :+1:

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
