### PR TITLE
Added profile data

### PR DESCRIPTION
**Pull request by Kunal0007**
Fixes #

## Proposed Changes

  -
  -
  -

## Screenshots

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/151"></a>

### CODE REVIEW

**Review by FayasNoushad — APPROVED** [review]

**Comment by Kunal0007** [comment]
how to solve this error?

**Comment by FayasNoushad** [comment]
> how to solve this error?

That is not a error. If you don't know that. Wait for maintainers.

**Review by qwe123coder — CHANGES_REQUESTED** [review]
hey nice work :rocket: Thanks for your contribution
*  the files are Conflicted :( 
*  I do not think so you have to edit ```public/data/_list.json```
*  you have also messed up the aliment in ```public/data/_list.json```
*  I suggest read [Resolving a merge conflictt](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts)

**Comment by qwe123coder** [comment]
> how to solve this error?

i suggest you to read 
https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts

**Review by krishdevdb — CHANGES_REQUESTED** [review]
Looks awesome 🚀 Thanks for your contribution. I think there is small issue, There are a few merge conflicts in the PR. Here's a article on how to fix them: [Resolving a merge conflict on GitHub - (github.com)](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github). Feel free to ask for any help/guidance

**Comment by Kunal0007** [comment]
Should i follow this step or close this pull request and make new one ?

**Comment by krishdevdb** [comment]
You should follow the steps, but practically you could make a new one too! :D

**Pull request closed without merging**
