### PR TITLE
data:Aniket1026

### PR DESCRIPTION
**Pull request by Aniket1026**
## Changes proposed
Updating the LinkFree profile

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6348"></a>

### CODE REVIEW

**Review by khushalarora — APPROVED** [review]
Looks good, thanks :tada:

**Review by harshsingh32 — APPROVED** [review]
lgtm

**Review by SurajPratap10 — APPROVED** [review]
LGTM 🔥

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
