### PR TITLE
Updated the screenshots for the quick-start guide.

### LINKED ISSUE #4999: [DOCS] Update screenshots on /docs/quickstart
### Description

We need to update the screenshots on https://linkfree.eddiehub.io/docs/quickstart as new people are being confused.
It currently has `avatar` and `displayStatsPublic` which are no longer required.

### Screenshots

issue-ss-1
issue-ss-2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MAYANKpandey14**
## Fixes Issue

closes #4999

## Changes proposed
Changed the screenshots for the quickstart guide as in json file avatar section has been removed but the old screenshots were displaying it in an illustration. 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Screenshot 2023-03-10 at 12 56 00 AM
Screenshot 2023-03-10 at 1 02 21 AM

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5412"></a>

### CODE REVIEW

**Comment by MAYANKpandey14** [comment]
## Giving this as the cause of conflict.
Is deleting the updateSS branch's line and keeping the main branch's line a solution to this conflict.
Just wanted a second opinion before doing anything further.

Screenshot 2023-03-13 at 10 45 27 PM

**Review by Panquesito7 — COMMENTED** [review]
Looks good. Just a few things:

1. You should probably hide your mail from the screenshot.
2. I'm not sure if your name or Sara's name should appear in the fork of the repository. We should probably discuss this.

**Comment by eddiejaoude** [comment]
- I think you have conflicts because your fork is out of date
- please use the correct commit message in the screenshot (there is a space after the `:`), for example `data: eddiejaoude`
- my concern is, that it looks like you are editing someone else's profile (which we do not allow, that is why @Panquesito7 mentions it). I think it would be better if you combine both images, so only use the code part of your image and put it on top of the original one

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
- I think you have conflicts because your fork is out of date
- please use the correct commit message in the screenshot (there is a space after the `:`), for example `data: eddiejaoude`
- my concern is, that it looks like you are editing someone else's profile (which we do not allow, that is why @Panquesito7 mentions it). I think it would be better if you combine both images, so only use the code part of your image and put it on top of the original one

**Comment by MAYANKpandey14** [comment]
### What do you think about this ?
Merged the code part of the new screenshot with the older one.

LinkFree SS

**Comment by MAYANKpandey14** [comment]
Before :- 

Screenshot 2023-03-10 at 12 56 00 AM

After :- 

ss

**Pull request closed without merging**
