### PR TITLE
Chore: Format public/data

### PR DESCRIPTION
**Pull request by Vyvy-vi**
## Changes proposed

This PR merges in changes from #678 and reformats all of the JSON files present in `public/data`

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

(kindly `rebase and merge`, so that the commit granularity is maintained)

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/689"></a>

### CODE REVIEW

**Review by krishguptadev — APPROVED** [review]
Looks good! But how about a github action that formats the files? I would love to work on it.

**Review by Panquesito7 — APPROVED** [review]
Nice work on this 🚀 Thank you! 😄👍

**Comment by Vyvy-vi** [comment]
> Looks good! But how about a github action that formats the files? I would love to work on it.

Personally, I would love a github-action for the same. Either of these would be great-
- A github action that formats any json file edited in a PR, right inside the PR
or
- A github action that format checks the PRs using prettier, and flags when things have issues. (which can then be fixed by running "npm run format" locally)

Also, we should probably set up a "npm run format" script...
I also think that as maintainers, we should probably merge these PRs to a staging branch and format the files and merge back to `main`. This would make it easier for others to add their profile(until we get an action for the same)

**Review by Vyvy-vi — COMMENTED** [review]
looks alright.
prettier go brrr...

**Comment by krishguptadev** [comment]
Sounds good, shall I make a PR for github-actions or we go with the maintainers' format...

**Comment by Vyvy-vi** [comment]
> Sounds good, shall I make a PR for github-actions or we go with the maintainers' format...

feel free to open an issue to discuss, or open a PR with a draft for the implementation

**Pull request merged**
