### PR TITLE
added new profile - salahawk

### PR DESCRIPTION
**Pull request by salahawk**
## Check List (Check all the applicable boxes) 
- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1909"></a>

### CODE REVIEW

**Comment by salahawk** [comment]
@Panquesito7 Can you please review this PR if it's mergeable?

**Comment by salahawk** [comment]
@EmmaDawsonDev I'd have your input on this PR - just to add my profile!!!

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thanks! 🎉

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good to me! 🎉

**Pull request merged**
