### PR TITLE
data: PRATHAM-099

### PR DESCRIPTION
**Pull request by PRATHAM-099**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4350"></a>

### CODE REVIEW

**Review by sidharthviz — APPROVED** [review]
Looks great ✨

**Comment by raghu-007** [comment]
Nice

**Review by Ananya2001-an — DISMISSED** [review]
Looks good!

**Comment by PRATHAM-099** [comment]
Finally thanks a lot for the time.

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
You previous PR also looks good too, not sure why you closed that one. 

You need to rename your file to `data/PRATHAM-099.json` like you did in previous one. Then it should be good to go.

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thank you for your Contribution! 🎉 

<p align="center"></p>

**Comment by PRATHAM-099** [comment]
thank you, man, for your support really.
And sorry for those silly mistakes.

**Comment by kumarsonsoff3** [comment]
It's okay Pratham, it does happen. 🙂
We all make mistakes & learn from each other. 🤝

**Pull request merged**
