### PR TITLE
Feature filter map by tag

### LINKED ISSUE #4957: [FEATURE] Ability to filter map by tag
### Description

Add tag filter to map page to increase consistency across the UI and provide users a way to interact with the data displayed there in a meaningful way.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by amandamartin-dev**
## Fixes Issue #4957 

 Closes #4957

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5067"></a>

### CODE REVIEW

**Comment by amandamartin-dev** [comment]
@eddiejaoude here's the draft PR for the tag filters.  Take a look and see if you think it's too similar to the search code and we should looks at pulling this out the decrease any repetitive code.

I fixed the search oddity I saw before, this was due to the tags pulling in for ALL users vs. the map users.  You will see a filter after the tag API request that handles this.

If you think this is fine to start, lmk and I'll switch to a regular PR for others to review

**Comment by amandamartin-dev** [comment]
One thing that filtering the tags didn't address is the little orange numbers indicating how many users per tag.  I can look into this as well before it's finalized or save that for a separate issue.  I thought filtering the tags would take care of that number, but it seems to come straight from the API

**Comment by amandamartin-dev** [comment]
@eddiejaoude lil bump - lmk if you think this is a good start or if we should look at abstracting out the search code for use in multiple places as part of this effort

**Comment by eddiejaoude** [comment]
Sorry I missed this, thanks for bumping 👍 

> I can look into this as well before it's finalized or save that for a separate issue

yes this can come in a separate issue/pull request 💯 

> Take a look and see if you think it's too similar to the search code and we should looks at pulling this out the decrease any repetitive code.

I think that can also come later as there isn't too much

**Comment by amandamartin-dev** [comment]
> Sorry I missed this, thanks for bumping 👍

> yes this can come in a separate issue/pull request 💯

> I think that can also come later as there isn't too much

great - then ready for reviewing by you and anyone else!

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍 

I think further improvements can come in another PR, for example...
- keeping tag highlighted when selected
- possibly clear selected tag button

**Comment by amandamartin-dev** [comment]
> Looks good 👍
> 
> I think further improvements can come in another PR, for example...
> 
> * keeping tag highlighted when selected
> * possibly clear selected tag button

agreed. I'll open up issues for these

**Pull request merged**
