### PR TITLE
Feature: Socials section design

### LINKED ISSUE #2182: [FEATURE] New design for socials section
### Description

this issue is with continuity with #2171 

the links section design can be changed from horizontal to grid-type style like

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ManishBisht777**
## Changes proposed

New design for social section

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
image
image

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2214"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
note: we might need to take this into a temporary branch and allow multiple templates, as some people will want `list` and not `tiles`

**Comment by ManishBisht777** [comment]
does the current project have some other branch available for this?

**Comment by eddiejaoude** [comment]
not yet, either way you don't need to close this, the destination branch for it can be updated later

**Comment by ManishBisht777** [comment]
ok :)

**Comment by eddiejaoude** [comment]
@ManishBisht777 I am thinking before then, we could use this design on the "popular" page to get more people to display, what do you think? Then later port it over to here when we have the template option

Screenshot 2022-11-12 at 10 12 11

**Comment by ManishBisht777** [comment]
Great idea @eddiejaoude, but how are we going to do this? because there is a little HTML change also but for the CSS part we can do that by collecting them in a stylesheet and applying them by `@apply` this way the `html` will look more clean as well

**Comment by eddiejaoude** [comment]
I think update this PR for the "popular" page and later the "profile" page can be done.

I think the "apply" improvements can come later in another PR

**Comment by ManishBisht777** [comment]
ok @eddiejaoude  I am creating an issue addressing the same

**Comment by eddiejaoude** [comment]
I have added a `blocked` label to this PR, I think it would be better to have this as an optional template option - so this design would come in later after the templating options system is in place (separate PR)

**Comment by EmmaDawsonDev** [comment]
These color combinations need checking for contrast issues.

**Review by krishstwt — COMMENTED** [review]
Are there any updates to this @ManishBisht777?

**Comment by eddiejaoude** [comment]
@krishstwt I marked this as blocked, so there are no changes from @ManishBisht777 to be done.

Now forms are almost done, we are now going to have more layout options for the profile page, for example https://github.com/EddieHubCommunity/LinkFree/issues/7310

@ManishBisht777 I suggest you create a new Issues and PR, from the latest code, so I will close this.

**Pull request closed without merging**
