### PR TITLE
Sectioned my Linkfree profile

### PR DESCRIPTION
**Pull request by CBID2**
## Changes proposed

I improved my Linkfree profile. 

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5734"></a>

### CODE REVIEW

**Review by SandeepKrSuman — APPROVED** [review]
Looks good!

**Comment by CBID2** [comment]
> Looks good!

Thanks @SandeepKrSuman! :)

**Review by Deva-1903 — APPROVED** [review]

**Comment by Deva-1903** [comment]
Looks good🎉

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
