### PR TITLE
updated broken links

### PR DESCRIPTION
**Pull request by yrncollo**
## Fixes Issue
There was some of broken links on my bio. So I have updated them.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5157"></a>

### CODE REVIEW

**Review by Hrishi5111998 — APPROVED** [review]

**Review by senali-d — APPROVED** [review]
Look Good

**Review by SandeepKrSuman — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by yrncollo** [comment]
> Look Good

Awesome

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
