### PR TITLE
chore: add zabihhaqqani.json

### PR DESCRIPTION
**Pull request by zabihhaqqani**
## Changes proposed

added my data on linkfree

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
sc

## Note to reviewers

Please review my pull request. Thank you!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1575"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good to me! 
Thanks for contributing! 🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Comment by zabihhaqqani** [comment]
Thank you!

**Review by jaynarayan-vaishnav — APPROVED** [review]
LGTM🚀
keep up the good work

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

**Review by Panquesito7 — APPROVED** [review]
Thanks for contributing! 🎉


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
