### PR TITLE
Daily user stats

### LINKED ISSUE #2587: [FEATURE] Daily stats for new users
### Description

It would be great to keep stats per day for the app

https://github.com/EddieHubCommunity/LinkFree/blob/main/models/Stats.js

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

fixes #2587

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot 2023-01-13 at 08 31 13

## Note to reviewers
Screenshot 2023-01-13 at 08 31 13

### CODE REVIEW

**Comment by Aadarsh805** [comment]
@eddiejaoude Shouldn't it be `930` after the increase of `2` from `928`, like the other tabs displaying `4` -> `14` after that `10` increase

**Comment by eddiejaoude** [comment]
Thanks @Aadarsh805 , the `2` is how many new profiles today

**Comment by Aadarsh805** [comment]
> Thanks @Aadarsh805 , the `2` is how many new profiles today

What's `3` then, shouldn't active profiles be previous + `2` new

**Comment by eddiejaoude** [comment]
- `3` is active profiles (have stats against them in the db - so this number will be very near the `928` on production)
- `928` is total json files
- `2` is new profiles today (have stats against them in the db **today**)

I hope that makes sense?

**Comment by Aadarsh805** [comment]
> * `3` is active profiles (have stats against them in the db - so this number will be very near the `928` on production)
> * `928` is total json files
> * `2` is new profiles today (have stats against them in the db **today**)
> 
> I hope that makes sense?

Ohh okay, got it

**Comment by eddiejaoude** [comment]
But it is good you raise the question, maybe it is not as clear as I thought 🤔

**Comment by eddiejaoude** [comment]
I think we can merge to start collecting the stats, but then improve the way it is displayed

**Pull request merged**
