### PR TITLE
Added My Profile json file.

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
This is a PR which adds [Saptarshi Sarkar's](https://github.com/SaptarshiSarkar12) Profile json file to the public folder.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1586"></a>

### CODE REVIEW

**Review by Njong392 — APPROVED** [review]
Everything looks good to me.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Review by Panquesito7 — APPROVED** [review]
Thanks for sharing! 🎉


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Please update your filename to `username.json` which should be `SaptarshiSarkar12.json`! 

Rest looks good to me! 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by SaptarshiSarkar12** [comment]
@kumarsonsoff3 Renamed the file. Check that out.

**Review by Pradumnasaraf — APPROVED** [review]
Thank you for the changes. Looks good to merge :tada:

**Pull request merged**
