### PR TITLE
data:Ananya2001-an

### PR DESCRIPTION
**Pull request by Ananya2001-an**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3836"></a>

### CODE REVIEW

**Review by ChinmayMhatre — DISMISSED** [review]
Looks good!

**Comment by Ananya2001-an** [comment]
> Looks good!

Thanks.

**Review by Tejender1521 — APPROVED** [review]
Everything looks good to me

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
