### PR TITLE
Added showwcase icon

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
## Fixes Issue #1592

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1593"></a>

### CODE REVIEW

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
The icon needs adding in 3 places and they should always be added in alphabetical order. In icons.md it needs moving to the correct place but should also be imported into getIcons.js and a color specified in config/links.js

**Comment by SaptarshiSarkar12** [comment]
### I have not learned **_React_** yet, so , anyone please make a PR in my [fork](https://github.com/SaptarshiSarkar12/LinkFree) making the below required change : 
- ### adding 'showwcase' icon in GetIcons.js file

### I shall then merge it with my own repository and submit the changes with this PR.

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
As Emma said, to add an icon to LinkFree, you'll need to add that in 3 files! 
- import in `getIcons.js`
- color in `config/link.js`
- icon in `Readme.md`
But there is no showwcase icon is available in [React icons](https://react-icons.github.io/react-icons), so we cannot import it currently! 

You can have a look at issue #1043, to get into the discussion! 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient, Not maintainable

**Comment by SaptarshiSarkar12** [comment]
### I made a [PR](https://github.com/FortAwesome/Font-Awesome/pull/19268) in [Font Awesome repository](https://github.com/FortAwesome/Font-Awesome) to include the showwcase icon. Waiting for them to merge it.

**Comment by EmmaDawsonDev** [comment]
Please let us know when the pr to font awesome is successful and we can take another look at this pr

**Comment by SaptarshiSarkar12** [comment]
> Please let us know when the pr to font awesome is successful and we can take another look at this pr

@EmmaDawsonDev Okay, I shall inform you all when that PR is merged in the font-awesome repository.

**Pull request merged**
