### PR TITLE
gradient background

### PR DESCRIPTION
**Pull request by Occupying-Mars**
I just added a good gradient background we can change it personal profiles of people too
we can also do opacity stuff to make it look glassy

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/513"></a>

## A preview
https://user-images.githubusercontent.com/62864373/138594968-d6c046dc-3180-4dbf-9ceb-3fb7612d070f.mov

### CODE REVIEW

**Comment by Panquesito7** [comment]
Could you please add a screenshot of how it looks?

**Comment by ssensalo** [comment]
Nice idea @Vyvy-vi

**Review by krishguptadev — CHANGES_REQUESTED** [review]
After @Vyvy-vi's idea, what has to be done with this PR? 😅

**Comment by Vyvy-vi** [comment]
Maybe, we can merge this to a feature branch and this gets integrated into the project when that customization has been created?

**Comment by krishguptadev** [comment]
The background duplicating issue has still not been fixed I believe.

**Comment by Tejas-Teju** [comment]
Further this can be discussed in [Customizable background](https://github.com/EddieHubCommunity/LinkFree/issues/616)

**Review by CodingSpecies — COMMENTED** [review]
@Occupying-Mars Is there any updates on this? This has been inactive for a while now. Thank you.

**Comment by Tejas-Teju** [comment]
@CodingSpecies, we can close this PR for now. 

@emmalearnscode suggested (in [PR #820](https://github.com/EddieHubCommunity/LinkFree/pull/820)) to move the discussion back to issues and do some mock ups before proceeding with design changes.

Discuss more about the feature in [Issue #616](https://github.com/EddieHubCommunity/LinkFree/issues/616)

**Comment by Vyvy-vi** [comment]
Closing this PR due to the points above^

**Pull request closed without merging**
