### PR TITLE
Changed profile name font color on hovering in Dark mode. #2027

### LINKED ISSUE #2027: In Dark Mode in Search section white Box-shadow creates eye strain
## Issue
In Dark mode in the search section while hovering over the user component white box-shadow creates eye strain and the user name is not visible.
## Solution
We can simply fix this by adding this `color:black !important` in `.p-chip:hover` pseudo class .

### Screenshots

This is the issue:
Screenshot (23)
And this is the after adding the above line of code :
Screenshot (25)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MAX-786**
## Fixes Issue
Closes #2027 

## Changes proposed

- In Dark mode when hovering over the user profile's font color is changed from `white` to `black`.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Screenshot (26)

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2029"></a>

### CODE REVIEW

**Comment by MAX-786** [comment]
Hi @eddiejaoude, this closes #2027 can you please review this and merge this PR. Thanks.

**Comment by CBID2** [comment]
Looks great @MAX-786! :) 👍🏾  What inspired you to create this feature?

**Comment by MAX-786** [comment]
Thanks @CBID2, it was just my instincts since I love creating better ui/ux designs ^_^ .

**Comment by CBID2** [comment]
> Thanks @CBID2, it was just my instincts since I love creating better ui/ux designs ^_^ .

Instinct is always best! :)

**Comment by MAX-786** [comment]
😊👍

**Review by eddiejaoude — APPROVED** [review]
Thanks 👍

**Pull request merged**
