### PR TITLE
data: alek-v

### PR DESCRIPTION
**Pull request by alek-v**

### CODE REVIEW

**Review by AbbeyIT — CHANGES_REQUESTED** [review]
I think you need to rename the file with accordance with your GitHub username.

**Review by swagataroy30 — COMMENTED** [review]
Your file name needs to match your Github username, can you please change it to
`data/alek-v.json`. Thank you!

**Comment by alek-v** [comment]
It should be ok now, thank you.

**Review by Hrishi5111998 — APPROVED** [review]
thanks for contributing!

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"></p>

**Pull request merged**
