### PR TITLE
added personal links

### PR DESCRIPTION
**Pull request by masete**
## Changes proposed

- Added My personal links

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1396"></a>

### CODE REVIEW

**Review by bishal7679 — CHANGES_REQUESTED** [review]
Your profile looks good but please undo the changes made to the package-lock file.
Please revert this change from version `"0.68.3"` to `"0.68.0"`
Screenshot (141)



__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by Vyvy-vi — CHANGES_REQUESTED** [review]
Please view the comment from bishal7679 - https://github.com/EddieHubCommunity/LinkFree/pull/1396/#pullrequestreview-1011532095

The package-lock.json file shouldn't be committed. You can exclude it from the PR by using the following git commands -
```
git reset --soft HEAD~1
git reset HEAD package-lock.json
git commit --amend
```


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by masete** [comment]
> Please view the comment from bishal7679 - #1396
> 
> The package-lock.json file shouldn't be committed. You can exclude it from the PR by using the following git commands -
> 
> ```
> git reset --soft HEAD~1
> git reset HEAD package-lock.json
> git commit --amend
> ```
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** hammer_and_wrench This code needs a fix

Thank you for your feedback and the exact steps to be followed.

**Comment by masete** [comment]
> Please view the comment from bishal7679 - #1396
> 
> The package-lock.json file shouldn't be committed. You can exclude it from the PR by using the following git commands -
> 
> ```
> git reset --soft HEAD~1
> git reset HEAD package-lock.json
> git commit --amend
> ```
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** hammer_and_wrench This code needs a fix

I have added the changes already

**Review by emmalearnscode — CHANGES_REQUESTED** [review]
Please remove the changes to the gitignore file and the package lock file.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Not maintainable

**Review by bishal7679 — COMMENTED** [review]
Dont make any changes in .gitignore file.
Just your profile.json file and revert changes the package-lock.json 
From `0.68.3` to `0.68.0` and then push together all.

**Comment by kumarsonsoff3** [comment]
Hey @masete, the checks are failing because you have unfortunately deleted the dependencies file from your fork! 
**You were only asked to revert the Changes**

I've restored it for you, **kindly merge the [PR #1](https://github.com/masete/LinkFree/pull/1) to your fork. Rest will take care of it!**

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Hey @masete, the checks are failing because you have unfortunately deleted the dependencies file from your fork!
**You were only asked to revert the Changes**

**I've restored it for you, kindly merge the https://github.com/masete/LinkFree/pull/1 to your fork. Rest will take care of it!**

**Comment by masete** [comment]
> Hey @masete, the checks are failing because you have unfortunately deleted the dependencies file from your fork! **You were only asked to revert the Changes**
> 
> I've restored it for you, kindly merge the **[PR #1](https://github.com/masete/LinkFree/pull/1)** to your fork. Rest will take care of it!

Thank you, all checks are now passing

**Review by bishal7679 — APPROVED** [review]
LGTM!
cc @emmalearnscode @Vyvy-vi 
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by krshkodes — APPROVED** [review]
Looks awesome! Thank you!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Efficient

**Review by kumarsonsoff3 — APPROVED** [review]

**Pull request merged**
