### PR TITLE
ci: add label `status: blocked` to PR

### LINKED ISSUE #5371: [FEATURE] Pull Request label "status:blocked"
### Description

Add label to PR `status: blocked` if

- not `chore: profile`
- and there is no `issue` number
- ~~and issue does not have label `status: ready for dev`~~ this can happen in a new PR

Can this be done with Reviewpad?

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Ananya2001-an**
## Fixes Issue
closes #5371 

## Changes proposed

Add label to PR status: blocked if

- not `chore: profile`
- and issue does not have label `status: ready for dev`
- and there is no issue number

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5394"></a>

### CODE REVIEW

**Comment by Ananya2001-an** [comment]
Hey @eddiejaoude I have created a draft PR for now since I wanted to discuss some things.

When checking for label `chore: profile` in the PR, it gives YAML error since the colon is being interpreted as some key:value.

image
 
Other than that I guess we are able to add label `status: blocked` when `chore: profile` is not added and no issue is linked but I am not sure how to check the issue's labels. Do you have any idea?

**Comment by eddiejaoude** [comment]
Thank you for raising a draft PR, it makes it clearer to discuss 👍 

> When checking for label chore: profile in the PR, it gives YAML error since the colon is being interpreted as some key:value.

I think you can wrap the rule in single quotes, looking at one of their examples https://docs.reviewpad.com/guides/syntax#example-8

**Comment by eddiejaoude** [comment]
> I am not sure how to check the issue's labels. Do you have any idea?

I think you could get the description and check if it contains an issue number

- get description https://docs.reviewpad.com/guides/built-ins#description
- check if it contains https://docs.reviewpad.com/guides/built-ins#contains

**Comment by Ananya2001-an** [comment]
> Thank you for raising a draft PR, it makes it clearer to discuss 👍
> 
> > When checking for label chore: profile in the PR, it gives YAML error since the colon is being interpreted as some key:value.
> 
> I think you can wrap the rule in single quotes, looking at one of their examples https://docs.reviewpad.com/guides/syntax#example-8

Cool! That worked.

**Comment by Ananya2001-an** [comment]
> > I am not sure how to check the issue's labels. Do you have any idea?
> 
> I think you could get the description and check if it contains an issue number
> 
> * get description https://docs.reviewpad.com/guides/built-ins#description
> * check if it contains https://docs.reviewpad.com/guides/built-ins#contains

That is already solved. I can see whether the PR has a linked issue or not with this:
image

The main problem is how to check if the `status: ready for dev` label is present for that issue or not. What I mean to say is that I can get the issue number from the description but I don't think there is any built in function for giving issue no. as input and then getting its labels.

**Comment by eddiejaoude** [comment]
> The main problem is how to check if the status: ready for dev label is present for that issue or not. What I mean to say is that I can get the issue number from the description but I don't think there is any built in function for giving issue no. as input and then getting its labels.

We might have to do the following steps
1. get the description and regex for the issue number
2. get the labels from the GitHub API https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#get-an-issue

**Comment by Ananya2001-an** [comment]
> 

I agree. That's what I suggested earlier. Let me see what I can do with it.

**Comment by eddiejaoude** [comment]
Great, thank you @Ananya2001-an 👍

**Comment by Ananya2001-an** [comment]
> Great, thank you @Ananya2001-an 👍

Happy to help 😊

**Comment by Ananya2001-an** [comment]
Hey @eddiejaoude I am facing issues with implementing the issue label thing. I feel I will waste more time if I continue working on it. Better alternative would be to merge the current changes to a temporary branch for now and maybe someone else can continue working on it. I am sorry I am leaving it halfway but I thought that's the best thing to do rather than prolonging it.  Hope you understand.

Right now with my changes we can label the PR `status: blocked` when it has no `chore: profile label` and then if it has no linked issue to it.

**Comment by eddiejaoude** [comment]
> Hey @eddiejaoude I am facing issues with implementing the issue label thing. I feel I will waste more time if I continue working on it. Better alternative would be to merge the current changes to a temporary branch for now and maybe someone else can continue working on it. I am sorry I am leaving it halfway but I thought that's the best thing to do rather than prolonging it. Hope you understand.
> 
> Right now with my changes we can label the PR `status: blocked` when it has no `chore: profile label` and then if it has no linked issue to it.

Thank you @Ananya2001-an for your honesty. We can leave your PR in draft and someone else can continue it 👍

**Comment by eddiejaoude** [comment]
Actually I think this already adds value and a new PR could be added later to make it more advanced

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by Ananya2001-an** [comment]
> Looks good 👍 

Awesome. Thanks for merging it 😊

**Pull request merged**
