### PR TITLE
added outline to hamburger on tab

### LINKED ISSUE #4226: Hamburger menu has no visible focus when focussed with keyboard
### Description

When tabbing through the site it should be possible to see which element is in focus by the presence of a visible focus outline. The hamburger menu and its corresponding close button are missing this outline.

### Screenshots

Screenshot 2023-01-29 165736

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alokVerma749**
## Fixes Issue

Closes #4226 
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
image

image

## Note to reviewers

Now hamburger is navigatable through tab

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4245"></a>

### CODE REVIEW

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
The outline should only be visible on focus, when a user tabs to it with the keyboard.

**Comment by alokVerma749** [comment]
> The outline should only be visible on focus, when a user tabs to it with the keyboard.

yes it is working as you state

**Comment by alokVerma749** [comment]
Untitled design
   
on tab it got outlined

**Comment by EmmaDawsonDev** [comment]
Ok, must be an inconsistency of tailwind. I would’ve expected it to need `focus:` to only trigger on focus

**Comment by alokVerma749** [comment]
i think i should put `focus:` , as it reflects the purpose of the style

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
