### PR TITLE
Feature : Profile Header Style changes

### LINKED ISSUE #2171: [FEATURE] New styles for profile section header
### Description

we can change the profile section from 
##this
image

## to this
image

hence making it more promising in continuity with #2141 

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ManishBisht777**
## Fixes Issue #2171 

Closes #2171 

## Changes proposed

position change for no of views

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2215"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
As more social icons could appear, I think keep the views at the top next to the profile picture is probably best

**Comment by ManishBisht777** [comment]
image
like this?

**Comment by eddiejaoude** [comment]
no, how it is now already, check the `main` branch or https://linkfree.eddiehub.io/eddiejaoude

**Comment by ManishBisht777** [comment]
ok, closing this issue then @eddiejaoude

**Comment by eddiejaoude** [comment]
It does look very similar to what we have already? is it because you have another PR merged?

**Comment by eddiejaoude** [comment]
Yes, maybe close this one and focus on your other PR https://github.com/EddieHubCommunity/LinkFree/pull/2214#pullrequestreview-1178074931

**Comment by ManishBisht777** [comment]
actually, I created #2177 but pushed some changes which are not created by me so it closed that one and started from a new branch with the new changes

**Pull request closed without merging**
