### PR TITLE
fix: the darkmode padding issue fixed

### PR DESCRIPTION
**Pull request by KSSaiTeja**
## Fixes Issue

Fixes: #8196 

## Changes proposed

Added neccesary styings and changed some meta data for SEO

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

https://github.com/EddieHubCommunity/LinkFree/assets/130981122/a5f7372e-d979-4337-afe3-f73b7fc85bb0

## Note to reviewers

please take this into consideration, i worked earier but not able to raise PR, with some issues as i am a beginner i dont know how to make another commit and push in different branch i worked for different issue for LINKFREE so that i cant able to make a PR from same fork due to my lack of knowledge.. If anyone knows how to fix my problem, help can be appreciated.

For now, i think the issue got fixed and also please consider this. I worked a lot to identify the issue where it is.. please consider me and merge my PR. Any changes needed? let me know i will fix them

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8690"></a>

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
Hi , can you add a screenshot to the description please. Thanks!

**Comment by KSSaiTeja** [comment]
> Hi , can you add a screenshot to the description please. Thanks!

hey @ChinmayMhatre sure here is the work i have changed..  

https://github.com/EddieHubCommunity/LinkFree/assets/130981122/f9591853-9dcd-496a-8095-b59980541fa4

please make a merge this issue got fixed.. Please consider this

**Comment by KSSaiTeja** [comment]
> Hi , can you add a screenshot to the description please. Thanks!

will you please check this and make a merge to it.. please

**Comment by ChinmayMhatre** [comment]
Closing this PR since issue already assigned to someone else and a PR has already been raised. @KSSaiTeja  Please check the community guidelines before raising a PR. You will have to be assigned to a issue before you can work on it, this avoids confusions 

https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by KSSaiTeja** [comment]
very sad to see this, but from next time i will work upon the issue assigned to me only

**Pull request closed without merging**
