### PR TITLE
adding my profile

### PR DESCRIPTION
**Pull request by doniwirawan**
Fixes #

## Proposed Changes

  -
  -
  -

## Screenshots

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/236"></a>

### CODE REVIEW

**Comment by voidz7** [comment]
Why would you delete package-lock.json ??? 🤔

**Comment by doniwirawan** [comment]
> Why would you delete package-lock.json ???

i'm so sorry, i'm beginner

**Review by rohan-kulkarni-25 — CHANGES_REQUESTED** [review]
- Please Don't Commit Package Json file

**Comment by voidz7** [comment]
> > Why would you delete package-lock.json ???
> 
> i'm so sorry, i'm beginner

If okay , dw close this pr and make another when with only your .json data added .

**Comment by doniwirawan** [comment]
it's okay

**Pull request closed without merging**
