### PR TITLE
feat: added past events and  ongoing events filter

### LINKED ISSUE #4358: [FEATURE] Filter to show past events
### Description

Currently past events are hidden, it would be good to be able to show these

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by swagataroy30**
## Fixes Issue
Closes #4358 

## Changes proposed

- Added `past events` filter
- Added `ongoing events` filter
- Changed `Show all` filter to `Show all future events` which now can be specific to show only future events
- Sorted the `past events`, so that the recently occurred events show at the top

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### Before
Screenshot from 2023-02-07 13-46-36

### After
Screenshot from 2023-02-07 13-45-45

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4574"></a>

### CODE REVIEW

**Review by Aadarsh805 — APPROVED** [review]
Great job, everything's working fine on my side

**Comment by Aadarsh805** [comment]
A suggestion here is that we don't need to add the word `show`, `All future events` and `All ongoing events` is sufficient as an indicator that it's going to show all the events

**Review by iamthecloverly — DISMISSED** [review]

**Comment by swagataroy30** [comment]
> A suggestion here is that we don't need to add the word `show`, `All future events` and `All ongoing events` is sufficient as an indicator that it's going to show all the events

Hey thanks for the suggestion ... let's wait for @SaraJaoude's view on it !

**Comment by SaraJaoude** [comment]
I agree, the shorter version is a great idea 👍

**Comment by swagataroy30** [comment]
> I agree, the shorter version is a great idea +1

Okay, I'll make the changes!

**Comment by Parsifal-M** [comment]
Nice contribution! :tada:  I actually started to look into this myself but stopped and thought, someone must be doing this already... :laughing: I am glad I checked :+1:

**Review by Parsifal-M — APPROVED** [review]

**Review by eddiejaoude — APPROVED** [review]
Looks great, thank you 👍

**Pull request merged**
