### PR TITLE
Create kelvinparmar.json

### PR DESCRIPTION
**Pull request by kelvinparmar**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2809"></a>

### CODE REVIEW

**Review by dan-mba — CHANGES_REQUESTED** [review]
Please remove the comma after the `}` on line 27

**Comment by kelvinparmar** [comment]
How can I change it from here

**Comment by dan-mba** [comment]
> How can I change it from here

Whatever method you used to create the file, use the same method to edit it and create a 2nd commit.
The PR will pick up the changes.

**Review by md-abid-hussain — CHANGES_REQUESTED** [review]
Remove ',' after '}' on line 27.

**Comment by kelvinparmar** [comment]
Changes are updated

**Review by dan-mba — APPROVED** [review]
Looks good to me

**Comment by kelvinparmar** [comment]
Thank you @dan-mba

**Comment by kelvinparmar** [comment]
Hey @dan-mba 
In my linkfree profile i have one problem in that i have added wrong link in my github profile 
So I need to change it. Please open my pr

**Comment by dan-mba** [comment]
> Hey @dan-mba
> In my linkfree profile i have one problem in that i have added wrong link in my github profile
> So I need to change it. Please open my pr

@kelvinparmar Since this PR is already merged, any changes should go through a new PR.

**Comment by kelvinparmar** [comment]
How can I do? because same filename will not allowed me to create

**Comment by dan-mba** [comment]
> How can I do? because same filename will not allowed me to create

Make sure to update your fork by clicking on the sync fork button.
Create a new branch from the updated main.
Edit your profile & submit a new PR.

**Comment by eddiejaoude** [comment]
@kelvinparmar we have documentation and screenshots on how you can edit your profile https://linkfree.eddiehub.io/docs/how-to-guides/editing

**Pull request merged**
