### PR TITLE
Changed tag text color to black

### LINKED ISSUE #7040: [FEATURE] Change tag text color on select
### Description

Tags text colour when selected on search page should change to black color instead of white to improve readibility.
Screenshot from 2023-05-20 20-06-47

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by JayK1524**
## Fixes Issue

Closes #7040

## Changes proposed

Changed tag text color to black when selected on search page to improve readability.

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7095"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you for your contribution. Please add a screenshot of before and after

**Comment by JayK1524** [comment]
> Thank you for your contribution. Please add a screenshot of before and after

I am unable to see the changes. I think the pull request has not been merged yet.

**Comment by ChinmayMhatre** [comment]
> > Thank you for your contribution. Please add a screenshot of before and after
> 
> I am unable to see the changes. I think the pull request has not been merged yet.

Please add a screenshot of the changes you have made in your branch

**Comment by eddiejaoude** [comment]
> > Thank you for your contribution. Please add a screenshot of before and after
> 
> I am unable to see the changes. I think the pull request has not been merged yet.

It has not been merge, it is still open waiting for you to address the maintainers comments first

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍  thank you

Screenshot 2023-05-31 at 23 05 47

**Pull request merged**
