### PR TITLE
data:Tanishka-dev

### PR DESCRIPTION
**Pull request by Tanishka-dev**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3621"></a>

### CODE REVIEW

**Review by dan-mba — CHANGES_REQUESTED** [review]
Please move your profile to the data directory and rename it to match your GitHub id.
It should be `data/Tanishka-dev.json`

**Review by accodes21 — APPROVED** [review]
Looks Great

**Review by dan-mba — CHANGES_REQUESTED** [review]
Removing the comma on line 55 should fix the JSON error

**Comment by Tanishka-dev** [comment]
> Please move your profile to the data directory and rename it to match your GitHub id. It should be `data/Tanishka-dev.json`

Done!

**Review by dan-mba — DISMISSED** [review]
Looks good to me

**Comment by dan-mba** [comment]
> When will it be merged?

It should get merged sometime today.

**Comment by dan-mba** [comment]
I would recommend fixing the cases of the profile file to match your GitHud id.
It should be `data/Tanishka-dev.json`.
Because of the difference in case on the d in dev, our automation isn't tagging this PR correctly.

**Comment by Tanishka-dev** [comment]
> I would recommend fixing the cases of the profile file to match your GitHub id. It should be `data/Tanishka-dev.json`. Because of the difference in case on the d in dev, our automation isn't tagging this PR correctly.

Done

**Review by dan-mba — APPROVED** [review]
LGTM

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Pull request merged**
