### PR TITLE
data: Kirtikagoyal

### PR DESCRIPTION
**Pull request by Kirtikagoyal**
## Changes proposed

renamed file and updated profile username.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3672"></a>

### CODE REVIEW

**Review by senali-d — CHANGES_REQUESTED** [review]
@Kirtikagoyal Revert the changes in `package.json`, `package.lock.json` and `CHANGELOG.md` files.

Let us know if you need any help with this! :)

**Review by Tejender1521 — CHANGES_REQUESTED** [review]
Remove all the files except your Kirtikagoyal.json

**Comment by Chandraprakash-Darji** [comment]
@Tejender1521 this github action is realesing it new version and creating confilict

**Comment by Chandraprakash-Darji** [comment]
@senali-d Can you help out?

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by Pradumnasaraf** [comment]
Hey, @Kirtikagoyal 

I see the PR has got lots of issues like conflict and unwanted files and for you getting hard you fix due to Action creating the release, so I have fixed it from my side (We generally don't fix from our end, because it can create a conflict in future)

A small note, next time create a branch and add changes to them, you are committing on the main, this is why the action is creating extra commits.

**Comment by Kirtikagoyal** [comment]
Thankyou for fixing it merging it.

**Pull request merged**
