### PR TITLE
data: SageKyle

### PR DESCRIPTION
**Pull request by SageKyle**
update LinkFree profile by adding a milestones section

## Note to reviewers

I changed the entire data because I used a JSON formater/validator to format the entire data before copying/pasting the formatted data.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5297"></a>

### CODE REVIEW

**Review by Krishnapro — APPROVED** [review]
LGTM 🚀 

you don't need to change the entire data Just make changes to what you want and then copy all the code and validate it using JSON validator. if you make any mistake in particular lines you only change those lines. (It's just a suggestion)

**Review by sidharthviz — APPROVED** [review]
🎉LGTM

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Review by Sindhuinti — APPROVED** [review]
Looks good

**Comment by rohitverse** [comment]
LGTM

**Review by rohitverse — APPROVED** [review]
LGTM

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by CBID2 — APPROVED** [review]
Looks great! :)

**Review by vedprakashnautiyal — APPROVED** [review]

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! 🎉

**Pull request merged**
