### PR TITLE
increses the font size

### LINKED ISSUE #7297: Font size is too small for Feature section description on MainPage (Desktop)
### Description

Font size is too small for the Feature Section (Heading/Description) on Main page.
We can increase it a little more to make it look good.

### Screenshots

image

### Additional information

Please make sure the Mobile view in not impacted, handle it too.

### PR DESCRIPTION
**Pull request by KushagraVarshney05**
## Fixes Issue

closes #7297

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

BEFORE
Screenshot 2023-06-04 120809

AFTER
Screenshot 2023-06-04 120751

## Note to reviewers

increases the font size without affecting the mobile view

also opened an issue for color contrast for better visibility and accessibility 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7367"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Previous PR https://github.com/EddieHubCommunity/LinkFree/pull/7342

**Comment by eddiejaoude** [comment]
Please can you add a before and after screenshot as suggested in the PR template description

**Comment by KushagraVarshney05** [comment]
> Please can you add a before and after screenshot as suggested in the PR template description

I have added the screenshots as you have suggested but don't know how to re-request for review.

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
