### PR TITLE
Issue:2562

### LINKED ISSUE #2562: backticks not getting rendered in Docs
### Description

On the website, the backticks are not getting rendered. It's bolding just bolding up the text. 

**It should look something like** `sample-text` 

- Link to Docs folder - https://github.com/EddieHubCommunity/LinkFree/tree/main/pages/docs
- Link to the hosted site -  https://linkfree.eddiehub.io/docs

### Screenshots

Screenshot 2023-01-01 at 3 49 46 PM

Above Screenshot hosted link - https://linkfree.eddiehub.io/docs/contributing/hacktoberfest

### PR DESCRIPTION
**Pull request by ayushsgithub**
Screenshot (11)

resolve #2562
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3839"></a>

### CODE REVIEW

**Review by ManishBisht777 — COMMENTED** [review]
can you explain a bit about the proposed changes and why they are needed 

it's easy to review when we have some context about the changes

**Comment by schmelto** [comment]
IG there is another PR already open for this issue see #2566

**Comment by eddiejaoude** [comment]
Thank you for the contribution and great collab everyone 👍 

@schmelto is correct, this is a duplicate of https://github.com/EddieHubCommunity/LinkFree/pull/2566 , so I will close

**Comment by ayushsgithub** [comment]
@ManishBisht777 sorry I didn't know about this much, I just wanted to contribute but I need to learn more, I have never solved a good first issue before.

**Comment by ayushsgithub** [comment]
Can anyone tell me how to deal with your very first good first issue and how to solve it?

**Comment by schmelto** [comment]
> Can anyone tell me how to deal with your very first good first issue and how to solve it?

Just look for good first issues in the repos you want to contribute.
Than in the issue ask if someone can assign you / if you can work on this issue or if someone else is already working on the issue.
When you get a go of a maintainer fell free to code and open a pr for the issue.

Ig this would be the workflow for that one.

**Comment by ayushsgithub** [comment]
Thanks @schmelto

**Pull request closed without merging**
