### PR TITLE
data:  jfmartinz

### PR DESCRIPTION
**Pull request by jfmartinz**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6950"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Please make sure that your filename to be exact same as your username. Rename your[ file here](https://github.com/JFMartinz/LinkFree/edit/JFMartinz-patch-1/data/jfmartinz.json) to `JFMartinz.json`

Change `jfmartinz.json`  -->  `JFMartinz.json` 

Let us know if you need any help with this! :)

**Comment by JFMartinz** [comment]
> Please make sure that your filename to be exact same as your username. Rename your[ file here](https://github.com/JFMartinz/LinkFree/edit/JFMartinz-patch-1/data/jfmartinz.json) to `JFMartinz.json`
> 
> Change `jfmartinz.json` --> `JFMartinz.json`
> 
> Let us know if you need any help with this! :)

Did I do it right?

**Comment by kumarsonsoff3** [comment]
It seems like you've recently changed the case of your username too!?

Please make sure that your filename exactly matches your GitHub username.

**Comment by jfmartinz** [comment]
> It seems like you've recently changed the case of your username too!?
> 
> Please make sure that your filename exactly matches your GitHub username.



> It seems like you've recently changed the case of your username too!?
> 
> Please make sure that your filename exactly matches your GitHub username.

I think i did it? can you check? tahnk you 🙌

**Review by harshsingh32 — COMMENTED** [review]
Thanks for contribution.

**Review by rupali-codes — COMMENTED** [review]
Looks good to me

**Review by SurajPratap10 — APPROVED** [review]
LGTM

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks! 🎉

**Pull request merged**
