### PR TITLE
data: isdavehill

### PR DESCRIPTION
**Pull request by Isdavehill**
## Changes proposed

Adds dave Hill's profile to LinkFree

## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8575"></a>

### CODE REVIEW

**Review by yassineatik — APPROVED** [review]
Looks good

**Review by sital002 — CHANGES_REQUESTED** [review]
Your file name must match your github username. Please change your filename to Isdavehill.json

**Comment by sital002** [comment]
> Looks good

Please don't approve changes without looking carefully.

**Review by SaraJaoude — CHANGES_REQUESTED** [review]
Please make sure your file name matches your GitHub username exactly (it is case sensitive). Instead of `data/isdavehill.json`   it should be `data/Isdavehill.json`

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart-json to help you update this Pull Request.

**Review by sital002 — APPROVED** [review]
LGTM 👍

**Review by kumarsonsoff3 — APPROVED** [review]
Looks awesome. Great collaboration everyone. 👍

**Pull request merged**
