### PR TITLE
Issue #6 - Add EddieHubCommunity template files

### PR DESCRIPTION
**Pull request by stemount**
We skipped using the template! But we can always merge it in!

### CODE REVIEW

**Review by FayasNoushad — APPROVED** [review]
Nice 👍

**Comment by nhcarrigan** [comment]
@stemount can you give this a rebase when you have a moment?

**Review by nhcarrigan — APPROVED** [review]
Looks good to me!

Thanks for your contribution!

**Comment by stemount** [comment]
hey @nhcarrigan thank you for the feedback, squashing/rebase would have tidied this up as you can see the mess of merge commits here. Thankfully there isn't LOADS of merge with "upstream" commits, and just 2.

thanks @rohan-kulkarni-25 managed to sneak in fixing the PNG thing in here too ;-) sneaky

**Pull request merged**
