### PR TITLE
Added link to Twitter page

### PR DESCRIPTION
**Pull request by CBID2**
## Check List (Check all the applicable boxes) 

- [X ] My code follows the code style of this project.
- [ X] My change requires changes to the documentation.
- [ X] I have updated the documentation accordingly.
- [ X] All new and existing tests passed.
- [ X] This PR does not contain plagiarized content.
- [ X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Feedback is appreciated 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4452"></a>

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
LGTM 👍🏻

**Review by himanshu1221 — APPROVED** [review]
LGTM :+1:

**Review by priyankarpal — APPROVED** [review]
LGTM 👍🏻

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by CBID2** [comment]
> Looks good to merge. Thank you for your contribution! :tada:
> 
> 
> 
> Welcome to Twitter 🐦 

Thanks

**Comment by CBID2** [comment]
I don't see the change @Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
It takes some for the deployment. it's live now 🎉 
https://linkfree.eddiehub.io/CBID2

**Pull request merged**
