### PR TITLE
Made changes for better navigation inside the website

### PR DESCRIPTION
**Pull request by Vedant-Manjrekar**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1933"></a>

### CODE REVIEW

**Comment by EmmaDawsonDev** [comment]
Can you fix the failing tests and also post a screenshot of how the site looks with your changes?

**Comment by Vedant-Manjrekar** [comment]
> Can you fix the failing tests and also post a screenshot of how the site looks with your changes?

Can you tell me what is causing the errors ? and how may I approach it, as everything was fine untill I synced my forked repository and pulled the changes.

**Comment by Vedant-Manjrekar** [comment]
Before: 
Screenshot 2022-10-18 at 12 01 12 PM

After:
Screenshot 2022-10-18 at 12 00 50 PM

**Comment by Vedant-Manjrekar** [comment]
@EmmaDawsonDev Done 👍🏽

**Pull request merged**
