### PR TITLE
Updated Profile Page

### PR DESCRIPTION
**Pull request by MadhuSaini22**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2698"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Looks good 👍 But I think your fork/branch are not up to date, as you have generated files in there - you can update your fork/branch and push the changes to your branch in your fork and it will automatically update your PR

**Comment by MadhuSaini22** [comment]
> Looks good 👍 But I think your fork/branch are not up to date, as you have generated files in there - you can update your fork/branch and push the changes to your branch in your fork and it will automatically update your PR

Tried to do that eddie, but don't know what's happening, all check are being failed
image

**Comment by MadhuSaini22** [comment]
Just done and made other PR, sorry for this Eddie

**Comment by eddiejaoude** [comment]
No problem, it happens to us all

**Pull request closed without merging**
