### PR TITLE
feat: manage profile with forms

### LINKED ISSUE #5575: [FEATURE] Manage profile with a form
### Description

Page to manage profile of authenticated user

- toggle switch to use json file or form
- profile (name, bio, etc)
- links
- social shortcuts
- events
- testimonials

Conditions
- profile form with json file data if new (not existing)
- display alert if json file and MongoDB entry both exist - recommend they remove the json file

### TODO

- [x] manage page
- [x] update basic profile
- [x] form tags
- [x] ~~toggle between file and database source~~ no longer needed
- [x] add manage link to navbar
- [ ] ~~toggle profile enable/disable~~ low priority
- [ ] ~~associate profile to the logged in account~~ moved to another issue https://github.com/EddieHubCommunity/LinkFree/issues/7065
- [ ] ~~if username is different from logged in user, show a warning and have a button to update (this will only work if someone logged in before they changed their username)~~ moved to separate issue https://github.com/EddieHubCommunity/LinkFree/issues/7065
- [x] warning if json file exists
- [x] form links + socials
- [x] form testimonials
- [x] form milestones
- [x] form events

**notes:**
- must be able to handle multiple profiles in the database
- rename the profile (username) if available

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

closes #5575 

> Deployment notes:
> - drop `linkstats` collection

To access forms visit `/account/manage/profile`

TODO
- [x] navigation to access profile form and statistics page
- [x] profile form
- [x] tags form
- [x] links form (+ social shortcut toggle)
- [x] testimonials form
- [x] events form
- [x] milestones form
- [x] test with non existing profile (new)

Screenshot 2023-05-25 at 06 04 49

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6638"></a>

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6875"></a>

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6998"></a>

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
Hey Eddie, I think the actions are failing because the api routes "users" have been renamed to "profiles" https://github.com/EddieHubCommunity/LinkFree/pull/7355

**Comment by eddiejaoude** [comment]
Thank you @ChinmayMhatre 👍 this is still in draft, there will be a few failures I will need to fix

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

Here is a suggestion. For new people, it will be hard to understand what **group**,  **enables** and **pin** mean we can do something like an `i` button or a line to explain things. 

Screenshot 2023-06-14 at 7 23 59 PM

**Comment by SaraJaoude** [comment]
Some suggestions:

- [ ] navbar: move `version no.` to footer
- [x] rename `login` to `login/sign up`
- [x] login page: add `Don't have a GitHub Account? Create one on GitHub` (add link to GitHub registration)
- [ ]  what appears for new profile after you register?

**Comment by eddiejaoude** [comment]
From @amandamartin-dev 

> 1. On save of a change to my NAME, i then navigated to search and searched for myself.  The card did not reflect my name change, but clicking into the card did reflect the change on my profile page.
I then changed my name a second time.
THe 1st change now presents on my profile care and change 2 now reflects in the profile page.
Refreshing the page does not seem to affect anything

> 2. There is no character limit on any of the fields so I can just spam away long content
I can write script tags, offensive content, links to offensive content
I can enter non-tag content in the tags (can put whatever there really)
Basically since this will bypass PR review, I think there should be some form validations

> 3. it's not clear what switching the layout will do since the preview does not reflect a change.  You have to save and go look

**Comment by CBID2** [comment]
> Notes for documentation:
> 
> * [x]  navbar: move `version no.` to footer
> * [x]  rename `login` to `login/sign up`
> * [x]  login page: add `Don't have a GitHub Account? Create one on GitHub` (add link to GitHub registration)
> * [ ]  link add/edit: show group on preview (if used)
> * [ ]  manage pages in responsive mobile drop down does not work
> * [ ]  what appears for new profile after you register?
> * [ ]  Dark mode for managing profile forms

Hi there. I just looked through the Quickstart file and noticed that the bullet points in the “Next Steps” section are not hyperlinked. Can I update those? I’ll gladly work with you on them! :)

**Comment by eddiejaoude** [comment]
> Hi there. I just looked through the Quickstart file and noticed that the bullet points in the “Next Steps” section are not hyperlinked. Can I update those? I’ll gladly work with you on them! :)

@CBID2 The `next steps` on the quickstart guide are links for me in the `main` branch and also this pull request (no changes were made in this PR) - please see screenshot and code below


Screenshot 2023-06-18 at 21 08 51


https://github.com/EddieHubCommunity/LinkFree/blob/f733de2d99e8750190396c00c22677441c01e7b4/pages/docs/quickstart.mdx?plain=1#L215-L219

**Comment by CBID2** [comment]
> > Hi there. I just looked through the Quickstart file and noticed that the bullet points in the “Next Steps” section are not hyperlinked. Can I update those? I’ll gladly work with you on them! :)
> 
> @CBID2 The `next steps` on the quickstart guide are links for me in the `main` branch and also this pull request (no changes were made in this PR) - please see screenshot and code below
> 
> Screenshot 2023-06-18 at 21 08 51
> https://github.com/EddieHubCommunity/LinkFree/blob/f733de2d99e8750190396c00c22677441c01e7b4/pages/docs/quickstart.mdx?plain=1#L215-L219

Oh ok @eddiejaoude! :) With that said, I can update the directions on those pages if you’re open :)

**Comment by eddiejaoude** [comment]
> Oh ok @eddiejaoude! :) With that said, I can update the directions on those pages if you’re open :)

@CBID2 I don't understand what you mean about "directions"?

**Comment by CBID2** [comment]
> > Oh ok @eddiejaoude! :) With that said, I can update the directions on those pages if you’re open :)
> 
> @CBID2 I don't understand what you mean about "directions"?
@eddiejaoude, I mean update the steps on how a person can edit/add links to their profile. From what you showed in the Linkfree call, people can drag and drop their links.

**Comment by eddiejaoude** [comment]
> @CBID2 I don't understand what you mean about "directions"? @eddiejaoude, I mean update the steps on how a person can edit/add links to their profile. From what you showed in the Linkfree call, people can drag and drop their links.

There is no drag and drop - thank you, but the documentation for this pull request has already been done, I will push them tomorrow as it is very late here now

**Comment by CBID2** [comment]
> > @CBID2 I don't understand what you mean about "directions"? @eddiejaoude, I mean update the steps on how a person can edit/add links to their profile. From what you showed in the Linkfree call, people can drag and drop their links.
> 
> 
> 
> @CBID2 there is no drag and drop - thank you, but the documentation for this pull request has already been done, I will push them tomorrow as it is very late here now

Ok

**Comment by ChinmayMhatre** [comment]
Will create a new pr for the other theme changes

**Comment by eddiejaoude** [comment]
> Will create a new pr for the other theme changes

Great thank you @ChinmayMhatre 👍  please remember to branch from the latest version of this branch as I made more updates recently - this will make sure we don't get conflicts

**Review by Pradumnasaraf — APPROVED** [review]

**Pull request merged**
