### PR TITLE
Delete profile from Linkfree

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
## Fixes Issue
- Delete profile from Linkfree

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Seems that people don't like me being a part of EddieHubCommunity, thus left the organization and now want to delete my profile from Linkfree.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1137"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Hi Kendall, I am curious to know why you are deleting your profile? Are there any improvements we can make?

**Comment by KendallDoesCoding** [comment]
> Hi Kendall, I am curious to know why you are deleting your profile? Are there any improvements we can make?

Well, you guys have gotten complaints about me and I feel kinda unwanted in the community... I'm new to open source communities.

**Comment by eddiejaoude** [comment]
1. we are not just guys in the EddieHub community, we use inclusive language
2. The complaints were about you spamming many people in DMs where our rules clearly say do not DM people without consent and you accepted these rules when joining our Discord
3. In addition you make a lot of irrelevant noise on our and other people's repos, it is not about green squares but about collaboration

I hope you will take the feedback on board, I do not want to hurt your enthusiasm, that is why it took a lot of complaints before I messaged you about it, I was hoping you would figure it out naturally.

I wish you all the best in your open source adventures.

**Comment by KendallDoesCoding** [comment]
> we are not just guys in the EddieHub community, we use inclusive language

Sorry, updated the messege to yall

> The complaints were about you spamming many people in DMs where our rules clearly say do not DM people without consent and you accepted these rules when joining our Discord

I'm sorry about that... I wasn't really dming people from EddieHubCommunity, we just happend to have mutual servers with EddieHubCommunity as well as I didnt mean to cause any issues.

> In addition you make a lot of irrelevant noise on our and other people's repos, it is not about green squares but about collaboration

Totally understand this. But, I haven't done this many times, except for a couple of times.

> I hope you will take the feedback on board, I do not want to hurt your enthusiasm, that is why it took a lot of complaints before I messaged you about it, I was hoping you would figure it out naturally.

Yeah, thanks a lot for your feedback Eddie... I'm just new to these communities so I needed some time to figure things out.

> I wish you all the best in your open source adventures.

Thanks a lot! You too have a great time coding and with open source adventures and will continue watching your videos.

**Comment by KendallDoesCoding** [comment]
Further, I don't like causing any issues, thus left communities on GitHub, with mutual people from EddieHubCommunity and also the main reason I want my profile deleted from Linkfree.

**Comment by eddiejaoude** [comment]
Ok, I will accept the PR if that is what you prefer, you can always add your profile again in the future if you change your mind

**Review by eddiejaoude — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
> Ok, I will accept the PR if that is what you prefer, you can always add your profile again in the future if you change your mind

Thanks a lot Eddie for being supportive with my decision... Will be sure to do that in a bit, if I change my mind, just going to take a short break, from EddieHubCommunity and other communities for a bit.

**Comment by eddiejaoude** [comment]
Sure, we will be here, if/when you are ready. Taking a break could be good, don't burn out 👍

**Comment by KendallDoesCoding** [comment]
Thanks again.... I'll still create issues from time to time in the
organization.

**Comment by KendallDoesCoding** [comment]
> Sorry for your experience Kendall. But I am glad you are taking the criticism positively. Shows you are a better character than most people who violate the rules. Will look forward to you joining. Enjoy the break and your time. The world needs more of it right now.

Thanks Aditya, I understand I broke the rules, and won't do it again. I've joined back this organization :).

**Pull request merged**
