### PR TITLE
data:ZendeAditya

### PR DESCRIPTION
**Pull request by ZendeAditya**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4698"></a>

### CODE REVIEW

**Review by Krishnapro — APPROVED** [review]
LGTM 🚀

**Review by priyankarpal — APPROVED** [review]
LGTM 🎉

**Comment by ZendeAditya** [comment]
Where is my linkfree link @priyankarpal ?

**Review by Hrishi5111998 — APPROVED** [review]

**Comment by priyankarpal** [comment]
> Where is my linkfree link @priyankarpal ?

Wait, Maintainers will merge it soon & after merging it will automatically live.

**Review by SaraJaoude — APPROVED** [review]
looks good

**Comment by ZendeAditya** [comment]
Is there any update about my link-free link?

**Comment by SaraJaoude** [comment]
> Is there any update about my link-free link?

@ZendeAditya Have you checked the LinkFree website?  Your Profile is there: https://linkfree.eddiehub.io/ZendeAditya

**Comment by ZendeAditya** [comment]
> > Is there any update about my link-free link?
> 
> @ZendeAditya Have you checked the LinkFree website? Your Profile is there: https://linkfree.eddiehub.io/ZendeAditya

but why my link not on main domain?

**Comment by priyankarpal** [comment]
> > > Is there any update about my link-free link?
> > 
> > 
> > @ZendeAditya Have you checked the LinkFree website? Your Profile is here: https://linkfree.eddiehub.io/ZendeAditya
> 
> but why my link not on main domain?

I just checked your profile link it's live now https://linkfree.io/ZendeAditya

**Comment by ZendeAditya** [comment]
> > > > Is there any update about my link-free link?
> > > 
> > > 
> > > @ZendeAditya Have you checked the LinkFree website? Your Profile is here: https://linkfree.eddiehub.io/ZendeAditya
> > 
> > 
> > but why my link not on main domain?
> 
> I just checked your profile link it's live now https://linkfree.io/ZendeAditya

Yes Thank You

**Pull request merged**
