### PR TITLE
data:NikhilRaikwar

### PR DESCRIPTION
**Pull request by NikhilRaikwar**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4690"></a>

### CODE REVIEW

**Review by iamthecloverly — APPROVED** [review]

**Review by Saadat-B — APPROVED** [review]
Looks good 👍🏻
Thank you for your contribution 🎉

**Review by priyankarpal — APPROVED** [review]
LGTM 🎉

**Comment by NikhilRaikwar** [comment]
Hey When was my profile is added to LinkFree can you pls give me details.

**Comment by priyankarpal** [comment]
> Hey When was my profile is added to LinkFree can you pls give me details.

Wait maintainers will merge it soon.

**Review by Hrishi5111998 — APPROVED** [review]

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
