### PR TITLE
feat: Migration to NextJs

### LINKED ISSUE #1470: [FEATURE] Migrate to Next.js
### Description

By moving to next.js we could add and use several features by benefiting from the server component: 

1. Use SSR to prerender our pages on the server for performance optimization
1. Maybe use [ISR](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration) to dynamically re-render the index page to highlight a different profile every day on the index page
1. Use a database connection to store how often a page got clicked
1. Don't use PrimeReact, but use Tailwind for creating our custom components

wdyt @eddiejaoude 

Things like adding Cypress and/or other addition could come in future PRs. I think for us it's important to migrate with an MVP first.

We could use a `staging` branch, similar on how we did it for the API rewrite, to have things a bit more atomic, and not just a single big-bang

## TO DO

- [ ] by default hide stats and enable with json config

### PR DESCRIPTION
**Pull request by JealousGx**
## Fixes Issue

fixes #1470 

## Changes proposed
- Modified home page.
- Fixed bugs that prevented the deployment.
- Minor UI Changes in the Search tab.

## Check List (Check all the applicable boxes)

[x] My code follows the code style of this project.
[] My change requires changes to the documentation.
[] I have updated the documentation accordingly.
[x] All new and existing tests passed.
[x] This PR does not contain plagiarized content.
[x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1556"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you @JealousGx 👍  this is a big PR, is it possible to break it into smaller PRs?

**Comment by JealousGx** [comment]
> Thank you @JealousGx 👍 this is a big PR, is it possible to break it into smaller PRs?

@eddiejaoude Done. I have broken down the skeleton PR and homepage with some bug fixes into two PRs. Let me know if anything else needs to be fixed in these PRs.

**Comment by eddiejaoude** [comment]
Great! Thank you! Let me take a look 👍

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍

**Pull request merged**
