### PR TITLE
refactor: removed white spaces

### PR DESCRIPTION
**Pull request by Nithin108**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1172"></a>

### CODE REVIEW

**Comment by Nithin108** [comment]
just removed white spaces as this is my first pull request i did a small contribution

**Comment by Nithin108** [comment]
when will my pull request will be accepted?

**Comment by arpanaditya** [comment]
Congratulations on your contribution :) 🎉  You did a great job. Wait for a few hours and @eddiejaoude will accept this PR.

**Review by vikasganiga05 — APPROVED** [review]
LGTM :+1: Thanks for your contribution!

**Review by krshdev — APPROVED** [review]

**Review by emmalearnscode — APPROVED** [review]

**Pull request merged**
