### PR TITLE
fix: map toggle off tag filter (#5420)

### LINKED ISSUE #5420: Map toggle off tag does not work
### Description

After filtering by a tag, visually it toggles off, but functionality it does not seem to work

1. First coming to the page with no filters...

Screenshot 2023-03-14 at 08 29 13

2. Then after applying a tag filter...

Screenshot 2023-03-14 at 08 29 21

3. After removing the tag filter it should return to the first screenshot...

Screenshot 2023-03-14 at 08 29 30

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by weilincheng**
## Fixes Issue

Closes #5420 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

This commit updates the user filtering logic to use the tags in the `updatedSelectedTags` as filter conditions. 

If there are any concerns or suggestions regarding this approach, please let me know. Thank you for your time and consideration.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5447"></a>

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
The map results do not seem to change for me when toggling on/off tags

**Comment by Ananya2001-an** [comment]
Hey @weilincheng you can implement something like this for the filterData function. I tested it and it's working. The code addition `return updatedSelectedTags;` is correct. Keep that and just implement this for filterData(). 

```
const filterData = async (value) => {
      const selectedTagsArray = [...(await updateSelectedTagsFilter(value))];
      
      if(selectedTagsArray.length === 0){
        setFilteredUsers([]);
      }
   
      else{
        results = users.filter((user) => {
         
          if (selectedTagsArray.every(tag => user.name.toLowerCase().includes(tag.toLowerCase()))) {
            return true;
          }
  
          let userTags = user.tags?.map((tag) => tag.toLowerCase());
  
          if (selectedTagsArray.every((tag) => userTags?.includes(tag.toLowerCase()))) {
            return true;
          }
  
          return false;
        });
  
        setFilteredUsers(results);
      }
  };
```

https://www.awesomescreenshot.com/video/15630826?key=96eaea61948712ffae4c5a7746bf6588

**Comment by weilincheng** [comment]
> Hey @weilincheng you can implement something like this for the filterData function. I tested it and it's working. The code addition `return updatedSelectedTags;` is correct. Keep that and just implement this for filterData().

Hi @Ananya2001-an, thank you for taking the time to provide your suggestion! Your insights are much appreciated. I will review and analyze why my initial implementation didn't work and consider your suggestions as part of my revisions. Thanks again for your valuable input!

**Comment by Ananya2001-an** [comment]
> > Hey @weilincheng you can implement something like this for the filterData function. I tested it and it's working. The code addition `return updatedSelectedTags;` is correct. Keep that and just implement this for filterData().
> 
> Hi @Ananya2001-an, thank you for taking the time to provide your suggestion! Your insights are much appreciated. I will review and analyze why my initial implementation didn't work and consider your suggestions as part of my revisions. Thanks again for your valuable input!

Sure @weilincheng I am more than happy to help 🙂

**Comment by weilincheng** [comment]
> > Hi @Ananya2001-an, thank you for taking the time to provide your suggestion! Your insights are much appreciated. I will review and analyze why my initial implementation didn't work and consider your suggestions as part of my revisions. Thanks again for your valuable input!
> 
> Sure @weilincheng I am more than happy to help 🙂

Hi @Ananya2001-an,

I understand why my previous commit wasn't successful. In short, I used fake user data for testing purposes, which only included tags in lowercase. This is why my previous change, which did not convert selected tags to lowercase, seemed to work. I have since converted the selected tags to lowercase, so it will work with real user data!

I used fake user data because I was unsure of how user location information is populated. To address this, I have created issue #5473.

Thank you!!

**Comment by Ananya2001-an** [comment]
Amazing @weilincheng 👏 yeah what you are saying is right. Thanks for acknowledging and I appreciate the detailed explanation 😊

**Review by eddiejaoude — APPROVED** [review]
Looks good! Great collaboration 👍

**Pull request merged**
