### PR TITLE
data: KunalVerma

### PR DESCRIPTION
**Pull request by verma-kunal**
## Changes proposed

Adding my profile to LinkFree

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7525"></a>

### CODE REVIEW

**Review by SaptarshiSarkar12 — APPROVED** [review]
**Looks good to merge 👍.**

**Review by SaraJaoude — APPROVED** [review]
looks good

**Comment by verma-kunal** [comment]
Thank you @SaraJaoude & @SaptarshiSarkar12 for reviewing :)

**Comment by SaptarshiSarkar12** [comment]
> Thank you @SaraJaoude & @SaptarshiSarkar12 for reviewing :)

Welcome @verma-kunal 😄

**Pull request merged**
