### PR TITLE
Closes #6101

### LINKED ISSUE #6101: [OTHER]
### What would you like to share?

Search by Tags picture is too old. Can I change it?

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by geeky-sambhav**
## Changes proposed

--> Updated the "Search by tags" image in the homepage with the image that matches the current UI
--> Updated husky to the latest version

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Before:
before

After:
after

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6309"></a>

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
Hey @geeky-sambhav  could you add a descriptive title to the PR

**Comment by sansarmaske** [comment]
According to the discussion on issue #6101, the newer image should not include the navbar.

**Review by sansarmaske — CHANGES_REQUESTED** [review]
There are multiple file changes. It would be better if this PR addresses only the issue at hand.

**Comment by eddiejaoude** [comment]
Thank you for your contribution 👍 , there are too many changes in 1 PR, please create new PRs that are specific to the issue that is trying to be resolved, otherwise you are blocking your own changes from being merged

**Comment by geeky-sambhav** [comment]
> Thank you for your contribution 👍 , there are too many changes in 1 PR, please create new PRs that are specific to the issue that is trying to be resolved, otherwise you are blocking your own changes from being merged

Okay Eddie will submit PR again

**Pull request closed without merging**
