### PR TITLE
docs: add section for conventional commit style #2583

### LINKED ISSUE #2583: [DOCS] Contributing section in docs for conventional commits style
### Description

I think in the docs it would be useful to have a section on our commits convention and a link to conventional commits website

https://linkfree.eddiehub.io/docs

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sansarmaske**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
linkfree

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4595"></a>

### CODE REVIEW

**Comment by sansarmaske** [comment]
@SaraJaoude  Some of the contents are directly from  [Conventional Commits](https://www.conventionalcommits.org). Is this fine or should I re-write my own?

**Comment by SaraJaoude** [comment]
We don't want to duplicate their docs.  Best to have a brief example of how they are used in EddieHub and a link to the Conventional Commits website.

**Comment by sansarmaske** [comment]
Sure, I will make the changes.

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍

**Pull request merged**
