### PR TITLE
data: sadath-12

### PR DESCRIPTION
**Pull request by sadath-12**
json added to start contributing

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5007"></a>

### CODE REVIEW

**Comment by sadath-12** [comment]
json added

**Review by sansarmaske — COMMENTED** [review]
LGTM

**Review by shubhsharma19 — APPROVED** [review]
LGTM, Thanks for your contribution 🎉

**Review by mahfuztbt — APPROVED** [review]

**Comment by sadath-12** [comment]
I optimised the search page using useCallback with debounce instead of useEffect

**Comment by sadath-12** [comment]
I dont see my name as a part of people in the community ??

**Comment by shubhsharma19** [comment]
> I dont see my name as a part of people in the community ??

Have you applied to join?

**Comment by sadath-12** [comment]
> > I dont see my name as a part of people in the community ??
> 
> Have you applied to join?

I added a first pr with json as my details joined discord and followed in the github thats it what else?

**Comment by sadath-12** [comment]
> > > I dont see my name as a part of people in the community ??
> > 
> > 
> > Have you applied to join?
> 
> I added a first pr with json as my details joined discord and followed in the github thats it what else?

Yeah now i see i raised a issue

**Comment by shubhsharma19** [comment]
> > > > I dont see my name as a part of people in the community ??
> > > 
> > > 
> > > Have you applied to join?
> > 
> > 
> > I added a first pr with json as my details joined discord and followed in the github thats it what else?
> 
> Yeah now i see i raised a issue

Great 👍

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for your contributions, but there are too many changes in a single pull request.

Your profile changes should be separate from any other changes.

Please break this down into multiple pull requests and any code changes (not profile) must have an issue first for triage by the maintainers before making a pull request. Thanks

**Comment by sadath-12** [comment]
moving sadath-12.json from root to data dir

**Comment by eddiejaoude** [comment]
I am closing this Pull Request as there are too many changes. Please create new Pull Requests

**Pull request closed without merging**
