### PR TITLE
updated profile link to preview correctly on share

### PR DESCRIPTION
**Pull request by sandramsc**
Closes issue #7604

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7609"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Hi Sandra, did you mean to close this PR?

**Comment by sandramsc** [comment]
Hi Eddie,

yes, I pulled too soon ...testing the cleanBio part of the issue.

Apologies for the notification prompt.

**Comment by eddiejaoude** [comment]
No problem

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍 

Screenshot 2023-06-16 at 08 54 47

Btw check your Prettier VScode plugin, I think it isn't formatting the file content correctly - bit I can fix as this is urgent to get merged

**Pull request merged**
