### PR TITLE
footer icons fixed correctly

### LINKED ISSUE #7422: YouTube logo present in the footer was not correct
### Description

The YouTube present in the footer was not full 👇

Screenshot 2023-06-06 212759

 I think the original icon will looks like below 👇

Screenshot 2023-06-06 213240

Reference: https://react-icons.github.io/react-icons/search?q=youtube

Can I work on this issue?

### PR DESCRIPTION
**Pull request by shaikahmadnawaz**
## Fixes Issue 

fixes #7422 

## Changes proposed

Based on the suggestions of @dan-mba I changed the icons(viewBox) which was present in the footer.

Screenshot 2023-06-07 112607

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7434"></a>

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
@shaikahmadnawaz We appreciate the enthusiasm about contributing to the PR. But please keep the guidelines of the projects in mind.

Please do not create a PR before the issue is assigned to you. I have assigned the issue to you this time but please keep this in mind next time. Thank you.

You can read the guidelines here https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz We appreciate the enthusiasm about contributing to the PR. But please keep the guidelines of the projects in mind.
> 
> Please do not create a PR before the issue is assigned to you. I have assigned the issue to you this time but please keep this in mind next time. Thank you.
> 
> You can read the guidelines here https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

Okay, I will remember and follow them 👍

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by shaikahmadnawaz** [comment]
> Looks good 👍

Thank you.

**Pull request merged**
