### PR TITLE
udated changes

### PR DESCRIPTION
**Pull request by kumar-kalyan**
## Fixes Issue
Upadated username
added github and gitlab

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1635"></a>

### CODE REVIEW

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍 . The changes can be merged.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant, Reusable, Maintainable

**Review by vedanshi555 — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by EmmaDawsonDev — APPROVED** [review]
Looks good 👍🏼

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thanks! 🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

**Pull request merged**
