### PR TITLE
Create C-M Sharan

### PR DESCRIPTION
**Pull request by CM-Sharan**
Hi,

Please add my profile.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1254"></a>

### CODE REVIEW

**Review by schmelto — APPROVED** [review]
## Looking good to me

Your suggested changes looking good to me.
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Review by kumarsonsoff3 — APPROVED** [review]

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please add the format `.json` to your file. Let us know if you need any help. :)

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey! there is duplicate PR for the same chnages https://github.com/EddieHubCommunity/LinkFree/pull/1259

Please close this one!

**Comment by Panquesito7** [comment]
Superseded by #1259.

**Pull request closed without merging**
