### PR TITLE
feat: improve overall docker development

### LINKED ISSUE #2432: [FEATURE] Improve Docker Compose file
### Description

Make the **Docker Compose** more standard and complete according to the project by including the LinkFree image (service) building on the fly. Currently, we are only using the  Mongo image just to get for DB connection which is not good. Changes will connect the App and DB internally.

Also after this, a contributor doesn't need to step into the environment locally, everything will run inside containers. After this, the whole project setup will need just two-step

- Clone the repo
- Then `docker compose up`

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
## Fixes Issue

Closes #2432

## Changes proposed

- Next App is now included in Compose (build on the fly)
- Added `.env.docker`

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2515"></a>

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
This works well for me 👍 

We will also try on Sara's laptop

**Review by schmelto — APPROVED** [review]

**Comment by eddiejaoude** [comment]
I merged so that people can start using it sooner - we can improve the docs in another PR

**Comment by Pradumnasaraf** [comment]
> I merged so that people can start using it sooner - we can improve the docs in another PR

Sounds good. Thank you!

**Comment by SaraJaoude** [comment]
Tried it on my laptop and it worked great, thank you!

**Comment by Pradumnasaraf** [comment]
Glad to hear that. Thank you!

**Pull request merged**
