### PR TITLE
Add user not found message on search

### LINKED ISSUE #520: [FEATURE] Add message when search returns no results
### Description

Currently when the search doesn't return any results the page is blank and the footer jumps up under the search box. Instead, it would be clearer for users if there was a "No results found" message

### Screenshots

Screenshot 2021-10-17 150154

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mtwn105**
Fixes #520 

image

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/524"></a>

### CODE REVIEW

**Comment by mtwn105** [comment]
Hi @emmalearnscode @krishdevdb I have refactored the code, it works fine as well.

**Comment by mtwn105** [comment]
Hello @All Any more changes required?

**Comment by Panquesito7** [comment]
> Hello @ALL Any more changes required?

https://github.com/EddieHubCommunity/LinkFree/pull/524#discussion_r731526967

**Comment by mtwn105** [comment]
Done @Panquesito7

**Pull request merged**
