### PR TITLE
fix: icons in all profiles

### LINKED ISSUE #693: Missing Icon
### Description

there used to be an arrow icon here 
image

but I think it's not there because the icon is too light 
because I can see a <i> tag for it 

image

we can fix it by change the color of the icon or change the icon itself 

### Screenshots

image

a icon is needed there 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Panquesito7**
## Fixes Issue

Closes #693.

## Changes proposed

- Fix icons in all profiles.

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/694"></a>

### CODE REVIEW

**Review by krishguptadev — APPROVED** [review]

**Review by qwe123coder — APPROVED** [review]
LGTM :rocket:

**Comment by Manidhiraj** [comment]
#{
  "name": "Dhiraj Mani Tiwari,
  "bio": "I am a software Developer from India. I am always open to collaborating on projects",
  "links": [
    {
      "name": "Follow me on github",
      "url": "https://github.com/Manidhiraj",
      "icon": "github"
    },
    {
      "name": "Follow me on Linkedin",
      "url": "www.linkedin.com/in/dhiraj19101",
      "icon": "Linkedin"
    }
  ]
}

**Comment by krishguptadev** [comment]
> #{ "name": "Dhiraj Mani Tiwari, "bio": "I am a software Developer from India. I am always open to collaborating on projects", "links": [ { "name": "Follow me on github", "url": "https://github.com/Manidhiraj", "icon": "github" }, { "name": "Follow me on Linkedin", "url": "www.linkedin.com/in/dhiraj19101", "icon": "Linkedin" } ] }

hmm.

**Review by thepranaygupta — APPROVED** [review]

**Comment by thepranaygupta** [comment]
> #{ "name": "Dhiraj Mani Tiwari, "bio": "I am a software Developer from India. I am always open to collaborating on projects", "links": [ { "name": "Follow me on github", "url": "https://github.com/Manidhiraj", "icon": "github" }, { "name": "Follow me on Linkedin", "url": "www.linkedin.com/in/dhiraj19101", "icon": "Linkedin" } ] }

@Manidhiraj please read [this](https://github.com/EddieHubCommunity/LinkFree#-to-add-your-profile)

**Review by ssensalo — APPROVED** [review]

**Review by Pradumnasaraf — APPROVED** [review]
LGTM

**Review by mohan-murali — APPROVED** [review]

**Comment by mohan-murali** [comment]
Wow that seems like a lot of work man. Well Done!

**Review by schmelto — APPROVED** [review]

**Pull request merged**
