### PR TITLE
[FEATURE] - Add ellipsis to profile cards

### LINKED ISSUE #3636: [FEATURE] Add ellipsis in cards
### Description

Right now, when there's a long text, we are cutting off some of it, which is fine, but I feel it would look better if we do something like Google, which adds the three dots at the end of the text (aka ellipsis)

Screenshot 1: Linkfree
Screenshot 2: Google search results

### Screenshots

Screenshot 2023-01-19 at 12 25 24 AM

Screenshot 2023-01-19 at 12 27 50 AM

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by FrozenHearth**
## Fixes Issue

Closes #3636  

## Changes proposed

Right now, when there's a long text, there's no ellipsis. An ellipsis would indicate that there's more text, otherwise the text looks incomplete.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

With **line-clamp-4**

Screenshot 2023-01-22 at 4 44 51 PM

With **line-clamp-5**

Screenshot 2023-01-22 at 4 44 58 PM

## Note to reviewers

I have used this plugin by tailwind (https://github.com/tailwindlabs/tailwindcss-line-clamp) to achieve this. We could do it without a plugin too, but the plugin provides us flexibility to specify how many number of lines we want to "clamp" (1-5)
Please let me know if any changes are required. Thanks!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3798"></a>

### CODE REVIEW

**Review by accodes21 — COMMENTED** [review]
Like the concept of adding ellipsis to bio, but it would approval of other maintainers.

**Review by amandamartin-dev — CHANGES_REQUESTED** [review]
Can you resolve the conflicts and then folks can do a final review. Thank you for contributing!

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍  great collaboration everyone 💪 

We might be able to use this feature in other places in the app also

**Review by amandamartin-dev — APPROVED** [review]

**Comment by amandamartin-dev** [comment]
I see the previous conflicts have resolved so I approved those but there is a failure in the build check

**Comment by FrozenHearth** [comment]
@eddiejaoude Can you please help with the build failure?

**Comment by eddiejaoude** [comment]
Sure I can take a look in a bit 👍

**Pull request merged**
