### PR TITLE
fix: remove clicks states (#6609)

### LINKED ISSUE #6609: [BUG] setState() is not get correct value
**update: code is no longer required and can be removed**

### Description

I found an issue in [components/user/UserLink.js](https://github.com/EddieHubCommunity/LinkFree/blob/main/components/user/UserLink.js) line number 29. Here we update state based on previous state, but current implementation of `setState()` is not correct. 
**Because**,
Whenever we update state and that depend on the previous state, for example, as we do it here [components/user/UserLink.js](https://github.com/EddieHubCommunity/LinkFree/blob/main/components/user/UserLink.js) line number 29. We should not do it like this but we should use an alternative form of this state updating function.

Screenshot (14)

### Why we shouldn't do it like this?
In many cases it will work fine, but according to React docs, React schedules state updates, it doesn't perform them instantly. And therefore, theoretically, if we schedule a lot of state updates at a same time, we could be depending on outdated or incorrect state snapshot if we use this approach.

### Screenshots

_No response_

### Additional information

Would love fix this if this a valid issue.
Thanks

### PR DESCRIPTION
**Pull request by badrivlog**
Closes #6609

## Changes proposed

clicks states is no longer required, as the clicks are not longer displayed on the profile page

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6625"></a>

### CODE REVIEW

**Review by Ananya2001-an — APPROVED** [review]
LGTM 👍🏼 Thanks for contributing 💯

**Comment by badrivlog** [comment]
> LGTM 👍🏼 Thanks for contributing 💯 

My first contribution 👍 Thanks 💯💯💯

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍 

Awesome to remove dead code 💪

**Comment by badrivlog** [comment]
Thanks 💪

**Pull request merged**
