### PR TITLE
data: paudelpr1

### PR DESCRIPTION
**Pull request by paudelpr1**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8073"></a>

### CODE REVIEW

**Review by Alkaison — APPROVED** [review]
Looks good.

If you would like to add more sections or remove anything as suggested in the future, you can do so either via a new PR with JSON or through our new Forms. Here are the Editing Guides for each:

Editing with JSON: https://linkfree.io/docs/how-to-guides/editing-json

Editing with Forms: https://linkfree.io/docs/how-to-guides/editing-forms

**Review by SaraJaoude — CHANGES_REQUESTED** [review]
Please make sure your file name matches your GitHub username exactly (it is case sensitive). Instead of `data/Prasansha_P.json`   it should be `data/paudelpr1.json`

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

**Comment by SaraJaoude** [comment]
> Looks good.

@Alkaison please do not approve a Pull Request without making a proper check as this can be confusing to the author - in this case not all the GitHub Actions had passed and the data file name is incorrect.

**Comment by Alkaison** [comment]
Sorry @SaraJaoude, I forgot to check that I will make sure it doesn't happen again.

**Review by SaraJaoude — APPROVED** [review]

**Pull request merged**
