### PR TITLE
Adjusted padding between section and pages

### PR DESCRIPTION
**Pull request by debadityasingh8972**
## Changes proposed
Adjusted Gaps between Horizontal line and hover line of pages

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8524"></a>

### CODE REVIEW

**Review by adityaraute — CHANGES_REQUESTED** [review]
Might be a good idea to revert changes for the package-lock.json file as it should remain constant for the repo. I can see the rest of your code isn't using any additional modules so this shouldn't cause an impact.

**Comment by adityaraute** [comment]
Also, I don't think this is ideal.

If you look at the first row - there is a lot of padding at the top and not enough at the bottom of the card
image


But on the second row - there is the same amount of padding at the top but a lot of padding at the bottom (because of the card on the right I assume)
image

Also a lot of gap between the two rows (that could be utilized by the top row)

It's not a showstopper, But I feel it can be modified

**Comment by debadityasingh8972** [comment]
Okay. I'm working on it.

**Review by amandamartin-dev — APPROVED** [review]
Checked in gitpod, looks good to me. Thank you for your contribution!

**Pull request merged**
