### PR TITLE
Add badges to README

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
## Fixes Issue
- No badges in README

## Changes proposed
- Add closed issues badge
- Add closed PR's badge

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1138"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
It'd be great if you could:

- Use Markdown instead of HTML.
- Add the badges below the first header.

Let me know what do you think and if you need any help. Thanks. 😄

**Comment by KendallDoesCoding** [comment]
> It'd be great if you could:
> 
> * Use Markdown instead of HTML.
> * Add the badges below the first header.
> 
> Let me know what do you think and if you need any help. Thanks. 😄

> Use Markdown instead of HTML.
Can you please suggest changes on this @Panquesito7 I'll be sure to merge this in this PR

> Add the badges below the first header.
Will do!

**Comment by KendallDoesCoding** [comment]
@Panquesito7 Shifted badges below the first header as requested.

**Comment by KendallDoesCoding** [comment]
@Panquesito7 Can you please assign me and you to this PR?

**Comment by schmelto** [comment]
> @Panquesito7 Can you please assign me and you to this PR?

Hey @KendallDoesCoding just curious to know why assigning to a Pull request? I'm just interested in the use case behind it 🙈

**Comment by KendallDoesCoding** [comment]
> 

Because, David needs to make some changes and then I have to come back to it and review but ig the email notific is fine?

**Comment by schmelto** [comment]
> Because, David needs to make some changes and then I have to come back to it and review but ig the email notific is fine?

Dont know if david is making any changes here? maybe you can try to face those issues by your own?

**Comment by KendallDoesCoding** [comment]
> > Because, David needs to make some changes and then I have to come back to it and review but ig the email notific is fine?
> 
> Dont know if david is making any changes here? maybe you can try to face those issues by your own?

Yeah, I'll try... David didn't make any changes yet.

**Comment by KendallDoesCoding** [comment]
@Panquesito7 Hi, I don't think there's a way to center align the badges in the markdown script, it's required to use HTML, I changed it from div tag to p tag (doesn't really make a difference though)... Requesting a re-review from you, if you know how to get this done in markdown though, feel free to suggest changes, but I can't find any way to do this from my research.

**Pull request closed without merging**
