### PR TITLE
data: vishnu-mouli-102408

### PR DESCRIPTION
**Pull request by vishnu-mouli-102408**
Updated Bio, Added Tags Section, Socials Section.

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4443"></a>

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
LGTM 👍🏻

**Review by accodes21 — COMMENTED** [review]
Everything's great, but try to limit number of tags

**Review by Panquesito7 — DISMISSED** [review]
Thanks! 🎉

**Review by priyankarpal — CHANGES_REQUESTED** [review]
Hey, there is some conflict error. you need to fix it. Choose your final branch to get merged. If you've any doubts you can ask.

**Comment by vishnu-mouli-102408** [comment]
> Hey, there is some conflict error. you need to fix it. Choose your final branch to get merged. If you've any doubts you can ask.

can you please tell me how to do that.

**Comment by priyankarpal** [comment]
@vishnu-mouli-102408 check this docs https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Review by priyankarpal — CHANGES_REQUESTED** [review]
Add bracket in last line
Screenshot from 2023-02-04 12-44-51

**Pull request closed without merging**
