### PR TITLE
data:souravsk

### PR DESCRIPTION
**Pull request by souravsk**
Updated the data file of my profile

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2812"></a>

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

Please revert changes in other file expect `data/souravsk.json`,

**Comment by souravsk** [comment]
So should I close this PR and then create a new one with only the souravsk.json file is that what you are saying?

**Comment by Pradumnasaraf** [comment]
> So should I close this PR and then create a new one with only the souravsk.json file is that what you are saying?

Yes, you can create a new PR or revert those changes from the PR. Do which works for you the best.

**Comment by eddiejaoude** [comment]
I think the fork/branch is not up to date. If you updated your fork and branch your PR will get updated and these changes extra changes from the generated files will go away

**Comment by souravsk** [comment]
> I think the fork/branch is not up to date. If you updated your fork and branch your PR will get updated and these changes extra changes from the generated files will go away

yes did that but the file are still there.

**Comment by eddiejaoude** [comment]
I think your branch/fork is not up to date, you have extra file changes from generated files 

Here are the docs on how to update your profile by keeping your fork updated and creating a new branch https://linkfree.eddiehub.io/docs/how-to-guides/editing

**Pull request closed without merging**
