### PR TITLE
## Created my Linkfree Profile

### PR DESCRIPTION
**Pull request by izzarzn**
I have created my Linkfree Profile.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1737"></a>

### CODE REVIEW

**Review by kumarsonsoff3 — DISMISSED** [review]
Looks Good! 👍 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Please create a separate PR for improvements in `README.md`. 
This PR should only contain your Profile data, revert the changes in Readme.md!! 

Let us know if you need any help with this!! :)

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

**Comment by izzarzn** [comment]
I have reverted the changes in **Readme File**

**Review by vedanshi555 — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by kumarsonsoff3 — APPROVED** [review]
Looks Good! 👍 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
