### PR TITLE
Create sagar1621.json

### PR DESCRIPTION
**Pull request by sagar1621**
Proposing a request to create a LinkFree profile using the JSON file submitted

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5971"></a>

### CODE REVIEW

**Review by accodes21 — APPROVED** [review]
Pls check the indentation rest all is great

**Comment by sagar1621** [comment]
Ok sure

**Review by SurajPratap10 — APPROVED** [review]
LGTM 👌

**Review by SaraJaoude — APPROVED** [review]
looks good

**Comment by sagar1621** [comment]
Thank you everyone for taking the time to review and give feedback😄

**Pull request merged**
