### PR TITLE
data:Deependra

### PR DESCRIPTION
**Pull request by Deepu178**

### CODE REVIEW

**Review by Tejender1521 — APPROVED** [review]
Everything Looks good and ready to be merged

**Comment by ChinmayMhatre** [comment]
Something is failing the build

**Review by ChinmayMhatre — CHANGES_REQUESTED** [review]
Please rename the json file to Deepu178.json

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"></p>

**Comment by ChinmayMhatre** [comment]
Hey @Pradumnasaraf , I think the json file name was not the same as the GitHub user name

**Comment by Pradumnasaraf** [comment]
Yes, I did a mistake. Sorry about that. I have fixed the issue. Next time @Deepu178 please update your profile at https://github.com/EddieHubCommunity/LinkFree/blob/main/data/deepu178.json. 

You can just fetch/ sync changes it will pick that up

**Comment by Deepu178** [comment]
Thanks,. @Pradumnasaraf 😃

**Pull request merged**
