### PR TITLE
data: SubhadeepZilong

### PR DESCRIPTION
**Pull request by SubhadeepZilong**
## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5000"></a>

### CODE REVIEW

**Review by sidharthviz — APPROVED** [review]
LGTM 🎉

**Comment by mahfuztbt** [comment]
LGTM

**Review by shubhsharma19 — APPROVED** [review]
LGTM 🎉

**Review by samyabrata-maji — APPROVED** [review]

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
