### PR TITLE
Improve Testimonials action to handle special characters

### LINKED ISSUE #2666: Testimonials with multiple lines breaks the json
### Description

We need to fix multi line testimonials that are submitted from the GitHub Issue with type `testimonial`

Currently these will not get created, so we have some basic protection from incorrect json files being committed

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dan-mba**
## Fixes Issue

Closes #2666 

## Changes proposed

Use `JSON.stringify()` to create JSON with proper escaped characters.
Fix action warnings

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by amandamartin-dev — APPROVED** [review]
@dan-mba I'm not sure how to test this since testimonials are added via issue submission/approval/merge process, but I don't see anything amiss in the code from looking. Let me know what you would suggest ot test if you think we should first

**Comment by dan-mba** [comment]
> @dan-mba I'm not sure how to test this since testimonials are added via issue submission/approval/merge process, but I don't see anything amiss in the code from looking. Let me know what you would suggest ot test if you think we should first

@amandamartin-dev I have been testing on a [test repo](https://github.com/dan-mba/lf-testimonial-testing) I created for this.
I can't get the action to create PRs on my repo for unknown reasons, but it will create a branch & commit the testimonial.
Open an issue against my repo & I will approve it to run.

**Comment by amandamartin-dev** [comment]
> Open an issue against my repo & I will approve it to run.

Done. https://github.com/EddieHubCommunity/LinkFree/issues/4137

**Review by Pradumnasaraf — APPROVED** [review]
Looks good!

**Comment by dan-mba** [comment]
> > Open an issue against my repo & I will approve it to run.
> 
> 
> 
> Done. https://github.com/EddieHubCommunity/LinkFree/issues/4137

You opened this against LinkFree where the action failed https://github.com/EddieHubCommunity/LinkFree/actions/runs/4027709864/jobs/6923754916

Open the same against my repo 
https://github.com/dan-mba/lf-testimonial-testing

**Comment by amandamartin-dev** [comment]
> > > Open an issue against my repo & I will approve it to run.
> > 
> > 
> > Done. #4137
> 
> You opened this against LinkFree where the action failed https://github.com/EddieHubCommunity/LinkFree/actions/runs/4027709864/jobs/6923754916
> 
> Open the same against my repo https://github.com/dan-mba/lf-testimonial-testing

oh my...eod on Friday.  Lemme follow directions over here. brb

**Comment by dan-mba** [comment]
> 
> 
> oh my...eod on Friday.  Lemme follow directions over here. brb
> 
> 
> 
> edit: DONE (in the right place this time)

Here is the resulting testimonial json

https://github.com/dan-mba/lf-testimonial-testing/blob/testimonial-from-d3f4cd96dc6d3bbb872047272825cd743a34a63c/data/dan-mba/testimonials/amandamartin-dev.json

**Comment by amandamartin-dev** [comment]
> Here is the resulting testimonial json

Seems to work, but interestingly since it puts everythiing into one line no one should be using any features of the WYSWYG but that could be clarified in the docs if anyone is trying things like that.
 
So LGTM!

**Comment by eddiejaoude** [comment]
Looks great 👍  Shall we merge and test it out, I can write some testimonials for people

**Comment by dan-mba** [comment]
> Looks great 👍 Shall we merge and test it out, I can write some testimonials for people

Sounds good. We may need to look for markdown remark plugins to support more things.
I am working on a storybook story to test testimonials.
I think we might need this plugin to better handle newlines
https://github.com/remarkjs/remark-breaks

**Comment by eddiejaoude** [comment]
> I think we might need this plugin to better handle newlines
https://github.com/remarkjs/remark-breaks

oh that looks interesting 👍

**Comment by eddiejaoude** [comment]
I created a testimonial https://github.com/EddieHubCommunity/LinkFree/issues/4141

**Pull request merged**
