### PR TITLE
fix: upgarde LinkFree-CLI version to v2.0.0

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
- Update the **LinkFree-CLI** to `v2.0.0` after new relaese.

Now we can 
- Creating a LinkFree profile.
- Updating a LinkFree profile.
- Giving a testimonial to a LinkFree profile.
- Adding events (conferences, meetups, etc).

And change the script to `cli: npx linkfree-cli`

```
npm run cli
```

Repo - https://github.com/Pradumnasaraf/LinkFree-CLI
NPM - https://www.npmjs.com/package/linkfree-cli

### CODE REVIEW

**Review by Ananya2001-an — APPROVED** [review]
Looks good!

**Comment by Pradumnasaraf** [comment]
> Looks good!

Thank you @Ananya2001-an for your collaboration and for making the v2 possible.

**Comment by Ananya2001-an** [comment]
> > Looks good!
> 
> Thank you @Ananya2001-an for your collaboration and for making the v2 possible.

Couldn't have done without your support 😊

**Review by krshkun — APPROVED** [review]
Wow! Awesome!

**Comment by Pradumnasaraf** [comment]
> Wow! Awesome!

Thank you, Krish

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍 

Does any documentation need updating?

**Comment by Pradumnasaraf** [comment]
> Looks good 👍
> 
> Does any documentation need updating?

Thanks, Eddie. 

We don't have docs right now this is why I raised another PR to add them https://github.com/EddieHubCommunity/LinkFree/pull/5027

**Pull request merged**
