### PR TITLE
feat: footer, premium, terms

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

**FOOTER**

Screenshot 2023-05-06 at 12 44 22

**PREMIUM PAGE**

Screenshot 2023-05-06 at 12 45 01

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6637"></a>

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
There is a premium page coming!!😮

**Comment by ChinmayMhatre** [comment]
I think you are still working on the issue but still wanted to make observations incase they slip by :
- Dark mode style aren't added in the premiums page

**Comment by ChinmayMhatre** [comment]
The padding seems missing in larger devices 

image

**Comment by ChinmayMhatre** [comment]
To me the forms seems miss aligned due to its padding

image

**Comment by ChinmayMhatre** [comment]
image

I was playing around with the ui.

- I added flex-1 to the button component
- These changes to footer.js
image

**Comment by ChinmayMhatre** [comment]
I found some of the reasons the tests are failing
1. The "100% Open Source on GitHub" in the footer has no link.
2. There is no longer a "Powered by EddieHub" button in the footer but there are still tests that look for that

**Comment by eddiejaoude** [comment]
@ChinmayMhatre wow thank you so much for solving all those issues 😍 !! So you can get green squares do you want to make a PR to my PR? (but note the form is generated from another platform, so there is not much we can do with it)


> There is a premium page coming!!😮

There are no Premium features coming for a while, we learnt from the GitHub Accelerator to try and see how many people would be interested in a Premium version - so this is just to get an idea

**Comment by ChinmayMhatre** [comment]
> @ChinmayMhatre wow thank you so much for solving all those issues 😍 !! So you can get green squares do you want to make a PR to my PR?
> 
> Some thoughts:
> - the form is generated from another platform, so there is not much we can do with it
> - we should add `Powered by EddieHub` back in, may be a link on `100% Open Source on GitHub, Powered by EddieHub` with a link on `Powered by EddieHub`
> 
> 
> > There is a premium page coming!!😮
> 
> There are no Premium features coming for a while, we learnt from the GitHub Accelerator to try and see how many people would be interested in a Premium version - so this is just to get an idea

I am travelling today, I can create one tomorrow if that works.

**Comment by eddiejaoude** [comment]
> I am travelling today, I can create one tomorrow if that works.

Sure @ChinmayMhatre that would be great 👍 . Safe journey!

**Comment by ChinmayMhatre** [comment]
Hey @eddiejaoude do I branch off from the 'new-footer' branch and then create a new pr into this branch again?

**Comment by eddiejaoude** [comment]
> Hey @eddiejaoude do I branch off from the 'new-footer' branch and then create a new pr into this branch again?

@ChinmayMhatre yes that is correct 👍

**Comment by Pradumnasaraf** [comment]
The footer looks fantastic 🎉

**Comment by eddiejaoude** [comment]
Thank you Pradumna!

**Pull request merged**
