### PR TITLE
data:AJcodes42

### PR DESCRIPTION
**Pull request by AJcodes42**
## Changes proposed
Added profile as file.

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5709"></a>

### CODE REVIEW

**Review by khushalarora — CHANGES_REQUESTED** [review]
Hi @AJcodes42, thank you for contributing  :tada: 
Please rename your file to **`data/AJcodes42.json`**

**Comment by AJcodes42** [comment]
Hi @khushalarora, updated the file name.

**Review by SandeepKrSuman — CHANGES_REQUESTED** [review]
Hey, @AJcodes42 the file name should be `data/AJcodes42.json` as suggested by @khushalarora.

```diff
- add/AJcodes42.json

+ data/AJcodes42.json
```

**Comment by AJcodes42** [comment]
Hey @SandeepKrSuman, moved file to data/AJcodes42.json.

**Review by iamthecloverly — APPROVED** [review]

**Review by SandeepKrSuman — APPROVED** [review]
LGTM

@AJcodes42  thanks for contributing 🎉

**Review by SurajPratap10 — APPROVED** [review]
thanks for contributing 🎉

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
