### PR TITLE
data:nanna3210

### PR DESCRIPTION
**Pull request by nanna3210**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4778"></a>

### CODE REVIEW

**Review by Hrishi5111998 — APPROVED** [review]

**Review by Hrishi5111998 — CHANGES_REQUESTED** [review]
hey @nanna3210 please put your json file in data folder!

**Review by iamthecloverly — DISMISSED** [review]

**Review by himanshu1221 — CHANGES_REQUESTED** [review]
Hey @nanna3210 You have to put your file into data folder ,Other than that everything looks good !

**Comment by nanna3210** [comment]
thank you for pointing out the mistake

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"></p>

**Pull request merged**
