### PR TITLE
Anujkumarwebdev patch 1

### PR DESCRIPTION
**Pull request by anujkumarwebdev**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4502"></a>

### CODE REVIEW

**Comment by AbbeyIT** [comment]
Looks like you created 2 files. Only 1 json file for every user, and it should be the same name as your GitHub username.

**Comment by anujkumarwebdev** [comment]
> Looks like you created 2 files. Only 1 json file for every user, and it should be the same name as your GitHub username.

Sorry i don't know that, Can you please check again, i have update the PR

**Comment by priyankarpal** [comment]
> 

you can check this full guide https://linkfree.eddiehub.io/docs/quickstart

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
