### PR TITLE
Create NathanRag.json

### PR DESCRIPTION
**Pull request by NathanRag**

### CODE REVIEW

**Review by amandamartin-dev — CHANGES_REQUESTED** [review]
Please add at least one link to your profile. The socials area will only give you icons, but you may also place these in links as well if you like.

for more information, see they docs https://linkfree.eddiehub.io/docs/quickstart

**Comment by NathanRag** [comment]
Hey, I am trying to figure this out. I dont have many links as of now but will add them in future.

**Comment by amandamartin-dev** [comment]
> Hey, I am trying to figure this out. I dont have many links as of now but will add them in future.

You have the e from socials you can use if you like?  Do you understand how to add them as links?

**Review by iamthecloverly — APPROVED** [review]

**Review by iAnonymous3000 — APPROVED** [review]

**Review by SaraJaoude — APPROVED** [review]
Looks good. 
When you are ready to add links please submit a new Pull Request (and perhaps take a look at our Editing Guide in Docs: https://linkfree.eddiehub.io/docs/how-to-guides/editing)

**Pull request merged**
